### ISSUE TITLE
PyPlot - set backend

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#10]
We should allow a symbol to be passed into the `pyplot!()` method which defines the PyPlot backend (:qt, :tk, etc) and set that up properly.

**Comment by tbreloff** [comment]
I don't think I'll implement anything specific... the recommended pattern (I think) is:

```julia
using Plots; pyplot()
ENV["MPLBACKEND"] = "agg"
plot(rand(10))
```

**Comment by randy3k** [comment]
I reckon that a headless backend, e.g. `ENV["MPLBACKEND"] = "agg"` is almost always necessary in Jupyter notebook. How about setting it automatically when IJulia is loaded?
