### ISSUE TITLE
'Abort trap: 6' crash in contour

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#100]
I had Julia crash during a contour plot, both with the Gadfly and PyPlot backend, with the message:
```Abort trap: 6```
This was generated via
```julia
Pkg.checkout("ApproxFun","development")
using ApproxFun,Plots
k=(e*(0.0:1.0:200.0))[109]
d=Interval()^2
B=dirichlet(d)
Δ=lap(d)
ny=150
u=pdesolve([B;Δ+k*I],[ones(∂(d))],ny)
contour(real(u))
```
I can provide the raw data given to Plots if that helps.

**Comment by tbreloff** [comment]
I'm sorry to say that I don't know much about ApproxFun, so it's hard to know what might be causing this. My guess is that pdesolve is corrupting memory, but the crash doesn't occur until the call to contour attempts to use the corrupted memory. Of course this is just a guess... I'll try to reproduce.

**Comment by dlfivefifty** [comment]
OK I looked into this further and the bug is not in Plots, sorry about that.

**Comment by dlfivefifty** [comment]
At least it's not in ApproxFun either!    The following line triggers the bug:

```julia
julia> norm(zeros(129,129))
Abort trap: 6
```
