### ISSUE TITLE
Possible to create an animation without modifying underlying data?

### ISSUE THREAD

**Issue by rcnlee** [tbreloff/Plots.jl#104]
Current method for creating an animation specifies a constant plt and then modifies the underlying data for plt.
```julia
immutable Animation{P<:PlottingObject}
  plt::P
  dir::ASCIIString
  frames::Vector{ASCIIString}
end
```
If I wanted to make major changes to the plot, it is a bit cumbersome to be manipulating the underlying object.  Would removing plt from Animation make sense? Something like this:
```julia
immutable Animation
  dir::ASCIIString
  frames::Vector{ASCIIString}
end
```
Then require the user to pass in the plt when pushing to frame:
```julia
function frame{P<:PlottingObject(anim::Animation, plt::P)
  i = length(anim.frames) + 1
  filename = @sprintf("%06d.png", i)
  png(plt, joinpath(anim.dir, filename))
  push!(anim.frames, filename)
end
```
What do you think?

**Comment by tbreloff** [comment]
This might be possible, while keeping the old behavior by calling current(). One thing I'd be worried about is using plots of different sizes, but I guess that's the user's problem.

**Comment by rcnlee** [comment]
Yep! Existing behavior (i.e., example 2) can be completely retained if plt defaulted to current() in frame:
```julia
function frame{P<:PlottingObject(anim::Animation, plt::P=current())
```
