### ISSUE TITLE
Support for SubDataFrame and other DataFrame Types

### ISSUE THREAD

**Issue by rcnlee** [tbreloff/Plots.jl#105]
The DataFrames package may produce derivative types depending on the operations performed.  For example, if you take a view into a DataFrame, you get a SubDataFrame.  A groupby gives a GroupedDataFrame, etc.  

Plots.jl can be easily modified to support all of these by changing the function signatures to accept the AbstractDataFrame type.  In particular, the functions in plot.jl  ``dataframes()`` can be modified like this:
```julia
@eval function createKWargsList(plt::PlottingObject, df::DataFrames.AbstractDataFrame, args...; kw...)
    createKWargsList(plt, args...; kw..., dataframe = df)
  end

  # expecting the column name of a dataframe that was passed in... anything else should error
  @eval function extractGroupArgs(s::Symbol, df::DataFrames.AbstractDataFrame, args...)
    if haskey(df, s)
      return extractGroupArgs(df[s])
    else
      error("Got a symbol, and expected that to be a key in d[:dataframe]. s=$s d=$d")
    end
  end
```

**Comment by ErwanPiR** [comment]
Hi,
I wonder if this question has been adressed, because when I try to plot SubDataFrame or GroupedDataFrame, I get the error : 
ERROR: No user recipe defined for SubDataFrame{Array{Int64,1}}

Thanks.

**Comment by mkborregaard** [comment]
You can't. See StatPlots for plotting of DataFrames

**Comment by ErwanPiR** [comment]
Ok, thank you. I already check StatPlots but it's the same error :)

**Comment by mkborregaard** [comment]
Yes because there is no recipe for DataFrames. If you have a use case that isn't covered by the functionality in StatPlots you're welcome to open an issue with the example.

**Comment by ErwanPiR** [comment]
Thank you. I open an issue in StatPlots to explain the case.
