### ISSUE TITLE
Individual labels in a subplot

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#109]
I would like to set individual labels on plots in a subplot. I assumed it would be the same as for example the background:

```jl
subplot(1:10, Any[rand(10), rand(10)], n = 2, layout = (2,1), leg = false, bg=[:orange :pink], xlabel=["label1", "label"])
```

However, it doesn't seem to work.:

```jl
LoadError: MethodError: `convert` has no method matching convert(::Type{Union{AbstractString,Void}}, ::Array{ASCIIString,1})
```

I also tried with `, xaxis=[("label1",), ("label",)])` but that also fails.

Any pointers?

**Comment by tbreloff** [comment]
It should work if you remove the comma and make it a row vector (matrix)

**Comment by KristofferC** [comment]
It does. Wops! Thanks a lot.
