### ISSUE TITLE
Immerse - subplots

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#11]
Need to make a small PR in Immerse to get access to the `GtkBox` that is created, then just compose them together in `GtkPaned`s

**Comment by tbreloff** [comment]
@timholy: Looks like this was successful!  With these commands:
```
using Plots
subplot(rand(100,4); n=3)
```
I produced a Gtk window with an "Immerse box" for each underlying plot object:

![snapshot1](https://cloud.githubusercontent.com/assets/933338/9894516/9aba21f4-5bf2-11e5-83ad-70b409afb01b.png)

and a second call of `subplot!(rand(100,4))` changed it to:

![snapshot1](https://cloud.githubusercontent.com/assets/933338/9894542/ddb62b60-5bf2-11e5-9876-166153a6a436.png)


Keep an eye out for my Immerse PR which will make this possible.  Thanks for the help!

**Comment by timholy** [comment]
ooh, awesome! I like how you replaced the zoom icon with the binoculars.

I wonder, do you think we can do one toolbar for the whole thing? We'd need to have a vector of Canvases for which we `map` the callbacks.

**Comment by tbreloff** [comment]
I do think it would be possible, but that would require a little more work on the Immerse side, I think.  I didn't really make any changes to Immerse (I hope), they were all on the Plots side.

(I didn't change any icons... maybe they're different due to the operating system?  I'm running Centos7 with a KDE desktop right now.)

**Comment by timholy** [comment]
In the long term I'd say that work will be worth doing.

I'm on KDE too, and you can see on the Immerse README what they look like for me. Amusing.
