### ISSUE TITLE
Several lines in each subplot not supported?

### ISSUE THREAD

**Issue by baggepinnen** [tbreloff/Plots.jl#110]
I'm trying to plot more than one line in each panel in a subplot

The first call to `subplot` creates the window and the first plot
The subsequent call to `subplot!` creates a new subplot, not a new plot in the same subplot as before. I can see no way of accomplishing what I'm after, having multiple lines in each subplot pane.

**Comment by tbreloff** [comment]
I have an example that does this. If it's not clear after reviewing the examples then I need a better description to help.

**Comment by baggepinnen** [comment]
```
y = rand(100,3)
subplot(y; n = 3)             # create an automatic grid, and let it figure out the shape
subplot(y; n = 3, nr = 1)     # create an automatic grid, but fix the number of rows
subplot(y; n = 3, nc = 1)     # create an automatic grid, but fix the number of columns
subplot(y; layout = [1, 2])   # explicit layout.  Lists the number of plots in each row
```

If you refer to the above example, it creates a new subplot within the same plot window for each call to `subplot!`

I want to have multiple calls to subplot! plotting in the same subplot, e.g.
```
subplot(1:5, randn(5), n=2) # first subplot
subplot!(1:10, randn(10), n=2) # also first subplot

new_subplot_in_same_plot_window(1:3, randn(3), n=2) # second subplot
subplot!(1:4, randn(4), n=2) # also second subplot
```

I hope this makes it somewhat clear? I refer to the separate panes in a plot at subplots, and the entire window as a plot.

**Comment by tbreloff** [comment]
I hope I understand you this time.  You'd like to create the subplots a little more independently.  I think you're making it more complicated than needs be... do these examples help:?

![tmp](https://cloud.githubusercontent.com/assets/933338/12218595/dbf9f8a6-b6f1-11e5-828a-35e9ed63a7e9.png)

**Comment by KristofferC** [comment]
I found that example extremely useful as well!. I didn't know about the indexing into a subplot.

**Comment by baggepinnen** [comment]
Ah, that was exactly what I was looking for, thanks!
Great package btw, I have been looking for this for quite long, and just found it today :D

**Comment by tbreloff** [comment]
Great glad that helped, and thanks for the kind thoughts. Feel free to ask more questions... There's tons of convenient functionality that I haven't had time to document well. (I'll make another complete pass at documentation someday...)

**Comment by baggepinnen** [comment]
While on the subject of documentation, I was missing a way of manually adding legend entries. All examples I can find only have the default strings y1, y2...

I have also been enjoying the functionality of producing plots, and then calling `savefig` to produce tikz output for inclusion in latex documents. I had to write a short function to replace all usage of \fontspec and a few other things in the output file since I have no support for it. On first glance, it seemed that savefig uses functionality from elsewhere, and this might be out of your control, but savefig with options would be nice. I am since long a heavy user of matlab2tikz, but am trying to ditch matlab altogether and your package is helping me breach one of my last barriers!

I include my short function to demonstrate what I mean

```
function saveandprocess(path)
    savefig(path)
    f = open(path,"r+")
    s = readall(f)
    close(f)
    removestring = """
    \\documentclass{minimal}
    \\usepackage{pgfplots}
    \\usepackage{fontspec}
    \\usepackage{amsmath}
    \\usepackage[active,tightpage]{preview}
    \\PreviewEnvironment{tikzpicture}
    \\begin{document}
    """
    s = replace(s,removestring,"")
    s = replace(s,"\\begin{tikzpicture}[x=1mm,y=-1mm]","\\begin{tikzpicture}[x=\\figurewidth,y=-\\figureheight]")
    s = replace(s,"\\fontspec{Nullable(\"Helvetica\")}","")
    s = replace(s,"\\end{document}","")
    s = replace(s,r"\\fontsize{.*}{.*}\\selectfont","")

    f = open(path,"w")
    write(f,s)
    close(f)
end
```

**Comment by tbreloff** [comment]
First off, I'll admit that I'm not as well versed in tikz/latex as I should be.  I don't fully understand the scope of what you need to do, and also whether it's something that:

- Applies to all (or more than one) backends
- Is generic for many types of use-cases
- Other people will want to use

If it fulfills those parameters, then it might be worth including in Plots, and we can discuss the best way to add it.  Otherwise, you should probably just keep using the method you made.

> missing a way of manually adding legend entries

At a minimum, the "Line Types", "Line Styles" and "Marker Types" examples all have examples of setting the legend entries.  The argument is `label`, with aliases `lab`, `labels`, and you can also pass strings as one of the tuple args for the "magic" arg `line`.  Let me know whether that helps.

**Comment by baggepinnen** [comment]
Sweet, I did find it now. My method of ctrl+F-searching for `legend` did not help. 
When you refer to examples, is it the pages like this
https://github.com/tbreloff/ExamplePlots.jl/blob/master/docs/gadfly_examples.md
you are talking about? 
I was sifting through the notebooks but did not find them searchable, but now I think I know where to look.

Regarding the tikz/latex issue.
My issue was that `savefig("name.tex")` outputs code that makes use of the package fontspec `\usepackage{fontspec}` which requires any of the engines X∃LATEX or LuaLATEX, whereas I use the quite common pdflatex engine. I'm not sure if the tikz output is available with gadfly only or if it would work with any other backend. PyPlot can make use of the library matplotlib2tikz
https://github.com/nschloe/matplotlib2tikz
which produces better output than savefig, comparable to matlab2tikz.

Anyway, my method above works, but the code output is not nearly as nice as the code produced by matlab2tikz https://github.com/matlab2tikz/matlab2tikz
I can live with this for the time being, your package is already a huge improvement to the overall plotting experience in julia!

**Comment by tbreloff** [comment]
> When you refer to examples, is it the pages like this

Yes. those are linked from the beginning of the README (although they are outdated, like the rest of the readme)

> I'm not sure if the tikz output is available with gadfly only or if it would work with any other backend

I think this might be only implemented for Gadfly right now.  Since you seem to have much more knowledge about this subject, maybe you'd be interested in submitting a PR with some additions?  This comes down to implementing the proper `writemime` method.  Here is where it's defined for Gadfly: https://github.com/tbreloff/Plots.jl/blob/master/src/backends/gadfly.jl#L659-L678

> your package is already a huge improvement to the overall plotting experience in julia!

:+1:

**Comment by baggepinnen** [comment]
>maybe you'd be interested in submitting a PR with some additions?

When I have converged on a descent approach, I will make an effort to submit a PR!

**Comment by tbreloff** [comment]
Closing for now... feel free to open a new issue for tikz support, or see: #98 #134

**Comment by rakeshvar** [comment]
I am unable to call subplot directly!
```
julia> using Plots

julia> subplot
ERROR: UndefVarError: subplot not defined

julia> pyplot()
Plots.PyPlotBackend()

julia> subplot
ERROR: UndefVarError: subplot not defined


```

**Comment by tbreloff** [comment]
There's no subplot now... Just plot. Use the layout attribute.
