### ISSUE TITLE
Animation interface

### ISSUE THREAD

**Issue by gdkrmr** [tbreloff/Plots.jl#111]
There is an issue with the current animation interface:
1. `using Plots; anim = Animation()` gives an error, shouldn't this initialize an empty animation object?
2.  Something like this does not work:
```julia
plot()
anim = Animation()
for i in 1:0.1:π
    plot([sin,cos], 0, π)
    scatter!([i,i],[sin])
    frame(anim)
end
gif(anim)
```
An ugly workaround would be this:
```julia
plot()
anim = Animation()
for i in 0:0.1:π
    plot([sin,cos], 0, π)
    scatter!([i],[sin])
    scatter!([i],[cos])
    anim = Animation(current(),anim.dir,anim.frames)
    frame(anim)
end
gif(anim)
```
Here is what my intuition would expect: `Animation` should be mutable, so that `anim.plt` can be changed and `frame()` should always  set `anim.plt` to `current()`.

**Comment by tbreloff** [comment]
Your second example won't work. You're creating a new animation in each iteration. The first example should work fine. Are you on master? If not, I recommend a Pkg.checkout("Plots"). If it still doesn't work after a checkout let me know.

**Comment by gdkrmr** [comment]
the second example is what actually works for me :-)
I have version 0.5.1

**Comment by tbreloff** [comment]
Ok I understand now why the second version works now, but both examples are very inefficient.  Here's some pointers:

- `plot` or `subplot` will open up a brand new window/figure.  This is not what you want... you really just want to update the data for one of the series
- `Animation()` should work fine if you checkout... there was a recent PR adding an empty constructor
- You can update just the underlying series data by indexing on the Plot object (i.e. `getindex` and `setindex!` are defined for the Plot)

So with those notes in mind, a better way to do what you're trying to do is this (which works for me):

```
using Plots
anim = Animation()
p = plot([sin,cos], 0, π, size=(300,300))
scatter!([0], [sin,cos])
for i in 0:0.1:π
    p[3] = [i], [sin(i)]
    p[4] = [i], [cos(i)]
    frame(anim)
end
gif(anim)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/12235779/f3e14d36-b843-11e5-8b35-c3cf14ccae2c.gif)

**Comment by gdkrmr** [comment]
ok, thanks, it works.
How would I reassign coordinates in scatter3d?

**Comment by tbreloff** [comment]
Sadly that's not implemented yet... an example placeholder is here: https://github.com/tbreloff/Plots.jl/blob/master/src/backends/pyplot.jl#L441-L444

**Comment by gdkrmr** [comment]
ok, thanks for the help.

**Comment by tbreloff** [comment]
I added a new macro: `@animate` (on dev branch).  This allows for some boilerplate reduction.  Here's a modification of the example above:

```
using Plots
pyplot(size=(300,200))
p = plot([sin,cos], 0, π, lab=[:sin :cos])
scatter!(1, lab="")
anim = @animate for x in 0:0.1:π
    p[3] = [x,x], [sin(x),cos(x)]
end
gif(anim)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/12895353/0b6b3340-ce6a-11e5-9705-93b3e7c5aa90.gif)

**Comment by pkofod** [comment]
Can't get any easier than that!

**Comment by Evizero** [comment]
nice. I will try this soon

**Comment by pkofod** [comment]
It's nice that you can still `frame(anim)` if `fps=1` is too fast.
![tmp](https://cloud.githubusercontent.com/assets/8431156/12912604/e29ee21c-cf19-11e5-8db3-f4f968b714b7.gif)

**Comment by tbreloff** [comment]
@pkofod based on your wording, it seems like you might be confused on `fps`.  It's `frames per second`, which is just how many of the calls to `frame(anim)` to fit into 1 second of real time (after the frames have been generated already).  

However, if you really meant "I don't want to save a frame on each loop iteration"... I was thinking about adding some syntax to the macro, maybe like:

```
p = plot(1)
anim = @animate when(mod1(i, 3) == 1) for i=1:100
    push!(p, 1, rand())
end
```

and maybe the shorthand:

```
p = plot(1)
anim = @animate every(3) for i=1:100
    push!(p, 1, rand())
end
```

which would save a frame on every 3rd point added.  It would expand to:

```
p = plot(1)
anim = begin
    anim = Animation()
    for i=1:100
        push!(p, 1, rand())
        if mod1(i, 3) == 1
            frame(anim)
        end
    end
    anim
end
```

Thoughts?  Ideas for alternative syntax?

**Comment by pkofod** [comment]
@tbreloff , I was actually wrong and thought I was able to create two frames in a row, such that it would show two identical frames in a row (every frame is there twice, so with fps = 1 it would appear to have fps = 0.5 which is not possible as per your explanation), actually I was just able to write `frame(anim)` because `anim` was previously defined, but it did nothing (of course).

I like both `when` for that general use and `every` for the case most would probably need.

**Comment by Evizero** [comment]
+1 for the macro suggestions

**Comment by tbreloff** [comment]
This is mostly done.  I invite you to try it out on the `dev` branch.  Here's the highlights:

A new macro `@gif` simplifies things more... choose from:
```
anim = @animate for i=1:10
  plot(rand(i))
end
gif(anim)
```
or 
```
@gif for i=1:10
  plot(rand(i))
end
```

Keyword `every` followed by a positive integer after the for loop will only save only those frames.  So "every 5" will save frames for loop iterations [1,6,11,...]:
```
@gif for i=1:10
  plot(rand(i))
end every 5
```

Keyword `when` followed by any valid boolean expression will only save a frame when the expression evaluates to `true`.  A full example:

```
using Plots; pyplot(size=(300,200))
x = 0:0.1:2π
p = scatter(1, xlim=extrema(x), ylim=(-1,1))

@gif for xi in x
    push!(p, 1, xi, sin(xi))
end when abs(sin(xi))>0.2
```

Let me know what you think! (and if there are bugs, of course)

**Comment by Evizero** [comment]
Looks awesome. I will play with this

**Comment by pkofod** [comment]
:+1:  from here as well, I will play around with it some time next week.

**Comment by tbreloff** [comment]
I'm not sure why this is still open... I think the functionality is finished?
