### ISSUE TITLE
Example `plot(dataset("Ecdat", "Airline"), :Cost)` does not work

### ISSUE THREAD

**Issue by cstjean** [tbreloff/Plots.jl#115]
I just check'ed out the latest version and I get an error with this example from the manual:
```julia
gadfly()
using RDatasets
Plots.plot(dataset("Ecdat", "Airline"), :Cost)
```

```
LoadError: MethodError: `convertToAnyVector` has no method matching convertToAnyVector(::DataFrames.DataFrame)
while loading In[22], in expression starting on line 3

 in createKWargsList at /Users/cedric/.julia/v0.4/Plots/src/plot.jl:284
 in plot! at /Users/cedric/.julia/v0.4/Plots/src/plot.jl:96
 in plot at /Users/cedric/.julia/v0.4/Plots/src/plot.jl:56
```

**Comment by tbreloff** [comment]
I reverted a change, so you have to explicitly call `dataframes()` to use them.  I think the best way to handle this is to wrap in a Requires block, and so the call to `dataframes()` would be unnecessary... I'll leave this open until I make that change.

**Comment by cstjean** [comment]
Oh, sorry, that was right in the comment next to the example, I should have seen that!

**Comment by tbreloff** [comment]
I changed the loading of DataFrames-specific functions into a `@require DataFrames` block, so you no longer need the call to `dataframes()`... the example above now works again.
