### ISSUE TITLE
linkx doesn't interact very well with formatting

### ISSUE THREAD

**Issue by cstjean** [tbreloff/Plots.jl#116]
Hi, I'm really digging Plots.jl! Hopefully this issue is more meaningful than the last one: 

```julia
df = dataset("Ecdat", "Airline")
df[:some_long_name] = df[:PF]

subplot(scatter(df, :Cost, :some_long_name), scatter(df, :Cost, :LF), nr=2, link=true, leg=true)
```

results in:

![screen shot 2016-01-18 at 19 44 10](https://cloud.githubusercontent.com/assets/8622776/12406553/0ce5ffce-be1c-11e5-9ef1-76bacadd29de.png)

which makes it hard to read the x-axis in the top-plot.

**Comment by tbreloff** [comment]
This is a case that some features are simply better with a different backend. Do you have PyPlot installed? I would try that. Also, you could just turn off the legend.

**Comment by cstjean** [comment]
I'll try with PyPlot. Turning off the legend will help, but on the left side, the difference between `0.5` and `5.0x10^6` is harder to get rid of.

**Comment by cstjean** [comment]
PyPlot worked much better, thanks!
