### ISSUE TITLE
Gadfly - markers

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#12]
Groundwork is laid, I just need the Compose contexts for other shapes.

**Comment by tbreloff** [comment]
Progress... see https://github.com/dcjones/Gadfly.jl/issues/644#issuecomment-140633096

**Comment by tbreloff** [comment]
I went on a shape-making spree, and filled out most of the shapes I need:

![image](https://cloud.githubusercontent.com/assets/933338/9944927/44cc6812-5d58-11e5-88db-ad06ad3935ba.png)

I've gotta say, it quickly brought me back to the days I spent as a kid hand-typing 3D coordinates for shapes to use in POV-Ray.

@dcjones: Would you like me to submit a PR to Gadfly for the extra shapes?

**Comment by dcjones** [comment]
Nice! I would appreciate a PR (against the `shape` branch).

**Comment by tbreloff** [comment]
Done... https://github.com/dcjones/Gadfly.jl/pull/693

**Comment by lobingera** [comment]
maybe it's just me, but shouldn't a hexgon have 6 corners, rather than 8?

**Comment by tbreloff** [comment]
Ha... yes you're right... oops.   I guess we'll get an octagon as well!

On Fri, Sep 18, 2015 at 12:55 AM, Andreas Lobinger <notifications@github.com
