### ISSUE TITLE
markercolors

### ISSUE THREAD

**Issue by jverzani** [tbreloff/Plots.jl#121]
Shouldn't `markercolors` take a vector of colors to color points in a scatter plot? Reference:
http://stackoverflow.com/questions/35130093/how-do-you-color-x-y-scatter-plots-according-to-values-in-z-using-plots-jl

**Comment by tbreloff** [comment]
I responded to that SO question.  Right now vectors aren't supported directly, but you can take advantage of the gradient framework by setting `zcolor`.  I would like to support color vectors for explicit control, but this will take some time to get right... each backend does this stuff differently.

**Comment by jverzani** [comment]
Thanks, I learned something new in your answer!

**Comment by pkofod** [comment]
The question was mine, and thanks for the answer @tbreloff . I asked at SO instead of here, because I thought the question was of general interest, and it would be a nice thing to have an answer that is easy to google.

**Comment by tbreloff** [comment]
That sounds reasonable. The only downsides: I won't see the question immediately (or at all, as I'm not active there), and also the answer may become quickly outdated.

**Comment by pkofod** [comment]
1) yeah, but maybe someone else knows. I actually thought you were active there, as I've seen you answering quite a few Plots questions.

2) That is a problem, but I actually thought it was just me who couldn't figure it out as opposed to a "bug" or missing feature. That is why I didn't want to open an issue.

Is julia-users better if I want to maximize my chances of you seeing the questions ?

**Comment by tbreloff** [comment]
>  I actually thought it was just me who couldn't figure it out as opposed to a "bug" or missing feature

My perspective is that if something is really hard to figure out, then it **is** a bug or missing feature.  My goal is that Plots is intuitive to the point that things "just work", so if that's not the case it should be fixed (eventually).

> Is julia-users better if I want to maximize my chances of you seeing the questions ?

If you want me to see it quickly, opening an issue is the quickest way (these posts go directly to my email inbox).  julia-users and SO I have to make a point to check for updates, but I typically see them within a day.

**Comment by juliohm** [comment]
@tbreloff what is the current status of this feature? I tried the answer in SO but it didn't work for me.
