### ISSUE TITLE
Disable legend but keep colorbar

### ISSUE THREAD

**Issue by codles** [tbreloff/Plots.jl#122]
Currently (at least with pyplot) setting `legend=false` also disables the colorbar. Is it possible to disable the legend but keep the colorbar?

**Comment by tbreloff** [comment]
I don't currently have an argument to distinguish a series legend vs a colorbar... I'm open to suggestions on the best way to do that.

In the meantime, there is always a hack ;)

![tmp](https://cloud.githubusercontent.com/assets/933338/12731872/ef2ec0f2-c900-11e5-933d-a7149ba66d62.png)

**Comment by codles** [comment]
Works perfectly! Thanks.

As the code only works with PyPlot is there a way I can check which back end is currently loaded so I can do something like
```julia
if backend == "PyPlot"
    PyPlot.colorbar(p.seriesargs[1][:serieshandle])
end
```

**Comment by tbreloff** [comment]
```
if backend() == Plots.PyPlotPackage()
    PyPlot.colorbar(p.seriesargs[1][:serieshandle])
end
```

or

```
if Plots.backend_name(backend()) == :pyplot
    PyPlot.colorbar(p.seriesargs[1][:serieshandle])
end
```

**Comment by codles** [comment]
Thanks very much. I am a massive fan of the package. Easy switching between backends is fantastic.

**Comment by tbreloff** [comment]
Glad to hear :+1:
