### ISSUE TITLE
Change label of colorbar

### ISSUE THREAD

**Issue by codles** [tbreloff/Plots.jl#123]
Is it possible to specify the text to accompany the color bar?

I am specifying color in the following way
```julia
p = scatter(x_tmp, y_tmp, zcolor=c_tmp, c=:heat, ms=s_tmp)
```

**Comment by tbreloff** [comment]
For PyPlot, this should work:

```
cb = PyPlot.colorbar(p.seriesargs[1][:serieshandle])
cb[:set_label]("COLORBAR LABEL")
```

Is this what you meant?  I don't have this as part of Plots yet... you have to reach into the underlying backend object.

**Comment by codles** [comment]
Thanks for the help. Worked perfectly.

**Comment by codles** [comment]
This method no longer works with #135. Can you suggest another method for setting the colorbar label? Thanks

**Comment by tbreloff** [comment]
It doesn't?  Can you post your code?

**Comment by codles** [comment]
My extended code is [here](https://github.com/codles/EEG.jl/blob/c700a19255b1a8d21b605c28124f9a3365fc2f4b/src/types/VolumeImage/Plotting.jl#L172).

I tried to create a minimum example. Its a bit rough, I turn off the colorbar then use the above code to try and name a new colorbar.

```julia
using Plots

x = randn(100,1)
p = subplot(n = 3, nr = 1)
p = subplot!(p, x, l=:line)
p = subplot!(p, x, l=:hist)
p = subplot!(p, x, l=:scatter, zcolor = x, colorbar = false)

cb = PyPlot.colorbar(p.plts[1].seriesargs[1][:serieshandle])
cb[:set_label]("Neural Activity Index")
```

it throws this error

```python
LoadError: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'list' object has no attribute 'autoscale_None'",)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2237, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1595, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/colorbar.py", line 1330, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/colorbar.py", line 880, in __init__
    mappable.autoscale_None()

while loading In[23], in expression starting on line 9
```

**Comment by tbreloff** [comment]
The error is saying that you're trying to call methods on a list object, which probably means that `p.plts[1].seriesargs[1][:serieshandle]` is a list.  Try adding a `[1]` to the end of that to see if that passes the first handle in the list?

**Comment by codles** [comment]
I changed the line above to 
```julia
cb = PyPlot.colorbar(p.plts[1].seriesargs[1][:serieshandle][1])
```
which now throws
```python
LoadError: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'Line2D' object has no attribute 'autoscale_None'",)
```
I will keep playing around and see if I can solve this.

**Comment by tbreloff** [comment]
Oh sorry... you need to get the right handle.  Your coloring is in the 3rd plot, so try:

```julia
cb = PyPlot.colorbar(p.plts[3].seriesargs[1][:serieshandle]) # might need [1] too?
```

**Comment by codles** [comment]
Thanks, [this worked](https://github.com/codles/EEG.jl/commit/5e105ce74a9555ce3975b7690d5315c49455015e)
```julia
cb = PyPlot.colorbar(p.plts[3].seriesargs[1][:serieshandle][1])
```

**Comment by ErwanPiR** [comment]
Hi,

Is this method still working ? When I try

`PyPlot.colorbar(p.seriesargs[1][:serieshandle][1])`

I get the error : 

`type Plot has no field seriesargs`

I'm trying to do a scatterplot with colorbar and a label for it such as

`scatter(x_, y_, zcolor=color_, ms = area_, msw = 0, colorbar =:left)`

What kind of code can I add to have the label next to the colorbar ?

Thanks

Erwan

**Comment by mkborregaard** [comment]
Use the `colorbar_title` keyword.

**Comment by ErwanPiR** [comment]
Awesome, thanks !
