### ISSUE TITLE
legend and alpha are not working for histogram

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#124]
![hist](https://cloud.githubusercontent.com/assets/2822757/12752725/99409e2a-c9a2-11e5-91a2-8ce8eb1eb812.png)

**Comment by tbreloff** [comment]
For histograms, the color is actually taken as the line color, so you would use `linealpha`.  (I'm not sure that I want to change that, though I would listen to arguments for/against)

For some reason I don't add to the legend currently for histograms.  I think I had a good reason for that, but I honestly can't remember right now.  I'll consider changing that logic.

**Comment by tbreloff** [comment]
I guess this is why:

```
PyError (:PyObject_Call) <type 'exceptions.ValueError'>
ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()',)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_axes.py", line 538, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/legend.py", line 385, in __init__
    self._init_legend_box(handles, labels, markerfirst)
  File "/usr/lib64/python2.7/site-packages/matplotlib/legend.py", line 627, in _init_legend_box
    handler = self.get_legend_handler(legend_handler_map, orig_handle)
  File "/usr/lib64/python2.7/site-packages/matplotlib/legend.py", line 569, in get_legend_handler
    if orig_handle in legend_handler_keys:
```

I'll see if there's a way around this error.  In the meantime I'm making the change for the Gadfly backend:

![tmp](https://cloud.githubusercontent.com/assets/933338/12754450/4da61e12-c999-11e5-8cd9-68854191e3b3.png)

**Comment by diegozea** [comment]
I found this error again... 

![image](https://cloud.githubusercontent.com/assets/2822757/14506458/32742e7e-01be-11e6-8199-bb247a800112.png)

I believe that `linealpha` and `fillaplha` should have different meanings in hist, the first for the border/line of the bar, and the second for their filled colors.

**Comment by tbreloff** [comment]
> I believe that linealpha and fillaplha should have different meanings in hist, the first for the border/line of the bar, and the second for their filled colors.

I agree with this.  I had hesitations at first because the "series color" is usually `linecolor`, but that's not true for scatters, so there's precedence.

It also makes sense if you think of the histogram recipe I just made, where you're drawing the outline of a histogram using `linetype = :path`.

**Comment by tbreloff** [comment]
Also... this is making me think whether I should have a new argument `seriescolor`, which might effect the line, marker, or fill (or multiple of them) depending on the series type.  Then aliases like `color` and `alpha` would map to `seriescolor` explicitly.  It feels less hacky than "if type is histogram, then swap line color and fill color defaults" and similar hackiness.

**Comment by diegozea** [comment]
Having `color` default to `seriescolor` explicitly sounds fine to me.

**Comment by tbreloff** [comment]
> Also... this is making me think whether I should have a new argument seriescolor, which might effect the line, marker, or fill (or multiple of them) depending on the series type. Then aliases like color and alpha would map to seriescolor explicitly.

I've made this change in the `tb_pyplot` branch... it's a much nicer flow now.  And you can do things like set the alpha for the entire series all at once:

```julia
using Plots
plot(y, zcolor=y, m=(10,:inferno), α=0.3)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/14761621/8fd0f034-0934-11e6-9ced-19c2d1ee5a82.png)
