### ISSUE TITLE
abline!

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#125]
Hi! 
It would be great to have an `abline` function, similar to [R](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/abline.html). 
Best,

**Comment by KristofferC** [comment]
Isn't this implemented with `hline`

**Comment by tbreloff** [comment]
Right now you can do `hline`, `vline`, or add a regression term with `smooth`.  Here's some examples:

![tmp](https://cloud.githubusercontent.com/assets/933338/12753519/7a107596-c995-11e5-9ae9-fdd1326934f4.png)

`abline` could be done manually of course, but I can see the use for it, so I'll leave this open.

**Comment by pkofod** [comment]
Just to be clear, how would you create the line `y=0.5+0.1*x` using the mentioned functions? I mean, as  `abline(a=0.5, b=0.1)` does.

**Comment by tbreloff** [comment]
Right now you would have to add the line manually:

![tmp](https://cloud.githubusercontent.com/assets/933338/12754650/02dc803c-c99a-11e5-8058-af5ee9ef357e.png)

**Comment by diegozea** [comment]
Also you can do
```plot!(0:100, x -> 0.5 + 0.1 * x, linetype=:l)```
but it's annoying when you don't know the limits for x.

**Comment by tbreloff** [comment]
Or better yet: `plot!([0,100], x->0.5+0.1x)` which doesn't plot the [1,2,3,...,99] points.

**Comment by pkofod** [comment]
Okay, so I just misunderstod the "could be done manually of course". So I guess something like

```julia
function abline!(a, b, ...)
    fetch x limits
    plot!([xmin, xmax], x-> b+a*x)
end
``` 
I can do a PR if this would be useful to have.

**Comment by tbreloff** [comment]
Sure if you want to give it a go... this probably belongs in recipes.jl

**Comment by tbreloff** [comment]
Please merge the PR into the dev branch, not master.  It makes my flow a
little easier.  Thanks!

**Comment by joshday** [comment]
Could there be a method for plotting a function which takes the x limits from the current plot?   It's a common use case, and a little more flexible than abline.  `plot!(x -> .5 + .1x)`

**Comment by pkofod** [comment]
@joshday how should we then choose how to sample the domain?

**Comment by joshday** [comment]
I'm not sure I understand the question.  Maybe my comment needs clarification.  This already works:
```julia
scatter(randn(100))
plot!(x -> .5 + .1x, 0, 100)
```

Intuitively, I'd expect this to work:
```julia
scatter(randn(100))
plot!(x -> .5 + .1x)
```
The second two arguments for `plot!(f::Function, ...)` could be optional using whatever trick you're using with `abline` to get the maximum and minimum of `current()`.  It'd be a very short PR.  I'd be happy to add it.

**Comment by pkofod** [comment]
My bad! I get it.

**Comment by tbreloff** [comment]
Josh this is a nice idea.  To implement, you should implement this existing function: https://github.com/tbreloff/Plots.jl/blob/master/src/plot.jl#L415

Look at the other methods defined nearby if you get confused, but you just need to call the same method with an x-value.

**Comment by pkofod** [comment]
Should I add something like 
```julia
xmin(plt::Plot) = minimum([minimum(plt.seriesargs[i][:x]) for i = 1:length(plt.seriesargs)])
xmax(plt::Plot) = maximum([maximum(plt.seriesargs[i][:x]) for i = 1:length(plt.seriesargs)])
```
in #126 if @joshday is going to look up the minimum and maximum value as well in his addition? So we avoid several different approaches of finding the min and max throughout the code.

**Comment by tbreloff** [comment]
That sounds good. It might look nicer as:

    minimum([minimum(d[:x]) for d in plt.seriesargs])

(Sorry I'm such a nitpicker)

**Comment by pkofod** [comment]
Much better, please nitpick - it's partly why I like to contribute where I cannot just commit myself - to learn from and be inspired by others more skilled than me.

**Comment by tbreloff** [comment]
Cool. And to add to the convenience, maybe implement "Base.extrema(plt::Plot) = ..."

**Comment by pkofod** [comment]
abline! Is now on the dev branch @diegozea .

**Comment by tbreloff** [comment]
The relevant PR is #126.

**Comment by diegozea** [comment]
¡That's great! Thanks @pkofod :D
