### ISSUE TITLE
PlotlyJS integration

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#128]
@spencerlyon2 Lets consolidate errors here.

Here's the first error I see:

```
julia> using Plots; plotly(); plot(rand(10))
[Plots.jl] Initializing backend: plotly
ERROR: type Plot has no field window
 in _add_series at /Users/tom/.julia/v0.4/Plots/src/backends/plotly_blink.jl:24
 in plot! at /Users/tom/.julia/v0.4/Plots/src/plot.jl:119
 in plot at /Users/tom/.julia/v0.4/Plots/src/plot.jl:56
```

Looking at your code it seems like maybe you abstracted the PlotlyJS display?  I'm happy to attempt to fix it, I can try to guess what you're doing.

**Comment by spencerlyon2** [comment]
Yes, I did abstract a little bit of it out.

You can still get the window using `get_window(p::PlotlyJS.Plot)`, but I see that in those lines you don't want to get the window, but rather check if it is active.

**Comment by tbreloff** [comment]
@spencerlyon2  I'm wondering if we should separate out the non-Blink Plotly backend and the Blink Plotly backend as 2 different choices?  I just went to use Plotly in IJulia and it automatically opened a Blink window (of course it's broken on this machine anyways)

Could be `:plotly` and `:plotlyjs` backends, the former uses my original code, the latter calls to your package.

**Comment by tbreloff** [comment]
I did the split... they are now standalone backends.  The file has been renamed `src/backends/plotlyjs.jl` as well.  Let me know if there are any issues.

**Comment by spencerlyon2** [comment]
Sounds good to me. Sorry I didn't respond earlier. I think it is a good idea. Though I will want to clean things up so that if you are in a notebook it uses that for display and not blink (as it does when you use use PlotlyJS.jl by itself)

**Comment by tbreloff** [comment]
>  if you are in a notebook it uses that for display and not blink

Yeah and this is accomplished by doing "inline display" from the writemime methods, and "gui display" from the display methods.  It can still be independent from the `:plotly` backend if that's needed.

**Comment by spencerlyon2** [comment]
I'm not sure I follow.

Here's what I'm doing in PlotlyJS.jl:

- If I'm in a notebook, run this code when I start up: https://github.com/spencerlyon2/PlotlyJS.jl/blob/5b896eb49f386fc21e8154997a24b26649df315b/src/display.jl#L102-L123
- Then this is my only `display(::PlotlyJS.Plot)` method: https://github.com/spencerlyon2/PlotlyJS.jl/blob/5b896eb49f386fc21e8154997a24b26649df315b/src/display.jl#L80-L95

Were you perhaps missing my custom implementation of `IJulia.display_dict(::PlotlyJS.Plot)`, which made that not kick in automatically?

**Comment by tbreloff** [comment]
We made some great progress here... the last major item is supporting subplots.  I'll leave this open until that's done (and then we can open individual issues for anything else that pops up).

**Comment by diegozea** [comment]
Is It possible to save the `js` and the `html` from a PlotlyJS plot generated with Plots.jl?

```julia
# save to html. `js` is a keyword argument that specifies  how plotly.js can be
# included. Supported values are `:local`, `:remote`, `:embed`. See docstring
# for more details
savefig(sp::ElectronPlot, "output_filename.html"; js::Symbol)
```

**Comment by tbreloff** [comment]
This worked for me:

```julia
julia> f = open("/tmp/tmp.html", "w")
IOStream(<file /tmp/tmp.html>)

julia> using Plots; plotlyjs()
Plots.PlotlyJSBackend()

julia> plot(rand(10));
[Plots.jl] Initializing backend: plotlyjs

julia> writemime(f, MIME("text/html"), current())

julia> close(f)
```

Then when I open `/tmp/tmp.html` I see a working/interactive Plotly plot.

**Comment by spencerlyon2** [comment]
That should work.

Alternatively if you have a Plots.jl created plot named `p`, you can apply any `SyncPlot` methods from PlotlyJS using `p.o`.

So in your example you could do `PlotlyJS.savefig(p.o, "my_file.html"; js=:remote)` to save an html+js file where plotly.js is loaded from cdn.

**Comment by diegozea** [comment]
Thanks!
