### ISSUE TITLE
Confidence intervals

### ISSUE THREAD

**Issue by pkofod** [tbreloff/Plots.jl#131]
I was thinking about doing a small julia-intro course at the department where I'm studying at some point, and I figures Plots.jl would be the best way to introduce plotting. I know that one of the first questions I would get is "how do I plot a regression line with shaded confidence intervals?". What is the best way to do this in Plots.jl? The simplest example would be a constant width 1.96 times a standard error, but it could potentially also very over the domain.

Edit: the feature im looking for is something like a fill_between kw

**Comment by tbreloff** [comment]
Here's an example to get you started (I'd like to add a `fillbetween` arg, but for now you have to live with the `fillrange` arg):

```
using Plots, OnlineStats
pyplot(size=(400,300), leg=false)
x = sin(1:100) .* rand(100)

# Compute online mean and variance
#   f updates the model and extracts mean and std
v = Variance(ExponentialWeight(50))
f(xi) = (fit!(v, xi); (mean(v), std(v)))

# get the means and std devs
μ, σ = map(f,x) |> Plots.unzip

# plot 2 filled regions... [μ,μ+σ] and [μ-σ,μ]
plot([μ μ], fillrange=[μ+σ μ-σ], fillalpha=0.3, c=:orange)

# scatter the series on top
scatter!(x, m=(4,0.4,:red), xlim=(0,100), ylim=(-1,1))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/12857355/b485f5b4-cc17-11e5-9940-d0d53bb83aab.png)

**Comment by tbreloff** [comment]
I'll assume this answers your question?  I'm closing, but feel free to reopen if you want.

**Comment by Evizero** [comment]
@tbreloff I see you post a lot of code but without the syntax highlighting. So with the risk of over-explaining something that you do as a conscious choice: you can enable Julia syntax highlighting for a codeblock by writing "```Julia" as the beginning of the block and close the block with just the three backticks

**Comment by tbreloff** [comment]
Thanks @Evizero ... I knew about that, and for some reason I'm just not in the habit... I'll try to include the julia going forward.
