### ISSUE TITLE
RFC: Require Requires

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#136]
I'm considering adding https://github.com/one-more-minute/Requires.jl as a requirement for Plots.  This will allow me to more easily add conditional functionality (DataFrames, FixedSizeArrays, etc) without requiring those packages for everyone.  I take minimal package requirements seriously, so I wanted to throw it out there... does anyone think this is a bad idea?

**Comment by lobingera** [comment]
It's not a bad idea, and given the current state of julia import/require/dependency resolution it's inevitable use something like this.
I'd recommend to get Requires.jl closer to a regular julia package (like in julialang) and have more testing etc.

**Comment by Evizero** [comment]
actually thought you already did it like that

**Comment by tbreloff** [comment]
This has been added.
