### ISSUE TITLE
Subplots

### ISSUE THREAD

**Issue by pkofod** [tbreloff/Plots.jl#137]
Filing an issue because I can't figure out how it works.

How do I make to subplots such that the left plot is a line plot, and the right plot is a scatter plot? Assume a setup such that

```julia
# line plot data
x = -π:.1:π
y = sin(x)

# scatter plot data
x = randn(17)
y = randn(17)
```

**Comment by Evizero** [comment]
```Julia
# line plot data
x = -π:.1:π
y = sin(x)
p1 = plot(x, y)

# scatter plot data
x = randn(17)
y = randn(17)
p2 = plot(x, y)

subplot([2], p1, p2)
```

**Comment by Evizero** [comment]
For clarity: 

The following would put the plots on top of each other instead:

```Julia
subplot([1, 1], p1, p2)
```

**Comment by pkofod** [comment]
Oh, in that order, I would have thought p1, p2 should go first. Thanks!

**Comment by tbreloff** [comment]
Heh... I saw @Evizero's answer and thought "no... that won't work!".  Sometimes I surprise myself... totally forgot I did that.

Anyways there are lots of ways to do this, I'll add a couple methods which I don't think were mentioned:

```
using Plots
x = -π:.1:π
y = sin(x)

# same x, need to repeat y, sets the linetype arg (using the alias "t") with a row vector (1x2 matrix)
subplot(x, [y y], t=[:path :scatter])

# build a subplot from 2 plots... in this case you won't need to give a layout
subplot(plot(x,y), scatter(x,y))

# be explicit... number of subplots (n) and number of rows (nr)
subplot(plot(x,y), scatter(x,y), n=2, nr=1)

# weird, but works... build a subplot to hold 2 plots, but only give data for the first.
# then add to the second plot after the fact, using current().plts[2] to get the reference
subplot(x,y, n=2)
scatter!(current().plts[2], x, y)
```

There are other ways to be sure, but this should get you thinking in the right way.  You can choose whatever makes the most sense for your specific plot-type.
