### ISSUE TITLE
New image/imagesc plot type

### ISSUE THREAD

**Issue by grinsted** [tbreloff/Plots.jl#138]
The main thing holding me back from Jlia at the moment is how i would go about making my usual visualizations, and the fragmented vis-options in julia  - so i am excited about Plots.jl . I very often need to plot gridded data on top of a map. E.g. https://www.youtube.com/watch?v=oX3w5z2onvU

For that reason I really need a julia-equivalent of image/imagesc (matlab). It would also be great to have something like a textured surface type. In the linked video, I have an image underneath, and a textured surface on top which is transparent for values near zero. 

I would also like to be able to deform the images so that you put gridded data on different map projections. e.g. https://upload.wikimedia.org/wikipedia/commons/e/e1/NCDC_temperature_trend.png

**Comment by pkofod** [comment]
Matlibplot (interfaced by PyPlot in Julia) has the imshow plot, which seems to be much like the imagesc function in Matlab, so it should be possible I think. The gradient which has alpha going from 1 to 0 and then back to 1 might be possible with Colors.jl colormap, but I am unsure (I asked in https://groups.google.com/forum/#!topic/julia-users/tbgpYKOY-Wc ).

Plotly seems to be capable of something a long the lines you're showcasing (http://moderndata.plot.ly/weather-and-geography-charts-made-in-python-or-r/). 

My best bet would be to look at the supported backends to see if they can do anything like what you're describing. It appears that Matplotlib (so maybe PyPlot?) can do it, and possibly also Plotly.

**Comment by grinsted** [comment]
Thank you - i was also thinking that pyplot, and gr (and perhaps also plot.ly) would be my best bets. But  think it would be great to add the infrastructure for these types of plots to Plots.jl. It might help drive the backends to support these types of plots.

**Comment by tbreloff** [comment]
These all sound like cool visualizations.  I think GLVisualize would be a backend to keep an eye on. It's not quite ready for prime time but I think it will be in not too long. 

As has been said, if you can do these commands in existing backends, then post complete examples here and we can talk through how to make it happen in Plots. New features are usually pretty easy.

**Comment by tbreloff** [comment]
Back at my computer now... I put together a quick demo for "gradients with alpha".  The idea is that you build a `Plots.ColorGradient` with a list of `Colors.RGBA` values and the interpolation positions (normalized to [0,1]).  In this example I'm "stretching" the lower half of the gradient by using interpolation positions `[0, 0.9, 1]`.  The color list can be of any length, and the interpolation points can be different length than the color list (it should still figure out the right thing to do). Any questions, let me know.

![tmp](https://cloud.githubusercontent.com/assets/933338/13011104/271cf892-d173-11e5-8d53-09da441c5dd2.png)

**Comment by timholy** [comment]
@grinsted, Images.jl supports both `Overlays` and custom `MapInfo` types that allow you to specify essentially arbitrary on-the-fly rendering, in conjunction with ImageViewer. It should be pretty easy to duplicate that video you posted, and have a slider that allows you to select the time-slice you want to see. 

The main thing lacking in ImageView is any kind of axes (i.e., tick marks, etc). I'm not sure I want to add that, though; better to integrate an ImageViewer with plotting packages.

**Comment by grinsted** [comment]
Thanks...  Lots to play with over the weekend!

**Comment by tbreloff** [comment]
Fyi... the "imagesc" functionality is done for plotly and pyplot backends.  See: #147

**Comment by tbreloff** [comment]
See: #196
