### ISSUE TITLE
Accept colormaps from PerceptualColourMaps.jl

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#139]
https://github.com/peterkovesi/PerceptualColourMaps.jl

I need to review, but this might be as easy as defining the appropriate `convert` method to convert these colormaps to `Plots.ColorGradient` and adding a `colorscheme` method that calls the `convert`.

edit: this should also be wrapped in an `@require PerceptualColourMaps` block

cc: @peterkovesi

**Comment by peterkovesi** [comment]
Tom,

I can easily add a convert method to my package.  However, as I understand it the Plots.ColorGradient constructor can simply take a vector of colorants, cs .  vals defaults to a vector [0:length(cs)]
Given that PerceptualColourMaps.cmap() returns a colour map as a vector of ColorTypes.RGB{Float64} are we good to go as we are?  Or have I missed something

Note that I am in Western Australia so the time difference may result in my responses being somewhat delayed

Cheers
Peter

**Comment by tbreloff** [comment]
Ah that's great. Yeah in theory you could just do something like "y=rand10; scatter(y, zcolor=y, marker=ColorGradient(cmap(...)))"

This is untested... I'm not at my computer.

**Comment by peterkovesi** [comment]
Works straight out of the box.  Here's an example using my 'Rainbow 3' diverging colour map
y=rand(100); scatter(y, zcolor=y, marker=ColorGradient(cmap("R3")[1]))

I'll add that example to my documentation

Cheers
Peter
