### ISSUE TITLE
Display only a selection of legend items

### ISSUE THREAD

**Issue by codles** [tbreloff/Plots.jl#140]
Is it possible to display only a selection of legend items?

Often I use a loop to add items to a plot and this creates multiple identical entries in the legend. Or some elements do not require legend items. I would like to be able to select a subset of shown legend entries. Alternatively is it possible to create something like matplotlibs proxy artists, and only show these items?

Thanks

**Comment by tbreloff** [comment]
Yes! If you have the latest version of Plots, then a blank label (empty string) should leave it out of the legend. 

If that doesn't work, please post back here, and you might have to temporarily do plot(y, label = [""])

**Comment by codles** [comment]
Just updated and it works perfectly. Sorry I didn't update before asking.

**Comment by tbreloff** [comment]
Excellent. And just a quick tip... If you usually want to leave the series out of the legend, you can set the label default:

default(lab="")

Or:

gadfly(lab="")
