### ISSUE TITLE
Errorbars/Ribbons

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#143]
I am planning to add a new keyword argument: `:errorbars`.  Some notes:

- I'll probably alias `err`, `error`, `errorbar`. 
- I want these to be closely linked to "ribbons", where there is a filled area surrounding the line.  I need to decide if `ribbon` should be its own keyword arg, or if I can somehow use `errorbars` for both.
- I also need to decide if `fillrange` overlaps here.  Should one pass the numerical values into `fillrange`, then `errorbars` could be the "style", for example: `plot(y, fillrange=std(y), errorbars = :ribbon)`

If anyone has good ideas and/or opinions on how they'd like the interface to look, please post here.

**Comment by diegozea** [comment]
It would be great to have this for both axis (x and y) and supporting symmetric and asymmetric errors.

**Comment by tbreloff** [comment]
> would be great to have this for both axis

So I don't forget... it would be good to use the existing `orientation` argument for this purpose, which is currently only used for Plotly histograms.

**Comment by tbreloff** [comment]
See #178 and https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/errorbars.ipynb

**Comment by diegozea** [comment]
@tbreloff Is it possible to plot error for y and x in the same plot? [i. e.](http://astarmathsandphysics.com/a-level-physics-notes/179-principles-dimensions-units-and-error-analysis/2979-error-bars.html)

**Comment by tbreloff** [comment]
Yes it's easy, but need to decide on the right API.  Could pass a tuple, or have a separate `xerror`, or something else?  Type out the command you'd like to write to make this happen ;)

**Comment by diegozea** [comment]
I was looking at the code... At the moment only symmetric errors are supported, aren't they? Maybe tuples can be used for asymmetric errors (lower and upper limits), and add `xerror` (since `error` is `yerror`).

**Comment by tbreloff** [comment]
Yeah that's a good idea. Alias error to yerror and add xerror. Then I could remove the need for orientation, and keep access to asymmetric errors. I'll do this next.

**Comment by tbreloff** [comment]
Thanks for the API suggestions.  I haven't implemented asymmetric errors yet but it should be an easy extension.

```
using Plots
pyplot(leg=false, size=(500,300))
n = 10
x = [(rand()+1) * randn(n) + 2i for i in 1:5]
y = [(rand()+1) * randn(n) + i for i in 1:5]

f(v) = 1.96std(v) / sqrt(n)
xerr = map(f, x)
yerr = map(f, y)
x = map(mean, x)
y = map(mean, y)

plot(x, y, xerr = xerr, yerr = yerr, marker = stroke(2, :orange))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/14389239/bf58f1fa-fd7f-11e5-84a0-e9bddf8302a0.png)

**Comment by tbreloff** [comment]
All too easy ;)

```
plot(x, y, xerr = (0.5xerr,2xerr), yerr = (0.5yerr,2yerr), marker = stroke(2, :orange))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/14389722/f5d5bcac-fd81-11e5-9e17-35ce4218ec58.png)

**Comment by diegozea** [comment]
Awesome! You're welcome :D

**Comment by AsimHDar** [comment]
In case someone is looking here for single scatter points and asymmetric error bars (inputs to xerr and yerr need to be arrays):

```julia
x = 10
y = 4
xe = (2,3) 
ye=  (2,1)

scatter((x,y), yerr=([ye[1]],ye[2]), xerr=([xe[1]],xe[2]) )
```

**Comment by jabruniessner** [comment]
Hi there!

After reading all this, I still do not understand. Is it possible to represent the xerror as a ribbon as well somehow?

I would really like to do this!
