### ISSUE TITLE
redraw plot

### ISSUE THREAD

**Issue by CarloLucibello** [tbreloff/Plots.jl#144]
Hi, and thanks for this great package.

I'm trying to move away from PyPlot to Plots with pyplot or other backends, but I couldn't find a way to clear and redraw plots, something like;

```julia
using PyPlot
for t=1:10
clf()
subplot(2,1,1)
plot[:hist](rand(100))
subplot(2,1,2)
plot[:hist](rand(100))
sleep(1)
end
```

Is this feature currently supported for some of the backends (immerse or pyplot for example)?

Bye,
Carlo

**Comment by tbreloff** [comment]
This isn't currently supported, but it's on my radar (see #47).  Of course you could approximate this example with an animated gif! 

```
using Plots
anim = @animate for t=1:10
    subplot(rand(100,2), t=:hist)
end
gif(anim, fps=1)
```

**Comment by CarloLucibello** [comment]
Ok, thanks, feel free to close the issue if it is covered by #47

**Comment by tbreloff** [comment]
I just rewrote figure creation for the pyplot backend... I added a new argument `overwrite_figure` with aliases `clf`, `clearfig`, `overwrite`, and `reuse`.  You can either set the default for the session, or pass it into `plot`/`subplot` just like any other option:

```julia
using Plots; pyplot(reuse=true)

for i=1:10
  # these should all use the same figure, overwriting the last
  plot(rand(10)) 
end

# this should create a new figure
plot(rand(10), reuse=false)
```

Do `Pkg.checkout("Plots","dev")` to use right away.

**Comment by CarloLucibello** [comment]
Nice, thanks!

**Comment by tbreloff** [comment]
A poll for anyone watching: should the default behavior be to re-use an existing figure when creating a new plot, or create a new figure?

**Comment by CarloLucibello** [comment]
maybe `reuse=false` would be a better default, also because this is what happens for any other backend
