### ISSUE TITLE
steppre in UnicodePlots?

### ISSUE THREAD

**Issue by dpo** [tbreloff/Plots.jl#146]
When I try to use `:steppre` with the UnicodePlots backend, I get
```
WARNING: linetype steppre is unsupported with Plots.UnicodePlotsPackage().  Choose from: [:none,:line,:path,:steppost,:sticks,:scatter,:heatmap,:hexbin,:hist,:bar,:hline,:vline]
```

UnicodePlots does support `:steppre` (with `stairs(style=:pre)`).  I might be misunderstanding the code, but isn't `:steppre` implemented [here](https://github.com/tbreloff/Plots.jl/blob/master/src/backends/unicodeplots.jl#L95)?

Thanks.

**Comment by tbreloff** [comment]
Looks like I just need to add the symbol to the list of supported plot types. Thanks.

**Comment by tbreloff** [comment]
Fixed on dev branch

**Comment by Evizero** [comment]
:tada:
