### ISSUE TITLE
True heat maps

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#147]
Hi!
`heatmap` are actually more like a *2D histogram* plot than a real [heat map](https://en.wikipedia.org/wiki/Heat_map).
Would be great to have heatmap to take a single `Matrix` and plotting its values are colors or to take three vectors: x, y and  z (color).
Maybe `heatmap` with only x and y could be the actual *2D histogram* or the actual `heatmap` could be renamed to `histogram2D` or something similar.
Best,

**Comment by tbreloff** [comment]
I think I agree with you... But I'd like to review the terminology that other graphics packages use to look for precedence of notation. If packages are split on the usage then I lean towards backwards compatibility. In that case maybe there's another way to distinguish the uses... Checking for matrix input maybe?  Could utilize the z argument?

**Comment by diegozea** [comment]
Maybe the default value of z, if z is missing, should be counts/frequencies. With a `Matrix` as input `z` is defined,  because x are the row numbers, y the column numbers and z the matrix values. That shoulds maintain backwards compatibility, I guess.

**Comment by tbreloff** [comment]
Looking at [plotly examples](https://plot.ly/javascript/), I think I agree with the proposed change:

- [ ] `hist2d`: new name for current `heatmap`
- [ ] `hist3d`: http://matplotlib.org/examples/mplot3d/hist3d_demo.html
- [ ] `heatmap`: https://plot.ly/javascript/heatmaps/  (similar/same as [imshow](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.imshow)?)

Going along with all this, I want to overhaul the api for 3D data... namely I want to better use context of what is being plotted to determine what a vector/matrix/etc refers to:

```julia
z = rand(10,10)

# this should be 10 lines:
plot(z)

# this should be a "surface"
plot(z, linetype = :contour)
```

**Comment by diegozea** [comment]
Sounds good :+1:

**Comment by diegozea** [comment]
`hist2d` is already exported from Base, maybe will be better `histogram2d` to avoid the name collision...

**Comment by tbreloff** [comment]
Yeah... I had the same issue with `hist`, so I'll probably follow the same convention.

**Comment by tbreloff** [comment]
Kicking this off with plotly:

![tmp](https://cloud.githubusercontent.com/assets/933338/13650182/74f9060e-e60f-11e5-8db7-87d202f34f1e.png)

**Comment by diegozea** [comment]
It's working awesome with the matrix!!! :smiley: 

But I found this problems using x, y and z vectors:

![image](https://cloud.githubusercontent.com/assets/2822757/13651406/f9d89590-e625-11e5-99b4-854b859b95fa.png)

**Comment by tbreloff** [comment]
Yes passing in vectors which apply to surfaces is a big (not so easy) item on my todo list.

- Do you fit to a grid?
- Do you zero out positions not given?  Interpolate?

I think these questions are tricky in the general case, so there probably needs to be additional interface that the user can specify, but maybe Plots can try to guess the right answer.

If you have any ideas on proper behavior, please post.

**Comment by tbreloff** [comment]
I suspect you really want to do this in this case:

![tmp](https://cloud.githubusercontent.com/assets/933338/13651770/d046fd20-e616-11e5-8998-4bf880b6f510.png)

but this is not always what you'd want to do.  How do you generalize?

**Comment by diegozea** [comment]
I was expecting something like this:

![image](https://cloud.githubusercontent.com/assets/2822757/13654658/4e88038e-e638-11e5-84c8-09233df34d31.png)

Where the missing areas/points haven't colors. 
The most similar plot I get with Plots is:

![image](https://cloud.githubusercontent.com/assets/2822757/13654775/1ed55e60-e639-11e5-89b4-4910b34a5552.png)

I believe that, by default, missing point shouldn't be plotted like in the two examples above. If that isn't possible, plot missing points with the background color (and maybe excluding the background color from the color range).

Having a `default` argument, like in the `Base.get` function, to indicate the value to be used to replace NaNs, DataFrames' NAs, empty/null Nullables, etc. would be a good option. 

My favorite heatmap function from R is [heatmap.2](http://www.inside-r.org/packages/cran/gplots/docs/heatmap.2). It has the following arguments:

- `na.rm` : logical indicating whether NA's should be removed.
- `na.color` : **Color to use for missing value (NA). Defaults to the plot background color.**

**Comment by tbreloff** [comment]
I think this is what you're going for?

```julia
using Plots; plotly()
x = [1,1,1,2,2,3]
y = [2,3,4,3,4,4]
z = 1:6

# compress to unique values and remap to new indices
function remap(vals)
    compressed = sort(unique(vals))
    remapped = Array(eltype(x), length(vals))
    for (i,x) in enumerate(compressed)
        remapped[find(v -> v == x, vals)] = i
    end
    compressed, remapped
end

# create a matrix from the sparse representation
xs, I = remap(x)
ys, J = remap(y)
mat = full(sparse(I, J, z))

# create a gradient where (normalized) zeros are invisible
grad = ColorGradient(vcat(RGBA(0,0,0,0), Plots._gradients[:bluesreds]), [0,1e-6,0.5,1])

# plot a heatmap
heatmap(xs, ys, mat, c = grad)
```

<img width="586" alt="screen shot 2016-03-09 at 8 29 10 pm" src="https://cloud.githubusercontent.com/assets/933338/13656520/a434eff2-e635-11e5-97de-b4ee8bd645f9.png">



I think this belongs (if anything) as a recipe... not as standard behavior (but I could be convinced)

**Comment by tbreloff** [comment]
If you can think of a good function name, and other optional settings that you'd like, I can turn this into a proper Plots recipe...

**Comment by diegozea** [comment]
I must admit than the `heatmap(mat)` is more easy to use than the Vega `heatmap` and Gadfly `rectbin` interfaces with `x`, `y` and `color`. However, sometimes I have matrix with a lot of NaN values where `x`, `y` and `z` are a better representation. 

If  `heatmap(mat)` is the only option, a good way to deal with NaNs, NAs and Nullables will be useful.

I'm having this problems with the last master:

![image](https://cloud.githubusercontent.com/assets/2822757/13659469/ac02ec9a-e660-11e5-96e1-4d0c0467b34a.png)

P.S.: I'm willing to replace the actual `protovis` function of [PairwiseListMatrices](http://diegozea.github.io/PairwiseListMatrices.jl/#ploting) by a Plots' recipe ;)

**Comment by tbreloff** [comment]
Your output looks really wierd.  I just started up a notebook and ran:

```julia
using PairwiseListMatrices, Plots; plotly()
mat = PairwiseListMatrix([1,2,-1,-3,4,0])
heatmap(mat, yflip=true)
```

and this is what I got:

<img width="579" alt="screen shot 2016-03-10 at 7 58 06 am" src="https://cloud.githubusercontent.com/assets/933338/13670108/dc725c78-e695-11e5-96b6-967fd8ad1543.png">

Try a `Pkg.checkout("Plots","dev")`?

Also this is what I see when I add a NaN:

```julia
mat[1,2] = NaN
heatmap(mat, yflip=true)
```

<img width="583" alt="screen shot 2016-03-10 at 8 01 07 am" src="https://cloud.githubusercontent.com/assets/933338/13670166/46f87d84-e696-11e5-9ea7-f6e926763e09.png">

**Comment by tbreloff** [comment]
And after checking out your current viz... that's pretty straightforward to reproduce:

```julia
plotlyjs()
x = 1:4
n = length(x)
scatter(x, zeros(n), m=(10,:orange), leg=false)

zmin,zmax = extrema(mat)
grad = ColorGradient(:bluesreds)
curvecolor(v) = getColorZ(grad, (v-zmin)/(zmax-zmin))

for i=1:n, j=1:i-1
    curve = BezierCurve(P2[(x[i],0), ((x[i]+x[j])/2, i-j), (x[j], 0)])
    plot!(curve_points(curve), line = (curvecolor(mat[i,j]), 0.5, 2))
end
```

<img width="610" alt="screen shot 2016-03-10 at 8 15 09 am" src="https://cloud.githubusercontent.com/assets/933338/13670480/3eda5918-e698-11e5-889b-71aa90e4a8dc.png">

**Comment by diegozea** [comment]
Thanks! It works fine in the `dev` branch :)

**Comment by diegozea** [comment]
Could the [arc diagram](https://en.wikipedia.org/wiki/Arc_diagram) be a function of Plots?

**Comment by tbreloff** [comment]
Sure... it would belong in [recipes.jl](https://github.com/tbreloff/Plots.jl/blob/master/src/recipes.jl).  Any interest in adding it?  It seems like you're into graph algos.  You can use the example above as a baseline.

**Comment by diegozea** [comment]
I could try it :) Is there a way to plot real semicircles instead of Bézier curve?

**Comment by tbreloff** [comment]
Sure... there's always a way.

![tmp](https://cloud.githubusercontent.com/assets/933338/13704723/53f46536-e76b-11e5-9062-8f4e6449bb73.png)

Function signature is `function partialcircle(start_θ, end_θ, n = 20, r=1)`

The coordinates might be easier to work with if you unzip:

```julia
using Plots; plotly(size=(400,300),leg=false)
circ = Plots.partialcircle(0.25π, π, 50, 1)
x, y = Plots.unzip(circ)
plot(2x+3, 4y-2)
```

**Comment by diegozea** [comment]
Two more question:  
1. Now, If the mouse is over the line, plotly shows the coordinates. Is there a way to customize that behavior? Would be great to show the edge value and/or the nodes linked by that edge instead of the line coordinates.
 2.

**Comment by tbreloff** [comment]
Yes it's possible: https://plot.ly/javascript/hover-events/

I expect PlotlyJS to support this eventually. (cc: @spencerlyon2)

**Comment by spencerlyon2** [comment]
Definitely, julia callbacks to javascript events are one of my next goals.

However, this is possible without needing to use events. See the [text](https://plot.ly/javascript/reference/#scatter-text) and [hoverinfo](https://plot.ly/javascript/reference/#scatter-hoverinfo) trace attributes

**Comment by diegozea** [comment]
@tbreloff Is It possible at this moment to access `text` and `hoverinfo` plotly attributes from `Plots`? How can I do that?

**Comment by tbreloff** [comment]
Well if you do:

```julia
using Plots; plotlyjs()
p = plot()
```
then `p.o` is a `PlotlyJS.SyncPlot`.  I don't know PlotlyJS well enough to say exactly what the commands would be, but I suspect you can just make a call on that object.

**Comment by spencerlyon2** [comment]
Hey @diegozea as `tbreloff` says `p.o` will be a `PlotlyJS.SyncPlot` so you can do anything PlotlyJS allows using that object.

In this example I believe you want to alter the text/hoverinfo attribute on a particular trace. To do that you will want a call similar to:

```julia
PlotlyJS.restyle!(p.o, trace_number; hoverinfo=my_hover_info, text=my_text)
```

For more info on  what `restyle!` and it's friends so, check out [this section](http://spencerlyon.com/PlotlyJS.jl/manipulating_plots/#api-functions) of the PlotlyJS.jl docs

**Comment by diegozea** [comment]
`p.o` works with `plotlyjs()` but with `plotly()` `p.o` is `nothing`.

**Comment by tbreloff** [comment]
What were you hoping it would be?  `plotly()` is a much different beast... it's bare-bones access to plotly.js.  While both backends share much of the "Plots-to-Plotly" translation code, `plotlyjs()` has much more in the way of features/interaction.

**Comment by diegozea** [comment]
Ok... Is it possible to use `text` and `hoverinfo` with `plotly()` ?

**Comment by tbreloff** [comment]
Not without some hacking.  I recommend using PlotlyJS if you can.

**Comment by diegozea** [comment]
@tbreloff Is there a way to plot a [**heatmap with categorical axis labels**](https://plot.ly/javascript/heatmaps/#heatmap-with-categorical-axis-labels)?

**Comment by tbreloff** [comment]
This works out of the box:

```julia
julia> using Plots; plotly()
Plots.PlotlyBackend()

julia> x = ["Mon","Tues","Wed","Thur","Fri"];

julia> y = ["Morning","Afternoon","Night"];

julia> heatmap(x, y, rand(length(x), length(y)))
[Plots.jl] Initializing backend: plotly
```

**Comment by diegozea** [comment]
Great, It works! 

How can I modify the margins?
![margin](https://cloud.githubusercontent.com/assets/2822757/14649973/d6c64926-0669-11e6-9607-6d07765a0af4.png)

**Comment by tbreloff** [comment]
You can't do it directly through Plots right now (it's hardcoded).  You should approach it similarly to how you did text/hover.

I should add back an argument to allow for arbitrary overrides, which get merged into the Plotly dictionary before converting to JSON.  Then you could add something like:  `override = KW(:margin => KW(:l=>35, :b=>30, :r=>8, :t=>20))`

**Comment by diegozea** [comment]
I like `override`, having a way to pass data to plotly/plotlyjs sounds really useful!
