### ISSUE TITLE
Cannot set xmin/xmax, ymin/ymax independently

### ISSUE THREAD

**Issue by ma-laforge** [tbreloff/Plots.jl#150]
Hi Tom,

I like where this package is going very much. Thanks for this!

**Now, about axis limits:**
When looking at my data I often find it useful to specify _either_ ymin or ymax.

In a typical example: looking at a circuit response in dBs, one could reasonably want to dismiss all values under -50dB (when sufficiently small to be insignificant), while still auto-detecting ymax from the dataset.  Of course, inf values would have to be eliminated to avoid practical plotting issues.

In PyPlot, I can read back xlim/ylim, and modify only the limit of interest.  Of course, it would be preferable to have an API that supports setting limits independently.  One could even use something as simple as ylim(-50, nothing).

Anyways, I cannot seem to find a way to do this with the Plots.jl API (as far as I could see).

Is this already supported?  If not, I would like to add this feature request.

**Comment by tbreloff** [comment]
Seems reasonable... I don't think it's possible right now but something like (-50, Inf) or (-50, nothing) could work. Just need to implement it. 

And of course if you want to try the feature yourself I won't argue ;)

**Comment by tbreloff** [comment]
This should work on the dev branch now... I only made the change for pyplot, I'll roll out to others eventually.  Inf or -Inf will make the limit tuple one-sided:

```julia
using Plots; pyplot()
plot(rand(10), ylims=(-1,Inf), xlims=(-Inf,20))
```

**Comment by ma-laforge** [comment]
Perfect. Thanks.
