### ISSUE TITLE
Why force Gtk on Winston?

### ISSUE THREAD

**Issue by ma-laforge** [tbreloff/Plots.jl#152]
Hi,

I noticed that Plots.jl only renders Winston using Gtk kit.  I could not get Gtk.jl to work, but I noticed that the base Winston package works fine on my system.  Apparently, it uses Tk.jl instead of the Gtk.jl module.

Is there a reason why Plots.jl is forcing the use of Winston on Gtk?

Thanks.

**Comment by tbreloff** [comment]
I don't support winston anymore. I thought that I added a warning about that. It just didn't seem to offer anything that the other backends didn't have. Anything that works is purely by luck.

**Comment by tbreloff** [comment]
I removed the Gtk line and added a warning for Winston... changes on the `dev` branch.

**Comment by timholy** [comment]
Gtk is also superior to Tk in most respects. If you had trouble with the installation, it would be great to have you report your problems so they can be fixed. (No promises anyone will get to it quickly, but for the record.)

**Comment by ma-laforge** [comment]
@tbreloff: Sorry, missed that. Thanks.

@timholy: I think my comment was erroneous:

The Plots.jl/Winston.jl combination caused the following error for me:
`FATAL ERROR: Gtk state corrupted by error thrown in a callback`

It looks like the error was with Winston's support of Gtk... not with Gtk.jl itself.
