### ISSUE TITLE
`histogram` fails with `x=`

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#154]
I found this confusing...

![image](https://cloud.githubusercontent.com/assets/2822757/13610804/38354bb4-e53e-11e5-8c6f-fa3f8003490b.png)

Best!

**Comment by tbreloff** [comment]
Which part is confusing?  That `x=values` doesn't give you the histogram?  Yeah I can see that.  I never use `x=...`, so it never bugs me.  I'll keep this in mind as I'm making other changes, and I'll probably fix along the way.

**Comment by diegozea** [comment]
I were expecting `hist(x=` to work, so I found the single point very strange. I found this bug migrating code from `Gadfly` (using `x = ...`) to `Plots`.

**Comment by diegozea** [comment]
I used the word *confusing* as: *I don't understand why isn't  `hist(x = ...`  working*.

**Comment by tbreloff** [comment]
> I found this bug migrating code from Gadfly (using x = ...) to Plots.

:+1:
