### ISSUE TITLE
Concatenated labels

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#158]
Hi!  I'm having problems with this plot. 

![image](https://cloud.githubusercontent.com/assets/2822757/13616850/749ad0a8-e55a-11e5-805c-33f69f5716bf.png)

Using the `plotly()` backend the labels are concatenated. 
The same code gives the next error with `gadfly()`:

```
`convert` has no method matching convert(::Type{AbstractString}, ::Array{ASCIIString,1})

in addToGadflyLegend at /home/diego/.julia/v0.4/Plots/src/backends/gadfly.jl:270
in addGadflySeries! at /home/diego/.julia/v0.4/Plots/src/backends/gadfly.jl:317
in _add_series at /home/diego/.julia/v0.4/Plots/src/backends/gadfly.jl:587
```

With `pyplot()` I see only one level:
![image](https://cloud.githubusercontent.com/assets/2822757/13617038/73d5bd08-e55b-11e5-8d09-73b85de16c27.png)

Best!

**Comment by tbreloff** [comment]
In Plots, you need a row-vector (i.e. Array{T,2}) as attributes are applied column-by-column.  So it should be `lab = ["lab1" "lab2"]`.  By passing an Array{T,1}, you're saying "apply this vector for every series"

**Comment by diegozea** [comment]
Ok, thanks!

**Comment by diegozea** [comment]
It works perfect :D

![image](https://cloud.githubusercontent.com/assets/2822757/13617572/30c0f6e2-e55e-11e5-9ce7-97937c8bf340.png)
