### ISSUE TITLE
Cannot add Package

### ISSUE THREAD

**Issue by cortner** [tbreloff/Plots.jl#160]
I am unable to install `Plots`: 

```
Sunrise:~ ortner$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.add("Plots")
fatal: Not a git repository (or any of the parent directories): .git
ERROR: failed process: Process(setenv(`git rev-parse --git-dir`; dir="/Users/ortner/.julia/v0.4/.cache/Plots"), ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in readbytes at process.jl:515
 in readall at process.jl:520
 in dir at pkg/git.jl:12
 in git at pkg/git.jl:18
 in set_remote_url at pkg/git.jl:112
 in prefetch at pkg/cache.jl:39
 in resolve at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in edit at pkg/entry.jl:26
 in anonymous at task.jl:447
 in sync_end at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:46
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23
```

I also tried

```
julia> Pkg.clone("https://github.com/tbreloff/Plots.jl.git")
INFO: Cloning Plots from https://github.com/tbreloff/Plots.jl.git
INFO: Computing changes...
fatal: Not a git repository (or any of the parent directories): .git
ERROR: failed process: Process(setenv(`git rev-parse --git-dir`; dir="/Users/ortner/.julia/v0.4/.cache/Plots"), ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in readbytes at process.jl:515
 in readall at process.jl:520
 in dir at pkg/git.jl:12
 in git at pkg/git.jl:18
 in success at pkg/git.jl:29
 in installed_version at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in installed at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in edit at pkg/entry.jl:26
 in clone at pkg/entry.jl:168
 in clone at pkg/entry.jl:186
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in clone at pkg.jl:34
```

**Comment by Dawny33** [comment]
Weird!  I just tried just now, and it installed alright!

```
julia> Pkg.add("Plots")
INFO: Cloning cache of Plots from git://github.com/tbreloff/Plots.jl.git
INFO: Installing Plots v0.5.3
INFO: Package database updated
```

Version Info: 

```
julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by cortner** [comment]
thanks - maybe a problem with my julia installation?

**Comment by Dawny33** [comment]
@cortner Maybe. I have just installed v0.4.3, and it installs good there, too.

**Comment by tbreloff** [comment]
Might have been internet troubles?

**Comment by cortner** [comment]
not really - I tried it from a clean Julia installation; *all* other packages installed ok, `Plots` is the only one that didn't.

**Comment by tbreloff** [comment]
I'm sorry @cortner ... I saw this:

> Weird! I just tried just now, and it installed alright!

and thought that was from you.  

Can you please clear your cache?  Start with:

```
rm -rf ~/.julia/.cache/Plots
rm ~/.julia/lib/v0.4/Plots.ji
```

and see if that helps any?  I find it hard to believe this is a Plots issue... probably just a corrupted cache.

**Comment by cortner** [comment]
yep - that was it. Thank you, and I'm really sorry I wasted your time with this.
Christoph

**Comment by tbreloff** [comment]
No worries! Glad you figured it out.

**Comment by samirOs** [comment]
weired works fine on centos 0.5.1 
![image](https://user-images.githubusercontent.com/9787109/27011312-0280d028-4eca-11e7-8d20-2e1e2a0b50bf.png)
but fails on windows 

![image](https://user-images.githubusercontent.com/9787109/27011318-13b353a2-4eca-11e7-8149-6a5c2818ce34.png)

on windows with 0.5.2 
it fails with this error 
ERROR: Cannot clone FixedSizeArrays from https://github.com/SimonDanisch/FixedSi
zeArrays.jl.git. failed to send request: The server name or address could not be
 resolved

 in prefetch(::String, ::String, ::Array{String,1}) at .\pkg\cache.jl:56
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{Version
Number,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::D
ict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) a
t .\pkg\entry.jl:511
 in edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Ty
pes.VersionSet,N}) at .\pkg\entry.jl:30
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at .\task.jl:36
0
 in sync_end() at .\task.jl:311
 in macro expansion at .\task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at
.\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::S
tring) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at
.\pkg\dir.jl:31
 in add(::String) at .\pkg\pkg.jl:100
