### ISSUE TITLE
JavaScript error of Interact after plotly()

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#164]
I see this error message if I load `Interact` after `plotly()`. Everything is fine if `Interact` is loaded before `plotly()`.

![image](https://cloud.githubusercontent.com/assets/2822757/13761504/c3979b84-ea17-11e5-87ae-8db035411aa1.png)

**Comment by tbreloff** [comment]
I've seen that before too. I'm not sure whose fault it is.

**Comment by spencerlyon2** [comment]
That's my fault... I'll try to fix soon.

// Spencer

**Comment by spencerlyon2** [comment]
fixed in PlotlyJS.jl: https://github.com/spencerlyon2/PlotlyJS.jl/commit/8b4a9e208d48287c9505490a9f128e419da4705e

You should borrow that instead of the hack that I initially had :)

**Comment by diegozea** [comment]
@tbreloff In `IJulia`, using the `dev` brach of Plots, I'm getting the following error (without using `Interact`):

```
Javascript error adding output!
ReferenceError: Plotly is not defined
See your browser Javascript console for more details.
```

**Comment by tbreloff** [comment]
What browser? See: https://github.com/spencerlyon2/PlotlyJS.jl/issues/28

**Comment by diegozea** [comment]
I'm using Chromium in Ubuntu. Loading `Plots` and `plotly()` in a fresh session don't give me problems, but it fails now in [this notebook](http://nbviewer.jupyter.org/github/diegozea/MIToS.jl/blob/11ea31e8f8402e1b6a285cf80a63289f055a0d88/docs/Information.ipynb) (cell number 11).

![image](https://cloud.githubusercontent.com/assets/2822757/13850180/966efde0-ec61-11e5-9ffd-145f6ed40fa9.png)

**Comment by diegozea** [comment]
Works again after:  

1) Kernel -> Restart -> Clear all outputs and restart
2) Save
3) Close IJulia
4) Open IJulia and run

**Comment by tbreloff** [comment]
Closing in favor of meta-issue
