### ISSUE TITLE
subplot assignement

### ISSUE THREAD

**Issue by rveltz** [tbreloff/Plots.jl#172]
Hi,

I am struggling to assign data to specific subplots. For example, in `subplot(Plots.fakedata(100,10),n=4,palette=[:grays :blues :heat :lightrainbow],bg=[:orange :pink :darkblue :black])` 

How can I tell subplot, that the first two datas **only** should be plotted in the first subplot?
Thank you for your help,

**Comment by tbreloff** [comment]
I think you'll want to build the plots individually.  Syntax like:

subplot(plot(rand(10,2)), plot(...), ...)

You also might be able to get tricky and build a temporary subplot and then extract the plots:

subplot(plot(rand(10,2)), subplot(rand(10,8), n=3).plts...)

This is untested but should probably work.

**Comment by rveltz** [comment]
This solution satisfies me, thank you.
