### ISSUE TITLE
Image DPI control ?

### ISSUE THREAD

**Issue by GravityAssisted** [tbreloff/Plots.jl#173]
First of all, thanks for creating this package. Its really nice and has cleaned up 30% of my code. I would like to use it as my default plotting library but I can't seem to control the resolution of the image. 

Is there a parameter to control the image DPI ? The default seems really low (100 or something). Anything above 300 DPI is good for publishing. I am trying to save the image as a PNG.

thanks,
Nitin

**Comment by GravityAssisted** [comment]
With more digging, I found the pdf function, that should provide a workable solution for now.

**Comment by tbreloff** [comment]
I don't have a clean way to set DPI without reaching into the backend api... It's certainly something that should be supported well.

**Comment by lobingera** [comment]
providing correct DPI forwarding - even in a e.g. cairo-only environment - is a nightmare. That's why many people prefer vector output (.pdf/.svg/tex-like) backends. And render to their desired DPI.

**Comment by tbreloff** [comment]
closing in favor of meta-issue
