### ISSUE TITLE
plotly backend in notebook

### ISSUE THREAD

**Issue by spencerlyon2** [tbreloff/Plots.jl#174]
Now that we are using requirejs  to load plotly (a good thing) we need to make sure that all calls to `Plotly` (javascript) functions happen after requirejs has loaded plotly.

We can do this with the following js:

```javascript
require(['plotly'], function(Plotly) {
    // Plotly code here
});
```

In PlotlyJS.jl I have changed all the display commands to wrap calls to `Plotly.newPlot` in this require statement. You can see the change [here](https://github.com/spencerlyon2/PlotlyJS.jl/commit/4c030351c2f02b13480e9b6562cbd8e5ca2c0770)

The reason I did this was because I noticed that in nbviewer if I had very simple plots (easy to generate/parse quickly) at the top of a notebook the javascript console complained about `window.Plotly` not being defined and the plot wasn't shown. However, plots later in the notebook showed up without a problem. 

with plotlyjs backend you get this for free, but I believe you might want to make these adjustments for the plotly backend

**Comment by tbreloff** [comment]
Thanks for the detail!

**Comment by tbreloff** [comment]
closing in favor of the meta-issue
