### ISSUE TITLE
plots.jl and Atom

### ISSUE THREAD

**Issue by rveltz** [tbreloff/Plots.jl#175]
Hi,

From https://groups.google.com/forum/#!searchin/julia-users/status$20plots|sort:relevance/julia-users/5C5LlgbR5EM/k5Spl5g3BgAJ, I thought that Plots.jl would plot in the plot window of Atom-juno. 

I tried your dev branch as suggested,

```
julia> Pkg.status("Plots")
 - Plots                         0.5.3+             dev
```
but when typing in Atom:

```
using Plots
Plots.gr()
Plots.plot(rand(100))
```

nothing appeared. Do I have to do something else?

**Comment by rveltz** [comment]
I updated to Julia 0.4.5 but nothing changed, the plot does not appear in  Atom's PlotPane, is it expected?

**Comment by tbreloff** [comment]
This should be fixed... please reopen if you continue to have problems.

**Comment by rveltz** [comment]
Typing `using Plots` return the following warning in the console 

`WARNING: Error requiring Atom from Plots:
unsupported or misplaced expression <:`

The PlotPane does not display anything then upon calling `Plots.plot`

Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3


and:

38 required packages:
 - ApproxFun                     0.1.0+             development
 - Atom                          0.4.1
 - Bokeh                         0.2.0
 - CLBLAS                        0.1.0+             master
 - CLFFT                         0.1.0
 - Clang                         0.1.0
 - Conda                         0.1.9
 - Cubature                      1.0.10
 - DataFrames                    0.6.11
 - Distributions                 0.8.10
 - FastAnonymous                 0.3.2
 - GLPlot                        0.0.5+             master
 - GLVisualize                   0.0.6+             master
 - GR                            0.9.17+            master
 - Gadfly                        0.4.2
 - Gtk                           0.9.3
 - IJulia                        1.1.8
 - ImageMagick                   0.1.3
 - Immerse                       0.0.11
 - Jewel                         1.0.8
 - Lexicon                       0.1.18
 - MATLAB                        0.2.4
 - MPI                           0.4.0
 - Mocha                         0.1.2
 - ODE                           0.2.1
 - OpenCL                        0.3.6+             master
 - Plotly                        0.0.3
 - Plots                         0.5.3+             dev
 - ProfileView                   0.1.1
 - ProgressMeter                 0.3.0
 - PyPlot                        2.1.1
 - Qwt                           0.0.1
 - Roots                         0.1.26
 - SingularIntegralEquations     0.1.0
 - StatsBase                     0.8.0
 - Sundials                      0.2.0
 - SymPy                         0.2.39
 - UnicodePlots                  0.1.2
91 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.21
 - Blink                         0.3.4
 - Blosc                         0.1.4
 - Cairo                         0.2.31
 - Calculus                      0.1.14
 - CodeTools                     0.3.0
 - Codecs                        0.1.5
 - ColorTypes                    0.2.1
 - ColorVectorSpace              0.1.1
 - Colors                        0.6.3
 - Compat                        0.7.12
 - Compose                       0.4.2
 - Contour                       0.1.0
 - Cxx                           0.0.0-             master (unregistered)
 - DataArrays                    0.2.20
 - DataStructures                0.4.3
 - Dates                         0.4.4
 - Debug                         0.1.6
 - Distances                     0.3.0
 - Docile                        0.5.23
 - DualNumbers                   0.2.2
 - FactCheck                     0.4.2
 - FastGaussQuadrature           0.0.3
 - FileIO                        0.0.4
 - FixedPointNumbers             0.1.2
 - FixedSizeArrays               0.0.10
 - ForwardDiff                   0.1.6
 - FreeType                      1.0.3              master
 - GLAbstraction                 0.0.10             master
 - GLFW                          1.1.2
 - GLWindow                      0.0.9              master
 - GZip                          0.2.18
 - GeometryTypes                 0.1.3              master
 - Gillespie                     0.0.0-             master (unregistered)
 - Graphics                      0.1.3
 - Grid                          0.4.0
 - GtkUtilities                  0.0.8
 - HDF5                          0.5.8
 - HTTPClient                    0.2.0
 - Hexagons                      0.0.4
 - Hiccup                        0.0.2
 - Homebrew                      0.2.0
 - HttpCommon                    0.2.4
 - HttpParser                    0.1.1
 - HttpServer                    0.1.5
 - Images                        0.5.3
 - ImmutableArrays               0.0.11
 - Iterators                     0.1.9
 - JLD                           0.5.9
 - JSON                          0.5.0
 - JuliaParser                   0.6.4
 - KernelDensity                 0.1.2
 - LNR                           0.0.2
 - LaTeXStrings                  0.1.6
 - Lazy                          0.10.1
 - LibCURL                       0.2.0
 - Loess                         0.0.6
 - Logging                       0.2.0
 - MacroTools                    0.3.0
 - MbedTLS                       0.2.1
 - Measures                      0.0.2
 - Media                         0.1.2
 - MeshIO                        0.0.4
 - ModernGL                      0.0.7
 - Mustache                      0.0.14
 - Mux                           0.2.0
 - NaNMath                       0.2.1
 - Nettle                        0.2.2
 - Optim                         0.4.4
 - PDMP                          0.0.0-             master (unregistered)
 - PDMats                        0.4.0
 - Packing                       0.0.4              master
 - Polynomials                   0.0.5
 - PyCall                        1.4.0
 - Quaternions                   0.1.0
 - Reactive                      0.3.0              master
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - SHA                           0.1.2
 - SIUnits                       0.0.6
 - Showoff                       0.0.6
 - SignedDistanceFields          0.0.1
 - SortingAlgorithms             0.0.6
 - StatsFuns                     0.2.0
 - TexExtensions                 0.0.3
 - URIParser                     0.1.3
 - WebSockets                    0.1.2
 - WoodburyMatrices              0.1.5
 - ZMQ                           0.3.1
 - Zlib                          0.1.12

**Comment by tbreloff** [comment]
Did you both checkout dev and restart the kernel?

**Comment by rveltz** [comment]
I restarted my computer and it is now working. Thank you.

As a side note, your subplot example
`Plots.subplot(Plots.fakedata(100,10),n=4,palette=[:grays :blues :heat :lightrainbow],bg=[:orange :pink :darkblue :black])` does not appear in the PlotPane
