### ISSUE TITLE
xlims/ylims not working for logscale in gadfly

### ISSUE THREAD

**Issue by mfalt** [tbreloff/Plots.jl#177]
It seems like the handling of xlims/ylims is not working in Gadfly when updating a plot, example:
```julia
Plots.gadfly()
plot()
plot!(0.1:0.1:10, 0.1:0.1:10,yscale=:log10, ylims=(0.1,10))
```
which gives a plot from 10^0.1 to 10^10, contrary to how the limits usually work, and contrary to how it works with `pyplot()`. This also make it impossible to have a plot from 10^-2 since negative numbers throw an error.

I'm on julia 0.4.3 with Plots v0.5.3

**Comment by tbreloff** [comment]
I could reproduce on the dev branch.  It's weird that it works properly when creating a new plot, but fails when updating an existing plot.  I'll investigate.

**Comment by mfalt** [comment]
Do you have any idea what might be causing this? I could spend a few hours to try to fix this if I knew where to look, I am quite dependent on this feature.

**Comment by tbreloff** [comment]
> Do you have any idea what might be causing this?

I suspect that Gadfly is applying the transformation function on the `minvalue`/`maxvalue` fields right [here](https://github.com/dcjones/Gadfly.jl/blob/master/src/scale.jl#L268-L283), so to handle that (IMO strange) behavior, Plots would have to do the inverse transformation to the `minvalue`/`maxvalue` parameters [here](https://github.com/tbreloff/Plots.jl/blob/dev/src/backends/gadfly.jl#L383-L384).  Wanna take stab at a PR and check that the changes work?

**Comment by mfalt** [comment]
I think I was able to fix this in #190, your comment was very helpful, even though the problem was not with the push to Scale, it was in Coord.

I left a comment about another bug that I noticed, which is regarding how the limits are handled by Gadfly. If we want them to be able to crop away parts of the plot we should add them in Gadfly.Coord.cartesian when a plot is created, I don't think this is done now.

**Comment by tbreloff** [comment]
I saw the PR... thanks for the contribution!  I'll merge when the tests pass, but just for the future... can you try to branch/merge to the `dev` branch of Plots?  I prefer to accumulate new PRs which change functionality in the "unstable" branch, so that someone that uses master can be somewhat confident that things work.

> If we want them to be able to crop away parts of the plot we should add them in Gadfly.Coord.cartesian when a plot is created

I think I did this correctly at one time... I guess I broke it during a refactor?  If you know how to fix, please do!

**Comment by mfalt** [comment]
No problem. Yes of course, that makes sense.
I was looking quickly at it but I am not sure what is causing the problem and I will unfortunately not have time to look at it for at least a week. I might take a stab at it at a future date, but I can't make any promises.

**Comment by tbreloff** [comment]
If I ever un-deprecate Gadfly, I'll create a meta issue
