### ISSUE TITLE
ImageMagick not found in path

### ISSUE THREAD

**Issue by dpsanders** [tbreloff/Plots.jl#179]
```
julia> savefig("hist.pdf")
ERROR: ArgumentError: ImageMagick not found in path
```

This is with a just `Pkg.add()`ed `Plots.jl` on
```
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

However,
```
13:15 $ brew install imagemagick
Warning: imagemagick-6.9.3-0_2 already installed
```

**Comment by dpsanders** [comment]
```
13:15 $ which convert
/usr/local/bin/convert

13:15 $ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
```

**Comment by dpsanders** [comment]
Just trying out `Plots.jl`. Seriously impressive stuff!
Which backend do you recommend for saving PDFs? There doesn't seem to be a `pdf()` command.

**Comment by tbreloff** [comment]
Hi @dpsanders I'm surprised you haven't checked it out before!  PDF support depends on the backend, but there is a `pdf` command which I didn't realize is unexported.  (Although I might have done that on purpose so as not to pollute the global namespace with small/common names)

I just ran:

```
using Plots
plot(rand(10))
Plots.pdf("/tmp/tmp")
```

which saved a line plot to `/tmp/tmp.pdf` for me using the PyPlot backend.

As a general rule, if you come across missing packages, just add them. (i.e. `Pkg.add("ImageMagick")`) I purposely allow conditional includes so as to keep dependencies down.  (I try really hard to avoid the Gadfly-like mess of depending on every package that exists)

Let me know if you have any questions!

Also, it would be super helpful if you take note of the things that are confusing when first starting out... this way I can either improve or highlight in the docs.

**Comment by tbreloff** [comment]
Just to note... your `savefig("hist.pdf")` call was fine... it just passes through to the `Plots.pdf` method.

**Comment by dpsanders** [comment]
Oh, sorry, I didn't realise that `ERROR: ArgumentError: ImageMagick not found in path` was referring to a Julia package. That error message has at least improved a bit on 0.5. (But PyPlot doesn't seem to be working on 0.5?)

I had checked out the package, but not "in anger"!

How about this:
```
julia> using Plots

julia> plotlyjs()
Plots.PlotlyJSPackage()

julia> x = randn(10000);

julia> histogram(x)
[Plots.jl] Initializing backend: plotlyjs

julia> Plots.pdf("hist.pdf")
ERROR: MethodError: `writeimage` has no method matching writeimage(::ImageMagick.MagickWand, ::IOStream)
Closest candidates are:
  writeimage(::ImageMagick.MagickWand, ::AbstractString)
 in writemime at /Users/dpsanders/.julia/v0.4/PlotlyJS/src/savefig.jl:185
 in writemime at /Users/dpsanders/.julia/v0.4/Plots/src/backends/plotlyjs.jl:11
 in pdf at /Users/dpsanders/.julia/v0.4/Plots/src/output.jl:25
 in pdf at /Users/dpsanders/.julia/v0.4/Plots/src/output.jl:28
```

**Comment by tbreloff** [comment]
No worries.  This is @spencerlyon2 's turf (the error is in PlotlyJS).  Maybe he can help?

**Comment by spencerlyon2** [comment]
Yep, I see what's going on here. Details about saving figures are a bit in flux right now, but once I've resolved them I'll make sure things play nicely with Plots.jl.

For right now, this is how you would do it:

```
julia> using Plots

julia> plotlyjs()
Plots.PlotlyJSBackend()

julia> x = randn(10000);

julia> p = histogram(x)
[Plots.jl] Initializing backend: plotlyjs

julia> PlotlyJS.savefig3(p.o, "my_file.pdf")
```

A few caveats:

- you need to have Rsvg.jl installed and checked out to master
- You need to check out Blink.jl also
- Only works with the electron frontend (i.e. wouldn't work in the notebook). I'm about 95% finished making things work in the notebook, I just have to tidy up a couple things.

**Comment by tbreloff** [comment]
Closing in favor of #128
