### ISSUE TITLE
Could you provide more examples about PlotlyJS.jl?

### ISSUE THREAD

**Issue by YaoLuCNS** [tbreloff/Plots.jl#180]
I saw your video on youtube.

**Comment by tbreloff** [comment]
What sort of examples were you looking for?  Did you see http://plots.readthedocs.org/en/latest/examples/pyplot/ and https://github.com/tbreloff/ExamplePlots.jl/tree/master/notebooks?

I should note that there's nothing different about the syntax or usage of the PlotlyJS backend vs anything else... only the feature set.  See http://plots.readthedocs.org/en/latest/backends/ for some brief descriptions about the differences.

If you have any specific ideas for good examples which will highlight functionality well, please suggest.

**Comment by spencerlyon2** [comment]
Echoing what @tbreloff said, if you have any ideas in mind for the type of exercise you would like to do, please let us know and we can write up an example or two.

Thanks!
