### ISSUE TITLE
Polar coordinates

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#181]
Example:

```julia
using Plots
pyplot()
plot(linspace(0,3π,100), rand(100), polar=true, m=:red, bg=:black)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/14424915/c9c38c8e-ffb1-11e5-81c5-fc396d9f5656.png)

Backends supported:

- [x] pyplot
- [ ] gadfly/immerse
- [x] plotly/plotlyjs
- [x] gr

**Comment by tbreloff** [comment]
Strangely, I just found out that the "radius axis" is scaled incorrectly on scatter plots.  So this is broken:

```julia
scatter(linspace(0,3π,100), rand(100), polar=true)
```

but this is ok:
```julia
plot(linspace(0,3π,100), rand(100), polar=true, w=0, marker=:o)
```

I guess this is just one more reason to stop using matplotlib's `scatter` function, and just convert it to an equivalent `plot` call.

**Comment by nico202** [comment]
For future readers, polar=true became proj = :polar
