### ISSUE TITLE
Use PlotlyJS.jl backend in Atom

### ISSUE THREAD

**Issue by YaoLuCNS** [tbreloff/Plots.jl#182]
In Atom, I could use p=plot(...);display(p) to show electron GUI. However, this doesn't work when using Plots.jl.

**Comment by spencerlyon2** [comment]
This need to be hooked up,  but in the mean time you can build your
plotlyjs plots using Plots.jl and then do `display(p.o)` instead of just
`display(p)`

**Comment by YaoLuCNS** [comment]
Thank you. It works!
