### ISSUE TITLE
New processing hook for converting custom types?

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#183]
While helping @jverzani with https://github.com/jverzani/SymPy.jl/issues/69, I decided that it was unnecessarily hard to define a conversion from a user type to an accepted Plots input.

I'm thinking about adding an exported function (or macro?) to define rules to convert one type to something else during Plots preprocessing, eliminating the need for defining every permutation of possible inputs.  Something like:

```julia
using Plots
type MyFunc
  f::Function
end
Plots.plots_input(mf::MyFunc) = mf.f

# then this just works:
plot(MyFunc(sin), 0, 10)
```

Thoughts? Name ideas?

**Comment by spencerlyon2** [comment]
This feels like a specialized version of what I explored in spencerlyon2/PlotlyJS.jl#29 where I allow for arbitrary functions to be run as pre-display hooks. 

I didn't love the implementation I came up with as it caused `display` to mutate the data it was supposed to be displaying, but I think that the idea has a ton of potential. 

If we do come up with something here, I think we could have it do more than just allow display of user defined types.

**Comment by tbreloff** [comment]
The problem isn't that there's something we can't accomplish... the problem is that you need to think about too much and implement too much when you're forced to act too early or too late in the processing pipeline. 

There are so many combinations of input data types and parameters, some of which have very different results depending on how they are combined.  It's too much to ask an end user to know (or care) about handling the zillion corner cases that crop up.  This is where Plots is important... ensuring that the end user can think about only their use case, but then many other use cases magically also work.

I'll reiterate what I said in that issue... it would be a shame (IMO) if one had to call PlotlyJS with un-processed inputs to get some cool features.  It would require bypassing Plots, and the ecosystem would suffer.  I'd much rather the Plots-to-Plotly link was featureful (i.e. anything supported in plotly.js is supported through Plots) and then add all the preprocessing in Plots so that all backends can benefit.

**Comment by tbreloff** [comment]
I think this can be supported nicely through recipes... I just need to switch the processing pipeline a tiny bit in Plots.  Right now I have a bunch of definitions like:

```julia
# string vector
convertToAnyVector{T<:@compat(AbstractString)}(v::AVec{T}, d::KW) = Any[v], nothing
```

But I can change these to recipes with the type information as part of dispatch:

```julia
@recipe f{T<:AVec{UTF8String}(::Type{V}, v::V) = Any[v]
```

And replace the `convertToAnyVector` calls inside Plots to `apply_recipe(typeof(v), v)`, then it should accomplish the same goal, but allow users to define data conversions themselves without the Plots dependency.

**Comment by tbreloff** [comment]
Done with b36f8c7
