### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jw3126** [tbreloff/Plots.jl#184]
The following piece of code eats up almost 2GB of memory which are never released.
```
using Plots

pyplot()
x = 1:0.3:1000
y = x
f(x,y) = sin(x) + cos(y)
contour(x,y,f,fill=true)
```

while this specific plot is silly, the problem becomes real if I try to create lots of sane plots in a loop. Not sure though if its the fault of Plots, PyPlot.jl, matplotlib or a combination of these. Is there some workaround?

**Comment by pkofod** [comment]
I had problems creating large surfaces (or contours) last night, but are you sure it's a leak? Maybe it just needs that much memory to create the plot.

**Comment by jw3126** [comment]
There is also a leak (though maybe the plot would still use 2GB during creation without it). Just put the script below in a file, execute it and watch memory consumption. You will see a steady increase, that only gets released after julia exists. However I do not know how one could reference the plots anymore (except for the last one maybe).
```
using Plots

pyplot()
function do_plots()
    for i in 1:10
        println("plot", i)
        x = 1:0.3:500
        y = x
        f(x,y) =  sin(x) + cos(y)
        contour(x,y,f,fill=true)
    end
    println("plots done")
end

do_plots()
sleep(30)
```
If you paste the script in the repl instead, lots of plots windows will open, which don't release memory after closing either.

**Comment by tbreloff** [comment]
The obvious question... Did you try this with any other backends besides pyplot? That could help narrow down the search. 

Ignoring a potential leak, though... The memory usage of a moderately sized surface could get pretty big even without any leaking. This bugs me a ton, especially when the input is a function and not an existing matrix. I think my hands are tied for pyplot (I have to build the full matrix), but I should try to avoid it when possible. 

I'm happy to have any help in testing/analysis to figure out what's going on here.

**Comment by jw3126** [comment]
Good question. I tried gadfly. There each of the above plots is much smaller in the order of a few MB. So a leak would not be as easy to spot (I just use htop to monitor memory usage, any suggestions to do it better?). Anyway I am not yet sure if gadfly leaks, I plan to run a ton of gadfly plots over night to be certain.

**Comment by tbreloff** [comment]
Ok... I've had suspicions in the past that PyPlot, PyCall, and/or matplotlib have memory leak issues, but nothing concrete to note. Any insight you can provide would be appreciated.

**Comment by jw3126** [comment]
Ok gadfly runs fine. Also I remember to have seen an issue with matplotlib where one had to explicitly use both 
```
fig.clf()
plt.close(fig)
```
to get rid of a plot. Googling for it I could not find it again, but there are at least some stackoverflow questions in this direction. I tried 

```
using Plots
using PyPlot

x = 1:0.3:500
y = x
f(x,y) =  sin(x) + cos(y)
p = Plots.contour(x,y,f,fill=true)
p.o.fig[:clf]()
PyPlot.close(p.o.fig)
```

and `p.o.fig[:clf]()` does indeed clear the figure in the sense, that the plot is empty after calling it. However memory is still not freed.

**Comment by tbreloff** [comment]
I don't think this is a Plots issue, but one more thing to try... 

```julia
using Plots
pyplot(reuse=true)
```
