### ISSUE TITLE
Add new matplotlib color maps to colors.jl

### ISSUE THREAD

**Issue by oschulz** [tbreloff/Plots.jl#185]
It would be great to have the new matplotlib color maps (esp. the future default "viridis") available in Plots.jl (a native Julia implementation would make it available in all backends, right?). It appears that a substantial amount of research (resp. color theory) went into these new color maps, and the difference to simple gradients, etc., is striking:

* http://matplotlib.org/style_changes.html
* http://bids.github.io/colormap/

**Comment by tbreloff** [comment]
Do you know anything about the licensing of those colormaps? I could add them to Plots, but only if it stays MIT licensed. 

There are a few packages dedicated to colormaps... The matplotlib colors may already exist somewhere else.

**Comment by lobingera** [comment]
i had plans to centralise the colormap access in an own package. But i'm not far(*). This was also driven by my trial to get jet and cubehelix running and on board of Color.jl. And there is ColorBrewer etc.
@tbreloff, see http://bids.github.io/colormap/ for some claims about the licensing

(*)= a colormap would just be an ordered, discrete set of colors and i'd like to address colorscales, i.e. somehow functions between value and Color also...

**Comment by oschulz** [comment]
They provide the color map data here: https://github.com/BIDS/colormap/blob/master/colormaps.py .

They're "released under the CC0 license / public domain dedication" - that should be MIT compatible, right?

I just did a quick test (based in the Plots.jl PyPlot contours example), using Plots.ColorGradients (is that the right way to do it, for so many values?). Seems to work nicely: https://gist.github.com/oschulz/1058f2b9cfe2f6e20a97cac66f78023c .

**Comment by tbreloff** [comment]
> They're "released under the CC0 license / public domain dedication" - that should be MIT compatible, right?

Yes it seems like we could put attribution inline in the code and that would be plenty... no license changes needed.

> i had plans to centralise the colormap access in an own package

This is a pretty straightforward addition to Plots, and until all the color functionality is adequately reproduced in another package (and Plots is properly refactored to use it), I think it would be fine to add it to Plots.  To be clear... I'll be happy to switch all my color code to an external library when it's feasible and doesn't remove features.

> I just did a quick test... Seems to work nicely

:+1: agreed

> using Plots.ColorGradients (is that the right way to do it, for so many values?)

exactly... though I wonder if those values can be compressed (are they approximately linear in RGB space?)

**Comment by tbreloff** [comment]
> a colormap would just be an ordered, discrete set of colors and i'd like to address colorscales, i.e. somehow functions between value and Color also...

You can see how I've approached some of these problems: https://github.com/tbreloff/Plots.jl/blob/master/src/colors.jl

I have a pretty general framework that allows for wrapping individual colors, vectors, and gradients with the same code... feel free to take inspiration from it if you're making something new (attribution appreciated if you copy anything).

**Comment by oschulz** [comment]
> exactly... though I wonder if those values can be compressed (are they approximately linear in RGB space?)

@tbreloff: Definitely not. :-)

The color values are equidistant in perceptual space (that's the point about the new color maps, nicely demonstrated here: http://bids.github.io/colormap/images/screenshots/option_d.png). The creators even took care that they still look good for color blind people and when printed in grayscale. The whole math behind is not trivial, there's a good talk about it linked here: https://bids.github.io/colormap/ .

The Python code to generate the color maps should be open source, but I don't know under what license and how much work it would be to translate it to Julia. Some of it would make a very nice addition to Colors.jl, I guess.

**Comment by tbreloff** [comment]
> Definitely not.

While I agree you can't just take 2 or 3 samples and call it a day, there's certainly a middle ground.  Here's a plot of the viridis red/green/blue colors.

![tmp](https://cloud.githubusercontent.com/assets/933338/14499604/010e5950-016d-11e6-97f8-3878960d7e74.png)


I agree they are highly non-linear, but not so non-linear that you couldn't take, say, every 5th color and have essentially the same gradient.


> The Python code to generate the color maps should be open source, but I don't know under what license and how much work it would be to translate it to Julia

Isn't it as easy as copying the RGB values?

**Comment by oschulz** [comment]
> I agree they are highly non-linear, but not so non-linear that you couldn't take, say, every 5th color and have essentially the same gradient.

Sure, one could definitely do a rougher approximation and still reproduce them fairly well. But then, it's not like it's a lot of data in the first place, right? Or does the lookup speed depend on the size of the table (I would assume not)?

> Isn't it as easy as copying the RGB values?

I meant the implementation of the perceptual color space, the color value generation algorithm, etc. But for Plots.jl is of course enough to just copy the tablulated values.

**Comment by oschulz** [comment]
The human eyes is also quite sensitive to small differences in certain ranges of the RGB color space (because it's so very non-linear, perceptually). It might be best to just use the "official" values.

**Comment by tbreloff** [comment]
> The human eyes is also quite sensitive to small differences in certain ranges of the RGB color space (because it's so very non-linear, perceptually). It might be best to just use the "official" values.

I'm staring at contour plots using the original list vs a sampled list (less than 10% of the values), and I can't see the tiniest difference.  

> Or does the lookup speed depend on the size of the table (I would assume not)?

It does currently, because I support shifting/skewing/warping color gradients.  It isn't a simple table lookup.

The optimal solution would be another gradient type which is evenly spaced so that a table lookup would be possible, but that doesn't seem important enough at the moment.

**Comment by tbreloff** [comment]
I'm almost done adding these, and I'm planning to switch the default colormap to inferno.  Does anyone have objections to that?

Right now I am sampling 30 colors from each list, evenly selected and including the endpoints.  We can change that later if we decide it doesn't look ok (but I doubt you'll notice).

**Comment by tbreloff** [comment]
See: https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/scratch/colormaps.ipynb

Changes are pushed to the dev branch.  This should work now:

```julia
using Plots

x = 1:0.3:20
y = x
f(x,y) = sin(x) + cos(y)
contour(x, y, f, fill = true, c = :viridis)
```

**Comment by oschulz** [comment]
>It does currently, because I support shifting/skewing/warping color gradients. It isn't a simple table lookup. The optimal solution would be another gradient type which is evenly spaced

Ah, ok, I get it. Well, can always add a linear LUT gradient type later, right?

> Changes are pushed to the dev branch. This should work now

Thanks a bunch for adding this (and in record speed)! Would you be interested in adding the other three new color maps (magma, inferno, plasma) as well? Personally, I really like viridis, but the others may be good for certain situations - two of then start with black, and also a map with red/yellow for high values may sometimes be preferable to green/yellow (when high values mean "this is bad" ;-) ).

**Comment by oschulz** [comment]
Strike my last, you already added them, I saw ... sorry!

**Comment by oschulz** [comment]
> Changes are pushed to the dev branch. This should work now

It does, beautifully - thanks again, Tom!
