### ISSUE TITLE
Histogram: How can I get the same breaks/bins for both groups?

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#186]
Plots is taking 30 bins for each group by default and gives different breaks. How can I indicate the breaks or make it use the same bins for each group?

![image](https://cloud.githubusercontent.com/assets/2822757/14532035/d87f84b6-025f-11e6-8737-1aa52dac52bd.png)

**Comment by tbreloff** [comment]
This may not be currently supported, but you could produce it yourself without too much effort. Just make line plots filled to zero (step plot would be even easier). If you come up with a nice solution, please let me know.

**Comment by diegozea** [comment]
Is histogram/bar [dodge](http://docs.ggplot2.org/0.9.3.1/position_dodge.html) supported?

**Comment by tbreloff** [comment]
> How can I indicate the breaks or make it use the same bins for each group?

I put together a short notebook to show how to do this: https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/scratch/hist.ipynb

> Is histogram/bar dodge supported?

No... it could be either a recipe, similar to how I just did the hist notebook, or if backends support it directly (do they?) I could add an argument to specify the overlay method.

**Comment by diegozea** [comment]
Thanks! Nice notebook :) I haven't had enough time for trying it myself. 
[Gadfly](http://gadflyjl.org/geom_bar.html) has `:dodge` in bar `:position`, I don't know about other libraries.

**Comment by tbreloff** [comment]
I guess the best approach would be:

- [ ] Add an `edges` argument, which overrides `nbins` when set.
- [ ] Add an `overlap_policy` or something like that, which sets the appropriate backend setting, or maybe triggers a Plots recipe.

As every backend does histograms differently, I'd probably have to resort to a recipe for many.

**Comment by diegozea** [comment]
What is the difference between `edges` (MATLAB) and `breaks` (R) or `bins` (Numpy)? I used to think of `breaks` because of R.

`overlap` taking `Symbol`s or `Bool`s sounds good. How It will manage `stacked` histograms/bar plots?

**Comment by tbreloff** [comment]
> How It will manage stacked histograms/bar plots?

Same as for `dodge`, I suppose.  Either setting a backend parameter or choosing an alternative Plots recipe, depending on what's supported natively.

**Comment by oschulz** [comment]
> Add an edges argument, which overrides nbins when set.

I would *love* to have an `edges` (or `bins`) argument. At least with PyPlot, it could be passed through directly to it's `bins` argument. Some very common operations are just impossible to do without control over the bin width - like plotting a histogram together with the expected distribution:

* You either have to scale the (normalized distribution) by multiplying it with `n_entries * bin_width`, or
* you have to normalize the histogram, by setting the weight of all entries to `1 / (n_entries * bin_width)`.

I find myself needing both types of plot very often. Btw. support for something like PyPlot's `normed` argument would be awesome as well (I don't know how many other backends have something like it).

**Comment by oschulz** [comment]
Actually, for the PyPlot backend, at least, there's already a workaround: Using

    Plots.histogram(..., nbins = -10:0.1:10)

seems to work fine, since `nbins` seems to be passed through to PyPlot's `bins` unchanged.

**Comment by tbreloff** [comment]
Yes all of this should already work for pyplot. Pass an array for bins,
normed accepts a bool (though thats an alias), and weights is also
supported. Try it out and let me know if it works for you.

**Comment by oschulz** [comment]
> Yes all of this should already work for pyplot [...] let me know if it works for you.

Yes, it does - sorry, my bad, I missed that you had already added "normed". This is great, thanks!

**Comment by tbreloff** [comment]
I think this issue has been addressed... open a more specific issue if you don't agree

**Comment by diegozea** [comment]
Yes, this can be closed ;)
