### ISSUE TITLE
`_apply_recipe` depending on the Backend

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#188]
Is it possible to know the backend inside `_apply_recipe` to define arguments depending on that?

**Comment by spencerlyon2** [comment]
I would imagine that the API/design should be such that all functionality in `_apply_recipe` should go through standard Plots methods (meaning backend agnostic functions).

@tbreloff is that the right idea?

**Comment by tbreloff** [comment]
> all functionality in _apply_recipe should go through standard Plots methods (meaning backend agnostic functions)

This would be ideal, but if there's something that absolutely must know about the backend, you can always call `backend()` which gives a type or `backend_name()` which gives a symbol, and have an if-statement.

**Comment by diegozea** [comment]
Thanks!
