### ISSUE TITLE
Marginal distributions

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#189]
It would be great to have:

 - [x] marginal [histograms](https://stanford.edu/~mwaskom/software/seaborn/examples/hexbin_marginals.html)
 - [ ] marginal [density](https://stanford.edu/~mwaskom/software/seaborn/examples/joint_kde.html) plots
 - [ ] marginal [boxplots](http://sandymuspratt.blogspot.com.ar/2013/02/scatterplot-with-marginal-boxplots.html)
 - [ ] marginal [ticks](https://stanford.edu/~mwaskom/software/seaborn/examples/marginal_ticks.html)

I imagine a `xmarginal` and `ymarginal` (`marginal` for both) keyword arguments taking: `:boxplot`, `:histogram`, `:density`, `:ticks` or a [combination](https://stanford.edu/~mwaskom/software/seaborn/examples/regression_marginals.html) of those symbols (tuple).

**Comment by tbreloff** [comment]
These are all good ideas as recipes... I don't think they should be "built in" for Plots.

>marginal histograms
 marginal density plots
marginal boxplots

I need to allow a little more control over subplot layouts, but this should be done with linked subplots:

```julia
using Plots
pyplot(size=(500,400), grid=false)
n = 10000
x, y = randn(n), randn(n)

subplot(
    histogram(x),
    plot(),
    histogram2d(x, y, nbin=10),
    histogram(y, orientation=:h),
    link=true
)
```

> marginal ticks

A nice implementation would require the ability to draw over the plot... this functionality will vary heavily by backend.  I'm open to implementation ideas.

**Comment by tbreloff** [comment]
See #60

**Comment by tbreloff** [comment]
These are going in https://github.com/JuliaPlots/PlotRecipes.jl

![tmp](https://cloud.githubusercontent.com/assets/933338/15868831/7ba9e4ca-2cb7-11e6-9e58-86aae6b657f8.png)

**Comment by diegozea** [comment]
That's awesome! :)

**Comment by pkofod** [comment]
That is super cool! Yay for recipes

**Comment by tbreloff** [comment]
closing in favor of "Recipe ideas" issue
