### ISSUE TITLE
Lorenz attractor example segfaults

### ISSUE THREAD

**Issue by ahwillia** [tbreloff/Plots.jl#192]
I quickly tried the Lorenz attractor example on the front page of the documentation, but the code crashed:

```
ERROR: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("WeakValueDictionary instance has no attribute '_iterating'",)
```

My hypothesis is that this has something to do with my default matplotlib backend `qt5agg`. Haven't investigated this yet... Is there an easy way to switch this backend through Plots? It also might be worth noting this in the documentation if `qt5agg` is the culprit.

**Comment by tbreloff** [comment]
Does it crash if you run it from a clean session? (I.e start the REPL then immediately run it)

**Comment by ahwillia** [comment]
Yes. I should mention I checked out the most recent master. (When I was on
the last stable release, `Pkg.add("Plots")`, I had an error along the lines
of `zlab` is not a defined keyword arg).

**Comment by tbreloff** [comment]
The zlab error makes sense, as I recently added that. The python crash is weird though. Can you send the full output of a session that crashes? Do you have any issues with PyPlot (without Plots)?

**Comment by ahwillia** [comment]
Haven't been having any problems with PyPlot, but I haven't been trying to produce GIFs... I usually use `anim[:save]("foo.mp4")`

Below is what I get from pasting into the REPL:

```
signal (11): Segmentation fault: 11
PyObject_Malloc at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyString_FromStringAndSize at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
file_readlines at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalFrameEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalCodeEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalFrameEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalCodeEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalFrameEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalCodeEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalFrameEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalCodeEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalFrameEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyEval_EvalCodeEx at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
function_call at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
PyObject_Call at /Users/alex/anaconda/lib/libpython2.7.dylib (unknown line)
pycall at /Users/alex/.julia/v0.4/PyCall/src/exception.jl:78
show at /Users/alex/.julia/v0.4/PyCall/src/exception.jl:39
showerror at replutil.jl:83
julia_showerror_22627 at  (unknown line)
jlcall_showerror_22627 at  (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1691
anonymous at REPL.jl:101
with_output_color at util.jl:313
display_error at REPL.jl:99
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1691
print_response at REPL.jl:127
jlcall_print_response_22619 at  (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1691
print_response at REPL.jl:121
jlcall_print_response_22618 at  (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1691
anonymous at REPL.jl:624
run_interface at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_run_interface_17905 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1325
run_frontend at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
run_repl at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1325
_start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall__start_18579 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1325
true_main at /usr/local/bin/julia (unknown line)
main at /usr/local/bin/julia (unknown line)
Segmentation fault: 11
```

**Comment by tbreloff** [comment]
So you have a system-installed Julia, a buildbot installed Julia, and a local Anaconda distribution?  I don't know enough about your setup, but certainly if you have mismatched libraries (i.e. referencing multiple versions of a library) then python/PyCall will probably have occasional crashes.  It might be that other workflows you've done haven't had enough activity to trigger a crash, even though the memory may have been corrupted already.  This is going to be really hard for me to help debug, sorry to say.

The only suggestion I would try is to allow PyCall to install a local anaconda distribution using Conda.jl:

```julia
ENV["PYTHON"] = ""
Pkg.build("PyCall")
```

Let me know how it goes.

**Comment by tbreloff** [comment]
Also... if you install `wkhtmltopdf` (using homebrew?) then you could do this on the dev branch with the `plotly()` backend.  Or `plotlyjs()` might work, or `gr()`.

(please post your experience... it'll help the development tremendously)

**Comment by ahwillia** [comment]
Hmm. Apologies, I sort of shoot from the hip when setting up my libraries. Any quick pointers on how to make the install more sane?

Installed `wkhtmltopdf` via homebrew successfully. I don't have `plotlyjs()` or `gr()` backends installed... is there a preferred way to do that?

With `plotly()` backend got the following... (the `tmp.gif` file appears to be empty or maybe a bunch of white frames. I did get a pretty and interactive (but empty) 3d plot showing up after the `plt = path3d(...)` command executed (see screenshot).

```julia
julia> # initialize a 3D plot with 1 empty series
       plt = path3d(1, xlim=(-25,25), ylim=(-25,25), zlim=(0,50),
                       xlab = "x", ylab = "y", zlab = "z",
                       title = "Lorenz Attractor", marker = 1)
[Plots.jl] Initializing backend: plotly
WARNING: Keyword argument zlabel not supported with Plots.PlotlyBackend().  Choose from: [:annotation,:background_color,:color_palette,:fillrange,:fillcolor,:fillalpha,:foreground_color,:group,:label,:layout,:legend,:linecolor,:linestyle,:linetype,:linewidth,:linealpha,:markershape,:markercolor,:markersize,:markeralpha,:markerstrokewidth,:markerstrokecolor,:markerstrokestyle,:n,:nbins,:nc,:nr,:show,:size,:title,:windowtitle,:x,:xlabel,:xlims,:xticks,:y,:ylabel,:ylims,:yticks,:xscale,:yscale,:xflip,:yflip,:z,:zcolor,:tickfont,:guidefont,:legendfont,:grid,:levels,:xerror,:yerror,:ribbon,:quiver,:orientation,:polar]
WARNING: Keyword argument zlims not supported with Plots.PlotlyBackend().  Choose from: [:annotation,:background_color,:color_palette,:fillrange,:fillcolor,:fillalpha,:foreground_color,:group,:label,:layout,:legend,:linecolor,:linestyle,:linetype,:linewidth,:linealpha,:markershape,:markercolor,:markersize,:markeralpha,:markerstrokewidth,:markerstrokecolor,:markerstrokestyle,:n,:nbins,:nc,:nr,:show,:size,:title,:windowtitle,:x,:xlabel,:xlims,:xticks,:y,:ylabel,:ylims,:yticks,:xscale,:yscale,:xflip,:yflip,:z,:zcolor,:tickfont,:guidefont,:legendfont,:grid,:levels,:xerror,:yerror,:ribbon,:quiver,:orientation,:polar]

julia> # build an animated gif, saving every 10th frame
       @gif for i=1:n
           dx = σ*(y - x)     ; x += dt * dx
           dy = x*(ρ - z) - y ; y += dt * dy
           dz = x*y - β*z     ; z += dt * dz
           push!(plt, x, y, z)
       end every 10

WARNING: Tried to create gif using convert (ImageMagick), but got error: could not spawn `convert -delay 5 -loop 0 /var/folders/hf/29fnnkpx3zb2dj49q5m2czkw0000gn/T/tmpEDkCdf/*.png -alpha off /Users/alex/tmp.gif`: no such file or directory (ENOENT)
Will try ffmpeg, but it's lower quality...)
INFO: Saved animation to /Users/alex/tmp.gif
```

<img width="479" alt="screen shot 2016-04-21 at 2 02 19 pm" src="https://cloud.githubusercontent.com/assets/636625/14724250/c8944a5e-07c9-11e6-8589-eaa9d6f332b2.png">

**Comment by tbreloff** [comment]
>  Tried to create gif using convert (ImageMagick)

You'll need to install imagemagick to create the gif.  Eventually I should use ImageMagick.jl, but for now I think you can install with `brew install imagemagick`?

The image you posted is probably the output from that first `path3d(...)` call (when it was empty).  Just type `plt` in the REPL and it should display the final plot.

**Comment by ahwillia** [comment]
Thanks, typing `plt` into REPL indeed produces a the expecting 3d plot. I installed `imagemagick` and saved the gif successfully this way... But it is **still a bunch of white blank frames** when I open with preview or in chrome/safari.

```julia
INFO: Saved animation to /Users/alex/tmp.gif
Plots.AnimatedGif("/Users/alex/tmp.gif")
```

Interestingly I still get the `zlabel` and `zlim` "aren't supported with plotly backend" warnings... But the specified label and axis limits show up just fine.

**Comment by tbreloff** [comment]
Still a bunch of white frames? That's weird. Any chance you have IJulia installed? Does it work in a notebook?

**Comment by ahwillia** [comment]
Yep:

<img width="542" alt="screen shot 2016-04-21 at 3 54 32 pm" src="https://cloud.githubusercontent.com/assets/636625/14726741/7905bc06-07d9-11e6-9f87-9348c22acb51.png">

Also:

<img width="546" alt="screen shot 2016-04-21 at 3 55 43 pm" src="https://cloud.githubusercontent.com/assets/636625/14726751/8856810e-07d9-11e6-94d1-bd71fb5d130e.png">

**Comment by tbreloff** [comment]
:( 

Ok I'll try to reproduce on my end... Not sure what could be going wrong. Just to check... Do you have the latest dev version of Plots?

**Comment by ahwillia** [comment]
Yep, I did `julia> Pkg.checkout("Plots","dev")`

Best of luck tracking this down... I really like the semantics of `@gif for ... end every N`. I hope to get it working soon!

**Comment by tbreloff** [comment]
Ok I can reproduce the blank gif for the plotly backend on my OSX laptop... which is good for you but bad for me ;)  The example worked fine with the pyplot backend though, so I suspect you have an issue with your python setup, not with Plots.

Also this should work for plotlyjs, except that I'm waiting on [a PR](https://github.com/JuliaIO/ImageMagick.jl/pull/38) to be merged.

I'll try to dig into plotly... I only just added support for png generation, and I've never run it on a mac, so it's not terribly surprising that there are quirks.

**Comment by tbreloff** [comment]
I can confirm that `wkhtmltoimage` just isn't working on the mac (always produces a white screen).  Nothing to do with the Plots calls.  I'll keep investigating.

**Comment by tbreloff** [comment]
I'm going to close this as the topic got diverted towards wkhtmltoimage issues.
