### ISSUE TITLE
Support hist2d for PyPlot backend

### ISSUE THREAD

**Issue by oschulz** [tbreloff/Plots.jl#193]
Currently, hist2d ist mapped to hexbin for PyPlot. hexbin is great, but sometimes a rectangular binning is preferable - would it be possible to support matplotlib's hist2d as well?

**Comment by tbreloff** [comment]
Yes... I will make this change while working on #194

**Comment by oschulz** [comment]
Thanks!!

**Comment by tbreloff** [comment]
This is supported on the tb_pyplot branch now.
