### ISSUE TITLE
Setting aspect ratio

### ISSUE THREAD

**Issue by dpsanders** [tbreloff/Plots.jl#195]
I cannot find an option to set the aspect ratio, as in `axis("image")` or `axis("equal")` in PyPlot, e.g. for getting `spy` of a square matrix to look right.

**Comment by tbreloff** [comment]
This doesn't exist natively... I'd have to think through all the scenarios that this might be used, and come up with a good abstraction. 

In the meantime you can always set the xlim/ylim manually, or call PyPlot's method directly.

**Comment by dpsanders** [comment]
The xlim and ylim are equal -- it's the plot shape itself that is wrong (rectangular default).
How can I set the plot shape in a backend-agnostic way?

How do I call PyPlot's method directly and have it affect the `Plots`-generated plot?
e.g. 
```
Plots.spy(Z)
PyPlot.axis("image")
```
doesn't work.

**Comment by tbreloff** [comment]
The size keyword takes a (width, height) tuple. You can set a default when you set the backend, or set it for just one plot. 

using Plots; pyplot(size = (500,500))

**Comment by dpsanders** [comment]
Thanks. This feels a bit too coupled to the backend somehow, though.

**Comment by tbreloff** [comment]
What's your full example? Maybe I can help make it more Plots-like.

**Comment by diegozea** [comment]
I think would be great to have a keyword argument `ratio` taking parameters like `:free` (default) or `:equal` to internally set the necessary stuff for each backend without change the size (even if that means large margins). Other option could be and `equalratio` or `ratio` taking a `Bool` value (default to `false`) or a tuple of them for (x,y) or (x,y,z). For example, if you want to fix only x and y in a 3D plot, you will use `(true, true, false)`.

**Comment by tbreloff** [comment]
Done.  See: 5dfd3d2f5d74b32f8024f46a6ed743fb80d513f0

It only works in PyPlot on the dev branch.  Set to `:none` (default), `:equal`, or give a "height/width" ratio (a number):

![tmp](https://cloud.githubusercontent.com/assets/933338/14831711/e5cc5324-0bc4-11e6-9053-0ea66551104c.png)

If this works for you, feel free to close the issue.

**Comment by diegozea** [comment]
Awesome! It works fine for me. Thanks!
