### ISSUE TITLE
3d scatter plots: not supporting indexed variables 

### ISSUE THREAD

**Issue by mauriciotm** [tbreloff/Plots.jl#197]
I have a code that was running okay with the last version, however, after the update I am having a typo error when trying to plot a scatter3d plot with three vectors: 

LoadError: PyError (:PySequence_GetItem) <type 'exceptions.TypeError'>
TypeError("'Patch3DCollection' object does not support indexing",)

Is there anyway how to fix it according to the new definition? 

Thank you.

**Comment by tbreloff** [comment]
Yes this error is on my radar. I have a planned refactor of PyPlot... I expect this will get resolved during that.

**Comment by tbreloff** [comment]
Ref: #194

**Comment by tbreloff** [comment]
This is fixed on the tb_pyplot branch
