### ISSUE TITLE
Support optional "weights" argument for histograms

### ISSUE THREAD

**Issue by oschulz** [tbreloff/Plots.jl#198]
Often, one needs to histograms weighted values. matplotlib (I hope other backends, too) has a "weights" argument for 1D and 2D histograms. This also necessary to plot a histogram for data that is already binned (e.g. a StatsBase Histogram or so). Would it be possible to support this in Plots.jl?

**Comment by tbreloff** [comment]
This is implemented now with a new `weights` keyword... it'll be merged when I finish with the pyplot refactor (see the `tb_pyplot` branch).

**Comment by oschulz** [comment]
Great - thanks, Tom!
