### ISSUE TITLE
legend = false not working for heatmap and most backends

### ISSUE THREAD

**Issue by jbrea** [tbreloff/Plots.jl#199]
Hi

great package!

I just realized that for most backends
the setting `legend = false` does not remove 
the legend/colorbar for heatmaps (works for pyplot).

Is this easy to fix?

**Comment by tbreloff** [comment]
Which backends did you test? It may be easy or hard... Depends on the backend. If there's something high priority for you a PR is the best way to ensure it gets done! Otherwise I'll probably get to it eventually.

**Comment by tbreloff** [comment]
Just tested... works on pyplot, gr/plotly don't hide the colorbar, pgfplots doesn't support heatmaps yet.  All hide the legend.  Closing in favor of the meta-issues for each backend.
