### ISSUE TITLE
Ribbons

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#20]
Similar to [this example](http://gadflyjl.org/geom_ribbon.html), I'd like an easy way to add this to a plot.  I think it should be attached to a series (and not its own series).. possibly with a `ribbon` keyword arg.  Some possible syntax:

```
# add a ribbon, centered around y, with width 0.5
plot(y; ribbon = 0.5)

# add a ribbon, centered around y, where the width varies randomly
plot(y; ribbon = rand(length(y)))

# tuple of vectors... explicit min/max coords
plot(y; ribbon = (y-0.2, y+0.8))

# vector of tuples... explicit min/max coords
plot(y; ribbon = [(z-0.5, z+rand()) for z in 1:length(y)])
```

Probably should support `ribboncolor`, etc args as well.

**Comment by tbreloff** [comment]
This might be easiest to implement as a `fillfrom` argument... since `fillto` is defined to fill an area from `y` to `fillto`... this means we are already defining a `fillfrom` value and implicitly setting it to `y`.  Make it explicit (default is that `y == fillfrom`) and we can draw ribbons.  

That being said, I still think the ribbon argument can be shorthand for this functionality...

**Comment by diegozea** [comment]
+1 to ribbons on `Plots.jl`. Also would be great to have error bars like [Gadfly](http://dcjones.github.io/Gadfly.jl/geom_errorbar.html).

**Comment by tbreloff** [comment]
Heh... yes!  I was thinking about that yesterday, and never got around to creating an issue... gonna do that now and link from here.

**Comment by tbreloff** [comment]
Closing in favor of #143
