### ISSUE TITLE
Set default backend?

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#200]
Is it possible to set the default backend to Gadfly instead of PyPlot?

**Comment by tbreloff** [comment]
I think the best approach is to add the setup to your `.juliarc.jl` file:

```julia
using Plots
gadfly()
```

Then you can set your preferred defaults for other settings as well.

I don't think I'm going to change the standard default, as PyPlot generally has more features than Gadfly... there's very little that works in Gadfly but **not** in PyPlot.

**Comment by spencerlyon2** [comment]
What about an environment variable PLOTS_DEFAULT_BACKEND?

Then you could set that in your juliarc, but not have to load plots
whenever julia starts

// Spencer

**Comment by tbreloff** [comment]
Yes that would be a reasonable alternative... I'm happy to add this right now (but it won't be merged until I finish the pyplot refactor).

**Comment by KristofferC** [comment]
See https://github.com/timholy/ProfileView.jl/blob/8bf5312fda0f7137c2abe30a67581ba1b1b3669a/src/ProfileView.jl#L46

**Comment by tbreloff** [comment]
See d4ccf0ec624bbbaf2ab613f623121ded716d6a9e
