### ISSUE TITLE
subplot from existing plots ignores layout kw

### ISSUE THREAD

**Issue by jw3126** [tbreloff/Plots.jl#202]
The layout keyword argument is ignored, if one creates a subplot from existing plots. For example

```
subplot(plot(randn(3)),
    plot(randn(3)),
    plot(randn(3)),
    layout=[1, 1, 1]
)
```
gives
![plt](https://cloud.githubusercontent.com/assets/7261506/14785734/889cbf22-0afc-11e6-843b-1af8d89d9c3c.png)

**Comment by tbreloff** [comment]
Thanks... found and fixed.  It'll be available when I merge the `tb_pyplot` branch.
