### ISSUE TITLE
Heatmap using non-numeric (categorical) colormaps

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#204]
I want to include in MIToS some visualization for Multiple Sequence Alignments like [alignfigR](http://htmlpreview.github.io/?https://github.com/sjspielman/alignfigR/blob/master/vignettes/introduction.html). 
Is there a way with Plots to do a [heatmap like plot for categorical variables](http://stackoverflow.com/questions/12998372/heatmap-like-plot-but-for-categorical-variables)?

**Comment by tbreloff** [comment]
This works right now on the `tb_pyplot` branch:

![tmp](https://cloud.githubusercontent.com/assets/933338/14795480/b84c7588-0af6-11e6-8132-efa8e503cbeb.png)

**Comment by diegozea** [comment]
I were asking for a case where `z` is the categorical/`group`ing variable.

**Comment by tbreloff** [comment]
I'm not sure I understand.  (Your link doesn't work... maybe fixing that would help explain?)

**Comment by diegozea** [comment]
I'm sorry. The link is: [http://stackoverflow.com/questions/12998372/heatmap-like-plot-but-for-categorical-variables](http://stackoverflow.com/questions/12998372/heatmap-like-plot-but-for-categorical-variables)

**Comment by tbreloff** [comment]
So really what you're asking is if the colormap can have non-numeric data as it's values?  I don't think it's possible out of the box... it's on the list.

**Comment by diegozea** [comment]
Exactly, I renamed the issue ;) Thanks!

**Comment by tbreloff** [comment]
Note: here's one possible method for pyplot: https://gist.github.com/jakevdp/8a992f606899ac24b711

**Comment by tbreloff** [comment]
Getting closer:

![tmp](https://cloud.githubusercontent.com/assets/933338/14826873/d7111d36-0bad-11e6-8890-e9a2c9ad0188.png)

I want to accept a `Plots.ColorVector` which makes it a discrete colormap.  Right now it only accepts a `Plots.ColorGradient` with a continuous colormap.  It works though! (sort of)

**Comment by tbreloff** [comment]
Good progress!

![tmp](https://cloud.githubusercontent.com/assets/933338/14827521/ce00f0a6-0bb0-11e6-87a2-8dc8b73861ad.png)

**Comment by diegozea** [comment]
That looks really great!

**Comment by diegozea** [comment]
I'm getting the following error with `axiscolor=nothing` and also with `border=nothing`

```
MethodError: `convertColor` has no method matching convertColor(::Void)
Closest candidates are:
  convertColor(::Any, !Matched::Real)
  convertColor(::Any, !Matched::Void)

 in getPyPlotColor at /home/dzea/.julia/v0.4/Plots/src/backends/pyplot.jl:91
 in updateAxisColors at /home/dzea/.julia/v0.4/Plots/src/backends/pyplot.jl:849
 in finalizePlot at /home/dzea/.julia/v0.4/Plots/src/backends/pyplot.jl:1062
 in writemime at /home/dzea/.julia/v0.4/Plots/src/backends/pyplot.jl:1108
 in writemime at /home/dzea/.julia/v0.4/Plots/src/output.jl:118
 in writemime at multimedia.jl:43
 in sprint at iostream.jl:206
 in display_dict at /home/dzea/.julia/v0.4/Plots/src/Plots.jl:280
```

**Comment by diegozea** [comment]
Also I'm getting the following error:

```
@show z'
heatmap(z', yflip=true, grid=false, ratio=:equal)
```

```
z' = ASCIIString["B" "C" "A" "B" "B" "C" "C" "A" "A" "A" "A" "C" "C" "B" "B"
            "A" "C" "C" "B" "B" "C" "C" "A" "A" "B" "A" "A" "A" "C" "C"
            "B" "A" "C" "A" "B" "B" "A" "C" "B" "C" "B" "C" "B" "C" "C"
            "C" "A" "C" "B" "B" "A" "B" "B" "B" "A" "A" "C" "C" "A" "B"]
LoadError: type Void has no field surf
```

**Comment by diegozea** [comment]
Why am I seeing blue lines with the recipe? 

![image](https://cloud.githubusercontent.com/assets/2822757/15007069/36dadd34-11ac-11e6-99ba-b8967cc2b237.png)

**Comment by tbreloff** [comment]
I think these issues are solve now?

**Comment by diegozea** [comment]
Yes, It's solved :D Thanks @tbreloff !

![image](https://cloud.githubusercontent.com/assets/2822757/15625334/61024e8c-2479-11e6-89c3-3cc5db165361.png)

**Comment by diegozea** [comment]
Hi! I've found that the GR backend doesn't use a categorical colormap for categorical values:

![imagen](https://user-images.githubusercontent.com/2822757/37534053-f1b2343a-2943-11e8-89ee-16ca008c7508.png)

The code of the example is the same that the one that tbreloff commented on 26 Apr 2016:
```julia
using Plots
gr()
n, m = 15, 4
xs = [string("x",i) for i in 1:n]
ys = [string("y",i) for i in 1:m]
z = rand(["A","B","C"], n, m)
heatmap(xs, ys, z, yflip=true, c=[:red, :blue, :green], l=(1,:black),
grid=false, axiscolor=nothing, border=nothing, size=(600,300))
```

**Comment by youngjaewoo** [comment]
I can't replicate this example from above.

```
n,m = 15,4
xs = [string("x",i) for i=1:n]
ys = [string("y",i) for i=1:m]
z = rand(["A","B","C"], n, m)
heatmap(xs, ys, z, yflip=true, c=[:red :blue :green])
```
![image](https://user-images.githubusercontent.com/8863211/58502495-9e06ea00-8154-11e9-9bd5-a6e36319443d.png)

Any idea?

**Comment by mkborregaard** [comment]
Does it work with the pyplot backend?

**Comment by youngjaewoo** [comment]
I can't test PyPlot in my machine at the moment, but think I figured out the problem.
```
n,m = 15,4
xs = [string("x",i) for i=1:n]
ys = [string("y",i) for i=1:m]
z = rand(["A","B","C"], n, m)
heatmap(xs, ys, z, yflip=true, c=cgrad([:red, :blue, :green]))
```
![image](https://user-images.githubusercontent.com/8863211/58511859-b46b7080-8169-11e9-91e1-a4c15f7d3758.png)

Looks like syntax for color input has changed since the last post where discrete colors aren't allowed.
