### ISSUE TITLE
Scales

### ISSUE THREAD

**Issue by pkofod** [tbreloff/Plots.jl#205]
If I write `xscale = :log` does it mean log base 10 as on many calculators, or log base e as mathematicians would have it? I get `log2`, `log10` and `ln`, but what as `log`? @tbreloff Is it consistent between backends, or does it do what the backend would do given a "log" keyword?

**Comment by tbreloff** [comment]
It's an alias for log10.  It's consistent.  See: https://github.com/tbreloff/Plots.jl/blob/dev/src/args.jl#L106

**Comment by pkofod** [comment]
Didn't catch that, thanks.
