### ISSUE TITLE
GR heatmap issue

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#207]
@jheinen The matrix only has 0 and 1 values, why are there white points in the heatmap?

![image](https://cloud.githubusercontent.com/assets/2822757/14866614/cd37cc34-0cc4-11e6-8c50-38fb3af0d4ba.png)

@tbreloff sometimes categorical values are numeric values, like in this case. Related to https://github.com/tbreloff/Plots.jl/issues/204

**Comment by tbreloff** [comment]
> sometimes categorical values are numeric values

Yeah I had this thought too.  I was thinking there could be some sort of keyword to choose from `(:auto, :discrete, :continuous)`, so that you could override the current behavior if so desired.  I'm open to ideas/names.

**Comment by jheinen** [comment]
@diegozea : I'll have to check this. Do you have a minimal exaple to reproduce the problem?

**Comment by diegozea** [comment]
@jheinen My code was:

```julia
using MIToS: Pfam, MSA
using Plots
msafile = downloadpfam("PF00030")
msa = read(msafile, Stockholm, checkalphabet=true)
gr()
heatmap(convert(Matrix{Int}, msa .== GAP)')
```

@tbreloff Having a `scale` keyword argument with a good default `:auto` ( `:discrete` for `Bool`, `Char`, strings and `PooledDataArray`) but being able to indicate `:discrete` or `:continuous` to change the default choice would be great.

**Comment by jheinen** [comment]
Using the "native" GR cell array function gives the following (correct) result:

![t](https://cloud.githubusercontent.com/assets/5718244/14899731/baa5c9c6-0d8d-11e6-9e92-5ed25f14ac57.png)

As you can see, there are only 2 colors. The display driver, however, tries to smooth the image (by interpolating black and white cells with grey levels). The same effect can be observed when viewing the PDF output using Apple's Preview app, as opposed to Acrobat Reader, which does **not** "interpolate".

For PDF files, I can probably find a solution to disable the interpolation and/or resampling.

This was my test scenario:

```
using MIToS: Pfam, MSA
using GR

msafile = downloadpfam("PF00030")
msa = read(msafile, Stockholm, checkalphabet=true)
a = convert(Matrix{Int}, msa .== GAP)'

beginprint("t.png")
w, h = size(a)
selntran(0)  # use complete window
cellarray(0, 1, 0, 1, w, h, a)
endprint()
```

**Comment by diegozea** [comment]
Will It be possible for `Plots.jl`to avoid the interpolation?

**Comment by tbreloff** [comment]
I think this is fixed now
