### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#21]
I'd like an easy way to support annotations, which will need to be mapped to a 3-tuple `(x, y, annotation)`.  So maybe:

```
# create a text annotation with the value of y under each point (3-tuple of vectors)
plot(x, y; annotations = (x, y, map(string,y)), annotationguide = :under)

# create a text annotation with the value of y automatically positioned for each point (vector of 3-tuples)
plot(x, y; annotations = [(x[i], y[i], string(y[i])) for i in 1:length(y)], annotationguide = :auto)
```

Annotations could be text, shapes, images, svg, or anything else that a backend might support.

- [x] Gadfly
- [x] Immerse
- [x] PyPlot
- [x] Winston
- [ ] Qwt

**Comment by tbreloff** [comment]
First steps are done... basic text annotation works for Gadfly.  I want to figure out a generic way to add other types of annotations.

![tmp](https://cloud.githubusercontent.com/assets/933338/10138683/b350e272-65cd-11e5-962d-fb53a5669d60.png)

**Comment by tbreloff** [comment]
This is done for every backend except UnicodePlots... closing

**Comment by SimonEnsemble** [comment]
Great feature. Is there a way to change the font size of the annotation? Something like:
`annotate!([(.6, 1.5, L"L = M\frac{KP}{1+KP}")], fontsize=48)`
Thanks.

**Comment by mkborregaard** [comment]
Try `annotate!([(.6, 1.5, text(L"L = M\frac{KP}{1+KP}",48))])`

**Comment by Sounakdas013** [comment]
how to annotate with images in julia?
