### ISSUE TITLE
Issue with subplot

### ISSUE THREAD

**Issue by rveltz** [tbreloff/Plots.jl#212]
Hi,
The following code works:

`Plots.pyplot()`
`Plots.wireframe(ones(4,4))`

but not this one:

`Plots.pyplot();
Plots.subplot(Plots.wireframe(ones(4,4)),Plots.wireframe(ones(4,4)))`

Can you help me please?

Note: everything works fine with GR.

**Comment by tbreloff** [comment]
Seems like a bug and that the matplotlib axes aren't being set to 3D... I'll take a look.

**Comment by tbreloff** [comment]
Seems to be fixed on latest dev
