### ISSUE TITLE
Wrong png for gadfly's boxplot

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#214]
## Code and IJulia plot:

![image](https://cloud.githubusercontent.com/assets/2822757/14929039/c0faf2b4-0e5b-11e6-910f-453d60ddbc74.png)

## Saved png:

![rho](https://cloud.githubusercontent.com/assets/2822757/14929004/8c74a44a-0e5b-11e6-89b5-884e9b0b3199.png)

**Comment by tbreloff** [comment]
~~I suspect you have an outdated Compose.jl?~~  I fixed this in a PR: https://github.com/dcjones/Compose.jl/pull/192.  It was never merged!  I'll bump it again...

**Comment by tbreloff** [comment]
The PR was merged!  So `Pkg.checkout("Compose")` should fix it.  Let me know if you still see any problems.

**Comment by diegozea** [comment]
Great! Thanks!
