### ISSUE TITLE
Plots missing in Jupyter PDF export

### ISSUE THREAD

**Issue by oschulz** [tbreloff/Plots.jl#215]
When downloading a PDF from Jupyter, or when using `jupyter nbconvert --to=PDF`, all plots generated with Plots.jl are missing.

I tested this with both the PyPlot and the Gadfly backend - no plots. However, when I plot with PyPlot or Gadfly directly, the plots do show up in the PDF.

**Comment by tbreloff** [comment]
I suspect it's from: https://github.com/tbreloff/Plots.jl/blob/005ce11313ca2ff927f7bc29da74743e02d19278/src/Plots.jl#L273

I have this to solve an annoyance that multiple writemime methods are called when displaying in IJulia.  I'm happy to hear suggestions for fixes that would not re-introduce that issue...

**Comment by oschulz** [comment]
Uh, I'm really not an expert there ... any idea how PyPlot & Co. handle this themselves?

**Comment by pkofod** [comment]
Had the same problem the other day. I just printed to pdf. It's not a solution, rather a workaround, but might be ok for now.

**Comment by tbreloff** [comment]
This is sort of related to https://github.com/stevengj/PyPlot.jl/issues/197.  I want to have better control over what gets displayed with IJulia, and I need to figure out a good approach...

**Comment by tbreloff** [comment]
If anyone knows how IJulia does PDF export and can offer suggestions, please do.

**Comment by tbreloff** [comment]
closing in favor of meta-issue
