### ISSUE TITLE
Streamplot question (continuation from Gitter question)

### ISSUE THREAD

**Issue by goedman** [tbreloff/Plots.jl#217]
Hi Tom,

I switched away from Gitter as I couldn't figure out how to upload/include a files.

You suggested to create a 'recipe'. You mean just a small example?

PyPlot.streamplot certainly works nicely. Is that what you mean? This particular example might contain too much (solving an underlying linear differential equation, but that's what I needed).

![streamplot](https://cloud.githubusercontent.com/assets/52200/14987802/d7047858-1105-11e6-9def-e31561c983f9.png)

[streamplot03.pdf](https://github.com/tbreloff/Plots.jl/files/247137/streamplot03.pdf)

**Comment by tbreloff** [comment]
@goedman thanks.  certainly we could consider just passing through parameters into matplotlib's streamplot function, but the more ideal scenario would be to build a generic recipe within Plots so that other backends (which don't necessarily implement this) can benefit.

For an example of what I mean: https://github.com/tbreloff/Plots.jl/blob/master/src/recipes.jl#L264-L307

An example notebook:
https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/quiver.ipynb

This "recipe" takes in all the processed arguments from the user's plots call, and allows you to replace them as needed to create a new set of plotting commands.  For the quiver, it takes the x/y coordinates passed into the plot call, and combines them with the (u,v) pairs defining velocity vectors, then replaces the series with the coordinates required to draw the arrows.

It's fully generic... backends only need implement lines, shapes, etc.

Of course until someone writes a generic recipe, it would be fine to just call the matplotlib method and pyplot would be the only backend that supports it.  If you want to take a stab at that, you can model it on: https://github.com/tbreloff/Plots.jl/blob/master/src/backends/pyplot.jl#L626-L639

**Comment by tbreloff** [comment]
Also:

> I switched away from Gitter as I couldn't figure out how to upload/include a files.

I think you can just drag and drop?

> streamplot03.pdf

it would be a little more ideal if you could post code directly instead of an included pdf... before a code block add 3 backticks followed by the word "julia", then close the block with 3 backticks:

\`\`\`julia
#put your code here
\`\`\`

**Comment by goedman** [comment]
HI Tom,

Thanks for your responses. Below the code in a more useful way.

The pointer to quiver in the recipes.jl is very helpful. I'll see if I can come up with a generic Plots.jl streamplot.

Regards,
Rob

```
#
# Based on the EDx course Math 226.2 by Paul Blanchard
# Julia version derived by Rob J Goedman
# April 2016
#

using Plots
pyplot(reuse=true)
plot()

#
# y'[t] = -x[t]
# x'[t]= -3 x[t] + y[t]
#
# or
#
# y''[t] = -3 y'[t] + y[t]
#
# In matrix form:
#
m = [-3 1; -1 0]

e = eigfact(m)
e |> display
println()

#
# 2 negative eigenvalues: slow eigen line will act as a sink
#

function xf(k::Vector{Float64}, t::Float64)
  k[1] * e[:vectors][1, 1] * exp(e[:values][1] * t) +
    k[2] * e[:vectors][1, 2] * exp(e[:values][2] * t)
end

function yf(k::Vector{Float64}, t::Float64)
  k[1] * e[:vectors][2, 1] * exp(e[:values][1] * t) +
    k[2] * e[:vectors][2, 2] * exp(e[:values][2] * t)
end

t1 = -5.0:0.01:5.0
k = e[:vectors]\e[:vectors][:,1]
# Extend eigen lines to cover full range
xfast = [xf(-k, t) for t in t1]
yfast = [yf(-k, t) for t in t1]
xfast = [xfast; [xf(k, t) for t in t1]]
yfast = [yfast; [yf(k, t) for t in t1]]

t2 = -5.0:0.01:5.0
k = e[:vectors]\e[:vectors][:,2]
xslow = [xf(-k, t) for t in t2]
yslow = [yf(-k, t) for t in t2]
xslow = [xslow; [xf(k, t) for t in t2]]
yslow = [yslow; [yf(k, t) for t in t2]]

t3 = -0.15:0.01:5.0
k = e[:vectors]\[-3, 2]
xvals = [xf(k, t) for t in t3]
yvals = [yf(k, t) for t in t3]

N = 40
vals = collect(linspace(-6, 6, N))
x = vals'
y = vals
for i in 1:N-1
  x = vcat(x, vals')
  y = hcat(y, vals)
end

u = zeros(N, N)
u = m[1, 1]*x + m[1, 2]*y
v = zeros(N, N)
v = m[2, 1]*x + m[2, 2]*y

PyPlot.streamplot(x, y, u, v, color=u, density=0.7)
plot!(title = "Streamplot", xaxis=("x(t)", (-4,4)), yaxis=("y(t)", (-4,4)))
plot!(xvals, yvals, color=:black, linewidth=2, linestyle=:dot, lab="Y[0]=[-3,2] soln")
plot!(xfast, yfast, color=:red, linewidth=2, lab="Fast eigen line")
plot!(xslow, yslow, color=:green, linewidth=2, lab="Slow eigen line")

png("/Users/rob/Desktop/streamplot.png")
```

**Comment by tbreloff** [comment]
The part that will be tough (impossible?) for most backends is adding a color gradient to a line.  This is something that I want to be possible, but might not happen generically in the near-term.

**Comment by goedman** [comment]
Probably, you know that way better than me. But that feature is not a top priority. Thanks for letting me know though.

In my case, your quiver notebook example is an eye-opener, I might be able to get away with 2 separate graphs, a stream plot and a simple function plot (x(t), y(t) solutions as function to time). 

Regards,
Rob

**Comment by tbreloff** [comment]
Ref: #218

**Comment by lobingera** [comment]
just for my curiosity, what actually is displayed with the color gradient on the streamlines? And how would be the color calculated? 
I'll look into a few Compose.jl/Gadfly problems later today and from rendering perspective, putting color gradient onto a line should not be an issue.

**Comment by tbreloff** [comment]
@lobingera If you're able to contribute to https://github.com/tbreloff/Plots.jl/issues/218 for Gadfly it would be awesome, and would enable this streamplot functionality.

**Comment by goedman** [comment]
@lobingera You are quite right, in my use case (stream plots for linear ode's), the arrowheads are more important. That's why I considered that feature not a top priority.

If color is available, it could maybe show the magnitude of the derivative? Having used various different versions of VectorPlot and StreamPlot in Mathematica I have found that varying the arrow lengths and arrow head sizes does not always work very well. Kind of like in the final example of quiver.jl towards the edges where arrows are almost dots.
