### ISSUE TITLE
Support color gradients/vectors for line segments

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#218]
For pyplot, the implementation might use a `LineCollection`, as seen in this SO answer: http://stackoverflow.com/a/17241345/5075246

**Comment by pkofod** [comment]
I think pgfplots supports this

**Comment by tbreloff** [comment]
Cool... you could enable it just by checking the type of the linecolor:

```julia
C = typeof(d[:linecolor])
if C <: ColorGradient
    # handle multicolored line segments
    # note: we probably want to add a keyword line_z which mirrors the existing marker_z
elseif C <: ColorVector
    # map the colors directly (no need for line_z)
else
    # normal handling
end
```

I'll need to think if there's a more generic way to do this, so we don't have to repeat this if-block in every backend.

**Comment by diegozea** [comment]
This is a nice feature! I used to use it with [ROCR](http://rocr.bioinf.mpi-sb.mpg.de/rocr_gallery.html) to have and idea of the cutoff/threshold value at any point of the ROC curve.

**Comment by tbreloff** [comment]
This is implemented in the pyplot backend.  I'll add a checkbox to the meta-issues for the other backends, then close this.

```julia
using Plots
y = cumsum(randn(500))
plot(y, line_z = y, w = 3)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/16057373/ccb381e2-3247-11e6-9962-eccf0c38cca7.png)
