### ISSUE TITLE
spy seems broken

### ISSUE THREAD

**Issue by jebej** [tbreloff/Plots.jl#219]
The spy function does not seem to work currently. Also, it seems that the gadfly backend has not been defined for it, when the Gadfly spy function actually exists.

![capture](https://cloud.githubusercontent.com/assets/11141558/15002057/199d3b54-116b-11e6-8c43-cfa12b9895d6.PNG)

**Comment by jebej** [comment]
I should note that this is not just a colorscale issue. When plotting in Plotly, I can see that the z values are wrong: all the nonzero values have been changed to 1.

**Comment by tbreloff** [comment]
I think this behavior matches matplotlib... In my mind it's a boolean plot
whether there's a nonzero value. Any opinions on this one? How would we see
the sparsity of randn(100,100)? So many numbers would have the same color
as the zeros... It would require some special logic.

**Comment by jebej** [comment]
You are right. I suppose I was looking for a function to plot a matrix, which is not necessarily a sparse pattern. I guess the bug is actually with Gadfly!

I would then suggest the creation of a function to plot a matrix (more easily than by using heatmaps at least). It would work in the same way as spy for Gadfly currently, ie: make the color proportional to the value.

**Comment by tbreloff** [comment]
I'm going to close this, and continue the discussion in #196
