### ISSUE TITLE
Pyplot image cut off

### ISSUE THREAD

**Issue by swt30** [tbreloff/Plots.jl#220]
`Plots.savefig` is cutting off some annotations which run off the edge of the axes, even when the figure is adjusted with `PyPlot.subplots_adjust`. 
![plot](https://cloud.githubusercontent.com/assets/6207820/15017272/d4d829dc-120c-11e6-9b7a-eea11beb862c.png)

In matplotlib I'd add `bbox_inches="tight"` to the savefig command to fix this. Should this line be uncommented? https://github.com/tbreloff/Plots.jl/blob/3c09921cbd4da44b36fb5a6ed03e0a528d0e38f8/src/backends/pyplot.jl#L1113

**Comment by tbreloff** [comment]
>  Should this line be uncommented?

Well it's certainly there for a reason!  I don't know if it should be uncommented... I think the reason I took it out is because it semi-arbitrarily changed the size of the plot, and I wasn't happy about it.

I think the better solution is to allow for better fine-tuning of the commands.  This is sort of related to the request for a DPI keyword (https://github.com/tbreloff/Plots.jl/issues/173).  I'm open to suggestions, but I want to avoid solutions that are too hacky.

**Comment by tbreloff** [comment]
And of course... you can always just run those commands yourself with the bbox_inches included if you're desperate...

**Comment by swt30** [comment]
I'm with you on semi-arbitrarily changing the size of the plot not being ideal. One could argue that it's on the user to not place annotations that run off the edge of the figure canvas anyway. The problem is that the behaviour is inconsistent between backends: in PlotlyJS the axes are resized automatically to hold the annotation, in Gadfly you have to manually adjust the axis limits to see the annotation, and in matplotlib you can either do that or use subplots_adjust to add white space without extending the axes - but then we run into the issue of needing to save it with `bbox_inches="tight"`. I suspect that this issomething that will be very annoying to get working in a consistent fashion. So I might just have to accept that I'll have to go to the backend-specific commands to make this kind of tweak, which is fine by me.

**Comment by tbreloff** [comment]
one more thing... you can set the horizontal and vertical alignment pretty easily.  in this case you might want your annotations to be `:right` and `:bottom`.  see: http://plots.readthedocs.io/en/latest/examples/pyplot/#annotations

**Comment by tbreloff** [comment]
In "Plots 0.7" you can do something like:

```
using Plots; pyplot()
plot(rand(10), series_annotations=["fdkhjsdkh" for i=1:10], left_margin = 15mm, right_margin = 15mm)
```

**Comment by swt30** [comment]
Thanks Tom, that's awesome!

**Comment by Amend-1634** [comment]
> In "Plots 0.7" you can do something like:
> 
> ```
> using Plots; pyplot()
> plot(rand(10), series_annotations=["fdkhjsdkh" for i=1:10], left_margin = 15mm, right_margin = 15mm)
> ```

1. Hi, I tried plot(...,bottom_margin=100**px**) or plot(...,left_margin = 15**mm**, right_margin = 15**mm**) but get the report: "**px**, **mm** not defined. My Julia version is v"1.2.0". 
2. gr(display_type=:inline) before plotting help a bit but the margin of the figure still crops parth of the annotation out. 
3. savefig("D:\\mutation1"**,bbox_inches='tight'**) report "ERROR: syntax: invalid character literal"

Are there any other solutions based on updated Julia?

**Comment by daschw** [comment]
`px`, `mm`, etc. are no longer exported. You can either do `using Plots.Measures` or use `Plots.mm` instead.
