### ISSUE TITLE
GR axes offset from true values

### ISSUE THREAD

**Issue by wkearn** [tbreloff/Plots.jl#221]
I'm not entirely sure if this is a Plots.jl or a GR.jl issue, but the following doesn't seem to be working right:

```julia
julia> scatter([randn(100);zeros(100)],randn(200))

julia> abline!(1,0)
```
![offset](https://cloud.githubusercontent.com/assets/4359487/15028159/7117d52e-1215-11e6-9f8b-a6168b97b551.png)

See how the line of points is offset from 0 on the x-axis and the line is offset on both axes? If I manually set the xlims and ylims, the points and line end up where they should though.

@jheinen

**Comment by tbreloff** [comment]
I think this is a bug with GR... the pyplot backend seems to be fine.

**Comment by jheinen** [comment]
Works fine with pure GR (``using GR; scatter([randn(100);zeros(100)],randn(200))
``), but has an X offset when ``GR`` is used as a ``Plots.jl`` backend.

I'll check this.
