### ISSUE TITLE
Bar-style histogram not great in some situations

### ISSUE THREAD

**Issue by oschulz** [tbreloff/Plots.jl#223]
Currently, Plots.jl always uses `histtype = "bar"` (resp. `"barstacked"`) for PyPlot. This is Ok when drawing a single histogram with a small number of bins, or even when comparing two nicely separated histograms. However, with large number of bins, the "bar"-style looks very ugly, compared to "stepfilled", and when comparing similar histograms, "step" is really the only option to still see anything. Here's a comparison (using PyPlot directly, obviously):

http://nbviewer.jupyter.org/gist/oschulz/f0beee3546df6a6758c46eec6a89ba50

Would there be any way to gain access to these styles from Plots.jl, without getting too backend-specific? The `"stepfilled"` style shouldn't be a problem, as it seems to be the default style for Gadfly, and the only style for PlotlyJS. I don't know if they support a `"step"`-like style - but in my personal experience, this is the only viable style for many real-life plots (not as shiny, but way more expressive, scientifically).

**Comment by oschulz** [comment]
API-wise, maybe the `linestyle`-argument could be used to switch between `"bar"` (e.g. `linestyle = :solid` or `linestyle = :bar`, as default) and `"stepfilled"`  (e.g. `linestyle = :step`)? Any switch to style `"step"` on `fillalpha = 0` or so?

**Comment by oschulz** [comment]
Hm, on second thought, maybe it's better to leave `linestyle` to it's original purpose, and add a `bars = true | false` argument? Then, `"step"` vs. `"stepfilled"` could be automatically chosen based on the values of `fillcolor`, `fillalpha`, `linestyle` and `linecolor`.

Would you be open to a PR in this direction, Tom (for PyPlot initially)?

**Comment by tbreloff** [comment]
Thereis already the 'bar_position' (which I should probably alias as 'bar_style') which is probably the right place to handle this logic. I am open to PRs, but only when there is thought to the generality of the solution. I really hate the idea of stringing together hacks just to access a feature on a specific backend. If you can figure out the right way to use bar_position, please go for it.

**Comment by oschulz** [comment]
> There is already the 'bar_position'

Yes, I noticed `bar_position`. It's currently used to select between stacked an non-stacked drawing styles, right? This is, in principal, kinda orthogonal to bar- or step-style (as step-style histograms can, in principal, also be stacked or non-stacked, though PyPlot doesn't seem to support stacking them). We could, of course, encode both in `bar_position`, resp. an alias `bar_style` with values

    bar_style = :bar (default) | :barstack (or :stack) | :step | :stepstack | (...)

I just wonder if two separate options might not be better, as bars vs. steps and non-stacked vs. stacked are, to me, independent style choices (some or all combinations of which may be supported by different plotting frameworks).

What's your opinion on this, Tom?

> but only when there is thought to the generality of the solution

Sure - I understand this can't be a PyPlot-only thing, but must be general.

**Comment by tbreloff** [comment]
I do see your point.  Let me ask you something... does this attribute apply to bar plots, or just histograms?  I could agree to a separate `bar_style` or `hist_style` keyword depending on that answer.  In pyplot it seems to be specific to histograms, but I suppose that in theory that need not be true.

I'm still thinking through how series recipes fit in with histogram and bar plots.  A histogram is just a bar plot that is pre-binned, and a bar plot is just a step function that may or may not be filled.  In plots I really only need the backend to support paths with fill, and the rest could be recipes.  All that to say... whatever we decide on may be re-coded anyways if I reorganize things.

I say make the PR... `bar_position` could be `overlay`, `stack` or `dodge`, and `bar_style` could be `bar`, `step`, or `stepfilled`.  The first options would be the default.  See if you can get it to work in pyplot and we can go from there.

**Comment by oschulz** [comment]
> Let me ask you something... does this attribute apply to bar plots, or just histograms?

Well, to me, a histogram and a bar plot should be the same, graphically, and could both be displayed as bars (separated or "touching") or steps (with/or without line/filling). The only difference, in principle, should be that a bar plot takes pre-binned data, and a histogram does the binning itself. The same goes for heatmap and histogram2d, for me. From what you write I guess you share that view?

Unfortunately, the backends seem to see this a bit differently - I think there's no way, for example, to make a PyPlot bar plot look exactly like a histogram. 

I do work a lot with pre-binned data (e.g. `StatsBase.Histogram` or so), often with a fine binning. My current workaround to display such pre-binned data is to use histogram, put in one entry per x-axis bin, and use `weights` for the bin counts.

It would be perfect if Plots.jl would present a same, consistent interface - default layout and  layout options independent from pre-binned or not - and then use whatever workaround is practical under the hood to handle backend idiosyncrasies.

**Comment by tbreloff** [comment]
> I think there's no way, for example, to make a PyPlot bar plot look exactly like a histogram.

Can you explain?  This should be possible

> It would be perfect if Plots.jl would present a same, consistent interface - default layout and layout options independent from pre-binned or not - and then use whatever workaround is practical under the hood to handle backend idiosyncrasies.

Exactly

**Comment by oschulz** [comment]
> > I think there's no way, for example, to make a PyPlot bar plot look exactly like a histogram.
> Can you explain? This should be possible

I have to admit I tried via Plots.py/PyPlot, not PyPlot directly. I just checked -  you're right, the PyPlot bar-plot does offer `drawstyle = [‘default’ | ‘steps’ | ‘steps-pre’ | ‘steps-mid’ | ‘steps-post’]`. Don't know if the steps can be unfilled, but I guess it's possible via fill style or so. But I was using "bar-style" and I think the issue was that the bar plot bars were narrow with space between them (which I didn't want), whereas the histogram plot bars were touching.

Whether bar-spacing is desired will often depend on the type of data: For discrete data, e.g. an integer-valued x-axis or string-labeled categories, bars with space between them are often preferred - unless the number of bars becomes large (space between or lines around bars would lead to moire-effects). For continuous data, steps or touching bars (with or without lines) will usually be preferred.

I think the best abstract model would be to have:

* Discrete "bar"-plots: Bars can have lines around or not, or be filled or not. Multiple series can be represented either by stacking, by putting the bars next to each other (PlotlyJS seems to like this), or by overlay.

* Continous "histogram"-plots: No space between bins, bins can have lines around (nice if bin count low and high chance of equal fill level for neighboring bins), step-lines above, or no lines. They can be filled or not. Multiple series can be represented either by stacking or by overlay.

For each of these, there should be a function that bins the data internally and one that takes pre-binned (resp. bar-labels-with-heights) data.

Question is, could this be mapped to the backends? :-)

**Comment by tbreloff** [comment]
Your thinking in separating lines from bars from histograms is the right direction.  I would prefer to add recipes for bars and histograms in order to convert them to filled paths.  Something like (when I finish what I'm working on now):

```julia
@recipe function f(::BarHack, args...)
    if d[:bar_style] == :stepfilled
        :fillrange --> 0
    elseif ...
    ...
    x,y = get_path_coords_from_bar_coords(d)
end
```

The idea here is that you would define a transformation from "data and attributes" to "data and attributes".  I would provide the hooks so that you don't need to be able to process every bit of input data... you assume you're given valid x/y data and attributes, and you can just change what needs to be changed.

In this example, you'd want to change the x/y data to trace the outline of the bars exactly how you want, then tell it to fill to 0 (or something else...another series in the case of stacked bars?).

**Comment by oschulz** [comment]
I'm not quite sure if I got that right - would that mean that Plots.jl draw the histogram itself? But then, to the backend it would be just a bunch of lines/areas, right? In that case, what about interactive feature, like Plotly showing the data under the cursor, zooming details, etc.?

**Comment by oschulz** [comment]
I just saw #261, and I think I understand where you want to go, now. :-) Still, wouldn't it make sense to let PyPlot to the drawing, at least in situations where it can do the right thing?

**Comment by tbreloff** [comment]
If I knew programmatically when PyPlot would make good decisions, then
maybe...  I think they do a fine job of drawing series, but subplot layout
is horribly inconsistent, buggy, unintuitive, and frequently just wrong.  It
works because of massive effort and tons of code, but when something
doesn't work as expected it requires monolithic hacks. Better to avoid all
that if I can.

**Comment by oschulz** [comment]
Ok, so long term, better if Plots.jl takes full control, I guess. Until then (I guess  tb_recipes will take a while to become main-line?) would you be open to a  workaround like via a `bar_style`/`bar_style` argument? I'd see if I can put a pull-request together.

**Comment by tbreloff** [comment]
Sure if you can put a PR together then I'll check it out.

**Comment by tbreloff** [comment]
This should be implemented by a series recipe... I'm thinking it could be called `stephist`?  This should be pretty straightforward... why don't you give it a go?  You can model it off of this: https://github.com/tbreloff/Plots.jl/blob/master/src/recipes.jl#L399-L405

**Comment by tbreloff** [comment]
closing in favor of "Recipe ideas" issue

**Comment by oschulz** [comment]
Reopen?

**Comment by oschulz** [comment]
Current thinking after recent discussions: `:bar` is intended for binned data. `:bar` will plot boxes, e.g. lines around each bin by default, but should draw a path around the histogram instead of boxes if `barwidth == 0` (possibly implemented as an internal `:binned` plot style).

Question: What about people who want to draw a histogram with few bins (possibly of different width), and *do* want lines to separate the bins. A fixed `barwidth` won't help, here - maybe an additional `style` (or so) kw arg is necessary after all?

**Comment by oschulz** [comment]
I've been thinking a bit more about the whole bins, bars, steps and axes issue. My conclusion was that we should disentangle semantics and presentation a bit, and make both explicit and easily available to the user. I think there are several orthogonal concerns (sorry, the following is a bit lengthy, but I wanted to be clear and detailed):


### Binned axes vs. discrete axes

I believe there is a fundamental difference here that should not be hidden, but explicitly expressed. Both are about categorization of data along the axes: With bins, the categorization is explicit, defined by the binning of each axis and a plot can visually represent this. In the discrete case, the categorization is implicit: Either the data is discrete by nature (e.g. non-numeric or samples from a discrete distribution), or has been pre-categorized (e.g. by year, geographic region, etc.). Floating point data will always have to be binned, non-numeric data will always be discrete, but integer data may be both: We may want to create a histogram for a discrete distribution for `x = 0:20`, without binning. But we may also want to plot that distribution over a wide range, and may need to bin, e.g. `x = 0:100:10000`.

So binned vs. discrete can't always be auto-detected for data points, the user must be able to specify it. However, if the data is already aggregated (i.e. the user gives us axes and counts), we could decide based on axis size: If `length(axes[i]) == size(weights, i)` it's discrete, if `length(axes[i]) == size(weights, i) + 1` it's binned. However, I think we should not auto-detect, but let the user make an explicit choice - see below.


### Dimensionality and graphical representation

Data may originally be one, two or three dimensional (higher-dimensional data is, of course, only plotable after projection/marginalization). Depending on dimensionality, different graphical representations are possible. I will not use the term "bars" here, as "bars" seems to mean different things to different people.

#### 1D data

There are several popular representations:

* Towers (`:towers`): Boxes of a fixed width in x, from y=0 up to y=weight, usually with space separating them. The tower width (specified as 0.0 to 1.0, rel. to bar distance?) is a style choice and does not reflect how the data was categorized (i.e. it's *not* a bin width). The tower width could be non-uniform, though, and express an unrelated numeric property of the categories. Typically, the lines around each box (if desired) are on the sides and on top, not on the bottom.

  For multiple series, towers can be grouped next to each other (should be the default), or stacked, but overlay makes no sense.

  While this is a natural representation for discrete categories, this kind of plot is sometimes chosen for binned data as well (e.g. to group multiple series side-by side) - in this case, the bin centers should be used as categories (resp. tower positions). This is why I think we shouldn't auto-detect discrete vs. binned based on axis lengths.

* Steps (`:steps` or `:bins`): A stepped path, from y=0 up to the value of the first bin, horizontal over each bin, down to y=0 again after the last bin. If there are few bins and few counts in each bin, it can be helpful to have additional vertical lines that separate the bins. I won't call this bars/boxes, because the vertical lines could have a different line-style / -width / -alpha. In fact, the plot is often clearer if they are less strong than the "covering" line. This is something entirely different from `:steppre` and `:steppost` (where the data points are the be beginning/end of the steps)!

  For multiple series, the paths can be overlaid (should be the default) or stacked. They can't be grouped next to each other, so sometime people may prefer towers even for binned data (see above).

  While this is a natural representation for binned data, this kind of plot is sometimes chosen for discrete categories as well, as binned (without lines in between) work well for both a small and large number of bins/categories. For discrete data, the steps/bins should begin/end at the mid-point between the discrete category values.

* Points: Data points with some kind of marker and some representation of the bin widths (typically) horizontal bars. This style is often chosen to display vertical ranges (e.g. statistical errors) as well, usually with vertical bars. As this is usually realized as a scatter plot with errors bars (interpreting the horizontal "errors" as bin widths), we probably don't need a special series type for this.

  Note that while there is a corner case that makes towers and steps look the same (touching towers and steps with strong lines in between), I believe they are fundamentally different (multi-series representation, meaning of tower/step width, etc.), and should definitely be different series types (let's call them `:towers` and `:bins`).

Concerning `:bar` - maybe `:bar` could be a meta-recipe that internally uses either `:towers` or `:steps`/`:bins`, depending on that seems more suitable for the given input?

#### 2D data

Possible representations are:

* Heatmap (`:bins2d` or `:heatmap`): This the 2D equivalent of `:steps`. Rectangular patches of colors, the color scale represents the category/bin weight values. This style is very common for both discrete data (cell size defined by category distance) and binned data (cell size equals bin size). Another application is the graphical display of matrices (or grayscale images) - in this case, the axes (i/j) are usually implicit. For binned data, the positioning of the cells is clear. However, for discrete data, the cells are typically not aligned with the axis values on their centers, but their corners.

  The cells may optionally be separated by lines - the equivalent of lines between bins in a 1D steps-plot. This only works for large cells, though, so the default should be "no lines".

* Hexagonal cells: Like above, only hexagonal patches of color. Useful as a 2D histogram style, but pre-aggregated/binned data rarely comes on a hexagonal grid. Nice for large cells, unsuitable for small cells (as screen pixels are usually square).

* Lego (`:lego`): This is just a heatmap lifted into the third dimension (see [this example](https://root.cern.ch/js/latest/examples.htm#th2_lego)). Typically, both box height and color represent the category/bin weight value. I've never seen a hexagonal version.

* Variable sized boxes/circles/...: This the 2D equivalent of `:towers`. Box size and color can be used to represent weights and other properties. As this can be realized as a scatter plot with variable marker size, we probably don't need a special series type for this.

#### 3D data

Typical representations are boxes or balls of different size/color in x/y/z. To a certain extent, this is a 3D scatter plot with variable-sized markers - but to do this properly, the markers should be 3D objects themselves. I'm not sure what's possible with the current backends, but one doesn't encounter this type of plot very often. Without an interactive display (with rotation), it's usually hard to gain insights (see [this example](https://root.cern.ch/js/latest/?nobrowser&file=../files/glbox.root&item=h31;1&opt=)).


### Kind of input data

Here we have two possibilities:

* Pre-aggregated data (aggregated into bins or discrete categories). Input will be axes and counts/weights, and can be plotted directly using one of the styles described above. The user will often use a recipe, e.g. `plot(h::StatsBase.Histogram)`, instead of calling plot with the series type he wants directly.

* Non-aggregated data, input is data points and an aggregation specification (explicit bins/categories, number of bins for auto-binning, for fully automatic binning, implicit discrete categories like integers). We want Plots/StatPlots to aggregate the data for us, and the user will use a recipe like `histogram(data, bins = ...`. If the data is floating point or non-numeric, we can auto-detect whether we should have discrete or binned axes. For integer data, the default could be discrete, and the user could override by setting `bins = :auto | n | a:b:c | ...`.

In both cases, the user should be free to explicitly choose the graphical representation he wants. While there are typical choices depending on discrete/binned, and Plots should choose the default accordingly, the recipe should not fix the series type and allow the user to override via `seriestype = :towers | :steps | :scatter | ...`

**Comment by tbreloff** [comment]
@oschulz Thanks for putting so much thought into this.  I'll be honest that it's a little hard to process it all... do you think it would be possible to make quick example plots of what you expect each series type to look like?  This would make discussion and implementation orders of magnitude easier.

**Comment by oschulz** [comment]
@tbreloff: Sure - I actually had planned to provide examples, but ran out of time. Gimme a little bit of time, rest of the week is likely to be quite busy ...

**Comment by oschulz** [comment]
@tbreloff: I'm going to provide those example plots, I swear - but things are a bit busy at the moment, so it'll take a bit more time, sorry.

**Comment by oschulz** [comment]
Getting back on this now.

**Comment by fredRos** [comment]
@oschulz I know you have been gone for a while for good reasons. Is there a way to change the plot style of histograms? I totally agree that currently with many bins, the result is ugly.

**Comment by oschulz** [comment]
@fredRos I am working on it (will go into StatPlots.jl, initially). I have some code ready, I just have to find the time to round things off and get a PR ready for Tom.
