### ISSUE TITLE
linealpha broken in v0.6.1 (at least for histogram)

### ISSUE THREAD

**Issue by oschulz** [tbreloff/Plots.jl#224]
The `linealpha` argument doesn't seem to work anymore, at least for `histogram`, in Plots.jl v0.6.1. In v0.5.4, this worked fine (tested with Gadfly and PyPlot), e.g.

```
Plots.histogram(randn(10000) - 1, color = :blue, label = "a", linealpha = 0.5)
Plots.histogram!(randn(10000) + 1, color = :green, label = "b", linealpha = 0.5)
```

resulted in (Gadfly):

![histlinealpha](https://cloud.githubusercontent.com/assets/546147/15039462/aff44488-12ad-11e6-9f2f-c60f28777303.png)

But with v0.6.1 (resp. current master), it looks like this  (Gadfly):

![histlinealpha](https://cloud.githubusercontent.com/assets/546147/15039609/b23f7202-12ae-11e6-949b-ca96d71cd226.png)

**Comment by tbreloff** [comment]
Just to quickly address the alpha (I'll think about the rest later)... Colors and alpha are handled a little differently now. Specifically for histograms the linecolor/line alpha correspend to the border of that bars, and fillcolor/fillalpha to the inside. Also though there is the new seriescolor/seriesalpha which can apply to all aspects of a series, and the aliases color, alpha, etc map to the series. So in your example, change it to alpha or fillalpha depending on whether you also want the border to have alpha.

**Comment by oschulz** [comment]
My apologies - I should have taken a closer look at the changes. `fillalpha` is of course a much better fit, semantically, and works nicely.
