### ISSUE TITLE
zlims not implemented for gr backend. 

### ISSUE THREAD

**Issue by wwywong** [tbreloff/Plots.jl#227]
Calling

    using Plots
    gr()
    plot(0:10,1:0.1:2,3:0.2:5, xlims=(-2,12), ylims=(-2,3))

works as expected, but

    plot(0:10,1:0.1:2,3:0.2:5, xlims=(-2,12), ylims=(-2,3), zlims=(1,6))

shows

    WARNING: Keyword argument zlims not supported with Plots.GRBackend().  Choose from: [:annotation,:axis,:background_color,:linecolor,:color_palette,:fillrange,:fillcolor,:foreground_color,:group,:label,:layout,:legend,:colorbar,:linestyle,:linetype,:linewidth,:markershape,:markercolor,:markersize,:markerstrokewidth,:markerstrokecolor,:n,:nbins,:nc,:nr,:smooth,:show,:size,:title,:windowtitle,:x,:xlabel,:xlims,:xticks,:y,:ylabel,:ylims,:yrightlabel,:yticks,:xscale,:yscale,:xflip,:yflip,:z,:zcolor,:tickfont,:guidefont,:legendfont,:grid,:nlevels,:fillalpha,:linealpha,:markeralpha]

in contrast with what is shown on http://plots.readthedocs.io/en/latest/supported/

**Comment by tbreloff** [comment]
I don't see the warning (on dev branch) but it also didn't work for a surface plot!  We'll look into it.  

cc: @jheinen

**Comment by wwywong** [comment]
Right, I am not using the dev branch. Pkg.status() tells me I am on 0.5.4, FWIW, with GR at 0.10.0.

**Comment by tbreloff** [comment]
Ok 0.5.4 is very old at this point... I would recommend `Pkg.checkout("Plots")`

**Comment by wwywong** [comment]
Thanks for the advice. Yes, the warning is gone. But as you observed the zlims kw doesn't seem to be doing what it should be doing.

**Comment by jheinen** [comment]
Has been fixed in 42a175b.
