### ISSUE TITLE
Series recipes

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#228]
Notes from gitter:

> Diego Javier Zea @diegozea 14:43
@tbreloff I was thinking... BezierCurve should be a series type, in order to use it in recipes

> Tom Breloff @tbreloff 14:46
Yes true... on that thought, there might be a better way to separate core series types vs composite series types... i.e. a bezier curve is just a bunch of points in a path, a violin plot is just a list of shapes... it would be good to have a separation of "series recipes" (needs a better name) vs core series types
things that are series recipes: line (just a sorted path), steppre/post, sticks, box, violin, quiver, bezier curve...
things that are core: path, scatter, heatmap, hline/vline, contour, pie, surface, wireframe, ...
i already have the beginning of a "series recipe" framework... it would be good to make that distinct from seriestype

**Comment by diegozea** [comment]
Maybe `primary` and `secondary` series (like the `primary` and `secondary` colors). Does the user need to know the difference? i.e. `wireframe` looks to me like a lot of `path`s. I will never guest it is `primary`/`core`...

**Comment by tbreloff** [comment]
No the separation shouldn't be exposed to the user, it should be an implementation detail.  The benefit to the split:

- Can create new series types as combinations of core types (without updating a "supportedTypes" list)
- Can simplify the number of things that a backend must implement/maintain

**Comment by tbreloff** [comment]
So, similar to the recipe macro, one could define new series types from an external package, without needing to depend on Plots

**Comment by tbreloff** [comment]
see: https://github.com/JuliaPlots/RecipesBase.jl/issues/6

**Comment by tbreloff** [comment]
This is basically done.  See: https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/series_recipes.ipynb
