### ISSUE TITLE
Pyplot shows a half finished plot before finalizePlot is called

### ISSUE THREAD

**Issue by pkofod** [tbreloff/Plots.jl#229]
When calling a plot with a semicolon, a plot it shown, but isn't correct before it is actually "displayed", for example by calling `savefig`.

With semicolon
![semi](https://cloud.githubusercontent.com/assets/8431156/15094110/ae4d8902-149a-11e6-944c-f3f93f8001f9.png)

Without semicolon, or after `savefig`
![nosemi](https://cloud.githubusercontent.com/assets/8431156/15094111/ba487140-149a-11e6-9d23-9afde0beab33.png)

Above, it is the axis color and tick color that is not correctly applied before `finalizePlot` is called.

**Comment by KristofferC** [comment]
I've had a similar problem sometimes when I save a figure that is created in a function. For pyplot this made the legend not show up and for pgfplots the .o field was simply None. After displaying the plot it is ok.
