### ISSUE TITLE
Color palettes

### ISSUE THREAD

**Issue by pkofod** [tbreloff/Plots.jl#230]
Working on `PlotThemes.jl`, I'm trying to add color palettes to the themes. However, if I defined something like: 
```julia
add_theme(:theme_base, palette  = RGBA_vec)
```
I get another `p.plotargs[:color_palette]` than the standard, but it does not just consist of the `N` colors in `RGBA_vec` which is a vector of `RGBA`s, it is rather a 100 element vector of `RGBA`s, none of which are the original colors I provided. Am I doing it wrong? Or does the `palette` KW just not do what I think it does.

**Comment by tbreloff** [comment]
Can you post your code? 

Yes the vector you pass in will seed a computed gradient that, when combined with an algorithm I have for generating nicely distinct colors from a palette, should produce lines where the first n lines will match the n-length vector that you passed, but afterwards will grab colors interpolated in between in a manner that you should never see the same color twice. I can't remember if this also uses the distinguishable_colors algorithm, which would ensure the colors differ from the background as well. 

This was somewhat complex to get working, but I think it does a pretty good job.

**Comment by pkofod** [comment]
```julia
using Plots
_255_to_1(c::Symbol, colors) = RGBA(map(x-> x/255,colors[c])...)

const _stata_colors =  Dict{Symbol, Tuple}(
                       :gs6 => (96, 96, 96),
                       :navy => (26, 71, 111),
                       :maroon => (144, 53, 59),
                       :forest_green => (86, 117, 47),
                       :dkorange => (227, 126, 0),
                       :teal => (110, 142, 132),
                       :cranberry => (193, 5, 52),
                       :lavender => (147, 141, 210),
                       :khaki => (202, 194, 126),
                       :sienna => (160, 82, 45),
                       :emidblue => (123, 146, 168),
                       :emerald => (45, 109, 102),
                       :brown => (156, 136, 71),
                       :erose => (191, 161, 156),
                       :gold => (255, 210, 0),
                       :bluishgray => (217, 230, 235))

const _stata_palette = (:gs6, :navy, :maroon, :forest_green, :dkorange, :teal,
                       :cranberry, :lavender, :khaki, :sienna, :emidblue,
                       :emerald, :brown, :erose, :gold, :bluishgray)
                       
_get_stata_color(c) = _255_to_1(c, _stata_colors)

add_theme(:stata_s2,
    palette  = [map(c->_get_stata_color(c), _stata_palette)...])

set_theme(:stata_s2)

p = plot(rand(10,3))

for plt = p.seriesargs
    println(plt[:seriescolor])
end

[map(c->_get_stata_color(c), _stata_palette)...]
```
So this might be an error on my side, but the first color in the print loop is the first color in my palette, good. The second one is the last color from my palette (hm, okay...). The third color is not in my palette.

**Comment by tbreloff** [comment]
What happens if you add an arbitrary color to make n an odd number. Then does it match the first n-1 colors?

**Comment by pkofod** [comment]
No, but then it matches one more :)

**Comment by tbreloff** [comment]
Ha! Ok I'll have to look at it another time.

**Comment by tbreloff** [comment]
I wish I commented this code more! Gotta spend a little time to relearn. I may start splitting this off into a new repo JuliaPlots/PlotColors.jl since I'm going through the code anyways.

**Comment by tbreloff** [comment]
If you give it a Vector{RBGA} it should cycle through the values exactly (nothing funky)... So it's probably not a Vector{RBGA} exactly and so it's hitting my "trying to be super clever but failing" logic to generate infinite colors in your palette. I'll need to improve that.

**Comment by pkofod** [comment]
I inserted a println in the Vector{RGBA} method, and I *am* hitting that, so it is a Vector{RGBA} exactly.

**Comment by tbreloff** [comment]
I think maybe nothing will dispatch to Vector{RBGA}... I'd need to use a parametric definition. The other function should still work though...

**Comment by pkofod** [comment]
What other function?

**Comment by tbreloff** [comment]
I think this works now on dev... could you verify?

**Comment by pkofod** [comment]
I will check

**Comment by pkofod** [comment]
Works like a charm.
