### ISSUE TITLE
Sticks on Gadfly backend

### ISSUE THREAD

**Issue by tonyduan** [tbreloff/Plots.jl#232]
Looks like `sticks` line widths isn't set properly on the Gadfly backend:

![screen shot 2016-05-07 at 11 18 50 pm](https://cloud.githubusercontent.com/assets/1163598/15096382/1d95692e-14aa-11e6-8b94-2cd2aa1af0f1.png)

It works properly with PyPlot:

![screen shot 2016-05-07 at 11 20 11 pm](https://cloud.githubusercontent.com/assets/1163598/15096391/44f406c4-14aa-11e6-82d8-a8ababd0c4b8.png)

I'm on v0.6.1. This is an awesome library!

**Comment by tbreloff** [comment]
This is a bug with Gadfly: https://github.com/dcjones/Gadfly.jl/issues/758

The way I currently attempt to make sticks in Gadfly is by making very thin bars.  I can (and eventually will) change this to be a [series recipe](https://github.com/JuliaPlots/RecipesBase.jl/issues/6) to be made of line segments and markers.  Until then...

**Comment by tonyduan** [comment]
Thanks for clarifying. I'll leave this issue open for now, but feel free to close if you think it's not necessary.

**Comment by tbreloff** [comment]
If/when I un-deprecate Gadfly, this should be fixed by using a recipe.
