### ISSUE TITLE
DataFrames: Vector of Symbols

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#234]
This worked before:
```julia
using DataFrames
benchmark = readtable("./assets/benchmark.csv", separator=';')
using Plots
plot(benchmark, x=:Benchmark, y=[:Julia, :Python, :R], linetype=:scatter, yscale=:log10)
```
But now gives:
```
LoadError: MethodError: `convertToAnyVector` has no method matching convertToAnyVector(::Symbol, ::Dict{Symbol,Any})
Closest candidates are:
  convertToAnyVector(!Matched::Void, ::Dict{Symbol,Any})
  convertToAnyVector(!Matched::Integer, ::Dict{Symbol,Any})
  convertToAnyVector{T<:Number}(!Matched::AbstractArray{T<:Number,1}, ::Dict{Symbol,Any})
  ...
```

`scatter(benchmark, :Benchmark, [:Julia, :Python, :R])` gives the same error

**Comment by tbreloff** [comment]
Try on dev:

<img width="590" alt="screen shot 2016-05-09 at 8 32 06 am" src="https://cloud.githubusercontent.com/assets/933338/15113172/ab5fe5b0-15c0-11e6-8bd5-aafa190ba9f4.png">

**Comment by diegozea** [comment]
It works with positional arguments, but not with keyword arguments `x` and `y`. It doesn't work with `[:Julia :Python :R]` instead of `[:Julia, :Python, :R]`. 
![image](https://cloud.githubusercontent.com/assets/2822757/15117620/c6a057e2-15de-11e6-8c5b-f467c7a3f551.png)

**Comment by tbreloff** [comment]
>  but not with keyword arguments x and y.

This is weird... but please... you should never use this form if you can avoid it.  You're avoiding dispatch.  It only works at all because I specifically attempt to take those arguments and send them back through as much of the pipeline as I can.

What probably happens is this doesn't happen because the dataframe is there (i.e. it checks for no arguments, then (and only then) grabs x/y keyword arguments and re-calls with them in positions

**Comment by tbreloff** [comment]
Actually looking through the code briefly, I think there's a large amount of logic that gets bypassed by using keyword args for x/y/z (with or without dataframes).  I should probably add a warning if I see someone set x/y/z keywords manually.

**Comment by diegozea** [comment]
I imagine a test_x_y_args(args...; kargs..) with the following behaviour:
```julia
plot(x=X, y=Y) # Ok, then calls plot(x,y)
plot(X, x=X, y=Y) # Error duplicated x suggesting plot(x, y)
plot(X, y=Y) # Ok, then calls plot(x,y)
plot(X, Y, x=X, y=Y) # Error duplicated x and y suggesting plot(x, y)
plot(df::DataFrame, x=X, y=Y) # Error suggesting plot(df, x, y) or make it call plot(df, x, y)
plot(df::DataFrame, X, Y) # Ok
```

**Comment by tbreloff** [comment]
Sadly this is a lot of logic to get right (there are many versions of `plot`, `plot!`, `subplot`, and `subplot!`).  And I'm not really sure what the benefit is (besides people copying code from Gadfly).  Where-as the logic `if haskey(d,:x) || haskey(d,:y); error(); end` is clear and correct.  Can you think of a real, valid reason that this should be supported?

**Comment by diegozea** [comment]
Always throw an error with `x`, `y` and `z` sounds fine to me ;)

**Comment by tbreloff** [comment]
The matrix version should work now.

**Comment by diegozea** [comment]
Yes, It's working now :D Tahanks a lot!
