### ISSUE TITLE
DataFrames: String columns and axes

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#235]
In the following example, I expect the x axis to take string labels/ticks.

![image](https://cloud.githubusercontent.com/assets/2822757/15107238/fe316500-15a4-11e6-9a70-75b6a4e7091a.png)

**Comment by tbreloff** [comment]
This is a problem with the group keyword... not dataframes (I think)

**Comment by diegozea** [comment]
Yes, the x axis is fine if I remove the `group`ing...
![image](https://cloud.githubusercontent.com/assets/2822757/15117302/4ac677a6-15dd-11e6-967b-31f8d79c1d91.png)

**Comment by tbreloff** [comment]
This should work now... can you please test it out?

**Comment by diegozea** [comment]
Yes, It's fine now :D Thanks Tom!
