### ISSUE TITLE
some more plot types?

### ISSUE THREAD

**Issue by jverzani** [tbreloff/Plots.jl#24]
Here are some other plot types that might be useful to add to this package. They come from SymPy's plotting module and are supported in PyPlot and others, though not fully:

- [x] 2d contour plot (`contour`?)
- [x] 3d parametric line plot (just a third argument to `plot`?)
- [ ] 3d parametric surface plot (`surfaceplot`?)
- [x] 2d vector (or quiver) plot (`vectorplot`? `quiver`?)

~~plot_implicit for making plots of implicit functions~~

**Comment by tbreloff** [comment]
Thanks for the list. I'll probably take care of a few other things before I get to add these.

**Comment by tbreloff** [comment]
Contours are available: #36 

What do you mean by `plot_implicit`?  Do you have an example viz you can point me to?

**Comment by jverzani** [comment]
The name comes from SymPy (http://docs.sympy.org/dev/modules/plotting.html#sympy.plotting.plot_implicit.plot_implicit). There is also this package for Julia (https://github.com/jverzani/ImplicitEquations.jl). Really this isn't the most important graphic, but it would be nice to be able to push some of the graphing code in ImplicitEquations onto Plots.jl.

The more widely used plot would be an equivalent of PyPlot's `quiver` function.

**Comment by tbreloff** [comment]
I understand now. My gut feeling is that it should live in your ImplicitEquations package. You could consider creating a type which is a subtype of PlotRecipe and which wraps an equation. Then you only need to implement methods to generate the underlying data and Plots will handle the rest. I might not get to this soon, but I'm happy to answer questions.

**Comment by jverzani** [comment]
Okay, thanks for the pointers on how to wrap it.

On Mon, Oct 26, 2015 at 9:37 PM, Tom Breloff <notifications@github.com>
wrote:

> I understand now. My gut feeling is that it should live in your
> ImplicitEquations package. You could consider creating a type which is a
> subtype of PlotRecipe and which wraps an equation. Then you only need to
> implement methods to generate the underlying data and Plots will handle the
> rest. I might not get to this soon, but I'm happy to answer questions.
>
> > On Oct 26, 2015, at 8:38 PM, john verzani <notifications@github.com>
> wrote:
> >
> > The name comes from SymPy (
> http://docs.sympy.org/dev/modules/plotting.html#sympy.plotting.plot_implicit.plot_implicit).
> There is also this package for Julia (
> https://github.com/jverzani/ImplicitEquations.jl). Really this isn't the
> most important graphic, but it would be nice to be able to push some of the
> graphing code in ImplicitEquations onto Plots.jl.
> >
> > The more widely used plot would be an equivalent of PyPlot's quiver
> function.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbreloff/Plots.jl/issues/24#issuecomment-151338347>.
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by diegozea** [comment]
¡It's an awesome package right now! 
Maybe this list of plots/graphs can be useful for making `Plots.jl` even more awesome: http://www.datavizcatalogue.com/

**Comment by tbreloff** [comment]
> 3d parametric surface plot (surfaceplot?)

I was just looking back through the issue list, and realized that I'm not really sure what this is.  Do you have an example?

**Comment by jverzani** [comment]
I could update that list, as you've added the 3d functionality with the plotly and pyplot backends. This allows me to define what I wanted in SymPy. For example, the parametric surface plot in SymPy is implemented using Plots here https://github.com/jverzani/SymPy.jl/blob/master/src/plot.jl#L135. Similar things are done for all but the too-specific `plot_implicit` request, and that I worked around in `ImplicitEquations`. 

Upshot -- awesome job!

**Comment by tbreloff** [comment]
Closing in favor of #178
