### ISSUE TITLE
Bad lengths...?

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#242]
Z is (249, 67)
X is (249)
Y is (67) 

Lengths for X and Y are bad in the Error message...

```
LoadError: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError('Dimensions of C (249, 67) are incompatible with X (250) and/or Y (68); see help(pcolormesh)',)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 7736, in pcolormesh
    X, Y, C = self._pcolorargs('pcolormesh', *args, allmatch=allmatch)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 7377, in _pcolorargs
    C.shape, Nx, Ny, funcname))
```

I found it with:
```julia
using Plots
using MIToS: MSA, Pfam
using RecipesBase

msa = read(downloadpfam("PF08904"), Stockholm);

@recipe function plot(msa::AnnotatedMultipleSequenceAlignment)
    :linetype --> :heatmap
    :yflip --> true
    :grid --> false
    :linewidth --> 0
    1:ncolumns(msa), names(msa), map(string, msa')
end

plot(msa)
```

**Comment by tbreloff** [comment]
I'm pretty confused about this after the (breaking) changes from #196.  I think it's correct, but an assert was getting in the way.  You'll need to check out dev and then remove the transpose on your matrix.  Here's the reason:

By default, `match_dimensions = false` which means that the rows of the z matrix will correspond with the y-axis of the plot (like an upside-down matrix).  Your `msa` matrix is already aligned that way, so no need to transpose.

The x and y vectors still correspond to the x and y axis, so nothing changes there. (I was confusing myself on this point).

The match_dimensions keyword is **only** for describing whether or not to transpose the z matrix.  Again:

true implies `z=rand(3,10)` will correspond to an x-axis of length 3
false implies `z=rand(3,10)` will correspond to an x-axis of length 10

I'm open to suggestion on aliases to add for the match_dimensions keyword, as it confuses even myself.  😲

**Comment by diegozea** [comment]
`transpose` looks like the name to use.

**Comment by tbreloff** [comment]
Fair enough.
