### ISSUE TITLE
Remove unwanted axis from plot

### ISSUE THREAD

**Issue by codles** [tbreloff/Plots.jl#246]
Is there a way to remove axis from plots? I would like to remove the right and top plot, similar to this [question](http://stackoverflow.com/questions/925024/how-can-i-remove-the-top-and-right-axis-in-matplotlib).

Thanks

**Comment by tbreloff** [comment]
There's not a generic way to do it right now, but if you're using pyplot you can hack it:

![tmp](https://cloud.githubusercontent.com/assets/933338/15162249/e7267932-16cf-11e6-87e2-6dfea38c7d78.png)

**Comment by codles** [comment]
Thanks, worked perfectly.
