### ISSUE TITLE
KeyError: linetype not found

### ISSUE THREAD

**Issue by EricForgy** [tbreloff/Plots.jl#247]
Hi @tbreloff 

I'm FINALLY getting around to trying Plots.jl, but having some troubles:

![image](https://cloud.githubusercontent.com/assets/8954730/15175466/05ed6672-1799-11e6-89d0-d2d91d17551e.png)

Initially, Pkg.update() got me a version of Plots.jl that failed when I tried "using Plots", but a Pkg.checkout("Plots") fixed that. I got the GR backend working and wanted to try plotlyjs(), but no luck. Just to be sure, I also tried Pkg.checkout("PlotlyJS"). 

Any ideas? Maybe this is an issue for PlotlyJS? @spencerlyon2

**Comment by tbreloff** [comment]
This is definitely an error in Plots. Can you try the 'dev' branch?

I really wish I could test plotly on travis...

**Comment by EricForgy** [comment]
No worries! Will give dev a try :+1:

**Comment by EricForgy** [comment]
That did it. Thanks :)
