### ISSUE TITLE
xlim and ylim

### ISSUE THREAD

**Issue by joshday** [tbreloff/Plots.jl#25]
I hope this isn't something I missed.  Feature request for something similar to R's `xlim` and `ylim` plot arguments for specifying the endpoints for the axes.

Ticks:
- [x] Gadfly/Immerse
- [x] PyPlot
- [x] Qwt
- [ ] UnicodePlots (not possible?)
- [ ] Winston (not possible?)

Limits:
- [x] Gadfly/Immerse
- [x] PyPlot
- [x] Qwt
- [x] UnicodePlots
- [x] Winston

Tick labels:
- [x] Gadfly/Immerse
- [x] PyPlot
- [ ] Qwt (not possible?)
- [ ] UnicodePlots (not possible?)
- [ ] Winston (not possible?)

**Comment by tbreloff** [comment]
You didn't miss it. I also need to add the ability to set tick labels and grid lines. 

In general, you can always access the underlying plotting package directly. I export Gadfly for example, and you can get the underlying plot object from the "o" field. So if there's something missing you should still be able to access the underlying functionality.

**Comment by tbreloff** [comment]
Mostly done with limits/ticks for Gadfly/Immerse... I'll add some checkboxes to your comment to keep track.  For now, there are lots of ways to update.  I'll push to master soon:

```
using Plots
plot(rand(100), title="Changing ticks and axis limits")
plot!(xlims=(25,75),xticks=25:5:75)
ylims!((0.6,0.8))
yticks!([0.6,0.63,0.7,0.8])
```
![tmp](https://cloud.githubusercontent.com/assets/933338/10051432/5f007d4a-61ef-11e5-926b-47d0640747d4.png)

**Comment by joshday** [comment]
:+1:

**Comment by tbreloff** [comment]
This is as complete as I'm going to make it on first pass.  I'll close the issue, and if anyone wants more extensive functionality (and it's possible for that backend) I'll open separate issues.
