### ISSUE TITLE
y ticks are wrong in GR heatmap2

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#253]
pyplot y ticks and orientation are the correct:

![image](https://cloud.githubusercontent.com/assets/2822757/15203743/f6d4a058-17dc-11e6-956a-ad7a698bbe56.png)

**Comment by tbreloff** [comment]
Can you give a simpler example that I can copy/paste?

**Comment by diegozea** [comment]
Sure ;)
```julia
x=collect(1:100)
y=x.+rand(100)
pyplot()
histogram2d(x,y)
```
```julia
gr()
histogram2d(x,y)
```

**Comment by tbreloff** [comment]
Confirmed and fixed
