### ISSUE TITLE
Legend doesn't work with histogram

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#254]
Or am I doing something wrong?
![image](https://cloud.githubusercontent.com/assets/2822757/15203997/26df7528-17df-11e6-9715-08ffa1c96256.png)

**Comment by pkofod** [comment]
#124 (which you also opened :) ) was closed when the alpha part was fixed, but not legend AFAIC.

**Comment by tbreloff** [comment]
At some point we agreed that histograms (along with some other series
types) shouldn't be part of the legend. I don't remember the reasons and
I'm happy to revisit the discussion.

**Comment by diegozea** [comment]
I don't remember that... I really miss the histogram legends and also the not having equal bins by default (https://github.com/tbreloff/Plots.jl/issues/186). Even if legend is `false` by default in histograms, the user should be able to use it.

To me, a useful histogram for `group`ed data is something like the *ggplot2* default  (lines aren't a problem to me):

![](http://docs.ggplot2.org/current/geom_histogram-9.png)

**Comment by tbreloff** [comment]
This sounds like a job for... recipes!  :)

To expand, it would be good if we can do something like:

```julia
plot(GroupedHist(), inputdata...)
```

And that recipe would allow additional functionality/default behaviors that are maybe different than other histogram plots.

**Comment by tbreloff** [comment]
I find that as I explore the recipe idea more, that everything can fit into it.  It's kinda like a grammar of graphics on steroids.  "Shakespeare of Graphics"?

**Comment by diegozea** [comment]
Using types for dispaching plot kinds (recipes) is a good and julian idea :)
```julia
plot(GroupedHist, inputdata...) # ::Type{GroupedHist} looks cleaner ;)
```
But... How can it play with `@recipe`? Would be keyword arguments easy to manage inside other recipes than type parameters?

**Comment by tbreloff** [comment]
The WIP idea at the moment is that recipes create one or more "Series", which is just an attribute dictionary and the unhandled arguments left after the recipe.  So a low-level recipe would completely fill the dictionary with everything needed for a plot and return an empty tuple (signifying it's ready to be plotted)  Something higher-level like a grouped histogram would set some useful attributes (bins, bar_position, etc) and then return the input data for further processing:

```julia
@recipe function f(::GroupedHist, args...)
  bins --> calcbins(args...)
  args
end
```

So in this case, it's really just short circuiting early in the pipeline to set some better defaults for this specific visualization, and then continuing on as if the GroupedHist type was missing.

This may not seem as powerful to you as it does to me, but it opens up possibilities of making 3rd party types and logic first-class and allows for implementations reaching into any part of the pipeline without changing core Plots code.  Really cool.

**Comment by diegozea** [comment]
Is that meaning that I can define my own serie [`DotPlot`](https://en.wikipedia.org/wiki/Dot_plot_(bioinformatics)) just defining

 ```julia
immutable DotPlot # <: SerieRecipe ?
end

@recipe function plot(::DotPlot, seq, args...)
    # fill with dots 
    x, y
end
```

**Comment by diegozea** [comment]
Will 
```julia
GroupedHist(inputdata...)
``` 
work as
```julia
plot(GroupedHist(), inputdata...)
```
?

**Comment by pkofod** [comment]
The recipe would just create step plots after some precalculations of the counts right? Makes sense, as we could then support the grouped histogram with legends without any changes to Plots. It is also easier to implement it this way across backends (I think?).

**Comment by tbreloff** [comment]
> Will ... work as ...

Sure... if you define it ;)

>  # <: SerieRecipe ?

unnecessary

>  I can define my own serie DotPlot just defining

exactly... you do a simple mapping and set some attributes, and then let Plots recursively handle whatever you give it.

**Comment by diegozea** [comment]
Great!
I think that having something like
```
abstract SerieRecipe
call(x::SerieRecipe, args...) = plot(x, args...)
```
Will be great ;)

**Comment by tbreloff** [comment]
Right... likely what will happen is that there will be recipes to convert:

grouped hists --> hists with predefined bins
hists --> bars
bars --> paths with (or without) fill

And then some backends may natively support some cool operations/features with bar plots so that backend will tell Plots that it supports bars natively and the pipeline will short-circuit before applying that last "bars to paths" recipe.

**Comment by tbreloff** [comment]
Going on your `SeriesRecipe` idea, it would be nice to have a decorator macro which defines a lowercase function version:

```julia
@seriestype type GroupedHist end

groupedhist(args...)  # maps to plot(GroupedHist(), args...)
groupedhist!(args...)  # maps to plot!(GroupedHist(), args...)
```

**Comment by diegozea** [comment]
Good, lowercase functions are more Plots' style ;)

**Comment by tbreloff** [comment]
The pieces are (mostly) in place.  Here's an example.  Enjoy!

```julia
using Plots
pyplot(fmt=:png)

@userplot type StackHist
    vecs::Tuple
    StackHist(vecs::AVec...) = new(vecs)
end

@recipe function f(sh::StackHist)
    # get one set of edges to bin with
    alldata = vcat(sh.vecs...)
    edges,_ = hist(alldata, get(d,:bins,default(:bins)))
    
    # common attributes
    fillalpha --> 0.3    # optional override
    seriestype := :bar  # forced override
    
    # for each vector, we create a series... bar chart starting at the
    # last total height of the last series
    lastcnts = 0
    for v in sh.vecs
        @series begin
            # force the fillrange to the last heights
            fillrange := lastcnts
            
            # get the new hist counts, then add to total
            cnts = hist(v, edges)[2]
            lastcnts = lastcnts + cnts
            
            # compute bar widths
            dffs = diff(edges)
            bar_width := 0.8dffs
            
            # return centers and heights... this is the input data to the series
            centers = edges[1:end-1] + dffs
            centers, cnts
        end
    end
end

stackhist(rand(100), rand(200), randn(100), bins=20)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/15617336/77f610e6-2416-11e6-88e1-002b97a55902.png)
