### ISSUE TITLE
Demo plots from documentation not all working

### ISSUE THREAD

**Issue by davidparks21** [tbreloff/Plots.jl#256]
I'm new to Plots and it looks great, but I'm having trouble running some of the basic demos presented in the documentation. I'd be happy to help where I can improve things (perhaps starting with some documentation to smooth the new-user experience).  

The first example we encounter in the documentation is Lorenz Attractor, which looks beautiful, and seems like a natural place to get started. So I installed the Plots release, and later the master branch.

```
Pkg.checkout("Plots")
Pkg.add("PyPlot")
Pkg.add("GR")
Pkg.add("Gadfly")
Pkg.add("Immerse")
Pkg.add("UnicodePlots")
Pkg.add("PlotlyJS")

julia> Pkg.status("Plots")
 - Plots                         0.5.4+             master

julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

I've run into these issues:

- **After install copy/paste the Lorenz Attractor demo code, it initializes pyplot as the default backend and then gives this error:**
```
ERROR: KeyError: set_data not found
 in getindex at d:\myprojects\julia\.julia\v0.4\PyCall\src\PyCall.jl:228
```
Try switching to plotly():
```
WARNING: Keyword argument zlabel not supported with Plots.PlotlyJSBackend()...
WARNING: Keyword argument zlims not supported with Plots.PlotlyJSBackend()...
ERROR: Cannot find Electron. Try `AtomShell.install()`...
ERROR: ArgumentError: ImageMagick not found in path...
```
Trying the gr() backend:
```
ERROR: ArgumentError: reducing over an empty collection is not allowed
 in _mapreduce at reduce.jl:139
ERROR: SystemError: opening file gks.png: No such file or directory
```
- **So all of these errors lead me to a question, are my backends installed correctly? How can I verify that? Perhaps there are just dependencies that I'm missing. Perhaps the backends page in the documentation could list the dependencies and how to validate each backend?  Or is that example assuming a certain backend that isn't called out in the example?**

- **I then tried: Pkg.test("Plots"), which has errors:**

```
ERROR: LoadError: LoadError: ArgumentError: ExamplePlots not found in path
```

- **Documentation doesn't describe how to switch between backends. I've found plotlyjs(), gr() in some examples, and inferred pyplot(), but the function needed to switch backends doesn't seem to be documented. I would expect that on the backends or installation page.**

- **Atom: I have gotten some basic plots to work from the REPL, but I haven't gotten plots to show in the Atom plots window. That was one of my initial goals for getting set up, but I notice that it's not mentioned in the documentation.** 

- **Repeating the first gr() backend demo twice fails on the 2nd run without error or action, gui() ignores me as well.**
```
julia> using Plots                        # Ok
julia> gr()                               # Ok
Plots.GRBackend()
julia> plot(Plots.fakedata(50,5),w=3)     # Plots to a new window from REPL, close window
[Plots.jl] Initializing backend: gr
julia> plot(Plots.fakedata(50,5),w=3)     # Command executes without error and without action
```
I'd be happy to help smooth out the initial installation, perhaps initially with some tweaks to the documentation focused on new user experience if that's helpful, but I'd like some direction, and of course help knowing what I'm doing wrong so far. :)

**Comment by tbreloff** [comment]
Can you run: `PyPlot.matplotlib[:__version__]`?

Thanks for the detailed post... I'd love input/help with docs, and I'm sure we can work through these issues.

**Comment by davidparks21** [comment]
So I'm focused on just getting the Plotly backend working smoothly in both Atom and the REPL. The Plotlyjs documentation states that this command is needed, which I ran:

```
using Blink
Blink.AtomShell.install()
```

I'm just running this basic example:
```
plot(Plots.fakedata(50,5),w=3)
```

I can now plot using Plotlyjs from the REPL ok. 

It seems like the documentation from Blink: `Blink.AtomShell.install` should be added to Plots? I can do that, but I didn't quite know what I did with that command.

The bigger problem is when I run that plot in Atom I get nothing, no error, no action, no window pop up, nada...

![image](https://cloud.githubusercontent.com/assets/964997/15259411/ffdadd78-1905-11e6-897a-e96016be5a8e.png)

A secondary concern was that the window that's opened from the REPL wasn't resizeable, or more accurately the window was resizeable, but the plot didn't scale with it, which will make it hard to read on a 4k display.

**Comment by tbreloff** [comment]
> I can now plot using Plotlyjs from the REPL ok.

Great!  I highly recommend IJulia (Jupyter) as an alternative to Atom inlining...

> The bigger problem is when I run that plot in Atom I get nothing, no error, no action, no window pop up, nada...

This is an issue that goes way beyond Plots, and has to do with the way javascript works in Atom.  I wouldn't hold your breath for Plotly in Atom...

> A secondary concern was that the window that's opened from the REPL wasn't resizeable

This is an issue to raise at PlotlyJS.  However, you should be able to set the size yourself by just adding the `size=(w,h)` keyword.  You can set a default value for that if you want (or anything else for that matter)

**Comment by simonbyrne** [comment]
I'm seeing this as well:
```
LoadError: KeyError: set_data not found
while loading In[2], in expression starting on line 13

 in getindex at /Users/simon/.julia/v0.4/PyCall/src/PyCall.jl:270
 in getindex at /Users/simon/.julia/v0.4/PyCall/src/PyCall.jl:275
 in _series_updated at /Users/simon/.julia/v0.4/Plots/src/backends/pyplot.jl:865
 in setxyz! at /Users/simon/.julia/v0.4/Plots/src/utils.jl:561
 in push! at /Users/simon/.julia/v0.4/Plots/src/utils.jl:612
 in push! at /Users/simon/.julia/v0.4/Plots/src/utils.jl:577
 [inlined code] from In[2]:17
 in anonymous at /Users/simon/.julia/v0.4/Plots/src/animation.jl:107

```

`PyPlot.matplotlib[:__version__]` gives "1.5.1"

**Comment by tbreloff** [comment]
Can you check out master and try it? I think that's fixed.
