### ISSUE TITLE
Start a news/history section in the docs

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#259]
For each release window, and for currently developed changes, track a list of everything that is changing (and being worked on) with some commentary when necessary.  Start a new section on every tagged release.  Should probably include yet-to-be worked on stuff in its own section so people have an idea of what's coming in the pipeline.

**Comment by Evizero** [comment]
I think the most standard way to do that is with a `NEWS.md`, which may or may not receive some special treatment in the future https://github.com/JuliaLang/julia/issues/16187

**Comment by tbreloff** [comment]
That's cool... I'll just have to mirror the contents in ExamplePlots.jl/docs so that it can go into the readthedocs site.
