### ISSUE TITLE
Create an empty plot/figure.

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#26]
Is there anyway to just get a handle to a plot/figure and then be able to add plots to it with `plot!` at a later stage.

I tried `plot()` but it didn't work.  Nice package by the way!

**Comment by tbreloff** [comment]
At this moment this won't work, but it's a case I want to handle.  I'll add
it now, and it should be part of the next release.  If you find anything
else please let me know.

**Comment by tbreloff** [comment]
This works now on master.  There is one caveat... I've noticed that Gadfly doesn't like it if you try to display a plot without any layers (it actually seems to break the internals).  You can get around this by adding a semicolor after the call to `plot()` when inputting through the REPL.
```
using Plots
plot(bg=:black);
plot!(rand(10), m = :star1)
```
![tmp](https://cloud.githubusercontent.com/assets/933338/9997146/9f835ef2-6058-11e5-982a-32e09b17aebb.png)

**Comment by KristofferC** [comment]
Cool! Thanks!
