### ISSUE TITLE
Feature request: panel labels for subplots

### ISSUE THREAD

**Issue by ahwillia** [tbreloff/Plots.jl#260]
It would be awesome to be able to turn this:

![image](https://cloud.githubusercontent.com/assets/636625/15306259/f0357584-1b7d-11e6-8487-81f39892e2d7.png)

Into something like this:

<img width="601" alt="screen shot 2016-05-16 at 3 53 40 pm" src="https://cloud.githubusercontent.com/assets/636625/15306326/6dc3648e-1b7e-11e6-8461-fbddf243a012.png">

With a short command. Still new to this API, but something like this?

```julia
plots(x, y, subplot_labels=(:default)) # reasonable default ordering
plots(x, y, subplot_labels=(("A","B","C","D"), 12, :bold) )
```

**Comment by tbreloff** [comment]
I'm in the middle of a massive rebuild of how subplots work.  This will be
possible, and likely easy.

**Comment by ahwillia** [comment]
Amazing. I can hardly contain my excitement.

**Comment by tbreloff** [comment]
Here's a little taste of what I'm working on.

```julia
using Plots
plt = plot(10rand(10,10), subplot=vcat(1:5,1:5)', layout=layout, title=["A" "B" "C" "D" "E"], titleloc=:left)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/15372978/22ff0d92-1d11-11e6-9033-1e3b9cfabe25.png)

**Comment by tbreloff** [comment]
This is mostly done (at least for pyplot)... gonna close in favor of #268
