### ISSUE TITLE
Issue with quiver

### ISSUE THREAD

**Issue by goedman** [tbreloff/Plots.jl#262]
Hi Tom,

Just wondering if I'm doing something wrong in below little test program. 

If I replace the ```pyplot(...)``` line by ```gadfly(size(500,500))```  (https://github.com/goedman/EDxMath226.jl/blob/master/examples/streamplot_gadfly.jl) it only shows the lower half of the quiver plot.

Rob

```
using Plots
pyplot(reuse=true, leg=false, size=(500,500))

# Define A matrix
A = [-3 -5; 3 1]

# Define domains
y = x = -4:0.5:4
xlim=(minimum(x), maximum(x))
ylim=(minimum(y), maximum(y))

# Setup derivatives
function df(x, y)
  vx = A[1,1] * x + A[1,2] * y
  vy = A[2,1] * x + A[2,2] * y
  colv = norm([0.0 0.0; vx vy])
  nvx = vx / (2.5 * colv)
  nvy = vy / (2.5 * colv)
  [nvx nvy]
end

# get a grid of points as a vector
pts = vec(P2[(x[i], x[j]) for i=1:length(x), j=1:length(x)])

# add the quiver plot
quiver(pts, quiver=df, marker=(:none,stroke(0.25,0.05)), color=:gray, lw=0.1,
  xlims=xlim, ylims=ylim)
```

**Comment by tbreloff** [comment]
On master, this works in PyPlot, GR, and Plotly (GR shown):

![tmp](https://cloud.githubusercontent.com/assets/933338/17826686/6f2af360-6641-11e6-8aed-e8eafe958b05.png)

**Comment by goedman** [comment]
Also correct, the PyPlot version works fine and that's the one I have been using until mid-June. Just got back to the US and will pick up the pieces over the next few weeks. I never tried it on Plotly, but did try GR a while back and also noted only the top half showing. Will try this again.
