### ISSUE TITLE
subplot show=true

### ISSUE THREAD

**Issue by abieler** [tbreloff/Plots.jl#263]
I am on master and just tried doing the following in a script:

```julia
p1 = plot(x,y)
p2 = plot(x2, y2)

subplot(p1, p2, show=true)
```

But no plot shows up (tried pyplot and gr).

**Comment by tbreloff** [comment]
How did you run the script? Was there anything else after it? The program
might have exited before anything could plot. Try include-ing from the REPL
or add a long sleep after that call?

**Comment by abieler** [comment]
there is a `readline(STDIN)` after the `subplot()` call. Also no plot is showing up when
putting this in a function and calling that function in jupyter

**Comment by abieler** [comment]
one difference I notice is that in jupyter `subplot()` does inline plotting. where `plot()` does not.
So my guess is the trouble in the jupyter notebook comes from the following `readline()` as it had to inline plot and provide the input field for the readline.

**Comment by tbreloff** [comment]
Weird ok. I'll see if I can reproduce.

**Comment by abieler** [comment]
in case this saves you any time

```julia
function bar()
    p1 = plot(rand(10))
    p2 = plot(rand(30))
    subplot(p1, p2, nr=2, show=true)
end

function baz()
    p1 = plot(rand(10))
    p2 = plot(rand(30))
    subplot(p1, p2, nr=2, show=true)
    readline(STDIN)
end
```

bar() works in the jupyter notebook, baz() doesnt.

**Comment by tbreloff** [comment]
Only the first should plot inline, but both should pop up a standalone gui
window. I'll try it out.

**Comment by tbreloff** [comment]
Closing, as there's no longer a `subplot`.
