### ISSUE TITLE
Plots killes kernel

### ISSUE THREAD

**Issue by aishenri** [tbreloff/Plots.jl#266]
Here is results in REPL :
surface(x,y,(x,y)->sin(x)+cos(y),
       line=(1,:black),fill=(0.8,:black),
           tickfont=font(8),guidefont=font(6),
           title="graphe",xlab="X",ylab="Y",
           size=(400,300))
[Plots.jl] Initializing backend: pyplot
Gtk-Message: Failed to load module "topmenu-gtk-module"
julia: symbol lookup error: /usr/bin/../lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType

**Comment by tbreloff** [comment]
Ok that error message is much more informative.  It seems like you have issues with libraries... likely the Gtk-backend of PyPlot and your version of pango aren't mixing well.  Does PyPlot.jl work?  You could try letting PyPlot install a local copy using Conda.jl with:

```
ENV["PYTHON"] = ""
Pkg.build("PyPlot")
```

**Comment by aishenri** [comment]
Pyplot works well (rarely before), and I am misconfident too use 
Conda.jl (is it conda ?) because I fear it doesn't mixed well with 
ubuntu python. On ubuntu it's very difficult if getting mixed with 
python 3 and 2, I tried conda with env but as I use sagemath often one 
is breaking. But I think I will try Conda.jl because Plots is quiet 
interesting, complementary of Pyplot

**Comment by tbreloff** [comment]
Ok if it helps, I am also on Ubuntu, and I don't have this issue.

**Comment by aishenri** [comment]
Here is result of your suggestion, kernel still die, I will try to remove Pkg.rm("Plots")
is there is way for cleaning julia ? (I mean delete .julia ?)
julia> ENV["PYTHON"] = ""
""

julia> Pkg.build("PyPlot")
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata: ....
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /home/pi/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.11.0                   py27_1  
INFO: PyCall is using /home/pi/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.11) at /home/pi/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/pi/.julia/v0.4/Conda/deps/usr/lib/libpython2.7.so

**Comment by tbreloff** [comment]
Can you try doing this before the first using statement?

```
ENV["MPLBACKEND"] = "Agg"
```

It will turn off the gui backends in PyPlot.

**Comment by aishenri** [comment]
Eureka ! Works fine 
Thanks
ENV["MPLBACKEND"] = "Agg"
using Plots
pyplot(reuse=true)
x=y=linspace(-5,5,30)
surface(x,y,(x,y)->sin(x)+cos(y),
line=(1,:black),fill=(0.8,:black),
    tickfont=font(8),guidefont=font(6),
    title="graphe",xlab="X",ylab="Y",
    size=(400,300))

**Comment by tbreloff** [comment]
Does it show inline plots in IJulia?

**Comment by aishenri** [comment]
Yes, sorry, I tried it directly in IJulia... Great
I will try now arrows vectors

**Comment by aishenri** [comment]
I changed from 16.04  +1 to 16.10, which is not very different, but the 
former was messed. When you send me this graphic some times ago, Pyplot 
wasn't working properly but now it does, and Plots too.
Wonderfull

**Comment by tbreloff** [comment]
Great to hear! Is it ok to close the issue?

**Comment by aishenri** [comment]
Yes sure... And thanks
