### ISSUE TITLE
It is unfortunate that the plt.o object is not always created until writemime/display is called

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#267]
This is probably related to #229. You sometimes want to just call plot and then save the .o object using maybe the backends own saver. This does not always work:

![image](https://cloud.githubusercontent.com/assets/1282691/15386938/bc32ba60-1daa-11e6-9c79-657da80fb797.png)

In order for .o to be populated, the display or writemime function need to be called:

![image](https://cloud.githubusercontent.com/assets/1282691/15386982/e048fa4a-1daa-11e6-8e91-c542d78bbd04.png)

Maybe this behavior is backend specific but it would be good to be consistent among the backends that `plot` always sets the .o object as it will be rendered by display. cc @fredrikekre

**Comment by fredrikekre** [comment]
I guess this would solve the problems I had [here](https://gist.github.com/fredrikekre/4fa0d9b4b5a17a25a574f543fdafe6dd) as well then, as long as the .o object is not overwritten by displaying the plot.

**Comment by tbreloff** [comment]
I do see the value in what you're suggesting but I think it's not ideal for
this to be default behavior. I'd rather heavy lifting is postponed until
it's needed.

One solution is to have an accessor function (bikeshed?) which generically
prepares the object without displaying. So you'd do:

custom_save(obj(plt))

**Comment by KristofferC** [comment]
An assessor function that does the updating if needed sounds like a good tradeoff!

**Comment by diegozea** [comment]
Doing `plt.o` is a bit cryptic/ugly/unjulian, I will prefer to have a (getter) function to do that (i.e. `backendobject`). The getter could manage the object creation when is needed.

**Comment by KristofferC** [comment]
Isn't that exactly what @tbreloff  suggested?

**Comment by diegozea** [comment]
I'm sorry, yes :) I will prefer the name `backendobject` over the suggested `obj`. `backendobject` is more clear.

**Comment by tbreloff** [comment]
Good we agree on the functionality... Name ideas please. backendobject is
annoyingly long... I'd prefer something shorter but still descriptive of
what it does.

**Comment by tbreloff** [comment]
I added a method `prepared_object(plt)`, which should (in most cases?) give you the `plt.o` object after being fully processed (but not displayed).

**Comment by KristofferC** [comment]
@tbreloff, doesnt seem to work.

![image](https://cloud.githubusercontent.com/assets/1282691/17479344/6eb09c28-5d72-11e6-916a-8134837a4d3a.png)
