### ISSUE TITLE
bar plot with GR

### ISSUE THREAD

**Issue by abieler** [tbreloff/Plots.jl#269]
bar plots do not work properly with the GR backend.

```julia
plot([2,4,8], [6,7,8], linetype=:bar, show=true)
```
works as expected for pyplot and plotly, but for gr it places the bars at [1,2,3] on the x axis.

There is also an issue with :step and gr. In the following example the line
of the curve goes back to [0,0] after the last coordinate pair from the data.
```julia
plot([2,4,8], [6,7,8], linetype=:step, xlims=(-1,10), ylims=(-1,10), show=true)
```

Sorry to keep opening all these issues, but I really like using your package :)

**Comment by tbreloff** [comment]
Keep em coming!  It's good to know about anything that's not right.

**Comment by tbreloff** [comment]
The first one is fixed on dev... step is still buggy.

**Comment by tbreloff** [comment]
Should be fixed
