### ISSUE TITLE
Updating labels in plot!

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#27]
Is there anyway in which you could specify the labels in not only the first plot. As an example:

![image](https://cloud.githubusercontent.com/assets/1282691/10014239/3bdc65e0-6118-11e5-8e17-a84304c444f1.png)

The x-label defined in the second plot command is not shown.

**Comment by KristofferC** [comment]
It would also be nice if you could only set the labels without plotting anything extra, for example

```jl
p = plot(rand(10))
plot!(;xlabel="label")
```

**Comment by tbreloff** [comment]
Yeah this should be possible with most backends. I see you're using pyplot, so I'll handle that first. 

I'll also add shorthands 'xlabel!()', etc. I should be able to do this today.

**Comment by KristofferC** [comment]
I'm using PyPlots because I'm having some troubles with the other backends in IJulia.

For example:

![image](https://cloud.githubusercontent.com/assets/1282691/10017751/5bd44660-6131-11e5-8669-4d9d597f14b7.png)

Same with Winston and Gadfly.

**Comment by tbreloff** [comment]
I'm a little confused what you're trying to do.  `x_mod` and `y_mod` are not valid arguments in Plots, so I wouldn't expect this to flow through to the backends at all.  Also what is `matstats`?  Let me know how you'd like to call this, and I can either tell you the right way, or add support for it.

**Comment by KristofferC** [comment]
Sorry, I understand your confusion, I should have explained bette. I am writing a package where the resulting data is a bit messy to extract from the type. To facilitate plotting of the results I therefore extend the `plot` function in `Plots.jl` with another function that take the types in my package (`matstat` is one of those types). This function then extracts the needed data from them and then finally calls the `Plots.jl` `plot`-function and return that plot object

However, the problem has nothing to do with this, it is just that with certain backends like Immerse, Gadfly, Winston I get no output in IJulia.

An example which does not contain any of my own code:

![image](https://cloud.githubusercontent.com/assets/1282691/10019854/041299fe-6140-11e5-972b-a852c0f83d0e.png)

**Comment by KristofferC** [comment]
Using for example Gadfly directly works.

![image](https://cloud.githubusercontent.com/assets/1282691/10019979/aa086898-6140-11e5-9b10-0b43727e8003.png)

**Comment by tbreloff** [comment]
Ah I see, so it's just not displaying in IJulia.  Ok I need to look into that... I don't actually use IJulia at all, but I know others do, so I want that to work as expected.

**Comment by tbreloff** [comment]
Just installed IJulia, so I'll investigate further.  However, does it work if you do:
```
using Plots
gadfly!()
plot(rand(10))
display(currentPlot())
```

**Comment by KristofferC** [comment]
Cool! That works beautifully for Gadfly

For Winston (works with `using Winston`):

```jl
LoadError: MethodError: `display` has no method matching display(::Gtk.GtkCanvas, ::Winston.FramedPlot)
Closest candidates are:
  display(!Matched::AbstractString, ::Any)
  display(!Matched::TextDisplay, ::Any)
  display(!Matched::MIME{mime}, ::Any)
  ...
```

**Comment by tbreloff** [comment]
Ok thanks.  I'll look into Winston, but I suspect that IJulia calls a
specific "writemime" method to show its results, and my display method is
only getting called from the REPL.  It should be a relatively easy fix, as
soon as I figure out the specific problem.

**Comment by tbreloff** [comment]
By the way, this works on the development branch, and I'll push it to master once I finish with a display/writemime re-write.

```
using Plots
plot(rand(10))
plot!(title="title", ylabel="ylabel")
xlabel!("xlabel")   # shorthand for plot!(xlabel="xlabel")
```

**Comment by tbreloff** [comment]
Both the original labels/title request, and the IJulia display issues should all be fixed now on latest master.  Please try it out.

**Comment by KristofferC** [comment]
Works great! Thanks!

**Comment by tbreloff** [comment]
Cool!  If there's anything that's not easy or intuitive, please let me
know.  I want this to be the kind of package that "just works" no matter
what you throw at it.

**Comment by KristofferC** [comment]
One thing, for Gadfly this works great:

![image](https://cloud.githubusercontent.com/assets/1282691/10047272/b23a24ca-620d-11e5-8b17-b0359ee75071.png)

For Pyplot I get two outputs, one that is above the `Out`:

![image](https://cloud.githubusercontent.com/assets/1282691/10047335/fa62b122-620d-11e5-9126-f18de7179f3a.png)


Winston works.

Unicodeplots workish (maybe this is a limitation with the backend):

![image](https://cloud.githubusercontent.com/assets/1282691/10047357/14e44830-620e-11e5-8047-aff9365a0616.png)

**Comment by tbreloff** [comment]
Thanks... I'll look into PyPlot's double-display.  As for UnicodePlots, that's more of a REPL plotting tool... I'm actually surprised it does anything even remotely good in IJulia!

**Comment by tbreloff** [comment]
Also one additional comment... unless you need the plot reference `p` somewhere later in your code, it's unnecessary.  Instead of
```
pyplot!()
p = plot(rand(10))
plot!(p, rand(10))
```
you can do:
```
pyplot!()
plot(rand(10))
plot!(rand(10))
```

Plots keeps track of the "current plot" for you, and when you leave it out it will automatically update the current plot.

**Comment by tbreloff** [comment]
I pushed to master.  The pyplot double-show issue is still there, and is not an immediately easy solution.  The pyplot code is a little hacky to get it to work in IJulia, and the figure seems to be displayed at various stages of the building process, and _not_ after the plot method returns.  It works fine at the REPL, so I need to pour through Steven's code a little more to understand what he's doing for IJulia.

**Comment by tbreloff** [comment]
closing for more specific issue #29
