### ISSUE TITLE
density=true not working in GR

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#272]
```julia
using Plots; gr()
r=randn(1000);plot(vcat(r...);t=:density)
```

doesn't rescale the y-axis.

**Comment by tbreloff** [comment]
Density should be coverted to a series recipe so we don't implement it for
each backend.

**Comment by tbreloff** [comment]
I made this a series recipe.  It uses the KernelDensity package if it's installed, otherwise it estimates with a line-histogram. 

```julia
using Plots; gr()
y = randn(1000)
histogram(y, normed=true)
density!(y, fill=0, line=(3,:green))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/15845894/7589a3c2-2c45-11e6-8122-4c94f13a1b2d.png)
