### ISSUE TITLE
Axes swapped in heatmap

### ISSUE THREAD

**Issue by oschulz** [tbreloff/Plots.jl#273]
Plots.jl 0.6.2 mirrors the axes for heatmap with the PyPlot backend:

```
Plots.heatmap(0:0.1:1, 0:0.1:1, (x, y) -> e^-x)
```

![exp-heatmap-mirrored](https://cloud.githubusercontent.com/assets/546147/15498209/f2e72c2e-219e-11e6-8d4b-fc8ac81dc786.png)

The bright area should be on the left, not on the bottom. This is a new problem, with the Plots.jl version (sorry, forgot which one) I used before, everything was fine. Interestingly, `histogram2d` still plots correctly:

```
# Random numbers distributed according to e^-x:
X = -log(rand(100000))
# Uniform random numbers:
Y = rand(100000)
Plots.histogram2d(X, Y)
```

![exp-histogram2d](https://cloud.githubusercontent.com/assets/546147/15498267/3ca475ce-219f-11e6-9614-c7d79a058b03.png)

**Comment by tbreloff** [comment]
This is actually a feature, not a bug.  I was convinced to change it to follow conventions in which the y-axis should match the rows of the z-matrix.  See: https://github.com/tbreloff/Plots.jl/issues/196#issuecomment-216725551

You can switch the behavior with `transpose = true`

**Comment by oschulz** [comment]
> This is actually a feature, not a bug.

It results in a lot of inconsistency, though, if x and y data have to be passed to heatmap in a different order than for all other plots (including histogram2d, which should be the same, modulo auto-binning of the data). I would imagine that it will surprise many users.

**Comment by oschulz** [comment]
> in a different order than for all other plots
Ok maybe not exactly in a different order - it's matrix data, after all. Still, it's confusing when using a generation function, like in my example - so shouldn't x and y be passed in a different order too, then, if z is a function?

**Comment by tbreloff** [comment]
I don't disagree... which is why I fought it.  Just like anything, there can only be one built-in default, and someone's always going to disagree with the choice.  My solution is to tie it to a keyword (`transpose` is an alias for `match_dimensions`) so that you can set your own personal default value if you want.

**Comment by oschulz** [comment]
Sure, transpose works. But what I mean is, couldn't Plots.jl just feed x and y into z in a different order if `transpose` is set to false? I would assume that if z is given as a function, the user would always assume that the x-axis is the first, and the y-axis the second argument. If z is a function, the user will never see the resulting matrix, after all.

**Comment by tbreloff** [comment]
It's worth considering, but we'd really have to think that through.  If anyone else has an opinion, please chime in!

**Comment by oschulz** [comment]
Thanks for considering it, Tom. I really have a feeling that the average user will be really surprised, otherwise, if he does something like (this time with axis labels)

```
Plots.heatmap(0:0.1:1, 0:0.1:1, (x, y) -> e^-x, xlabel = "x", ylabel ="y")
```

![out](https://cloud.githubusercontent.com/assets/546147/15505603/7884130e-21c4-11e6-8352-352784026520.png)

It's just such a natural thing to do - and if you don't know what the function should looks like, you may never notice it's "wrong". Or in other terms, the user will likely never thing in terms of a matrix, he's just plotting a function, in his mind.

**Comment by pkofod** [comment]
I'd prefer if `heatmap` had axis `(x,y)` as well; just as proposed in https://github.com/tbreloff/Plots.jl/issues/196#issuecomment-216731678 . At least the way I've ever used a heatmap, it was to draw a flattened 3D plot of a function.

**Comment by jebej** [comment]
It seems that matplotlib, whose heatmap equivalent is called `pcolor`, displays the matrix like Plots.jl (one reason why this behaviour was changed recently) but also relabels the axes! The x-axis thus becomes the rows, and the y axis the columns. I had not noticed this issue, because when discussing in issue #196 I was only concerned about the location of the points, not their association to any axis.

See [this question](http://stackoverflow.com/questions/14391959/heatmap-in-matplotlib-with-pcolor) on StackExchange and notice that the command to set the x-axis labels labels the vertical axis.

**Comment by jebej** [comment]
This command by @oschulz 
```julia
Plots.heatmap(0:0.1:1, 0:0.1:1, (x, y) -> e^-x, xlabel = "x", ylabel ="y")
```
would thus look the same, except that the xlabel would go on the left instead of at the bottom of the plot, matching the function used.

**Comment by jebej** [comment]
Plotly currently has the [same behaviour](https://plot.ly/python/heatmaps/) as Plots.jl, whereas the x-axis corresponds to columns of the matrix...

Pick your poison!

**Comment by tbreloff** [comment]
@jebej yes both PyPlot and Plotly do it this way, which was why I decided to follow suit.  The open question is whether functions should be called f(y,x) instead of f(x,y)... I'm really torn on this issue.  There's no right answer :(

**Comment by oschulz** [comment]
> except that the xlabel would go on the left instead of at the bottom of the plot

I don't think that would be a good solution - having the x-axis on the left, different from all other plots, would be a huge inconsitency - esp. compared to histogram2d.

> whether functions should be called f(y,x) instead of f(x,y)

I wouldn't say we'd call `f(y, x)` - I'd put it differently: For

    Plots.heatmap(0:0.1:1, 0:0.2:2, (x, y) -> e^-x, xlabel = "x", ylabel ="y")

we should *always* call f(x,y), with `x in 0:0.1:1` and `y in 0:0.2:2`, *never* f(y, x). The question is rather how the results should be mapped to a matrix, and we have free choice there. However, I would choose to do it just like the matrix display works now: Since the change in behaviour (which I like, in principle), matrices are displayed with i on the y-axis and j on the x-axis (and with `transpose = true`, the other way round).

So I'd say we should simply map the output of `f(x, y)` to the matrix to be plotted (let's call it `A`) the same way:

```
    if (transpose == false)
        A[i, j] = f(x[j], y[i])
    else
        A[i, j] = f(x[i], y[j])
    end
```

After all, why should be map x/y to i/j differently for matrix generation and matrix display?

So this way, the function will always be displayed correctly, with the x-axis corresponding to the first function argument, and the y-axis corresponding to the second function argument - which I believe is a pretty universal convention and will be every user's intuitive assumption.

**Comment by jebej** [comment]
That sounds like a good solution @oschulz , the user does not need to know about how the 2D function is internally converted into a matrix for display.

This would also mean that we would keep the x-axis on the horizontal, like Plotly is doing, but unlike matplotlib. I think that is fine anyway since the function used to make heatmaps in matplotlib is not called `heatmap` anyway.

**Comment by tbreloff** [comment]
![tmp](https://cloud.githubusercontent.com/assets/933338/15617856/be9fda98-2418-11e6-816d-774a45a49871.png)

**Comment by sje30** [comment]
Hi @tbreloff 

I found some inconsistency in the heatmap() for different engines:

```
using Plots
z = [2.0*x*y for x=1:5, y=1:8]
heatmap(z)
gr()
heatmap(z)
plotly()
heatmap(z)
```

The gr version (top-left) does not have a legend, and is inverted compared to the other two versions.

<img width="1217" alt="heatmaps" src="https://cloud.githubusercontent.com/assets/1095067/20259664/fd2ef03a-aa4d-11e6-9c03-1708f8753f65.png">

**Comment by tbreloff** [comment]
The cbar drawing is a known issue, but I'm surprised about the transpose.
What version of Plots?

**Comment by sje30** [comment]
Thanks.  NEWS.md reports this as version 0.9.4, and git says:

```
~/.julia/v0.5/Plots $ git log| head -10
commit 81302c1e9dad35ae1c713268f5fe39452819fa12
Author: Thomas Breloff <tom@breloff.com>
Date:   Tue Oct 11 12:43:38 2016 -0400

    NEWS; bump version
```

**Comment by tbreloff** [comment]
Check out Plots and PlotUtils and try again.

**Comment by sje30** [comment]
Thanks, update flipped the gr() to match the other two.
