### ISSUE TITLE
Ugly color bar legend with PyPlot in SVG

### ISSUE THREAD

**Issue by oschulz** [tbreloff/Plots.jl#274]
Sorry, to bother you again, Tom. ;-)

I noticed that (at least with the PyPlot backend) the color bar legend for 2D plots looks ugly for SVG output (and plot display in Jupyter):

```
Plots.histogram2d(randn(100000), randn(100000))
Plots.savefig("plots-color-legend.svg")
```

![plots-color-legend svg](https://cloud.githubusercontent.com/assets/546147/15498654/c3e67a36-21a0-11e6-868a-e4c44648f741.png)

PNG output is fine:

```
Plots.savefig("plots-color-legend.png")
```

![plots-color-legend](https://cloud.githubusercontent.com/assets/546147/15498698/f7246a8e-21a0-11e6-9e1c-59d1df58627a.png)

**Comment by oschulz** [comment]
Btw - is it possible to make PyPlot use PNG for display in Jupyter, except SVG (for all or only certain plots)?

Certain plots (like scatter plots with many points or 2D plots with many bins) are huge (in MB) in SVG, so the file size of the Jupyter notebook explodes. Such notebooks get really sluggish, and GitHub Gists even crashes when trying to upload them.

**Comment by KristofferC** [comment]
PyPlot says that it plots in png by default: https://github.com/stevengj/PyPlot.jl#svg-output-in-ijulia. I can't see if this is overridden in Plots.jl somewhere.

**Comment by oschulz** [comment]
Well, Plots.jl definitely produces SVG in Jupyter, for the PyPlot backend.

Still, should have check the PyPlot docs - I didn't know about `PyPlot.svg(true)`. With that, PyPlot produces ugly color bars, too. ;-)

So it's not a Plots.jl issue at all, my apologies.

**Comment by KristofferC** [comment]
Have you tried it in pure python? Maybe this is not a `.jl` issue at all.

**Comment by oschulz** [comment]
No, but you're right, it probably is.

**Comment by KristofferC** [comment]
See https://github.com/matplotlib/matplotlib/issues/4480/#issuecomment-106138783

**Comment by KristofferC** [comment]
From the commit message fixing that issue:

> Now, if a colorbar is showing 50 or more colors, it will be rasterized in vector backends."

Maybe that is what is happening.

**Comment by oschulz** [comment]
I guess I better move the PNG-plots question to a new issue (#275).

**Comment by oschulz** [comment]
Thanks for the pointer to the matplotlib issue @KristofferC!
