### ISSUE TITLE
What does fill=(0,:orange) mean?

### ISSUE THREAD

**Issue by AStupidBear** [tbreloff/Plots.jl#277]
taken from ```plot(sin,x->sin(2x),0,2π,line=4,leg=false,fill=(0,:orange))```

**Comment by tbreloff** [comment]
This is on my list for better documentation.  In the meantime you could follow the logic here: https://github.com/tbreloff/Plots.jl/blob/dev/src/args.jl#L589-L607

In this case, you're setting `fillrange = 0` and `fillcolor = :orange`.  Fillrange can be a number (fills to a flat line), or a vector to fill to varying numbers.  Colors can be lots of stuff, in this case the symbol orange will construct a `Colors.Colorant`.  Any other questions... gitter.im/tbreloff/Plots.jl is a great place to ask!

**Comment by AStupidBear** [comment]
Thank you
