### ISSUE TITLE
Plotting a function does not seem to work

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#28]
For example:

![image](https://cloud.githubusercontent.com/assets/1282691/10049357/67c46856-6217-11e5-918c-cfe626cee5bf.png)

**Comment by KristofferC** [comment]
Switching the arguments works but the README says that both ways should work I think.

**Comment by tbreloff** [comment]
Thanks... I was missing a `typeof` in an assert.  This will be fixed next time I push to master.
