### ISSUE TITLE
histogram2d messes up axis with GR

### ISSUE THREAD

**Issue by abieler** [tbreloff/Plots.jl#283]
The following code works as expected for pyplot backend, but
messes up axis for gr. resulting in an apparent inversion of the
correlation between variables. 

```julia
using Plots
gr()
x = rand(100)
y = 5.* x .+ rand(100)
histogram2d(x, y)
```

cheers,
andre

**Comment by tbreloff** [comment]
Try dev branch? Thought I fixed that. Need RecipesBase master.

**Comment by abieler** [comment]
yes, on the dev branch it works when RecipesBase is on master.
Thanks!
