### ISSUE TITLE
`isx` not defined in `addPyPlotTicks` 

### ISSUE THREAD

**Issue by gabrielgellner** [tbreloff/Plots.jl#284]
If you send an invalid tick spec to `plot` the final cascade calls:
```
error("Invalid input for $(isx ? "xticks" : "yticks"): ", ticks)
```
but `isx` is not defined anywhere leading to an undefined error from julia.

(PS as I read thru the code, is there a reason for using camelCase sometimes? Or is it just an artifact of early code?)

**Comment by tbreloff** [comment]
That's code that shouldn't exist anymore. I'll fix. Camelcase was what I
started with, but I've been transitioning to underscores. Takes a while to
get to everything though...

**Comment by gabrielgellner** [comment]
Cool. That is what I figured, switching coding styles is always a pain, I use so many camelCase languages I barely see that anymore ;)

 I just wanted to make sure it wasn't trying too mirror some wrapped api etc. that I wasn't aware of.
