### ISSUE TITLE
`plot(p1::Plot, ..., pn::Plot, layout=GridLayout)` does not align axis correctly

### ISSUE THREAD

**Issue by gabrielgellner** [tbreloff/Plots.jl#285]
A simple example:
```julia
x = linspace(0, 2π, 100)
y = sin(x)
plot(x, [y 2*y 10*y], layout=GridLayout(3, 1))
```
Has the correct alignment:

![aligned](https://cloud.githubusercontent.com/assets/9829364/15630413/9cb9192c-24ee-11e6-8c83-49a35944205a.png)

whereas
````julia
x = linspace(0, 2π, 100)
y = sin(x)
p1 = plot(x, y)
p2 = plot(x, 2*y)
p3 = plot(x, 10*y)
plot(p1, p2, p3, layout=GridLayout(3, 1))
```
Does not align the last plots left axes correctly

![not aligned](https://cloud.githubusercontent.com/assets/9829364/15630417/aa412b16-24ee-11e6-994b-d177f114ecf1.png)

**Comment by tbreloff** [comment]
Talk about being picky ;). Thanks for opening the issue.

**Comment by gabrielgellner** [comment]
I am a refugee from Mathematica. Aligning plots like this is a dark art in that world ... I am still recovering :)

**Comment by tbreloff** [comment]
This seems to be fixed now.  My OCD wins again.

![tmp](https://cloud.githubusercontent.com/assets/933338/15954130/5f0d0590-2ea1-11e6-9777-844c95549d99.png)
