### ISSUE TITLE
Surface command throwing errors on GR and Plotly

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#286]
For PyPlot, you simply need to give (x,y,z) coordinates. A simple example can be constructed as follows (uses a meshgrid implementation from my package, but it's just the same as the one you'd find anywhere)

```
x,y = DifferentialEquations.meshgrid(0:0.1:1)
z = rand(11,11)
Plots.pyplot(show=true)
Plots.surface(vec(x),vec(y),vec(z))
```

This gives a nice plot. However, if you try

```
Plots.gr()
Plots.surface(vec(x),vec(y),vec(z))
Plots.gui()
Plots.plotly()
Plots.surface(vec(x),vec(y),vec(z))
Plots.gui()
```

both of those will error on the gui call saying `type Array has no field surf`. However, [from this example](https://github.com/jheinen/GR.jl/blob/68e95c98e79e74b19b470e1b9184bcd067950857/examples/griddata.jl) it's clear that GR should also take in (x,y,z) vectors.

**Comment by tbreloff** [comment]
Thanks. This is called a "tri-surface plot" where the data needs to pass
through a triangulation algorithm to compute the triangles to draw. This
was recently added to GR, but hasn't been wrapped yet. I don't know if it
exists in Plotly... If you have a link for that it would be helpful.

**Comment by ChrisRackauckas** [comment]
I thought surface would call surface plots (though it does seem to call trisurf for PyPlot). I think that Plots should disambiguate between them and have it match the matplotlib/MATLAB/Plotly convention (seems pretty standard). [This page shows both in matplotlib](http://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html#surface-plots).

As for trisurf plots, in PyPlot the keyword arg is triangles. Does that not match with GR?

For a non-trivial example, I can make the following with PyPlot:

```
using DifferentialEquations
mesh = meshExample_lakemesh()
PyPlot.plot_trisurf(mesh.node[:,1],mesh.node[:,2],ones(mesh.node[:,2]),triangles=mesh.elem-1)
```

That just loads a mesh of (x,y) as node, and elem are the indices for the triangles ([1 3 4] means the 1st, 3rd, and 4th nodes are the vertices of the triangle). I'm just throwing in a ones for z because the mesh is more important here. Notice the triangle indices had to be moved down by 1 for Python's indexing. This gives the plot:

![trisurfexample](https://cloud.githubusercontent.com/assets/1814174/15633848/c4f8b5aa-256b-11e6-8095-b22ea9d9ad63.png)

So in this method you don't need to pass it through a triangulation algorithm, you just need to know the vertices (which for finite element solvers this is known).

**Comment by tbreloff** [comment]
+1 to splitting triangulation from plotting.  In fact, it would be ideal if Plots could call a triangulation routine (really just a series recipe) and generically pass triangles to the backends.

As for trisurf vs surf... I think the difference between the inputs is enough of a separation... there's no need to distinguish between surface types (though trisurf can be an alias).  Other software probably must distinguish due to implementation restraints.

**Comment by ChrisRackauckas** [comment]
I think the split can be whether triangles are given or not. If you do the PyPlot trisurf without triangles, it pretty much just "completes" all the triangles aand you get basically what you'd get from surface. I don't know about GR, and plotly is based off of matplotlib.

**Comment by tbreloff** [comment]
tracking in meta-issue #314

**Comment by hpoit** [comment]
Hi Tom. Should this issue be re-opened? I'm getting `type Array has no field surf` https://github.com/hpoit/ML-Coursera/blob/master/week%203/Exercise%202%20-%20Logistic%20Regression.ipynb
