### ISSUE TITLE
{x,y}lims silently ignores array input

### ISSUE THREAD

**Issue by gabrielgellner** [tbreloff/Plots.jl#289]
If one tries to give the axis limits using an array like
```julia
x = linspace(0, 10, 100)
y = sin(x)
plot(x, y, xlims=[5, 10])
```
The plot will still show the full range [0, 10]
![figure_1](https://cloud.githubusercontent.com/assets/9829364/15664572/e41c722e-26b9-11e6-95cd-28638bce0212.png)

**Comment by tbreloff** [comment]
This is allowed now, which also opens up the ability to pass in matrices to set many subplots:

![tmp](https://cloud.githubusercontent.com/assets/933338/15966877/01ba1ff2-2ef3-11e6-80a8-b222a5187512.png)

(note that each column of the xlims matrix is mapped to a subplot)
