### ISSUE TITLE
PyPlot - bug in IJulia display

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#29]
PyPlot seems to display at several intermediate stages of plot creation from IJulia, and doesn't show the final plot. I suspect this is due to PyPlot.jl automatically inserting the object into a display queue on calls to PyPlot.

Things to try:
- Bypass the call to `PyPlot.figure`?
- Replace `PyPlot.plot`, `PyPlot.legend`, etc with direct calls to matplotlib?

**Comment by KristofferC** [comment]
Maybe the commands `ion()` and `ioff()` can be off help. These turn on/off interactive mode and by calling `ioff()` first, the plots from PyPlot does not show up in IJulia. Maybe you can just display the plot object then?

**Comment by tbreloff** [comment]
@KristofferC you're a genius!! :100: 

![tmp](https://cloud.githubusercontent.com/assets/933338/10076092/852edcc4-62a7-11e5-85ea-9d4584d5f7b5.png)

I'll fix properly and push to master today.
