### ISSUE TITLE
Multiple gifs in IJulia notebooks

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#292]
`@gif` is saving a single `tmp.gif` file after each call, so you can use it more than once per IJulia notebook if you want to share it: In this [Example](http://nbviewer.jupyter.org/github/diegozea/AnalisisDeDatosCualitativos.jl/blob/master/material/I.%201.%20Variables%20aleatorias%20y%20funciones%20de%20distribuci%C3%B3n.ipynb#Distribución-Normal) the last plot of the notebook appears in each `@gif` cell...
This could be solved by adding a filename parameter to `@gif`, i.e.:
```julia
@gif for i=x
plot(...)
end name "x"
```

**Comment by KristofferC** [comment]
I don't like these suggestion where you tack on stuff after the `end`.

**Comment by tbreloff** [comment]
i agree with @KristofferC.  If you want finer control over animations, be explicit:

```julia
anim = @animate for i=1:100
    plot(...)
end
gif(anim, "/tmp/anim_fps15.gif", fps = 15)
gif(anim, "/tmp/anim_fps30.gif", fps = 30)
```

**Comment by diegozea** [comment]
That needs to be updated in the docs. I didn't know about the `@animate alternative`, I was using the tedious 3 step instead.

**Comment by tbreloff** [comment]
You're right... I just threw together a better description: http://plots.readthedocs.io/en/latest/animations/

**Comment by diegozea** [comment]
The [pyplot example link](http://plots.readthedocs.io/en/latest/examples/pyplot/#functions-adding-data-and-animations) hasn't an animation.
