### ISSUE TITLE
Feature Request: Color Limit in Heatmaps

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#293]
It would be nice to be able to normalize the colors in heatmaps. This is necessary for making coherent animations. Maybe a keyword of clim?

**Comment by tbreloff** [comment]
Done in pyplot:

![tmp](https://cloud.githubusercontent.com/assets/933338/15954735/8a37012e-2ea8-11e6-9cf5-0adf8f570ce8.png)

todo:

- [ ] gr
- [ ] plotly
- [ ] pgfplots

**Comment by tbreloff** [comment]
closing in favor of the linked meta-issues
