### ISSUE TITLE
Multiple issues with subplot and heatmap-style colors

### ISSUE THREAD

**Issue by wwywong** [tbreloff/Plots.jl#295]
The example is based on http://plots.readthedocs.io/en/latest/examples/pyplot/#colors

```
using Plots
pyplot()
y = rand(1000)
plot1 = scatter(y,zcolor=abs(y - 0.5),m=(:heat,0.8,stroke(1,:green)),ms=10 * abs(y - 0.5) + 4,lab="label 1", title="Plot 1")
```

This outputs 
![p1](https://cloud.githubusercontent.com/assets/19225547/15751688/fb9c8366-28b8-11e6-9e68-2def9f36fcbc.png)

```
y = rand(1000)
plot2 = scatter(y,zcolor=abs(y - 0.5),m=(:heat,0.8,stroke(1,:green)),ms=10 * abs(y - 0.5) + 4,lab="label 2", title="Plot 2")
```

![p2](https://cloud.githubusercontent.com/assets/19225547/15751728/17d8320a-28b9-11e6-9a4f-24d269d63a06.png)

So far so good. But next

```
plot(plot1,plot2,nc=1)
```

gives
![p3](https://cloud.githubusercontent.com/assets/19225547/15751775/5b7197fe-28b9-11e6-91ff-56e271cbe6a4.png)
which has two problems:

1. The color scale for the first plot disappeared. 
2. The `nc = 1` option is ignored! 

The color scale problem persists for using the `layout` syntax for laying out the plots. 

```
plot(plot1,plot2,layout=@layout([a;b]))
```

gives
![p4](https://cloud.githubusercontent.com/assets/19225547/15751864/b47948d8-28b9-11e6-898a-14ec43c6391e.png)

-------------

I just updated Plots.jl to the master branch today.

**Comment by tbreloff** [comment]
Thanks for the detailed report. I'll check it out when I can. You might
want to check out the dev branch as there's several fixes not on master.

**Comment by wwywong** [comment]
I can confirm that the behaviors both persist on 'dev'.

**Comment by tbreloff** [comment]
I fixed the colorbar issue... I'll push it to dev soon.  As for the `nc` keyword, I think I'm going to deprecate it in favor of setting `layout` explicitly.  So you'd want to do:

```julia
# 2 rows, 1 column
plot(p1, p2, layout = (2,1))

# 2 subplots, grid is auto-computed to be (1,2)
plot(p1, p2, layout = 2)
```
