### ISSUE TITLE
issue with heatmap

### ISSUE THREAD

**Issue by rveltz** [tbreloff/Plots.jl#297]
Hi,

Using the last branch

`- Plots                         0.6.3              master`

when using 

`using Plots`
`gr();heatmap(rand(20,20))`

I stumble into the following issue:

`ERROR: MethodError: `start` has no method matching start(::Plots.Extrema)
 in expand_extrema! at /Users/rveltz/.julia/v0.4/Plots/src/components.jl:372
 in _apply_series_recipe at /Users/rveltz/.julia/v0.4/Plots/src/plot.jl:236
 in _plot! at /Users/rveltz/.julia/v0.4/Plots/src/plot.jl:446
 in heatmap at /Users/rveltz/.julia/v0.4/Plots/src/Plots.jl:209`

Do you please have any idea what caused it?

Thank you for your help,

Best regards

**Comment by tbreloff** [comment]
Try dev branch?

**Comment by rveltz** [comment]
No luck...

`- Plots                         0.6.3+             dev`

**Comment by ChrisRackauckas** [comment]
I'm getting this issue with just standard line plots on dev. Switching to master fixed everything. I think dev might just have a problem with the last commit.

**Comment by rveltz** [comment]
On master, `plot` works but not `heatmap` for me

**Comment by tbreloff** [comment]
Should be fixed now (might need to wait for me to push another commit)
