### ISSUE TITLE
Plots! error when trying to change the margins

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#299]
I generated plots in a loop, and then when I tried to change the margins after the loop, I got an error that it could not find the background color (screenshot of Atom).

FYI I could still plot it, open it in the gui, adjust the size (and effectively the margins) and ad-hoc solve the problem. 

![error](https://cloud.githubusercontent.com/assets/1814174/15807027/0de29dbc-2b07-11e6-9827-93bf2e69921b.PNG)

**Comment by tbreloff** [comment]
I didn't see this error, but it made me realize that for any arg with default value `:match`, and updates to the reference arg of a matched variable wouldn't be processed.  So if you do `plot!(margin=20mm)` it would silently do nothing, but `plot!(left_margin=20mm)` would work.  I'm working on a small refactor to postpone the "match" logic until value retrieval.  This issue should be fixed afterwards.

**Comment by tbreloff** [comment]
Ok I think I got this working properly in PyPlot (and broke all other backends for now... though fixes are easy).  For a guaranteed seizure, try out:

```julia
using Plots
p = plot(rand(10))
@gif for i=1:10
    plot!(bg = RGB(rand(),rand(),rand()), margin = 40mm*rand())
end
```
