### ISSUE TITLE
Real-time updating of plot data

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#30]
I have lots of applications which require adding to or replacing the underlying x/y data in my plots.  I want a simple interface which likely overloads base methods like `push!`, etc.

Here's a sample prototype (backend is Immerse):

![tmp](https://cloud.githubusercontent.com/assets/933338/10080124/da45128c-62bb-11e5-9469-6b58397ce391.png)

**Comment by joshday** [comment]
:+1: I started messing around with plotting methods for OnlineStats, so this would be great.

**Comment by lobingera** [comment]
Better call it 'near-real-time' updating, or 'Update Data'. People would expect real-time plotting and for e.g. a PDF output that's hard to do...

**Comment by tbreloff** [comment]
@joshday Cool... are you working on the "josh" branch?  I have some ideas there... maybe we should start an issue to discuss at OnlineStats?

@lobingera I hear ya... certainly the degree of "real-time-ness" depends on the backend.  Likely UnicodePlots and Gadfly aren't good for this, but any of the others could be?

**Comment by lobingera** [comment]
But it like this: real-time-update sounds like you connect some data with some graph and if the data is updated, the graph follows. Actually earlier (some months ago) i asked if the REPL can support this -> filter, what has been changed (LHS of evaluation,assignment) and feed that information somewhere. Back then the REPL wasn't able, but maybe now. In any case you need some infrastructure to get that change down. How about auto-scaling in cases like this?

**Comment by tbreloff** [comment]
> real-time-update sounds like you connect some data with some graph and if the data is updated, the graph follows

This is exactly what I want to do, and the prototype can already work this way.  You can just call `gui()` to update the display between each `push!`.

This currently works as expected (on master)... one extra point is added to the graph every half-second:

```
using Plots; immerse!()
plt = plot([0,0.1], Any[rand(2),sin])
for x in 0.2:0.1:π
    push!(plt, 1, x, rand())
    push!(plt, 2, x, sin(x))
    gui(); sleep(0.5)
end
```

**Comment by lobingera** [comment]
as a side question: why immerse!() ? I thought, ! methods are supposed to change the argument, and there's little argument

**Comment by tbreloff** [comment]
@lobingera My interpretation of `!` methods is that they are appropriate whenever you are changing state (whether or not that state belongs to the arguments).  For this particular case, I agree that the `!` probably isn't necessary, and I could add `immerse()` to do the same thing.

**Comment by tbreloff** [comment]
Also technically speaking the `plot!(rand(10))` calls fall into this category as well.  You're changing the state of a `Plot` object, but it's not an argument to the method, it just happens to change the state of the return value from `currentPlot()`.

**Comment by lobingera** [comment]
Statefull vs. stateless plot commands is a tricky thing. Statefull makes great sense in REPL, but not necessarily in scripted plotting. And maybe this discussion should be in #1

**Comment by tbreloff** [comment]
I don't think I understand your point.  Why is REPL any different than scripting here?

**Comment by tbreloff** [comment]
In regards to the real-time-ness discussion, I ran a quick test... 17 millis per update may not be "real-time" but it's certainly close enough for most applications (and certainly better than re-writing a PDF every time).  However, in most cases you wouldn't update the display after every data point unless the points were updating very slowly.

![tmp](https://cloud.githubusercontent.com/assets/933338/10081558/71836a7a-62c3-11e5-83b5-b795d67826c4.png)

**Comment by lobingera** [comment]
@tbreloff 
In the REPL you work with a single scope, so the state will be atomic. When you run a script in a single instance you will use a single state, but what if you try to parallelize?

**Comment by tbreloff** [comment]
You can always call plot!(plt, args...; kw...) and control which object's state is changed...

**Comment by tbreloff** [comment]
I have pretty good support for updating plots now, so closing this.

**Comment by zsoerenm** [comment]
Is there a way to push errorbars or ribbons?
Something like this?
```
push!(plt, 3, 1, err = 2)
```
```
push!(plt, 3, 1, ribbon = 2)
```
If not is there a workaround?
At the moment I get the following error:
```
ERROR: function push! does not accept keyword arguments
```

**Comment by mkborregaard** [comment]
`plot!`?

**Comment by zsoerenm** [comment]
Well, I think `plot!` does only add a new line to the current plot, doesn't it?
Whereas, I want to extend a current line with an errorbar / ribbon at the end.

**Comment by mkborregaard** [comment]
If you give an MWE I wouldn't mind commenting on what you're doing. But `push!` isn't defined for `Plot` objects.

**Comment by zsoerenm** [comment]
Here you go:
```
using Plots
plt = plot(1:10, zeros(10), err = randn(10))
push!(plt, 1, 11, 0.1)
```
This extends the line without the errorbar by a new value.
Is there a way to do the same for the errorbars?

**Comment by mkborregaard** [comment]
Ha, I didn't realize you could do that :-) I just looked at the code, and no, it doesn't seem like you can do that, sry.

**Comment by zsoerenm** [comment]
I think I found a workaround using `plot!`
```
using Plots

plt = plot(1:10, zeros(10), err = randn(10))
plot!(plt, 11:11, 0.1:0.1, err = 0.5, legend=false)
push!(plt, 1, 11, 0.1)
```
![figure_1](https://user-images.githubusercontent.com/375486/29572097-84e72e80-875b-11e7-8cf3-727851d6f698.png)
Thanks for taking your time

**Comment by adhal007** [comment]
I have a plot for each of a 100 samples run for 1000 iterations, so it creates an array of 100 plots. How is it possible to merge these into one plot ? 

Thank you for your inputs
