### ISSUE TITLE
Feature Request: Automatic Conversion of Bigs before Plotting

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#303]
If you give Plots Bigs (BigInt,BigFloat), it throws errors. It would be nice if you could compute with Bigs and then have it automatically convert right before plotting. It shouldn't hurt too much to add a conversion, right?

**Comment by tbreloff** [comment]
I just plotted a BigFloat array successfully... can you give more details on the error(s)?
