### ISSUE TITLE
Scatter plot hides annotation when applied on top of other plots (PyPlot backend)

### ISSUE THREAD

**Issue by leethargo** [tbreloff/Plots.jl#304]
I have an issue concerning the layers of annotation text and markers. It all works well until I place the `scatter!` on top of at least *two* other calls of `plot`/`plot!`. See my [gist notebook](https://gist.github.com/leethargo/65d4a48a97ae10562e1e6a3465bc85d2) for details.

**Comment by tbreloff** [comment]
Thanks for that gist... Very helpful. Might need to set zorder on the
annotations? I'll look today.

**Comment by leethargo** [comment]
You mean setting `zorder` in the `pyplot.jl` implementation, not in my user calls, right? I played with giving various values for the `zorder` command, but I don't see any effect.

For what it's worth, I tried the same notebook with the `GR` and `Gadfly` backends, both of which work fine, so it's really an issue related to `PyPlot`.

**Comment by tbreloff** [comment]
I mean a change to Plots to always show annotations above other plot items.  Also you should be aware that I'll be making a change on the dev branch, and Gadfly has been deprecated since the last release.

**Comment by tbreloff** [comment]
Fixed on dev branch... note that you should be using the `series_annotations` keyword now... `annotations` is for those not attached to series data, and it expects (x,y,text) tuples.

**Comment by leethargo** [comment]
Thanks, it works beautifully, now :smile:
