### ISSUE TITLE
Apply kw arguments to subplots

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#307]
In Plots 0.6.3, `subplots` keyword arguments are applied to all the subplots. But in the current (dev) `plot(..., layout=..., other_args)` the `other_args` aren't applied to all the subplots. So, if you need the same setting for each subplot, you need to apply `other_args` to every subplot inside `plot`. 

i.e. The following doesn't work setting the same `xlim` to all the subplots:
```julia
plot(
histogram(rand(100)),
histogram(rand(10)),
histogram(rand(25)),
layout=grid(1,3), xlim=(0,0.5)
)
```

**Comment by tbreloff** [comment]
This seems to be working now:

![tmp](https://cloud.githubusercontent.com/assets/933338/15953937/d2a9403e-2e9e-11e6-9a5b-ab93812e4c36.png)

**Comment by diegozea** [comment]
That's great! Thanks Tom!
