### ISSUE TITLE
Add @recipe support for group and marker 

### ISSUE THREAD

**Issue by cstook** [tbreloff/Plots.jl#309]
add support for 'group' and 'marker' keys in @recipe macro

**Comment by tbreloff** [comment]
Group doesn't work from recipes yet, but all of the other Plots magic should work now.  I tested with these:

```julia
using Plots; gr()

# user recipe

type T end
@recipe function f(::T)
    line := (3,0.3,:red)
    marker := (20,0.5,:blue,:o)
    bg := :yellow
    rand(10)
end
plot(T())

# plot recipe

@recipe function f(::Type{Val{:hiplt}},plt::Plot)
    line := (3,0.3,:red)
    marker := (20,0.5,:blue,:o)
    t := :path
    bg:=:green
    ()
end
plot(rand(10),t=:hiplt)

# series recipe

@recipe function f(::Type{Val{:hi}},x,y,z)
    line := (3,0.3,:red)
    marker := (20,0.5,:blue,:o)
    t := :path
    ()
end
plot(rand(10),t=:hiplt)
```

For anyone following, it's important to remember that the `-->` operator won't work with aliases or magic args, since it would be checking for the existence of those fields and they would never exist in a processed KW.

**Comment by tbreloff** [comment]
The above applies, but also I just realized that you can get `group` to work already by returning this from a user recipe (where `args` is the x/y data you would normally return):

```julia
(extractGroupArgs(groupby_vec, args...), args...)
```

**Comment by cstook** [comment]
Great!  I'll try to move my plot to a recipe now.
Thank you!

**Comment by Arcumenn** [comment]
> 
> 
> The above applies, but also I just realized that you can get `group` to work already by returning this from a user recipe (where `args` is the x/y data you would normally return):
> 
> ```julia
> (extractGroupArgs(groupby_vec, args...), args...)
> ```

Hey, I am just wondering if this is still the case?  I am getting a 'extractGroupArgs not defined' error. I'm struggling to find more information about this so any help would be appreciated. The code is looking like this:

```
# There is another recipe here, that initalizes the following struct

struct Autocor; c; indeces; maxlag; end
@recipe function f(autoc::Autocor)

  xguide --> "Lag"
  yguide --> "Autocorrelation"
  xlims --> (0, +Inf)
  layout --> length(autoc.indeces)

  nrows, nvars, nchains = size(autoc.c.value)
  lags = 0:autoc.maxlag
  ac = autocor(autoc.c, lags=collect(lags))

  # want to create multiple subplots with 2 groups each
  for (index, i) in enumerate(autoc.indeces)

    @series begin
      subplot := index
      seriestype := :line
      title --> autoc.c.names[i]

      x = repeat(collect(lags * step(autoc.c)), outer=[nchains])
      y = vec(ac.value[i,:,:])

      g = repeat(autoc.c.chains, inner=[length(lags)])
      (extractGroupArgs(g, x, y), x, y)
    end # series
  end # for
end # recipe
```
