### ISSUE TITLE
winston backend not recognized

### ISSUE THREAD

**Issue by my-little-repository** [tbreloff/Plots.jl#31]
I am using julia 0.4rc. I just downloaded Winston and Plots but it seems that Winston is not recognized.

     julia> using Plots
     INFO: Precompiling module Plots...
     [Plots.jl] Default backend: winston
     
     julia> plot(x->sin(x),0,1)
     [Plots.jl] Initializing backend: winston
     WARNING: requiring "Dates" did not define a corresponding module.
     WARNING: module Winston should explicitly import * from Base
     ERROR: Couldn't import Winston.  Install it with: Pkg.add("Winston")
      in plotter at /home/yves/.julia/v0.4/Plots/src/plotter.jl:103
      in plot at /home/yves/.julia/v0.4/Plots/src/plot.jl:46
     
     julia> Pkg.add("Winston")    # actually it is installed.
     INFO: Nothing to be done
     
     julia> plot(x->sin(x),0,1)
     [Plots.jl] Initializing backend: winston
     ERROR: Couldn't import Winston.  Install it with: Pkg.add("Winston")
      in plotter at /home/yves/.julia/v0.4/Plots/src/plotter.jl:103
      in plot at /home/yves/.julia/v0.4/Plots/src/plot.jl:46

**Comment by tbreloff** [comment]
I assume this is related to the issue you raised earlier: https://github.com/nolta/Winston.jl/issues/241

Can you show the output of `Pkg.status()`?

**Comment by tbreloff** [comment]
Also have you tried with any other backends?  Winston is probably the least supported of all of them.

**Comment by my-little-repository** [comment]
Here is the output of Pkg.status().    

 julia> Pkg.status()
    8 required packages:
     - Dates                         0.4.4
     - Elliptic                      0.2.0
     - ImageView                     0.1.17
     - Iterators                     0.1.9
     - Memoize                       0.0.0
     - Plots                         0.2.0
     - Polynomials                   0.0.4
     - Winston                       0.11.12
    19 additional packages:
     - BinDeps                       0.3.17
     - Cairo                         0.2.31
     - ColorTypes                    0.1.6
     - ColorVectorSpace              0.0.4
     - Colors                        0.5.4
     - Compat                        0.7.3
     - Docile                        0.5.19
     - FixedPointNumbers             0.0.11
     - Graphics                      0.1.3
     - HttpCommon                    0.2.4
     - Images                        0.4.48
     - IniFile                       0.2.4
     - Reexport                      0.0.3
     - SHA                           0.1.2
     - SIUnits                       0.0.5
     - TexExtensions                 0.0.2
     - Tk                            0.3.6
     - URIParser                     0.1.0
     - Zlib                          0.1.9

I will install gadfly in a minute.

**Comment by my-little-repository** [comment]
I just installed Gadfly and Plots+Gadfly work as expected.

**Comment by tbreloff** [comment]
I'm assuming that this was a Winston issue, not Plots, so I'm going to close.
