### ISSUE TITLE
Plot inside a plot

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#315]
Is It possible to plot a plot inside a plot? I.e. to zoom up a region: ![plot](http://i.stack.imgur.com/3iTGO.png)

That features is really useful given the publication's limited space.

**Comment by tbreloff** [comment]
I was just thinking about a nice solution to this. We could store a
Dict{Subplot, AbstractLayout} as a field in Plot, which maps a Subplot
object to a layout which is the "parent" (which may be plt.layout). After
the parent layout is positioned, bounding boxes are set relative to the
parent layout's bbox. That's pretty much it.

The question is... How do you specify that with the layout macro? Or do we
add another arg? Maybe a subplot is only part of the main layout if the
'bbox' arg is nothing. Then you could do:

bb = ... # a relative bbox
plot(rand(10,3), layout = (1,2), bbox = [nothing nothing (1, bb)])

which would create 3 subplots (not 2) and the last subplot would be
positioned inside subplot 1 with relative bbox 'bb'. Subplots 1 and 2 would
be side by side.

Maybe the layout macro could take an optional list of floating subplots
after the array to accomplish the same thing.

**Comment by tbreloff** [comment]
This turned out to be easier than expected!

```julia
using Plots
plot((100:-1:1).*rand(100,5), layout=2, inset_subplots = [
        (1, bbox(150px,150px,150px,80px)),
        (2, bbox(100px,30px,200px,100px)),
        (nothing, bbox(200px,250px,200px,150px))
    ], leg=false, title=["Subplot $i" for i=1:5]')
```

![tmp](https://cloud.githubusercontent.com/assets/933338/16015147/6732e03c-3162-11e6-8a9f-ca87317a97b4.png)

If you can't figure it out purely from the plot command, `inset_subplots` takes a list of `(parent_layout, BoundingBox)` tuples, where the bounding box is relative to the parent.  Here's the logic for choosing a parent:

```julia
                P = typeof(parent)
                if P <: Integer
                    parent = plt.subplots[parent]
                elseif P == Symbol
                    parent = plt.spmap[parent]
                else
                    parent = plt.layout
                end
```

Note: `plt.layout` is the root layout (i.e. the whole canvas)

I'm sure there's still some kinks to work out, and a slightly nicer API would be better.  Ideas welcome.

**Comment by tbreloff** [comment]
Just pushed up some improvements... it's pretty flexible and mostly done, though the API could use a little more convenience.

```julia
using Plots
plot(heatmap(randn(10,20)), boxplot(rand(1:4,1000),randn(1000)), leg=false)
histogram!(randn(1000), inset_subplots = [(1, bbox(0.05w,0.95h,0.5w,0.5h, v_anchor=:bottom))], subplot=3, ticks=nothing)
sticks!(randn(100),subplot=4,inset_subplots=[bbox(0.35w,0.5h,200px,200px,h_anchor=:center,v_anchor=:center)])
```

Use px/mm/inch for absolute coords, w/h for percentage relative to the parent.  Origin is top-left.  Anchor is the position where x/y are.

**Comment by diegozea** [comment]
I didn't try it yet, but looks awesome!
