### ISSUE TITLE
julia 0.5 meta-issue

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#317]
Anything pertaining to supporting julia 0.5 should go here

**Comment by ChrisRackauckas** [comment]
I can confirm that Plots.jl with PyPlot and GR is working on v0.5 (with Juno).

**Comment by tbreloff** [comment]
Thanks... that's great to hear... I'll leave this open for anything that pops up

**Comment by tbreloff** [comment]
I think we're good to go on 0.5
