### ISSUE TITLE
Provide a save() function that adapts to different formats and backends

### ISSUE THREAD

**Issue by waldyrious** [tbreloff/Plots.jl#32]
As suggested in https://github.com/Evizero/UnicodePlots.jl/issues/19#issuecomment-143033337:

> This seems to me to be much in line with the philosophy of Plots.jl, i.e. generic methods that adapt to the backend, or in this case, the output format -- so that you might have something like `save(plot, format="png")` rather than `savepng()`, `savetxt()`, `savesvg()`, and so on.

**Comment by lobingera** [comment]
just wording: I'd prefer 'save' to save the plot as data structure, 'saveas' or 'export' or 'savepicture' for operations that render the plot to a document/bitmap/picture

**Comment by waldyrious** [comment]
Good point. `export()` would be fine with me.

**Comment by tbreloff** [comment]
Well it can't be `export` since that would clash with the Julia keyword.  I sort of understand the hesitation with `save`, so lets keep brainstorming.

**Comment by waldyrious** [comment]
I guess then `saveas()` would be the second best option (of those in the table. I can't think of anything better).

**Comment by tbreloff** [comment]
Thinking about it a little, I think `save` would be appropriate, however it runs the risk of clashing with `JLD.save`.  

I'm thinking the generic method should be `Base.serialize`, and the specific methods could be simply `png`, `pdf`, `jld` (for dumping the Plot object), etc.

**Comment by waldyrious** [comment]
> I'm thinking the generic method should be `Base.serialize`, and the specific methods could be simply `png`, `pdf`, `jld` (for dumping the Plot object), etc.

That sounds intuitive enough, but for the text-based plotting packages (which UnicodePlots seems to be subsuming) there could only be a `txt` method, and that method would only work for it.\* Something more generic that adapts to the plotting backend automatically would sound more elegant IMHO.

\* Unless you want to automatically convert plots that happen to use the feature-set supported by UnicodePlots and save them as txt -- although I can't imagine such an approach to be useful in anything but esoteric use cases...

**Comment by tbreloff** [comment]
I think calling serialize on a UnicodePlots object can write a text file by
default.  Some sort of default format map is reasonable... most would be
png, unicodeplots would be txt.  Extensions could be added automatically if
needed.   So `serialize("tmp")` would expand to write the plot to a text
file: tmp.txt

**Comment by waldyrious** [comment]
Yes, exactly, but "serialize" isn't exactly a function name I'd call intuitive. That said, having a unified method apply to all plotting backends would already be an improvement :)

**Comment by tbreloff** [comment]
Intuitive? Not really.  But it's better than exporting a name like `save` which is not defined in Base, and will cause issues with JLD and likely other packages.  I suppose `savefig` is another viable option, which has precedence elsewhere.  However, of all of these, I think `serialize` is the most clear what it actually does.

**Comment by stillyslalom** [comment]
+1 for `savefig`. I don't think it's imperative that the user understand how their plot is exported, and `savefig` is widely used already (Pyplot & Winston). It would also be nice to dispatch on the extension of the filename string (as is done by Pyplot & Winston), which lets the function be called with a single argument and prevents users from needing to refer to docs to determine kwarg syntax.

**Comment by tbreloff** [comment]
This should work as expected now:

```
using Plots
plot(rand(10))
png("tmp")  # saves as "tmp.png"
png("tmp.png") # saves as "tmp.png"
savefig("tmp") # error... can't extract extension
savefig("tmp.png")  # saves as "tmp.png"
```

**Comment by waldyrious** [comment]
would it make sense for every backend to have a default export format? Then `savefig("tmp")` wouldn't need to error out :)

**Comment by tbreloff** [comment]
Sure, that sounds reasonable enough. Do you think png is an appropriate default (except unicodeplots)?

**Comment by waldyrious** [comment]
> Do you think png is an appropriate default (except unicodeplots)?

Yes, I was thinking that, since it's pretty much the most common/universally supported lossless image format.

And since we're at it, if one doesn't want to bother choosing a filename, perhaps plain `savefig()` could produce an autogenerated filename, e.g. using a simple counter or the timestamp or something like that.

**Comment by lobingera** [comment]
+1 for png
Datetime names are tricky, because you still can get conflicts in parallel processing of images. But Base.tempname and friends might be OK as default.

**Comment by tbreloff** [comment]
I'm also wondering if this will fit in directly with animations. I plan on copying my animation code from Qwt which creates a gif, and a no-arg savefig could replace saveframe.

**Comment by tbreloff** [comment]
Now that FileIO.jl is official, I'm considering adding the dependency and using `FileIO.save` instead of `savefig`

**Comment by tbreloff** [comment]
@timholy @simondanisch  Do you think it makes sense to add the FileIO dependency here?  I haven't looked in detail at it yet, and I want to keep the requirements for Plots minimal.
