### ISSUE TITLE
Limits miscalculate when using log scale on both x and y

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#326]
As noted in the title. For example, using
```
plot(1:10,randn(10),xlim=(0,1),ylim=(0,1),xscale=:log10,yscale=:log10)
```

plots from nan to nan in x and y, while

```
plot(1:10,randn(10),xlim=(.1,1),ylim=(0,1),xscale=:log10,yscale=:log10)
```

Has the wrong limits in the y-direction.

**Comment by tbreloff** [comment]
Did you test on other backends? Or just pyplot?

**Comment by ChrisRackauckas** [comment]
I don't know how to make GR interactive to see exactly what the limits are, but it looks like it was working.

**Comment by tbreloff** [comment]
I changed the `set_xscale` call in pyplot to "symlog", and it seems to work better:

```julia
using Plots
x=linspace(-20,20,100)
plot(x,5sin(x),xscale=:log,yscale=:log, xlim=(-40,40),ylim=(-15,15))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/15991846/efec18ca-308c-11e6-85d7-273f816ec9c1.png)

Note that you should be setting the xlim/ylim in "data values", not "axis values".

**Comment by ChrisRackauckas** [comment]
```
plot(1:10,randn(10),ylim=(1e-3,2),xlim=(1e-6,0),xscale=:log10,yscale=:log10)
```

seems to not plot in log scale on the x-axis.

**Comment by tbreloff** [comment]
you have xmin > xmax... is that intentional?  Also my note:

> Note that you should be setting the xlim/ylim in "data values", not "axis values".

**Comment by ChrisRackauckas** [comment]
Fixed it. 

And yes, the example numbers I am plotting are bogus. I couldn't think of a good quick example that would be log scale in the right range. What I am actually plotting are values like (1e-5,1e-2).

**Comment by tbreloff** [comment]
> But PyPlot's interactive mode shows you how (x,y) are working even if nothing is plotted (and the axis is there).

not sure I understand...

**Comment by ChrisRackauckas** [comment]
PyPlot shows you the coordinates if you scroll over it in interactive mode, so I was just using that to check , meaning what was plotting was junk.

Here's a better example:

```
x = [0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5
 0.1 0.001 1.0e-5]

 y = [0.0021889525436027376 0.35659222056036843 0.33043423415636075
 0.9424830166697743 0.32905983826140905 0.5323522526461286
 0.8980367811851713 0.5851023638036172 0.9635129791975338
 0.7278550436967215 0.14375418537617246 0.8459107591426573
 0.9670431398766127 0.7907573057219593 0.34414032615720413
 0.6851831828080047 0.03448850125109714 0.4306057245607575
 0.8832339365031505 0.3908331974409296 0.7855195627654862
 0.346619925562331 0.5508437404281108 0.3633284323877666
 0.6030495176100843 0.018824906566774772 0.6853074955933027
 0.2803237595686069 0.8964487234352004 0.4578707778935155
 0.056210163568205546 0.7781724521378236 0.6657412793944562
 0.1816911323216972 0.6390641172467422 0.09261827654114826
 0.7577025464048941 0.33521797297624656 0.20331210514402692
 0.838110340559287 0.5789549347257892 0.16674841876418517
 0.9665401643706932 0.5170995435895653 0.49337129932046475
 0.06338287181294758 0.6258656423821837 0.41386477825009715
 0.8692192809124482 0.9271926214973887 0.14136885856912995
 0.11213041210117214 0.208631379717469 0.3879281447602907
 0.34499315705909117 0.5630461272358747 0.43965106717698355
 0.7388423387781814 0.2748895648384325 0.7933466395173441]

 plot(x,y,xscale=:log10,yscale=:log10,linetype=:scatter,ylim=(1e-3,1.1),xlim=(1e-6,.11))
```

![example](https://cloud.githubusercontent.com/assets/1814174/15992110/07763a38-307a-11e6-9542-3a70654097a6.png)

**Comment by tbreloff** [comment]
@ChrisRackauckas This looks right to me (although it's kinda crappy that pyplot doesn't show a second tick label automatically). Do you see a problem?

**Comment by tbreloff** [comment]
No scratch that... I see what you're saying

**Comment by tbreloff** [comment]
Should be fixed... I compute the minimum absolute value of the series data in this subplot, and pass that to the "linthreshx/linthreshy" arg in pyplot's [set_xscale](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.xscale).  Let me know if this is better.

**Comment by ChrisRackauckas** [comment]
It seems to double all the axes (i.e., reflect it over 0).

![example](https://cloud.githubusercontent.com/assets/1814174/15992707/39118bc6-3087-11e6-94ee-8c6047805c08.png)

**Comment by tbreloff** [comment]
My gut feeling is that's a pyplot bug. I can't look into it anymore today
though.

**Comment by tbreloff** [comment]
Just realized what was going on... so I made a quick fix:

![tmp](https://cloud.githubusercontent.com/assets/933338/15994777/7979b18a-30db-11e6-8aea-d6b4912a048b.png)
