### ISSUE TITLE
ERROR: LoadError: ArgumentError: RecipesBase not found in path

### ISSUE THREAD

**Issue by qvdgeer** [tbreloff/Plots.jl#328]
using plots; 
using Gadfly # to plot out symbolic expression
using SymPy

was working before now I get:

INFO: Precompiling module plots...
ERROR: LoadError: ArgumentError: RecipesBase not found in path
 in compilecache at loading.jl:377
 in require at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/quentinvandegeer/.julia/v0.4/plots/src/plots.jl, in expression starting on line 11
LoadError: Failed to precompile plots to /Users/quentinvandegeer/.julia/lib/v0.4/plots.ji
while loading In[4], in expression starting on line 3

 in error at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
 in compilecache at loading.jl:384
 in require at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib

also when calling Pkg.update()

NFO: Updating METADATA...
INFO: Cloning cache of Plots from git://github.com/tbreloff/Plots.jl.git
INFO: Updating cache of SCS...
INFO: Updating cache of FixedSizeArrays...
INFO: Updating cache of StatsBase...
INFO: Updating cache of DataArrays...
INFO: Updating cache of PyPlot...
INFO: Updating SCS...
INFO: Updating Plots...
INFO: Updating OpenCV...
INFO: Updating Cxx...
INFO: Computing changes...
LoadError: unsatisfiable package requirements detected: no feasible version could be found for package: Compat
while loading In[6], in expression starting on line 1

**Comment by tbreloff** [comment]
I don't think this is a Plots issue.  One of your packages has a minimum
version requirement of Compat, another has a maximum, and they don't
overlap. What is Pkg.status()?

**Comment by tbreloff** [comment]
Could it be https://github.com/JuliaLang/METADATA.jl/pull/5357/files#diff-0?

**Comment by tbreloff** [comment]
cc: @simondanisch @tkelman

**Comment by tbreloff** [comment]
the commit: https://github.com/SimonDanisch/FixedSizeArrays.jl/commit/b8d3d5ec4044549d8cfe71a0f9f7ffad3acb7a2f  @simondanisch Why is this necessary?  Any suggestions for resolving?

**Comment by tkelman** [comment]
I don't think I've ever seen a maximum version on Compat. If there's only one version, it's a lower bound.

**Comment by tbreloff** [comment]
Maybe his compat is dirty then? Is there any other way that he'd get that
error?

**Comment by tkelman** [comment]
Would have to see `Pkg.status()`. No use guessing without any more information.

**Comment by qvdgeer** [comment]
Here is the Pkg.status()

11 required packages:
 - Cairo                         0.2.31
 - Convex                        0.2.0
 - GLPKMathProgInterface         0.2.1
 - Gadfly                        0.4.2
 - Homebrew                      0.2.0
 - IJulia                        1.1.9
 - NPZ                           0.1.0
 - PyCall                        1.4.0
 - PyPlot                        2.1.1
 - SCS                           0.2.4              master
 - SymPy                         0.2.40
53 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.21
 - Calculus                      0.1.14
 - Codecs                        0.1.5
 - ColorTypes                    0.2.2
 - Colors                        0.6.3
 - Compat                        0.7.18
 - Compose                       0.4.2
 - Conda                         0.1.9
 - Contour                       0.1.0
 - Cxx                           0.0.0-             master (unregistered)
 - DataArrays                    0.3.0
 - DataFrames                    0.7.0
 - DataStructures                0.4.4
 - Dates                         0.4.4
 - Distances                     0.3.0
 - Distributions                 0.8.10
 - Docile                        0.5.23
 - DualNumbers                   0.2.2
 - FixedPointNumbers             0.1.3
 - FixedSizeArrays               0.1.0
 - GLPK                          0.2.17
 - GZip                          0.2.18
 - Graphics                      0.1.3
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - Iterators                     0.1.9
 - JSON                          0.5.0
 - KernelDensity                 0.1.2
 - LaTeXStrings                  0.1.6
 - Loess                         0.0.6
 - MacroTools                    0.3.0
 - MathProgBase                  0.4.3
 - Measures                      0.0.2
 - NaNMath                       0.2.1
 - Nettle                        0.2.3
 - OpenCV                        0.0.0-             master (unregistered)
 - Optim                         0.4.5
 - PDMats                        0.4.1
 - Plots                         0.7.0+             master
 - PositiveFactorizations        0.0.1
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - SHA                           0.1.2
 - Showoff                       0.0.7
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.8.1
 - StatsFuns                     0.2.1
 - URIParser                     0.1.3
 - WoodburyMatrices              0.1.5
 - ZMQ                           0.3.1
 - ZipFile                       0.2.6
 - Zlib                          0.1.12

**Comment by tkelman** [comment]
The error message is wrong, not sure why. You have SCS checked out which now conflicts with some of your other packages that require MathProgBase 0.4.x. Run `Pkg.free("SCS")`.

**Comment by qvdgeer** [comment]
Thanks.  After a successful Pkg.free and Pkg.update I now get


INFO: Recompiling stale cache file /Users/quentinvandegeer/.julia/lib/v0.4/PDMats.ji for module PDMats.
WARNING: Module Compat uuid did not match cache file
WARNING: deserialization checks failed while attempting to load cache from /Users/quentinvandegeer/.julia/lib/v0.4/PDMats.ji
INFO: Precompiling module PDMats...
INFO: Recompiling stale cache file /Users/quentinvandegeer/.julia/lib/v0.4/PDMats.ji for module PDMats.
WARNING: Module Compat uuid did not match cache file
LoadError: __precompile__(true) but require failed to create a precompiled cache file
while loading In[7], in expression starting on line 3

Pkg.status as follows:

11 required packages:
 - Cairo                         0.2.31
 - Convex                        0.2.0
 - GLPKMathProgInterface         0.2.1
 - Gadfly                        0.4.2
 - Homebrew                      0.2.1
 - IJulia                        1.1.10
 - NPZ                           0.1.0
 - PyCall                        1.6.2
 - PyPlot                        2.2.0
 - SCS                           0.2.1
 - SymPy                         0.3.0
53 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.21
 - Calculus                      0.1.14
 - Codecs                        0.1.5
 - ColorTypes                    0.2.2
 - Colors                        0.6.4
 - Compat                        0.7.20
 - Compose                       0.4.2
 - Conda                         0.2.0
 - Contour                       0.1.0
 - Cxx                           0.0.0-             master (unregistered)
 - DataArrays                    0.3.3
 - DataFrames                    0.7.3
 - DataStructures                0.4.4
 - Dates                         0.4.4
 - Distances                     0.3.1
 - Distributions                 0.9.0
 - Docile                        0.5.23
 - DualNumbers                   0.2.2
 - FixedPointNumbers             0.1.3
 - FixedSizeArrays               0.2.0
 - GLPK                          0.2.17
 - GZip                          0.2.18
 - Graphics                      0.1.3
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - Iterators                     0.1.9
 - JSON                          0.5.1
 - KernelDensity                 0.1.2
 - LaTeXStrings                  0.1.6
 - Loess                         0.0.6
 - MacroTools                    0.3.0
 - MathProgBase                  0.4.3
 - Measures                      0.0.2
 - NaNMath                       0.2.1
 - Nettle                        0.2.3
 - OpenCV                        0.0.0-             master (unregistered)
 - Optim                         0.5.0
 - PDMats                        0.4.1
 - Plots                         0.7.0+             master
 - PositiveFactorizations        0.0.1
 - RecipesBase                   0.0.3
 - Reexport                      0.0.3
 - SHA                           0.1.2
 - Showoff                       0.0.7
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.8.2
 - StatsFuns                     0.2.2
 - URIParser                     0.1.3
 - WoodburyMatrices              0.1.5
 - ZMQ                           0.3.2
 - ZipFile                       0.2.6
 - Zlib                          0.1.12

**Comment by SimonDanisch** [comment]
Try restarting Julia ;) This sometimes happens when precompilation gets confused...

**Comment by ahwillia** [comment]
I'm seeing the same original error as @qvdgeer. It started by a simple `Pkg.update()`. I'm not sure if I've made things worse somehow by mucking around, but `Pkg.free("SCS")` and `Pkg.rm("SCS")` currently both fail with the same error:

```
ERROR: unsatisfiable package requirements detected: no feasible version could be found for package: MathProgBase
```

This is quickly turning into a mess I don't want to deal with. Is there a simple way to "reset" everything? I could just push all my code to github and then reinstall packages as needed...

FWIW here is `Pkg.status()` for the required packages:

46 required packages:
 - ArgParse                      0.3.0
 - Clustering                    0.5.0+             hclust_order
 - Compose                       0.4.2
 - ComposeDiff                   0.0.1
 - Convex                        0.3.0              master
 - Devectorize                   0.4.2
 - DistributedArrays             0.2.0
 - Distributions                 0.8.2              hdi
 - EmpiricalRisks                0.2.4+             alex (dirty)
 - Escher                        0.3.2+             master
 - Formatting                    0.1.5
 - ForwardDiff                   0.2.0+             master
 - GLM                           0.5.2
 - GLPK                          0.2.17
 - GaussianProcesses             0.1.4+             master
 - Graphs                        0.6.0
 - HiddenMarkovModels            0.0.2+             pkg-merge (dirty)
 - Homebrew                      0.2.0+             master
 - IJulia                        1.1.10
 - InplaceOps                    0.0.5
 - Interpolations                0.3.5
 - Iterators                     0.1.9
 - JLD                           0.6.1
 - JuMP                          0.13.1
 - Logging                       0.2.0
 - MAT                           0.2.14
 - MNIST                         0.0.2
 - Mamba                         0.6.0
 - MultivariateStats             0.2.2              master
 - ODE                           0.2.1+             master
 - ParallelAccelerator           0.1.7
 - Plotly                        0.1.0+             master
 - Plots                         0.7.2+             master
 - ProgressMeter                 0.3.2
 - PyPlot                        2.2.0              master
 - RDatasets                     0.1.3
 - Reactive                      0.3.3+             master
 - Requests                      0.3.7
 - ReverseDiffSource             0.2.3
 - Roots                         0.1.26
 - SCS                           0.2.1
 - SGDOptim                      0.2.2+             alex (dirty)
 - Stan                          0.3.2
 - TensorDecompositions          0.1.0+             staged (dirty)
 - UnicodePlots                  0.1.3
 - Vega                          0.6.7+             master

**Comment by tkelman** [comment]
Back up your local modifications, push branches to your forks for all of them and go back to release versions. Using master of a package should generally only be done by contributors or testers of those packages. If the tags are out of date wrt deprecations or bugs, best to open issues asking for new tags to be released.
