### ISSUE TITLE
yscale broken in gr

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#331]
```julia
gr()
plot(exp(-1:10);yscale=:log10)
```

**Comment by tbreloff** [comment]
What's broken about it?  I see:

![tmp](https://cloud.githubusercontent.com/assets/933338/16013897/2da4ef90-315d-11e6-8668-ea57d3959542.png)

Maybe checkout Plots master/dev and try again?  Or am I missing something?

**Comment by dlfivefifty** [comment]
it should be exponentially decreasing

**Comment by KristofferC** [comment]
No?

**Comment by dlfivefifty** [comment]
Whoops
