### ISSUE TITLE
Place xticks along top axis

### ISSUE THREAD

**Issue by mauro3** [tbreloff/Plots.jl#337]
Further, it would also be good to be able to place them both top&bottom. Similarly for yticks, zticks.

**Comment by tbreloff** [comment]
Thanks.  Brainstorming on interface... would it make sense to set:

```julia
plot(y, xlocation = :secondary)
```

`top`/`right` could be aliases for `secondary`, `bottom`/`left` could be aliases for `primary`.  Or `both` would be allowed. This would be a parameter for the `Axis` object, so I want it to be somewhat generic.

Please post alternative names, and I can set aliases.

Does anyone know how to do this in the backends?  cc @jheinen @spencerlyon2 @pkofod

**Comment by pkofod** [comment]
only ticks or also labels?

**Comment by mauro3** [comment]
@pkofod you're right.  I think it would be good to be able to control both independently.  Probably the ticks defaulting to both sides.  Maybe `xtickloc` and `xticklabelloc`?

**Comment by tbreloff** [comment]
This now works using the `mirror` attribute.  Master only.

```julia
using Plots; gr()
bar(rand(20), xmirror=true)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/17826777/2d5fd490-6642-11e6-8f56-67bdb5fc2ebb.png)

It doesn't support both top/bottom, left/right.  How important is that to you?  Only pyplot and gr support this right now.  Please reopen if you want to explore this deeper

**Comment by luiarthur** [comment]
Hi, is adding xticks / yticks on both left / right and top / bottom supported currently?

**Comment by daschw** [comment]
No, I don't think so.
