### ISSUE TITLE
Get x/ylims of plots (possibly not displayed yet)

### ISSUE THREAD

**Issue by mauro3** [tbreloff/Plots.jl#341]
For instance, how to make  a function which plots a vertical line as long as needed to fill the ylims.  This does not work:
```
function f()
       histogram(randn(1000), normalize=true)
       vline!([0], w=3)
end
```
as `vline!` only works after the plot has been displayed (and presumably, the y-limits fixed).

**Comment by tbreloff** [comment]
I think this is pyplot-specific... it works in GR.  The fix is probably to remove native support of histograms in pyplot, and use the Plots recipe.

**Comment by mauro3** [comment]
Yes, it works with `scatter`.

**Comment by tbreloff** [comment]
This works now.  pyplot no longer natively supports bar/histogram/histogram2d, but instead uses Plots recipes.
