### ISSUE TITLE
heatmap particularly slow with IJulia

### ISSUE THREAD

**Issue by jongwook** [tbreloff/Plots.jl#344]
I noticed that `heatmap()` with a moderately sized image makes IJulia spend too much time to show the image: [steps to reproduce](https://gist.github.com/jongwook/40f40dfc0d0c1833ada998d76d463f6c).

In the example above, the evaluation of `heatmap()` finishes quickly (8s including PyPlot initialization), but the browser takes almost 2 minutes to show the result, so I suspect there is something going wrong within the communicating between the IJulia kernel. I don't experience this with `PyPlot.imshow()` as shown in the same link above. 

I'm using:

```
 - Plots                         0.7.2
 - PyPlot                        2.2.0
 - PyCall                        1.6.2
```

with Julia 0.4.5 on `Linux mint 3.16.0-38-generic`. I had similar results with `Plotly` and `GR`.

**Comment by tbreloff** [comment]
Thanks... closing this in favor of #357
