### ISSUE TITLE
Unable to plot with plotlyjs

### ISSUE THREAD

**Issue by baggepinnen** [tbreloff/Plots.jl#345]
I can not seem to get plotlyjs to work. I submit the printouts from a typical run. Anyone seen this before? All packages are up to date and I'm running Fedora 23, further versioninfo in the bottom of the post.

Thanks in advance for any tip that might guide me in the right direction!

(I have run `Blink.AtomShell.install()`)
```julia
              _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-redhat-linux

julia> plot(randn(10))
[Plots.jl] Initializing backend: plotlyjs
ERROR (unhandled task failure): ArgumentError: Array dimension must be 0 ≤ dim ≤ 9223372036854775807, got 18446744073709551615 for dimension 1
 in pointer_to_array at pointer.jl:41
 in on_body at /local/home/fredrikb/.julia/v0.4/HttpServer/src/RequestParser.jl:86
```
At this point the execution hanged and I pressed ctrl-c and got the following
```
^CError showing value of type Plots.MethodError: Plot`getindex` has no method matching getindex({::VoidPlots, .::ASCIIStringPlotlyJSBackend)}
: in 
handle_messageERROR: InterruptException: at 
/local/home/fredrikb/.julia/v0.4/Blink/src/rpc/callbacks.jl
julia> 7
julia>  [inlined code] from /local/home/fredrikb/.julia/v0.4/Lazy/src/macros.jl:265
 in anonymous at task.jl:63
julia> 

julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d* (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tbreloff** [comment]
Oh no. Fedora. Run for your life!

I used to use Centos 7, and I spent a month trying to work through issues
with HttpServer/HttpParser. There's something unsupported, system library
clashes maybe, which seem to make RH systems break HttpServer.

Sadly the only advice I can offer is to make your choice now... Fedora or
PlotlyJS?  I chose PlotlyJS, and I'm now perfectly happy with Ubuntu.

**Comment by baggepinnen** [comment]
Haha, that's too bad. I run plotlyjs perfectly at home under ubuntu, my computer at work however runs Fedora and there is not much I can do about it, so I guess PyPlot it is.. 
Thanks for the tip though, now I at least know that there is no point in me trying to figure it out.
