### ISSUE TITLE
rendered gifs failing to run in iJulia

### ISSUE THREAD

**Issue by ianshmean** [tbreloff/Plots.jl#346]
The following example renders the gif successfully, but the gif isn't running when displayed in iJulia

```
using Plots
pyplot(reuse=true)

@gif for i in linspace(0,2π,100)
    X = Y = linspace(-5,5,40)
    surface(X, Y, (x,y) -> sin(x+10sin(i))+cos(y))
end
```

juliabox/juliabox:41 
Julia Version 0.4.5 - Commit 2ac304d (2016-03-18 00:58 UTC)
 - Plots                         0.7.2
 - PyPlot                        2.2.0

This also exhibits the same behaviour:

```
anim = @animate for i in linspace(0,2π,100)
    X = Y = linspace(-5,5,40)
    surface(X, Y, (x,y) -> sin(x+10sin(i))+cos(y))
end

gif(anim, "/tmp/anim_fps15.gif", fps = 15)
```

**Comment by ianshmean** [comment]
It seems to be a file location issue with my setup. It works if I change the save path to a directory (that exists) in my juliabox session:

`gif(anim, "/home/juser/tmp/anim_fps15.gif", fps = 30)`

**Comment by ianshmean** [comment]
Given the example returns two visuals (one from the last rendered surface plot, and one from the gif) I assumed that the first was supposed to be animated. I didn't notice the broken link to the gif!

**Comment by tbreloff** [comment]
I'm looking at this... I think you're right that it's a problem of file access.  I used to dump a "tmp.gif" file to `pwd`, but I changed it to dump to a temp file location recently.  I think maybe IJulia needs the file to be in a location accessable below the directory where you started your IJulia session?
