### ISSUE TITLE
Color attributes on shapes

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#347]
I've been thinking that it makes more sense that the `:shape` seriestype  should use the attributes `linecolor` and `fillcolor` instead of the current behavior of using `markercolor` and `markerstrokecolor`.

I recently changed the `bar` recipe to output shapes instead of filled-paths, primarily because it was easier to support horizontal bars generically.  I think this is a good example where a shape is closer to a "line with fill" than a "marker".

If anyone has strong objections to this proposal, please let me know.

**Comment by ChrisRackauckas** [comment]
That makes sense to me.

**Comment by jverzani** [comment]
+1. I was just working on this and couldn't figure out why `fillcolor`  wasn't working as I expected!

**Comment by tbreloff** [comment]
I just pushed this to dev, along with new boxplots.  Please... if you find examples in notebooks or in the docs that still set marker/markerstroke attributes for the `shape` seriestype, please let me know so I can update to `line`/`fill`.
