### ISSUE TITLE
Ticks (for PlotUtils.jl)

### ISSUE THREAD

**Issue by timholy** [tbreloff/Plots.jl#351]
Gadfly's implementation of the tickmarking algorithm is in https://github.com/dcjones/Gadfly.jl/blob/master/src/ticks.jl

The paper I mentioned with a (seemingly) newer algorithm is http://vis.stanford.edu/files/2010-TickLabels-InfoVis.pdf. I'd suggest we start simple with what works now, and follow up on alternatives on an as-needed basis.

**Comment by tbreloff** [comment]
Thanks for the help and the link @timholy!  It was great to talk and work with you this week.

For reference: https://github.com/JuliaPlots/PlotUtils.jl/issues/1

**Comment by timholy** [comment]
I saw you'd beat me to it!

Great seeing you, looking forward to many more interactions. (And lots of fun using Plots!)
