### ISSUE TITLE
No check for gridlines

### ISSUE THREAD

**Issue by mfalt** [tbreloff/Plots.jl#353]
There doesn't seem to be a check to make sure that the scope adjusts so that gridlines are shown anymore, for example, using PyPlot (on your dev branch)
```julia
plot()
plot!(rand(10)+2, yscale=:log10)
```
will show no scale on the y-axis (in view). I am not sure if this is regarded a bug, but it is different than before.

**Comment by tbreloff** [comment]
I don't think it's a bug, but I agree it's not optimal. Do other backends
have the same behavior?

**Comment by tbreloff** [comment]
This should be better on master... I'm now generating ticks and labels inside Plots:


![tmp](https://cloud.githubusercontent.com/assets/933338/16955542/fc733136-4da2-11e6-98cd-2f8443c734b7.png)
