### ISSUE TITLE
No GUI window popping up from Jupyter notebook

### ISSUE THREAD

**Issue by abieler** [tbreloff/Plots.jl#355]
I only get the inline plots when using from Jupyter notebook.
Example:
```julia
using Plots
pyplot()
N = 10
x = collect(1:N)
y = rand(N)
plot(x,y, show=true)
```

Julia 0.4.6 on latest Ubuntu 64 bit and on Plots master.

**Comment by tbreloff** [comment]
This was a bug... thanks.  Fixed on dev (99fe4f6)
