### ISSUE TITLE
dates on x-axis

### ISSUE THREAD

**Issue by abieler** [tbreloff/Plots.jl#356]
It looks like too many x-ticks are created (one for every date?)
Once the graph is generated the x labels are overlapping.
It also takes a very long time to plot some ~10k dates, probably as a result of the many xticks.

Julia 0.4.6 on Ubuntu and Plots master

**Comment by odow** [comment]
I'm probably missing something here, but I can't get dates to work on the x-axis.

On the latest master
```
using Plots
plotlyjs()
plot([Date(2016,1,1), Date(2016,2,1)], [1,2])
```

![untitled](https://cloud.githubusercontent.com/assets/8177701/16403578/cb1ed058-3d4a-11e6-8c7c-cb21448b922d.png)

What am I missing?

**Comment by tbreloff** [comment]
Including [this fix](https://github.com/spencerlyon2/PlotlyJS.jl/pull/58) and latest dev:

![tmp](https://cloud.githubusercontent.com/assets/933338/16634017/f74cdbf2-4399-11e6-9e5c-8fb26c41e33e.png)

**Comment by odow** [comment]
Thanks @tbreloff! I'm moving all my plotting to Plots and it's great!

**Comment by tbreloff** [comment]
@odow :+1: Keep posting issues when you find them
