### ISSUE TITLE
LaTeX formulas don't render or have nasty text around them

### ISSUE THREAD

**Issue by kshyatt** [tbreloff/Plots.jl#359]
```julia
julia> using Plots;
julia> pyplot()
julia> x = linspace(0.,pi,200);
julia> plot(x,sin(x), label=r"$\sin$")
```
![sin](https://cloud.githubusercontent.com/assets/828643/16395810/b3e8ff74-3c89-11e6-9aef-8436113d2155.png)

If you do something similar in PyPlot, the weird wrapper text isn't there.
I'm pretty sure this doesn't work with other backends.

**Comment by tbreloff** [comment]
You need the L_str macro:

```julia
using Plots, LaTeXStrings; plot(sin,0,10,lab=L"$\sin$")
```

Using a Regex gives the same behavior in both Plots and PyPlot.  PyPlot exports the L_str macro automatically.

**Comment by kshyatt** [comment]
Yay! Thanks a lot.

**Comment by tbreloff** [comment]
Also... I just tested the exact same command with the pgfplots backend and it works.  cc: @pkofod
