### ISSUE TITLE
Contour plots

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#36]
Can maybe depend on https://github.com/tlycken/Contour.jl

**Comment by tbreloff** [comment]
Contour doesn't have exactly [what I want](https://github.com/tlycken/Contour.jl/issues/26), so I'll do it myself, and maybe submit a PR at some point.  I'm sure I'm not the first person to come up with an algorithm like this, but here's the back-of-the-napkin idea that I'm thinking through:

- Bucket (x,y,z) vertices into (x,y) squares
- Pick a "center vertex" (x,y,z) in each square
- Estimate the z-value of each corner given nearby points
- Create 4 triangles from the square corners and center vertex
- Each triangle will cross the "contour surface", or not.  If it crosses, the contour line will pass through exactly 2 edges (or vertex if it lies exactly on the surface).  Interpolate/store the intersection vertex for each edge.
- Now, starting at the borders, loop through edges looking for an intersection point.  When found, add to contour line, then search adjacent edges for intersection.  Stop at border or if we come to an intersection we've already added.
- Repeat this search until all edges have been visited

Repeat this process for each contour level needed.

I'll likely need to create some types representing vertices, edges, squares, triangles, contours, etc.

Some open questions:

- How to pick centers/squares
- How to set corner z-values for sparse data

**Comment by tbreloff** [comment]
Looking at using [Delaunay triangulation](https://en.wikipedia.org/wiki/Delaunay_triangulation) which is implemented in https://github.com/JuliaGeometry/VoronoiDelaunay.jl, which would replace the need for the grid and triangle creation steps, as well as reducing the effort to estimate z-values.

I think it's probably a good idea to smooth the z-values somehow... this could be parameterized.

**Comment by tbreloff** [comment]
Basics are done.  For now, I'm just allowing the inputs and passing through to a backend function.  (Geom.contour in Gadfly/Immerse, contour/contourf in PyPlot). I currently accept a function mapping (x,y) to a z-value, and z-matrices (similar to Gadfly's interface).  In the future I'll expand the allowed inputs to arbitrary points in 3D space, so I'll leave this open until I have more native support for estimating surfaces and contours and generically plotting them.  Here's some examples:

Gadfly/Immerse:

![tmp](https://cloud.githubusercontent.com/assets/933338/10743723/5d5f1952-7c0b-11e5-8458-ae7242de083d.png)

PyPlot:

![tmp](https://cloud.githubusercontent.com/assets/933338/10743783/b8f6623e-7c0b-11e5-8acb-a3dc5499b296.png)

**Comment by Evizero** [comment]
I think there is a bug with the Gadfly backend. I get different results for pyplot and gadfly, where I know for a fact that the minimum in the gadfly plot is wrong

```Julia
gadfly()
p_cost = plot(-4:.1:4, -4:.1:4, (θ1, θ2) -> cost(X, [θ1, θ2], y), nlevels = 100)
```

![gadfly](https://cloud.githubusercontent.com/assets/10854026/11318148/422fd2ee-9046-11e5-807a-a4ba21f753bd.png)

```Julia
pyplot()
p_cost = plot(-4:.1:4, -4:.1:4, (θ1, θ2) -> cost(X, [θ1, θ2], y), nlevels = 100)
```

![pyplot](https://cloud.githubusercontent.com/assets/10854026/11318149/52b6cb9a-9046-11e5-950b-82189b5058ae.png)

**Comment by Evizero** [comment]
actually there is a lot more going on. Both are wrong sometimes. Look at these gadfly plots that have the same minimum but are plotted with different ranges. I am not sure what's going on.

![gadfly1](https://cloud.githubusercontent.com/assets/10854026/11318182/83aa863c-9047-11e5-83bb-cd8ba52ff997.png)

![gadfly2](https://cloud.githubusercontent.com/assets/10854026/11318184/8646cb4e-9047-11e5-8faf-51bf86cc557e.png)

**Comment by tbreloff** [comment]
Can you post a full example so I can run it? (Or make a gist) does this happen if you do contours directly through pyplot/gadfly?

**Comment by Evizero** [comment]
Sure, I'll look into it

**Comment by Evizero** [comment]
Ah, I confused this issue with the closed one. So sorry that I opened a new one for this. see #80

**Comment by tbreloff** [comment]
Similar in spirit to what I wanted to do with this issue... I added support of pyplot's tri-surface to be able to plot a surface given only x/y/z as vectors (i.e. no need to build the full grid of values... way more memory-friendly for many problems):

![tmp](https://cloud.githubusercontent.com/assets/933338/14829457/7a2d5074-0bb9-11e6-9d24-e549f3eb1e81.png)
