### ISSUE TITLE
Documentation on recipes fragmented

### ISSUE THREAD

**Issue by baggepinnen** [tbreloff/Plots.jl#360]
I would like to share some of my experiences related to the documentation when trying to implement support for the new recipes methodology.
 
I'm trying to implement recipes for a few of my packages and data types and have found it quite hard to find the information I need to succeed. I find myself having several tabs open, all of which have a subset of the information I need
- http://plots.readthedocs.io/en/latest/recipes/
- https://github.com/JuliaPlots/RecipesBase.jl
- https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/usertype_recipes.ipynb

Finding the right information is made extra difficult since readthedocs is not searchable ("No results found. Bummer." for all queries.). I would appreciate a small section that would in a few (simple) words summarize how to
- Create a custom plot for arbitrary data
- Create a custom plot for a certain type
- When new function names are introduced (like `hitsogram2d`) and when the function is reached through the `plot` function

It has also taken me quite some time trying to figure out the macros `@userplot, @shorthands`, I'm sure the information is in the documentation, but I find it very hard to decode and when I get error messages, I find it hard to figure out what I am doing wrong, e.g.
```
julia> @recipe function f(::Type{Val{:trajplot}})
           title --> "Trajectory"
           @series squeeze(d[:x][1:3,4,:],2)'
       end
apply_recipe (generic function with 68 methods)

julia> trajplot(randn(4,4,100))
ERROR: In convertToAnyVector, could not handle the argument types: (Array{Float64,3},)
 [inlined code] from /local/home/fredrikb/.julia/v0.4/Plots/src/series_new.jl:87
 in __apply_recipe#75__ at /local/home/fredrikb/.julia/v0.4/RecipesBase/src/RecipesBase.jl:235
 in _plot! at /local/home/fredrikb/.julia/v0.4/Plots/src/plot.jl:312
 in trajplot at /local/home/fredrikb/.julia/v0.4/Plots/src/Plots.jl:160
```

I hope this can help make the documentation clearer and once I have gotten the hang of it, I'm convinced it will make maintaining packages with plotting support easier.

**Comment by tbreloff** [comment]
Thanks for the comments!  If you have time to help with docs, I'd love to
review PRs from someone that just learned. Everything is in PlotDocs.jl.

The no-search is known... Hoping that a new mkdocs theme will solve that.

**Comment by tbreloff** [comment]
I just switched the documentation, and updated the recipes page.  Please let me know what you think of the new docs: https://juliaplots.github.io/recipes/
