### ISSUE TITLE
bar doesn't  work with categorical x 

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#365]
I found this error working with strings as x:

![image](https://files.gitter.im/tbreloff/Plots.jl/ejko/blob)

**Comment by tbreloff** [comment]
![tmp](https://cloud.githubusercontent.com/assets/933338/16633078/6eb40a08-4395-11e6-83a8-d8eb607c863f.png)

**Comment by diegozea** [comment]
Thanks Tom! :)
