### ISSUE TITLE
yerror has wrong width

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#367]
It doesn't use the real values:
![image](https://files.gitter.im/tbreloff/Plots.jl/YouM/blob)

**Comment by tbreloff** [comment]
I think this is working as intended.  This is the description from the docs:  "y (vertical) error relative to y-value. If 2-tuple of vectors, the first vector corresponds to the bottom error (and the second to the top)"

The important part is "relative to y-value".  So if you pass `yerror = (e1, e2)`, then the bottom tick is `y-e1` and the top tick is `y+e2`.

**Comment by diegozea** [comment]
Ok, that's fine, It's my bad.
