### ISSUE TITLE
Adjusting margin with plotly

### ISSUE THREAD

**Issue by jverzani** [tbreloff/Plots.jl#370]
Is there some way to expose this adjustment:

https://github.com/tbreloff/Plots.jl/blob/master/src/backends/plotly.jl#L218-Lundefined

I find when I embed these plots into an HTML page, the axes get chopped off. A setting of 

```
KW(:l=>20, :b=>20, :r=>20, :t=>20)
```

is what I need, but I don't see how to get that without hardcoding the values.

(In case it matters, I'm writing to an HTML page through `write(buf,  Plots.html_body(result))` to avoid calling `html_head(plt)` which interferes with Mathjax.)

**Comment by tbreloff** [comment]
This is possible, but I suspect the better solution is to change the subplot margins.  Attributes: `margin`, `left_margin`, ...

**Comment by jverzani** [comment]
Okay, I see my problem lies elsewhere. I'm trying to write out a plot to be included in a web page. If I just use

```
p = plot([1,2,3],[2,3,1], left_margin=20mm)
Plots.html_body(p)
```

The `domain` values don't get changed. However, when I run through the display into a webpage they do. Doesn't the webpage display just call `standalone_html` which in turn just calls `html_body`? I'm missing some of display pipeline I fear. Any insight would be most appreciated.

**Comment by tbreloff** [comment]
which backend?  `plotly()` or `plotlyjs()`?

**Comment by jverzani** [comment]
plotly()

On Friday, July 1, 2016, Tom Breloff <notifications@github.com> wrote:

> which backend? plotly() or plotlyjs()?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tbreloff/Plots.jl/issues/370#issuecomment-229973553>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAZvTEl1BLlytNLXKYBi5yvlxFZUhmS0ks5qRS9MgaJpZM4JDMVl>
> .
>


-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by tbreloff** [comment]
You're missing `Plots.html_head(p)`, which includes the plotly javascript.  I'm surprised it runs at all!

**Comment by jverzani** [comment]
No, I have to load that earlier -- before mathjax, not after, as otherwise LaTeX doesn't render --so the plotly javascript inclusion is part of the header in my template. The issue is the `domain` isn't calculated the same by `plotly_domain` when I call `Plots.html_body(p)` but it is when `p` is displayed at the console. (It will be `"domain":[0.0,0.0]` on one hand and `[0.19685039370078738,0.9671916010498688]` when rendered properly.) Worst case I can just branch and hardcode values temporarily, but if you have any thoughts as to other things to try I'd be happy to give it a go.

**Comment by tbreloff** [comment]
Oh I see... ok.  Yeah this is really weird.  I'm going to have trouble helping unless I can see your full code/workflow.

**Comment by jverzani** [comment]
Sorry it is so weird. The issue is that this just making a plot and then calling `Plots.html_body(p)` doesn't compute the `plotarea` part, but that does get computed when `p` is displayed:

```
julia> p = plot([1,2,3], [2,3,1], left_margin=10mm);

julia> p.subplots[1].plotarea
BBox{l,t,r,b,w,h = 0.0mm,0.0mm, 0.0mm,0.0mm, 0.0mm,0.0mm}

julia> p   # display at console

julia> p.subplots[1].plotarea
BBox{l,t,r,b,w,h = 20.0mm,4.0mm, 147.4mm,94.6mm, 127.4mm,90.6mm}
```

Is there something I can call to compute the bounding box? It seems that `update_child_boxes` does this, but if I try to force that it gives a different set of values:

```
julia> p = plot([1,2,3], [2,3,1]);
julia> Plots.update_child_bboxes!(p.layout);
julia> p.subplots[1].plotarea
BBox{l,t,r,b,w,h = 20.0mm,5.0mm, -2.0mm,-10.0mm, -22.0mm,-15.0mm}
```

I'm guessing there is some lazy computation that isn't hit by the call to `html_body`. Anyways, unless something pops in mind, I'll just make a local hack. I doubt this is an issue others will encounter.

**Comment by tbreloff** [comment]
Oh! that's easy... just call `Plots.prepare_output(p)`

**Comment by tbreloff** [comment]
Sorry I didn't realize that's what was wrong immediately

**Comment by jverzani** [comment]
Awesome, that is it! Thanks so much.

On Fri, Jul 1, 2016 at 1:06 PM, Tom Breloff <notifications@github.com>
wrote:

> Oh! that's easy... just call Plots.prepare_output(p)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tbreloff/Plots.jl/issues/370#issuecomment-229998790>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAZvTEdf5st2da40adQYF8hw-MbVsGyKks5qRUkFgaJpZM4JDMVl>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jverzani** [comment]
Thanks for the help! Super appreciated.
