### ISSUE TITLE
`using Plots, GLVisualize` produces many warnings.

### ISSUE THREAD

**Issue by cstook** [tbreloff/Plots.jl#373]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using Plots, GLVisualize
WARNING: New definition
    ./(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:55
is ambiguous with:
    ./(AbstractArray, Union{DataArrays.DataArray, DataArrays.PooledDataArray}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:280.
To fix, define
    ./(Images.AbstractImageDirect, Union{DataArrays.DataArray, DataArrays.PooledDataArray})
before the new definition.
WARNING: New definition
    .-(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:40
is ambiguous with:
    .-(AbstractArray, Union{DataArrays.DataArray, DataArrays.PooledDataArray}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:280.
To fix, define
    .-(Images.AbstractImageDirect, Union{DataArrays.DataArray, DataArrays.PooledDataArray})
before the new definition.
WARNING: New definition
    .*(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:51
is ambiguous with:
    .*(AbstractArray, Union{DataArrays.DataArray, DataArrays.PooledDataArray}, AbstractArray...) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:290.
To fix, define
    .*(Images.AbstractImageDirect, Union{DataArrays.DataArray, DataArrays.PooledDataArray})
before the new definition.
WARNING: New definition
    .*(AbstractArray, Images.AbstractImageDirect) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:52
is ambiguous with:
    .*(Union{DataArrays.DataArray, DataArrays.PooledDataArray}, AbstractArray...) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:290.
To fix, define
    .*(Union{DataArrays.DataArray, DataArrays.PooledDataArray}, Images.AbstractImageDirect)
before the new definition.
WARNING: New definition
    -(AbstractArray, Images.AbstractImageDirect) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:37
is ambiguous with:
    -(DataArrays.DataArray, AbstractArray) at C:\Users\Chris\.julia\v0.4\DataArrays\src\operators.jl:276.
To fix, define
    -(DataArrays.DataArray, Images.AbstractImageDirect)
before the new definition.
WARNING: New definition
    -(AbstractArray, Images.AbstractImageDirect) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:37
is ambiguous with:
    -(DataArrays.AbstractDataArray, AbstractArray) at C:\Users\Chris\.julia\v0.4\DataArrays\src\operators.jl:300.
To fix, define
    -(DataArrays.AbstractDataArray, Images.AbstractImageDirect)
before the new definition.
WARNING: New definition
    +(AbstractArray, Images.AbstractImageDirect) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:20
is ambiguous with:
    +(DataArrays.DataArray, AbstractArray) at C:\Users\Chris\.julia\v0.4\DataArrays\src\operators.jl:276.
To fix, define
    +(DataArrays.DataArray, Images.AbstractImageDirect)
before the new definition.
WARNING: New definition
    +(AbstractArray, Images.AbstractImageDirect) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:20
is ambiguous with:
    +(DataArrays.AbstractDataArray, AbstractArray) at C:\Users\Chris\.julia\v0.4\DataArrays\src\operators.jl:300.
To fix, define
    +(DataArrays.AbstractDataArray, Images.AbstractImageDirect)
before the new definition.
WARNING: New definition
    .+(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:22
is ambiguous with:
    .+(AbstractArray, Union{DataArrays.DataArray, DataArrays.PooledDataArray}, AbstractArray...) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:292.
To fix, define
    .+(Images.AbstractImageDirect, Union{DataArrays.DataArray, DataArrays.PooledDataArray})
before the new definition.
WARNING: New definition
    .<(Images.AbstractImageDirect{Bool, N<:Any}, AbstractArray{Bool, N<:Any}) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:177
is ambiguous with:
    .<(AbstractArray{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:338.
To fix, define
    .<(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}})
before the new definition.
WARNING: New definition
    .<(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:178
is ambiguous with:
    .<(AbstractArray{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:338.
To fix, define
    .<(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}})
before the new definition.
WARNING: New definition
    .<(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:178
is ambiguous with:
    .<(AbstractArray, Union{DataArrays.DataArray, DataArrays.PooledDataArray}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:280.
To fix, define
    .<(Images.AbstractImageDirect, Union{DataArrays.DataArray, DataArrays.PooledDataArray})
before the new definition.
WARNING: New definition
    convert(Type{Array{#T<:ColorTypes.Colorant, N<:Any}}, AbstractArray{#S<:Any, #n<:Any}) at C:\Users\Chris\.julia\v0.4\Images\src\core.jl:400
is ambiguous with:
    convert(Type{Array{#S<:Any, N<:Any}}, DataArrays.DataArray{#T<:Any, #N<:Any}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\dataarray.jl:371.
To fix, define
    convert(Type{Array{#T<:ColorTypes.Colorant, N<:Any}}, DataArrays.DataArray{#T<:Any, #N<:Any})
before the new definition.
WARNING: New definition
    .>(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:179
is ambiguous with:
    .>(AbstractArray{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:338.
To fix, define
    .>(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}})
before the new definition.
WARNING: New definition
    .>(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:179
is ambiguous with:
    .>(AbstractArray, Union{DataArrays.DataArray, DataArrays.PooledDataArray}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:280.
To fix, define
    .>(Images.AbstractImageDirect, Union{DataArrays.DataArray, DataArrays.PooledDataArray})
before the new definition.
WARNING: New definition
    .==(Images.AbstractImageDirect{Bool, N<:Any}, AbstractArray{Bool, N<:Any}) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:181
is ambiguous with:
    .==(AbstractArray{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:338.
To fix, define
    .==(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}})
before the new definition.
WARNING: New definition
    .==(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:182
is ambiguous with:
    .==(AbstractArray{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:338.
To fix, define
    .==(Images.AbstractImageDirect{Bool, N<:Any}, Union{DataArrays.PooledDataArray{Bool, R<:Integer, N<:Any}, DataArrays.DataArray{Bool, N<:Any}})
before the new definition.
WARNING: New definition
    .==(Images.AbstractImageDirect, AbstractArray) at C:\Users\Chris\.julia\v0.4\Images\src\algorithms.jl:182
is ambiguous with:
    .==(AbstractArray, Union{DataArrays.DataArray, DataArrays.PooledDataArray}) at C:\Users\Chris\.julia\v0.4\DataArrays\src\broadcast.jl:280.
To fix, define
    .==(Images.AbstractImageDirect, Union{DataArrays.DataArray, DataArrays.PooledDataArray})
before the new definition.

julia>

**Comment by tbreloff** [comment]
Oh... This is a well known clash between Images.jl and DataArrays.jl...
Nothing to do with Plots or GLVisualize. Just deal with he warnings, or I
think there's a way to turn them off ('julia --depwarn=no' or something
like that)

**Comment by cstook** [comment]
Thanks!  Sorry for the noise.

**Comment by timholy** [comment]
And fixed in julia-0.5.

**Comment by tbreloff** [comment]
Seriously Tim? That's awesome!! Finally the killer 0.5 feature we've all
been waiting for!! ;)

**Comment by timholy** [comment]
https://github.com/JuliaLang/julia/pull/16125
