### ISSUE TITLE
multi-panel plots

### ISSUE THREAD

**Issue by mkborregaard** [tbreloff/Plots.jl#376]
Is it possible to do multipanel plots, eg plots where the y and/or x axes are merged among subplots? An example here: http://www.originlab.com/www/products/images/StackedPanel_Propulsion.png

I would think it might be possible with a layout/recipe, suppressing plotting of some axes, removing the margins between subplots and aligning the scales?

**Comment by tbreloff** [comment]
You want the `link = :both` attribute, which will "link axes" for x/y axes in the same column/row of a subplot grid.  Here's an example: https://github.com/JuliaPlots/PlotRecipes.jl/blob/master/src/hists.jl#L16.

**Comment by mkborregaard** [comment]
Hi, thanks for the swift response. I have played with it for the last hour or so (and RTFM'ed more than once), and unfortunately still cannot figure out how to do it. I am stuck here:
```
@userplot ToPlot
toplot! (generic function with 1 method)

julia> @recipe function f(h::ToPlot)
       link := :both
       legend := false
       layout := @layout [a b]
       end
apply_recipe (generic function with 66 methods)

julia> toplot(1:5, [1:5 1:5])
ERROR: In convertToAnyVector, could not handle the argument types: (Plots.GridLayout,)
 in error at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from /Users/michael/.julia/v0.4/Plots/src/series_new.jl:87
 in apply_recipe at /Users/michael/.julia/v0.4/RecipesBase/src/RecipesBase.jl:238
 in _plot! at /Users/michael/.julia/v0.4/Plots/src/plot.jl:313
 in toplot at /Users/michael/.julia/v0.4/Plots/src/recipes.jl:42
```

I am sorry if this is not the right place to ask recipe-related questions.
Also, would the :link attribute remove the margin between subplots?

**Comment by tbreloff** [comment]
You should return the arguments to the plot function, which, when you're using the `@userplot` macro are in the new type:

```julia
julia> @userplot ToPlot
toplot! (generic function with 1 method)

julia> @recipe function f(h::ToPlot)
              link := :both
              legend --> false
              layout := 2
              h.args
       end
apply_recipe (generic function with 66 methods)

julia> toplot(1:5, [1:5 1:5])
```

You should look at the `ticks` and `margin` attributes as well: https://juliaplots.github.io/attributes/

**Comment by mkborregaard** [comment]
Ohh, thanks. With that I can get pretty far:
```
@recipe function f(h::ToPlot)
                            link := :both
                            legend --> false
                            layout := 2 
                            margin --> 0mm
                            yticks --> [:auto nothing]
                            h.args
                     end

toplot(1:5, [1:5 2*(1:5)])
```

I cannot make the subplots merge completely, though, not even by setting margin to a negative value.
It doesn't work in the plotlyjs backend, btw.

**Comment by tbreloff** [comment]
Great the margin is on my radar. It's a different (and more complex) issue.
You should be able to get it tight with pyplot for now.

**Comment by mkborregaard** [comment]
Thanks, I believe it is complex. Just to be specific, the margins work in neither plotlyjs, pyplot or gr backends. It is the `link` attribute that does not work in plotlyjs, but that works in the two other backends.
