### ISSUE TITLE
top line missing in `histogram` with `gr()` backend

### ISSUE THREAD

**Issue by panlanfeng** [tbreloff/Plots.jl#377]
In the following example, the top box boarder of all the bars are missing. 
~~~~ julia
#Pkg.checkout("Plots")
using Plots
N=1000
gr()
x=randn(N);
Plots.histogram(x, normalize=true, fillcolor=:grey,linecolor=:red,
fillalpha=0.2, legend=:none, orientation=:v)
~~~~

See plot 
![Imgur](http://i.imgur.com/JX9K5PJ.png)

And by the way, setting `orientation=:h` seems not working.

**Comment by panlanfeng** [comment]
The issue is due to [this line](https://github.com/tbreloff/Plots.jl/blob/master/src/backends/gr.jl#L153)

The `polyline` in `GR` will leave the edge between the start point and the end point open. Could probably be fixed if add one a line 
~~~ julia
func(x[[iend, istart]], y[[iend, istart]])
~~~
But this will fail plots with other shapes. 
Seems it is necessary to add a separate function for `histogram` instead of using `gr_polyline`.

Best,
Lanfeng

**Comment by tbreloff** [comment]
This was fixed before you posted this issue, but I haven't pushed it up yet.  Sorry for wasting your time.

**Comment by panlanfeng** [comment]
Good to hear it was already fixed.

**Comment by tbreloff** [comment]
![tmp](https://cloud.githubusercontent.com/assets/933338/16632839/26528f56-4394-11e6-9e3f-643f32326f52.png)
