### ISSUE TITLE
Conversion Issue

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#379]
Plots.jl is having issues with converting arbitrary type Any arrays of Matrices (which should be vectors) into something plottable. This wasn't an issue in previous versions (~2 weeks ago?), but this code throws an error on the latest release and on dev:

```julia
using Plots

x = Rational{Int64}[1//2048,1//1024,1//512,1//256,1//128,1//64,1//32,1//16]
y = Dict("path1"=>rand(100,8),"path2"=>rand(100,8),"path3"=>rand(100,8))

type testType
 x
 y
end

@recipe function f(tt::testType)
 vals = [mean(y,1) for y in values(tt.y)]'
 seriestype --> :path
 xguide  --> "Convergence Axis"
 label  --> [key for key in keys(tt.y)]'
 yguide  --> "Error"
 xscale --> :log10
 yscale --> :log10
 println(vals)
 println(typeof(vals))
 println(tt.x)
 println(typeof(tt.x))
 println(map(typeof,vals))
 tt.x, vals
end

tt = testType(x,y)
plot(tt)
gui()
```

It prints out

```
Any[
[0.5007541654959673
 0.47212986961233705
 0.48839082021222363
 0.49871896937140475
 0.4970484319637364
 0.5148843364895784
 0.5001334949226919
 0.455567232041333] [0.5202282809140185
 0.5165789857837251
 0.47585822983320136
 0.501648864059354
 0.4781814164552657
 0.4996520831000397
 0.4403669446503416
 0.4815016237393302] [0.5288202843802993
 0.5126985157649259
 0.49759862659630144
 0.47372249105393516
 0.48703238578020874
 0.4584599184289848
 0.4983141145467932
 0.46964655137791755]]
Array{Any,2}
Rational{Int64}[1//2048,1//1024,1//512,1//256,1//128,1//64,1//32,1//16]
Array{Rational{Int64},1}
[Array{Float64,2} Array{Float64,2} Array{Float64,2}]
```

with the error message snipped from Juno:

![error](https://cloud.githubusercontent.com/assets/1814174/16631993/d7e7bee4-4376-11e6-831d-a3c46b0004de.PNG)

What's rather peculiar is that if you just take the output and plot it:

```
y= Any[
[0.5007541654959673
 0.47212986961233705
 0.48839082021222363
 0.49871896937140475
 0.4970484319637364
 0.5148843364895784
 0.5001334949226919
 0.455567232041333] [0.5202282809140185
 0.5165789857837251
 0.47585822983320136
 0.501648864059354
 0.4781814164552657
 0.4996520831000397
 0.4403669446503416
 0.4815016237393302] [0.5288202843802993
 0.5126985157649259
 0.49759862659630144
 0.47372249105393516
 0.48703238578020874
 0.4584599184289848
 0.4983141145467932
 0.46964655137791755]]
x = Rational{Int64}[1//2048,1//1024,1//512,1//256,1//128,1//64,1//32,1//16]
plot(x,y)
```

it works. In v0.5 it should automatically work because the issue is due to mean not dropping the extra dimension.

**Comment by tbreloff** [comment]
This works if you change to:

```
vals = Any[mean(y,1)' for y in values(tt.y)]
```

So you understand the difference, previously you had a "vector of row-vectors" (i.e. 1xn matrices), and you transposed the outside matrix, which made a "row-vector of column-vectors".  Matrices of matrices which are also poorly typed aren't handled well, however if it was a Vector{Any} instead of a Matrix{Any} then it works.  (I have special logic for Vector{Any}).   My change creates a "vector of column-vectors", which works, even with badly typed objects.
