### ISSUE TITLE
Plotly Backend Rational Handling

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#382]
If you run the command:

```
using Plots
N = 8
x = 0:1//N:1
y = rand(N)
plotly()
plot(x,y)
gui()
pyplot()
plot(x,y)
gui()
```

The PyPlot graph plots correctly while the Plotly graph is blank. It seems to be because x needs to be converted to floats.

**Comment by tbreloff** [comment]
So, this is fixed.  Except that I fixed it while in the middle of a massive overhaul to colors, which won't be merged for a bit.  I'll try to backport it sometime.
