### ISSUE TITLE
Different ColorGradient behaviour

### ISSUE THREAD

**Issue by axsk** [tbreloff/Plots.jl#384]
So far, using e.g. the `:blues` palette chooses the color for each series anew from the palette such that it remains maximally distuingishable to the previous color, resulting in "alternating colors" (see upper plot)

While such behaviour is desired for plotting categorical data, where the sequences ordering does not transport any structure, when using a sequential/gradient colormap I expect the ordering to be preserved (see lower plot).

![credits for the plots to tbreloff](https://files.gitter.im/tbreloff/Plots.jl/Hz8u/tmp.png)

To still allow for plotting categorical series see the proposal of "categorical palettes" #383

Edit: Concerning the API I would keep the `plot(..., palette=:inferno)` syntax, selecting `n` evenly distributed colors from the sequential/gradient palette for `n` given series.

**Comment by tbreloff** [comment]
closing in favor of #383
