### ISSUE TITLE
Box and violin plots in PlotlyJS

### ISSUE THREAD

**Issue by juanklopper** [tbreloff/Plots.jl#385]
Want to move away from Gadfly, so looking at Plots with PlotlyJS backend.  Looks great, except for box and violin plots.  From examples on juliaplots.github.io page I get this:
![box_violin_plotlyjs](https://cloud.githubusercontent.com/assets/8681335/16707079/29bcf9c4-45c4-11e6-89fe-ce3fc0783dfa.png)

Juan.

**Comment by mmagnuski** [comment]
I think its a castle - maybe you accidentally used `castleplot`? ;)

**Comment by tbreloff** [comment]
Don't worry I know about this. It turns out drawing polygons in Plotly is
tricky. :/

**Comment by juanklopper** [comment]
Well,  Plots is a brilliant package.  Hope you can fix this soon.  Box plots are bread and butter stuff in medicine.  It would be great to have the functionality for PlotlyJS.

Thanks!

**Comment by diegozea** [comment]
As a stop gap solution, you can use the pyplot() backend for boxplots. PyPlot backend is more mature than others at this moment.

**Comment by tbreloff** [comment]
@juanklopper I'd like to fix it soon, because I want to be able to draw graph nodes as polygons.  So you're in luck that our interests are aligned ;)

**Comment by tbreloff** [comment]
Good news:


<img width="616" alt="screen shot 2016-07-09 at 1 32 28 pm" src="https://cloud.githubusercontent.com/assets/933338/16709271/a8eb16ee-45d9-11e6-96d6-5fccb83bea2f.png">

**Comment by spencerlyon2** [comment]
Great work here @tbreloff!! Very exciting. Can you point me to a commit so I can see what it took?

**Comment by tbreloff** [comment]
https://github.com/tbreloff/Plots.jl/commit/5407fa73f8610f8dce5af701ca375be5eb233315

**Comment by juanklopper** [comment]
That is absolutely great @tbreloff .  I am introducing Julia at Groote Schuur Hospital (University of Cape Town).  It already plays a large part in my own unit.  Plots.jl is a great addition to the landscape.  Please keep going!

**Comment by juanklopper** [comment]
Thanks @diegozea .  I  do prefer the _interactive_ nature of Plotly, though.  Makes for great visualization during boring PPT presentations.
