### ISSUE TITLE
Precompile in Ubuntu

### ISSUE THREAD

**Issue by juanklopper** [tbreloff/Plots.jl#386]
I was using Plots in Juliabox.com and it worked well.  Tried it on a vanilla install of Ubuntu 16.04 and it would not precompile.  Realized I had to _apt-get install libz-dev_  

Hope this helps some other newbies to Plots.  

All is well (except of course for the PlotlyJS boxplots)!

**Comment by tbreloff** [comment]
Huh I haven't seen this issue... can you post your full error output?

**Comment by juanklopper** [comment]
Apologies for late reply.  I am a surgeon and was at the hospital.  Did quick reinstall of Mint 18 on old laptop.  Installed Julia.  Added Plots.  Took screenshot with my phone (was in a hurry).  Added below.  Did apt-get install libz-dev.  Worked well thereafter.  Perhaps it is not causal.  You would know much better.
![plots](https://cloud.githubusercontent.com/assets/8681335/16712345/eff50968-4684-11e6-8319-4b52e7755d38.JPG)

**Comment by tbreloff** [comment]
Thanks @juanklopper for the helpful output.  I opened an issue with GZip.jl: https://github.com/JuliaLang/GZip.jl/issues/54
