### ISSUE TITLE
Show large PyPlot's heatmaps on IJulia consumes a lot of RAM

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#388]
Maybe related to: https://github.com/tbreloff/Plots.jl/issues/157
The output of the *small* heatmap is `png`.

```julia
using Plots
pyplot(size=(200,200))
large = rand(9863, 417)
small = rand(  10,  10)
heatmap(small, html_output_format=:png)
heatmap(large, html_output_format=:png)
```

You can see the linear increment on RAM usage caused by the last line. I stopped the notebook before the computer swaps...

![image](https://cloud.githubusercontent.com/assets/2822757/16715844/28a61bfc-46c2-11e6-9bce-32c8ab7db5c3.png)

This works fine with GR.

**Comment by mauro3** [comment]
Yes, I see that too.  Note that calling the used pyplot `pcolormesh` is fast.

**Comment by mauro3** [comment]
Commenting out the lines https://github.com/tbreloff/Plots.jl/blob/23b25d495466d66ec7f167bb1c2328c0e4378765/src/backends/pyplot.jl#L742-L747 fixes most of the performance problems, in particular no RAM explosion.
```
julia> using Plots
julia> z = float((1:400) .* (1:1000)');
julia> heatmap(z) # about 4s after warm-up
```
vs
```
julia> using PyPlot
julia> z = float((1:400) .* (1:1000)');
julia> pcolormesh(z) # about 1s after warmup
```
Using ` z = float((1:4000) .* (1:1000)');` gives 30s vs 3s.  Thus for larger arrays the performance hit is still big but no death through swapping, as RAM usage is similar.

**Comment by tbreloff** [comment]
Thanks @mauro3 this is very helpful.  I've been wanting to get rid of that anyway... it's horrible.

**Comment by tbreloff** [comment]
How does this compare to calling pcolormesh directly through PyPlot.jl?

**Comment by mauro3** [comment]
That's the "vs"-part ;-)

**Comment by mauro3** [comment]
Also to compare, for the larger `z` using backends: gr ~3s, plotly ~6s, pyplot ~30s (and `PyPlot.pcolormesh` ~ 3s)

**Comment by tbreloff** [comment]
Oh! Ha that's pretty crappy.

**Comment by mauro3** [comment]
Hmm, also, pyplot-backend uses about 20s to get to the first display but then takes another 10s to scale it to the plot-window (or when re-sizing the window afterwards).  This suggests that pyplot has to handle much more data then when calling it with `PyPlot.pcolormesh(z)`.

**Comment by mauro3** [comment]
Ok, so also commenting line https://github.com/tbreloff/Plots.jl/blob/23b25d495466d66ec7f167bb1c2328c0e4378765/src/backends/pyplot.jl#L734 solves the rest of the performance problem: pyplot-backend is then ~4s vs ~3s of `PyPlot.pcolormesh(z)`.  Also, at first glance I cannot see a difference of the plot with that line commented, maybe it's not needed at all?

**Comment by tbreloff** [comment]
Seriously?? Really interesting.  If you add the edgecolors keyword to the
PyPlot call, does it also slow down? (Sorry I'm not in front of a computer)

**Comment by jgbos** [comment]
I just ran into this same issue, I commented out the lines @mauro3 suggested and everything seems to work efficiently now.

**Comment by tbreloff** [comment]
I see less than a second... I'll push up the fix soon.

**Comment by diegozea** [comment]
Thanks Mauro for tracking this :)
