### ISSUE TITLE
Axis scales

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#39]
Looking at Gadfly's list, should support: `:none`, `:log10`, `:log2`, `:log`, `:asinh`, `:sqrt`

This should probably be implemented similarly to `axes` or `linestyles`... there should be a `supportedScales` method, `_allScales`, etc.  Default to `:none` (identity)

- [x] Gadfly/Immerse
- [x] PyPlot
- [x] Qwt
- [x] Winston
- [ ] UnicodePlots

**Comment by waldyrious** [comment]
@tbreloff is there any place I can see examples of the asinh and sqrt scales in use? (I don't have a Julia installation at hand to try).

**Comment by tbreloff** [comment]
I don't know... just copy/pasted from Gadfly's docs to make sure I have a
starting list to work from.

**Comment by waldyrious** [comment]
Found some potentially interesting links:
- [matplotlib seems to have a symlog (symmetrical log) scale](http://stackoverflow.com/a/3513150/266309)
- [ggplot2 has several scaling options](http://stackoverflow.com/a/14674703/266309) (illustrated examples [here](http://docs.ggplot2.org/current/scale_continuous.html)) as well as a pretty comprehensive [scales](https://cran.r-project.org/web/packages/scales/scales.pdf) package
- besides `asinh`, there are [various sigmoid functions](https://en.wikipedia.org/wiki/Sigmoid_function#/media/File:Gjl-t%28x%29.svg) that can be used for this kind of scaling. `tanh` is a particularly elegant one, and I've used it in the past with nice results.

**Comment by tbreloff** [comment]
Thanks for the list!

**Comment by tbreloff** [comment]
The framework is in... Gadfly's scales are implemented.  Adding a check list for the other backends.  If anyone has requests of scale-types that aren't here, let me know and I'll add.  I won't bother unless I can implement it in one of the backends, though.

**Comment by tbreloff** [comment]
Mostly finished, so I'll close it for now.

Here's a sample:

<img width="611" alt="screen shot 2015-10-03 at 5 25 04 pm" src="https://cloud.githubusercontent.com/assets/933338/10265388/ba89540a-69f3-11e5-8f1f-f246519f2120.png">


<img width="633" alt="screen shot 2015-10-03 at 5 21 51 pm" src="https://cloud.githubusercontent.com/assets/933338/10265379/902c46e0-69f3-11e5-934a-c737c94783be.png">
