### ISSUE TITLE
Strange behaviour of fill keyword

### ISSUE THREAD

**Issue by jw3126** [tbreloff/Plots.jl#393]
The fill keyword sometimes seems to mess up the plot axes:
```
pyplot()
xs = linspace(0.13,0.15,10)
ys = linspace(0.80,0.82,10)
some_function = *
plot(
    contour(xs,ys, some_function),
    contour(xs,ys, some_function, fill=false),
    contour(xs,ys, some_function, fill=true),
)
```
![contour](https://cloud.githubusercontent.com/assets/7261506/16914229/c6d019de-4cf0-11e6-937c-34717bc29075.png)

It seems that the problem depends on the `xs, ys`, but not on `some_function`.

The gr backend has the same issue. For the plotly backend, the colormaps are messed up in the above plot, though the fill kw seems fine in this case.

**Comment by tbreloff** [comment]
Bah. I need to revert an "improvement" that I made, which had fillrange
default to 0 if you set the fill kw. The goal was that you wouldn't need to
set a value for fillrange for the common case of area plots filling to 0.
It's just not robust too do that. Too many corner cases.

**Comment by jw3126** [comment]
Okay, looking forward for this being fixed, it messes up quite some plots I would like to have. Btw I am very impressed by how Plots.jl manages it to wrap all this functionality under one consistent and clean api.

**Comment by tbreloff** [comment]
This should be fixed on `dev`

**Comment by jw3126** [comment]
I checked out the dev branch of Plots, the above code throws an error instead now:
```
unrecognized keyword argument "span_buffer"

 in optimal_ticks_and_labels at /home/admin/.julia/v0.4/Plots/src/axes.jl:155
 in get_ticks at /home/admin/.julia/v0.4/Plots/src/axes.jl:190
 in _before_layout_calcs at /home/admin/.julia/v0.4/Plots/src/backends/pyplot.jl:974
 in prepare_output at /home/admin/.julia/v0.4/Plots/src/plot.jl:223
 in writemime at /home/admin/.julia/v0.4/Plots/src/output.jl:160
 in base64encode at base64.jl:160
 in writemime at /home/admin/.julia/v0.4/Plots/src/output.jl:139
 in writemime at multimedia.jl:43
 in sprint at iostream.jl:206
 in display_dict at /home/admin/.julia/v0.4/Plots/src/output.jl:228
```

**Comment by tbreloff** [comment]
Pkg.checkout("PlotUtils")

**Comment by jw3126** [comment]
Thanks, looks good!

![contour2](https://cloud.githubusercontent.com/assets/7261506/16949610/0611b898-4dbc-11e6-9de3-0ec9d3c730b2.png)
