### ISSUE TITLE
line_z not working

### ISSUE THREAD

**Issue by kersulis** [tbreloff/Plots.jl#395]
I ran the code from #218:

```julia
using Plots
y = cumsum(randn(500))
plot(y, line_z = y, w = 3)
```
and the output doesn't match what I see there:
![cumsum](https://cloud.githubusercontent.com/assets/7925694/17038547/38fb5666-4f64-11e6-95a3-9f48d5b54f2a.png)
It looks like the first value of `y` is being used to select a color for the entire series.

I have Julia 0.4.5, Plots v0.8.1, and PyCall is linked to Python 3.4.5 installed by Anaconda, with matplotlib 1.5.1.

**Comment by tbreloff** [comment]
I changed the behavior, for reasons I don't have time to go into now. It
should hopefully work if you separate each segment with a NaN. Colors apply
to contiguous line segments, not each individual point.

**Comment by kersulis** [comment]
I tried inserting `NaN`s in the vector and plotting it again, no luck (might have understood you wrong though):
```julia
using Plots
pyplot()
y = cumsum(randn(500))
for i in 50:50:500
    insert!(y, i, NaN)
end
plot(y, line_z = y, w = 3, clim=(-5,5))
```
![cumsum2](https://cloud.githubusercontent.com/assets/7925694/17039648/7dded71c-4f69-11e6-8053-faeddebee96c.png)
The colors seem random, and it looks like the `clim` values aren't getting through. No big deal, I can just add points and color them instead. Thanks for the quick response!

**Comment by tbreloff** [comment]
Can you reopen? I want to explain more another time, and the clim needs a
fix. Thanks

**Comment by tbreloff** [comment]
So to expand on yesterday's answers... I've changed the treatment of lines to operate on contiguous segments (consecutive finite points), and colors, etc should treat each such segment as a "single unit".  So in your example, you'd want `line_z` to have the same number of values as the number of line segments... each line_z value would correspond to a full segment.

```julia
using Plots
y = cumsum(randn(500))
y = vec(vcat(reshape(y,50,10),fill(NaN,1,10)))  # this does what you intended to do above
plot(y, line_z = 1:10, w=3)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/17058221/18fc9dbe-4fed-11e6-893b-66bb7a1b3ac2.png)

Note that `line_z` has 10 elements... not 500.

This is generally more flexible and nicer to use than being forced to color every connected point... I'll give a couple examples:

- A recipe converts line segments into piecewise smoothed curves
- A graph is build where each edge corresponds to a color/weight... much more intuitive to have 1 color per edge, even if that edge is drawn with many strokes

In each, we avoid having to recompute linecolor, line_z, etc when the segments change, or if each segment is drawn with a more complex, smoother curve.

The case when you really do want each stroke to be a different color is still possible, of course, by adding NaNs yourself.  However I could see an argument for wanting to do this automatically.  Maybe there could be a `segments` series recipe which adds the NaNs for you.  Something like:

```julia
@recipe f(::Type{Val{:segments}}, x,y,z) = makesegs(x),makesegs(y),makesegs(z)
makesegs(::Void) = nothing
makesegs(v) = vec(hcat(v[1:end-1], v[2:end], fill(NaN,length(v)-1))')
```

**Comment by kersulis** [comment]
Thanks for the detailed response. I should have figured out my code was just using the first few elements of `line_z` to color the handful of segments I made.

Segment-wise behavior is better for my application too. I'm connecting relatively few points with segments, and playing with smoothing.

Leaving issue open as requested because of `clim` behavior. Thanks again!
