### ISSUE TITLE
Itty bitty UnicodePlots

### ISSUE THREAD

**Issue by lstagner** [tbreloff/Plots.jl#396]
When input commands on two separate command prompts I get the following
![screenshot from 2016-07-22 02-04-35](https://cloud.githubusercontent.com/assets/4305891/17052126/fb7218fa-4fb0-11e6-8dca-b39a36972f85.png)

If I do the same commands on a single prompt it behaves as it should
![screenshot from 2016-07-22 02-08-04](https://cloud.githubusercontent.com/assets/4305891/17052181/25d91bb6-4fb1-11e6-81cc-46d3000239a9.png)

```
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.installed("Plots")
v"0.8.1"

julia> Pkg.installed("UnicodePlots")
v"0.1.3"
```

**Comment by tbreloff** [comment]
fixed on dev (julia 0.5) and backports (julia 0.4)
