### ISSUE TITLE
Do not create Pkg.dir("PlotReferenceImages")

### ISSUE THREAD

**Issue by tkelman** [tbreloff/Plots.jl#397]
Please don't create an unregistered non-repo when someone runs the Plots.jl tests. You can create these things locally inside Plots.jl if you'd like, but creating them at the package level is the package manager's job.

**Comment by tbreloff** [comment]
Until you wrote this, I actually didn't know that Pkg.dir creates a directory.  That seems pretty silly to me.  I only want to **get** the directory in a platform-independent way... what's a better command for that?

**Comment by tbreloff** [comment]
It's also not very clear from the docs:

```
help?> Pkg.dir
  dir() -> AbstractString

  Returns the absolute path of the package directory. This defaults to joinpath(homedir(),".julia","v$(VERSION.major).$(VERSION.minor)") on all platforms (i.e. ~/.julia/v0.5 in UNIX shell syntax). If the JULIA_PKGDIR environment
  variable is set, then that path is used in the returned value as joinpath(ENV["JULIA_PKGDIR"],"v$(VERSION.major).$(VERSION.minor)"). If JULIA_PKGDIR is a relative path, it is interpreted relative to whatever the current working
  directory is.

  dir(names...) -> AbstractString

  Equivalent to normpath(Pkg.dir(),names...) – i.e. it appends path components to the package directory and normalizes the resulting path. In particular, Pkg.dir(pkg) returns the path to the package pkg.
```

**Comment by tkelman** [comment]
It doesn't. You're shelling out to `mkdir`.

**Comment by tbreloff** [comment]
Oh!  Thanks... you're right I need to fix that.

**Comment by tbreloff** [comment]
I commented out that section in the dev and backports branches.  I'll tag 0.8.x versions occasionally off of the backports branch, and dev is now 0.5-.

**Comment by tkelman** [comment]
There's also no need to shell out to things that Julia already has perfectly good (and much more portable) functions for.
