### ISSUE TITLE
Plots.jl doesnt work on Mac

### ISSUE THREAD

**Issue by vishaluk** [tbreloff/Plots.jl#399]
Hi,
I have installed Plots and I have tried pyplot, plotly and gr but they all give me the following statement on the console with no plot being drawn -
WARNING: _writemime is not defined for this backend. m=text/plain

**Comment by tbreloff** [comment]
I'll need more info. Versions, etc. Did you check out any specific
branches? What julia version?

**Comment by vishaluk** [comment]
Julia version with machine info is 
- Version 0.4.6 (2016-06-19 17:16 UTC)
- x86_64-apple-darwin15.5.0

The exact steps are 
julia> Pkg.checkout("Plots")
INFO: Checking out Plots master...
INFO: Pulling Plots latest master...
INFO: No packages to install, update or remove
julia> using Plots
julia> gr()
Plots.GRBackend()
julia> plot(x[:,11])
WARNING: _writemime is not defined for this backend. m=text/plain
julia> using Plots;plotly()
Plots.PlotlyBackend()
julia> plot(x[:,11])
[Plots.jl] Initializing backend: plotly
WARNING: _writemime is not defined for this backend. m=text/plain
julia> pyplot()
Plots.PyPlotBackend()
julia> plot(x[:,11])
WARNING: _writemime is not defined for this backend. m=text/plain

**Comment by tbreloff** [comment]
Try Pkg.checkout("Plots","backports")? Or Pkg.free("Plots")?

**Comment by ChrisRackauckas** [comment]
That's just the warning from being inside Atom. After making the plot, use `gui()`

**Comment by tbreloff** [comment]
Dup? https://github.com/tbreloff/Plots.jl/issues/437
