### ISSUE TITLE
Multiple figures generated in a single Jupyter cell

### ISSUE THREAD

**Issue by juliohm** [tbreloff/Plots.jl#403]
First of all, thank you for this package, it is awesome. I started using it today and I am impressed how the API is intuitive, flexible and easy to learn.

I have a simple question: how do you generate multiple figures in a single Jupyter cell? For example, with the matplotlib backend I would call `figure()`, is there a equivalent in `Plots.jl`?

**Comment by tbreloff** [comment]
This is not directly supported.  You could put them all in a single plot as subplots, or you could call show/writemime on the plot object to get the underlying png/svg data and display that yourself.

I don't want this to be the standard method of display, though PyPlot does it this way.  However if you come up with a clean solution I'd be happy to add it to src/output.jl.

**Comment by juliohm** [comment]
Thank you @tbreloff. I am closing the issue for now, just being able to save figures in a loop is enough in most practical scenarios.

**Comment by brunocastroibarburu94** [comment]
Hi, since a couple of years have passed I was wondering if now this feature may be available?

I believe from a UX point of view it would be a nice to have, but is ok if is still not available :)
