### ISSUE TITLE
Add subplots incrementally

### ISSUE THREAD

**Issue by juliohm** [tbreloff/Plots.jl#404]
How to add subplots incrementally? In PyPlot I would do:

```julia
subplot(1,2,1)
plot(foo)
subplot(1,2,2)
plot(bar)
...
```

**Comment by tbreloff** [comment]
You can do something like:

p1 = plot(...)
p2 = plot(...)
plot(p1, p2, layout = ...)

**Comment by juliohm** [comment]
Thank you @tbreloff , is there any other way to achieve the same result without saving intermediate variables like above? Sometimes I do more elaborated calculations on the `idx` of `subplot(m,n,idx)`. Maybe I will just save the intermediate p1, p2, ..., pmn into a 2D array P and flatten it at the time of `plot(P[:]..., layout=...)`. Do I actually need to flatten it or Plots.jl will figure the layout from the array of plots?

**Comment by juliohm** [comment]
Do you think it would be interesting to have a function that takes a 2D array of plots and arranges them in a layout? I tried the plot command without flattening, but it doesn't support this behavior apparently.

**Comment by tbreloff** [comment]
Yes this would be easy and useful. It should be a one-liner. I challenge
you to figure out the one line ;)

As for alternatives... you could also create the subplots, and then add to
them after:

plot(layout = 4)
plot!(..., subplot = 2)

There are other ways as well, but the matlab syntax isn't currently
implemented.

**Comment by juliohm** [comment]
@tbreloff that is perfect, all I needed. I don't think that Matlab syntax is necessary given this last approach. It produces the same effect without boilerplate.

The one-liner should be `plot(P[:]..., lauout=size(P))` or something similar :blush:
