### ISSUE TITLE
Inconsistent link behavior between PyPlot and PlotlyJS backends

### ISSUE THREAD

**Issue by juliohm** [tbreloff/Plots.jl#406]
I have two point clouds that I am plotting side by side. I don't specify the `link` attribute because I want the backend to scale each subplot differently. PyPlot does it correctly:

![pyplot](https://cloud.githubusercontent.com/assets/3345261/17085419/0514eade-519d-11e6-969f-2d5ac9644c2f.png)

but PlotlyJS is trying to match the Y limits:

![plotlyjs](https://cloud.githubusercontent.com/assets/3345261/17085425/2c75c29c-519d-11e6-9732-17d0dd295da3.png)

Is this is a known issue? I see that the examples in the documentation with PlotlyJS all link the subplots somehow.

**Comment by tbreloff** [comment]
Sounds like a bug. Don't know if it's easily fixible.

**Comment by tbreloff** [comment]
added to meta-issue (#316)
