### ISSUE TITLE
Inconsistent ticks behavior between PyPlot and PlotlyJS backends

### ISSUE THREAD

**Issue by juliohm** [tbreloff/Plots.jl#407]
Let's say I need to hide tick labels in a plot. I am passing the attribute `ticks=nothing` for that purpose. PyPlot does it correctly:

![pyplot](https://cloud.githubusercontent.com/assets/3345261/17085533/6db69cba-51a0-11e6-815a-a9f44939a6f4.png)

but PlotlyJS removes the frame entirely:

![plotlyjs](https://cloud.githubusercontent.com/assets/3345261/17085534/7b8c4b1e-51a0-11e6-8fca-e76a0db24fcc.png)

Is this easily fixable?

**Comment by tbreloff** [comment]
added to meta-issue (#316)
