### ISSUE TITLE
Weird tick labeling issue with PyPlot backend

### ISSUE THREAD

**Issue by crbinz** [tbreloff/Plots.jl#408]
See the included screenshots. Code for easy copy/paste:

```
using Plots
scatter([-3.120,-3.118],[.04,-.04])

xlabel!("Label")
```

![screen shot 2016-07-24 at 6 42 58 pm](https://cloud.githubusercontent.com/assets/3694987/17087086/e28026fe-51cf-11e6-8114-27f6eb4f9689.png)
![screen shot 2016-07-24 at 6 43 07 pm](https://cloud.githubusercontent.com/assets/3694987/17087088/e65921f4-51cf-11e6-9d89-a0a4ff449717.png)

**Comment by tbreloff** [comment]
I couldn't reproduce this using julia 0.5 and the dev branch.  Here's what I see:

![tmp](https://cloud.githubusercontent.com/assets/933338/17087612/2a3e294e-51dc-11e6-8b65-b1b8fdd70243.png)

What commit are you on?

**Comment by crbinz** [comment]
Works as expected after a `Pkg.update()`, sorry for the noise.
