### ISSUE TITLE
Cannot Add Package

### ISSUE THREAD

**Issue by meetmauro** [tbreloff/Plots.jl#41]
Installing Plots gives me the following errors:
If I do a Pkg.add("Plots") I get "Unknown package Plots" 
If I try with a Pkg.clone then the package Colors is missing

I'm using julia 0.3.10 / Juno, but I suppose that's OK right?
thanks for your beautiful library.

**Comment by joshday** [comment]
Plots.jl [requires](https://github.com/tbreloff/Plots.jl/blob/master/REQUIRE) julia 0.4-

**Comment by tbreloff** [comment]
I'm not supporting 0.3 right now, but I may try to get it working at some point.  However once 0.4 officially releases I expect most people will change to that anyways.

Can you switch to 0.4-release?

**Comment by meetmauro** [comment]
Oh I should have imagined this and read. I'll switch to the latest. Sorry.

**Comment by tbreloff** [comment]
I made a pass through Plots today and I'll try to support 0.3 going forward.  @meetmauro can you do 
```
Pkg.update()
Pkg.checkout("Plots","dev")
```
and let me know if the package works for you?  You could try:

```
include(joinpath(Pkg.dir("Plots"), "docs/example_generation.jl"))
PlotExamples.test_examples(:gadfly)
```

(or swap out `:gadfly` for something else... just not `:qwt` or `:immerse` as they are `0.4-`)

**Comment by tbreloff** [comment]
Also in case you are missing Colors, Reexport, or Compat... you can add them manually if needed (`Pkg.add("Colors")`, etc)

**Comment by meetmauro** [comment]
Tom, you're super awesome!
this is working perfectly :100: 
this is the sequence I used to make everything work:

```julia
Pkg.update()
Pkg.clone("https://github.com/tbreloff/Plots.jl.git")
Pkg.checkout("Plots","dev")
include(joinpath(Pkg.dir("Plots"), "docs/example_generation.jl"))
PlotExamples.test_examples(:gadfly)
#this is showing the example
```
now to be able to do 
```julia
using Plots
plot(rand(10))
```

I also had to
```julia
Pkg.add("Cairo")
```

but now everything works perfectly.
thank you, super

**Comment by tbreloff** [comment]
Great to hear!  Please open issues if you find bugs, or if there are features you'd like added/tweaked.

Also, just out of curiosity... what backend do you plan to use?  Gadfly is pretty good and PyPlot gets honorable mention.

**Comment by meetmauro** [comment]
Well the backed I am using is Gadfly. I've been a little bit unsure in the past, you know there are several backends... and you never know what will stick around. In any case your solution on top of all is the best :)

**Comment by tbreloff** [comment]
Thanks I agree.  :)  I think Gadfly is fine to stick with for now.  When you upgrade to 0.4 I would switch to Immerse, which uses Gadfly as the backend.  In the future, I think the best will be GLPlot and/or a new package I'm working on to wrap Qt5/QPainter using Cxx (very early in development).

It's really great that people could consider switching to something new without changing any code... :)
