### ISSUE TITLE
PyPlot shows two extra group colors

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#410]
In this example, `plotly` works fine but pyplot shows a red point and a green (close to `(20,2)`) point:

![image](https://cloud.githubusercontent.com/assets/2822757/17087976/e8510f4c-51ea-11e6-9653-ffa4f99b682a.png)

Code:
```
using RDatasets
msleep = dataset("ggplot2","msleep")
h1=msleep[complete_cases(msleep[:,[:Vore]]),[:Vore,:SleepTotal,:SleepRem,:SleepCycle,:Awake]]
using Plots
using StatPlots
scatter(h1, :SleepTotal, :SleepRem, group=:Vore, size=(300,300))
```

**Comment by tbreloff** [comment]
I ran this code and added `leg=:topleft`, and it looks fine to me.  I'm on dev branch using julia 0.5, and PlotUtils master:

![tmp](https://cloud.githubusercontent.com/assets/933338/17102305/f9c76a6c-5246-11e6-8695-c9be540d9134.png)

If you can find a way to reproduce with recent commits, then please reopen with more details.

**Comment by diegozea** [comment]
I haven't moved to Julia 0.5 yet. This happens with Julia 0.4.5 and the stable version of Plots for that Julia version (Plots 0.8.1 and PlotUtils 0.0.4). How can I get the latest version for Julia 0.4 (since master is now 0.5, isn't it?) ? Maybe this issue needs to be reopened and tagged like 0.4 issue.

**Comment by tbreloff** [comment]
I've been doing small backport fixes in the backports branch. I don't have
the time to backport big changes, so you'll have to figure out what's wrong
yourself if you need it fixed. (Or maybe this is good motivation to upgrade)

Feel free to reopen and add a "[0.4]" to the title, with the understanding
that 0.4 issues are lower priority for me.

**Comment by diegozea** [comment]
I'm not able to reopen it. Could you reopen it? Thanks! I'm not hurry about it.

**Comment by tbreloff** [comment]
Oh weird. You can't reopen your own issue?  Ok I'll do it tomorrow.

**Comment by diegozea** [comment]
Yes, It's weird!

![image](https://cloud.githubusercontent.com/assets/2822757/17121319/3e8cac22-52a9-11e6-9710-818d0c8131a7.png)
