### ISSUE TITLE
Tick Format

### ISSUE THREAD

**Issue by lstagner** [tbreloff/Plots.jl#413]
Is there anyway to specify the tick format. I have data that goes from 0-1e15 and I would like the ticks to use scientific notation. 

![screenshot from 2016-07-25 17-43-31](https://cloud.githubusercontent.com/assets/4305891/17122330/5b36739a-528f-11e6-81fd-981d3b4ed6ac.png)

**Comment by tbreloff** [comment]
This is something I've been thinking about. For my purpose I have a
TimeOfDay type which is like a number but I'd like to have special
formatting. I'm thinking maybe a 'tick_formatter' attribute that is a
function (or functor) and defaults to 'string'.

**Comment by tbreloff** [comment]
Trying this out:

```julia
using Plots; pyplot()
plot(1e6randn(100), yformatter = :scientific)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/17146522/d5f90c12-532c-11e6-9269-53efa3160e73.png)

```julia
plot(1e6randn(100), yformatter = yi -> "my custom label: $yi")
```

![tmp](https://cloud.githubusercontent.com/assets/933338/17146616/128441ba-532d-11e6-9ee5-e9eeb489ee77.png)

Only on julia 0.5 and Plots dev branch

**Comment by mkborregaard** [comment]
Sounds reasonable. Could you open a fresh issue?
