### ISSUE TITLE
Syntax for incrementally building up inset plots

### ISSUE THREAD

**Issue by lstagner** [tbreloff/Plots.jl#416]
I have been trying to make a complicated inset plot and I am finding harder then it should be (I still haven't figured it out). 

I would like to be able to do something like this.
```julia
x = linspace(0,2pi)
p = plot(x,sin(x))
vline!(p, [pi/2] )
#add more stuff to p
c = contour(x, y, z, inset=(bbox(...), p) ) #inset p into the contour plot
```

I feel this is a much cleaner way of creating insets.

**Comment by tbreloff** [comment]
This might be easiest (for now) to first make the contour with a blank
inset, then add to the inset.  You can either use 'subplot=2' to add to it,
or you can pass a Subplot object as the first arg: 'plot!(p[2], ...)'

**Comment by lstagner** [comment]
I tried that but it doesn't like changing insets 
```
ichan=1
i=300
w_los= squeeze(sum(wf_los[i:i+3,:,:,ichan],1),1)'
lam = mean(lambda[i:i+3])
p=contour(energy, pitch, w_los, fill=true, 
           zlim=(0,6),
           annotations=(3,0.3, text(@sprintf("%.2f nm",lam),:left,:white,:bold)),
           xlabel="Energy [keV]", xticks=[20,40,60,80,100],
           ylabel="Pitch",yticks=[-1.0,-0.5,0.0,0.5,1.0],size = (500,300))
l = bbox(0.15w,0.05h,0.3w,0.3h, v_anchor=:top,h_anchor=:right)
plot!(p,lambda,wf_los[:,20,20,ichan], inset_subplots = [(1,l)], subplot=2, xlim=(652,663),label="")
vline!(p[2],[lam])
```
![bad_inset](https://cloud.githubusercontent.com/assets/4305891/17136046/f090bb14-52e7-11e6-9441-0a69d7bb36ea.png)

It works as expected without the ```vline```
Also how can I make so I can see the inset tick labels.

**Comment by tbreloff** [comment]
It would be a big help if you could check other backends and/or reduce this to something I can copy/paste.

**Comment by lstagner** [comment]
```
x=linspace(0,2pi)
y=linspace(0,2pi)
z = [sin(xx)*cos(yy) for xx in x, yy in y]
p=contour(x,y,z,fill=true)
plot!(x,sin(x),inset_subplots = [(1, bbox(0.05w,0.05h,0.3w,0.3h))], subplot=2)
plot!(p[2],x,cos(x))
```
produces the following using both ```pyplot``` and ```gr``` backends
![bad_inset](https://cloud.githubusercontent.com/assets/4305891/17152581/3b92cc8e-532d-11e6-8166-259c7aef2daf.png)

**Comment by tbreloff** [comment]
This was very helpful... thanks.  I figured it out.  Change your last command to `plot!(p[2], cos, fg_text=:white)` and I get:

![tmp](https://cloud.githubusercontent.com/assets/933338/17152974/523424e0-5348-11e6-99d1-fd4256349873.png)

**Comment by lstagner** [comment]
Thanks, Is there anyway to have the tick labels be black on a white background?

**Comment by tbreloff** [comment]
A subplot background is not automatically drawn.

[This link](http://www.cilyan.org/blog/2016/01/23/matplotlib-draw-between-subplots/) might be a good reference for pyplot.  We'd get the coordinates similar to [here](https://github.com/tbreloff/Plots.jl/blob/master/src/backends/pyplot.jl#L1152) and draw a filled rectangle using `transform=fig.transFigure`
