### ISSUE TITLE
Use breadcrumbs in the website's header

### ISSUE THREAD

**Issue by JobLeonard** [tbreloff/Plots.jl#417]
Hey, just a request for a small enhancement on the website.

I think the navigation on the Plots.js website would be a bit more convenient if its header would be structured like breadcrumbs. I was actually a bit lost when navigating the website earlier because I could not click on `Examples` here:

![image](https://cloud.githubusercontent.com/assets/259840/17133422/404cd4f6-5326-11e6-8ac6-13a75c92b10a.png)

... and also a bit surprised that it was not structured as a growing trail of breadcrumbs: `Plots > Examples > PyPlot`. Also, because the default zoom on my computer is so big that I had to scroll up forever to be able to get back to the top-level page of the website.

**Comment by tbreloff** [comment]
If you can find these features I will happily add them. The docs are built
with mkdocs and the Material theme.

**Comment by JobLeonard** [comment]
I looked around - some mkdocs themes feature breadcrumbs, so it's *possible* at least. However, this theme doesn't appear to support them, presumably since it is mobile-first and breadcrumbs take up a lot of horizontal space. However, if could be made collapsible like the hamburger icon that should not be an issue. So I guess I'll just request this feature on the theme's github ;).

**Comment by JobLeonard** [comment]
Looks like staying up-to-date with the theme will eventually implement this feature automatically!

**Comment by tbreloff** [comment]
How do you feel about me closing this issue, since there's nothing actionable on my end?

**Comment by JobLeonard** [comment]
Oh sorry, should have done so myself. I will post here once the issue is closed upstream as a reminder.
