### ISSUE TITLE
Plotly and interact throw 'could not spawn wkhtmltoimage' error

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#419]
In Jupyter, 

```julia
using Plots
plotly()
@manipulate for k=1:10
    plot(1:k)
end
```

Throws the error:

```julia
could not spawn `wkhtmltoimage -f png -q --width 600 --height 400 --disable-smart-width /var/folders/rv/h1lw4d411svghj8sz5tdkns40000gn/T/juliaBENkD4.html /var/folders/rv/h1lw4d411svghj8sz5tdkns40000gn/T/juliaD5USbP.png`: no such file or directory (ENOENT)

 in _jl_spawn at process.jl:262
 in anonymous at process.jl:415
 in setup_stdio at ./process.jl:403
 in __spawn#58__ at ./process.jl:414
 in run at ./process.jl:530
 in html_to_png at /Users/solver/.julia/v0.4/Plots/src/backends/web.jl:51
 in writemime_png_from_html at /Users/solver/.julia/v0.4/Plots/src/backends/web.jl:61
 in writemime at /Users/solver/.julia/v0.4/Interact/src/IJulia/setup.jl:103
 in base64encode at base64.jl:160
 in display_dict at /Users/solver/.julia/v0.4/IJulia/src/execute_request.jl:32
```

**Comment by dlfivefifty** [comment]
The solution is to install http://wkhtmltopdf.org, though there could be a better warning.

**Comment by tbreloff** [comment]
Weird that it's trying to output png. Did you set 'fmt = :png' earlier in
the session?

**Comment by dlfivefifty** [comment]
No.  There were some package build failures due to Homebrew that may be related (I fixed Homebrew now using `brew doctor`.)

**Comment by tbreloff** [comment]
Can you try this with `plotlyjs()` instead?  If that works, lets close the issue as I don't have motivation to ever work on it.

**Comment by dlfivefifty** [comment]
They both seem to work (PlotlyJS finally works without the .o!), but I have wkhtmltopdf installed so it may be using it.  I could check in a couple weeks in my office (I'm on holiday), though if you want to close it that's fine.

**Comment by tbreloff** [comment]
I decided to explicitly throw an error for plotly and point the user to plotlyjs.
