### ISSUE TITLE
Margin

### ISSUE THREAD

**Issue by ghuba** [tbreloff/Plots.jl#421]
Is there a way to change the margins of the plot?

Within an IJulia notebook, I find that the plot is sometimes too much to the left so that some of the text gets clipped (y axis labels and title). It's this line in plotly.jl

    d_out[:margin] = KW(:l=>40, :b=>0, :r=>0, :t=>20)
    # d_out[:margin] = KW(:l=>0, :b=>0, :r=>0, :t=>20)

With l=40, the plot is better positioned.

**Comment by tbreloff** [comment]
Here's an example:

```
using Plots; plotly()
plot(1e7rand(100), left_margin=100px)
```

**Comment by ghuba** [comment]
Awesome. That does the trick!
