### ISSUE TITLE
PFGPlots

### ISSUE THREAD

**Issue by ghuba** [tbreloff/Plots.jl#422]
Sorry for the second question in the same day. Is there a way to save a PGFPlots to tex? I could not figure that out. Something like this:

        PGFPlots.save("input_for_latex.tex", my_axis, include_preamble=false)

Thanks.

**Comment by KristofferC** [comment]
You can just extract the `.o` field from the plot object which holds the pgfplots axis and call the `PGFPlots` function like you are doing. There might be a getter function to get the underlying plot object as well, I'm not sure if that was implemented.

**Comment by ghuba** [comment]
Thanks. Here is what I am trying to run, from within a Julia notebook 0.4.5:

    pgfplots()
    data = [ 1 0; 2 0; 3 0 ]
    axs = plot(data); 
    @show axs
    @show fieldnames(axs)
    @show axs.backend
    @show axs.o
    # PGFPlots.save("input_for_latex.tex", axs.o)

The output is:
    axs = Plot{Plots.PGFPlotsBackend() n=2}
    fieldnames(axs)= [:backend,:n,:attr,:user_attr,:series_list,:o,:subplots,:spmap,:layout,:inset_subplots,:init]
    axs.backend = Plots.PGFPlotsBackend()
    axs.o = nothing

PGFPlots.save does not work since axs.o is empty. I can see by reading pgfplots.jl that axs.o should have the info but I think it gets cleaned up before I can use it.

**Comment by KristofferC** [comment]
Try this https://github.com/tbreloff/Plots.jl/issues/267#issuecomment-222056840

**Comment by ghuba** [comment]
Got it.

For interested readers, here is what works. In your Julia notebook, type this inside one cell:

    using Plots
    pgfplots()
    data = [ 1 0; 2 0; 3 0 ]
    plt = plot(data)

You should see the SVG figure in your notebook. The key thing is that `plot(data)` should be the last instruction in your cell. In the next cell, type:

    pgf_axis = plt.o # pgf axis produced by Plots
    PGFPlots.save("input_for_latex.tex", pgf_axis) # tex output
    PGFPlots.save("my_figure.pdf", pgf_axis) # pdf output
    PGFPlots.save("input_for_latex_no_preamble.tex", pgf_axis, include_preamble=false)
    # tex output with only the tikz code; include in another tex file using
    # \input{input_for_latex_no_preamble.tex}
