### ISSUE TITLE
Examples in documentation error due to recipes having moved

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#424]
For example, that stats recipes moved out to [StatsPlots.jl](https://github.com/JuliaPlots/StatPlots.jl), so the Iris plot on the front page of the documentation now throws an error [like this](http://dpaste.com/02FNBJM). The documentation should be combed through to either take out the stats plots or mention the package.

**Comment by tbreloff** [comment]
I think this is fixed... please reopen if you find anything else.
