### ISSUE TITLE
How can I implement "axis off"?

### ISSUE THREAD

**Issue by AStupidBear** [tbreloff/Plots.jl#428]

**Comment by tbreloff** [comment]
I don't know... what do you expect that would do?  Remove the borders?  No tick labels?

**Comment by AStupidBear** [comment]
I mean "no axis", just lines and points.

**Comment by AStupidBear** [comment]
I mean "no axis", just lines and points.

**Comment by AStupidBear** [comment]
I mean "no axis", just lines and points.

**Comment by AStupidBear** [comment]
I mean "no axis", just lines and points.

**Comment by tbreloff** [comment]
I'm planning on adding some logic so that `plot(..., axis = nothing)` will be the same as `plot(..., ticks=nothing, border=nothing)`

**Comment by tbreloff** [comment]
```julia
using Plots; plot(rand(10), axis=nothing)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/17530938/b487d63c-5e47-11e6-9559-52f8cb29a801.png)

**Comment by Cody-G** [comment]
Actually it turns out setting `border=:none` does what I needed.  Note that `border=nothing` does not work.
