### ISSUE TITLE
Deprecated Gadfly bachend?

### ISSUE THREAD

**Issue by AStupidBear** [tbreloff/Plots.jl#429]
I'm using Gtk to display a graph. I only know how to draw a plot generated by gadfly/immerse on a canvas.
```julia
using Immerse
using Gtk.ShortNames,Graphics

win = @Window("Canvas",400,400) |> (c = @Canvas())
p=plot(x=rand(10), y=rand(10), Geom.point, Geom.line)
display(c,Immerse.Figure(c,p));
show(c)
	
c.mouse.button1press = @guarded (widget, event) -> begin
   println(event.x," ", event.y)
    p=plot(x=rand(10), y=rand(10), Geom.point, Geom.line)
	display(c,Immerse.Figure(c,p));
	show(c)
end

showall(win)
```
But now Gadfly bachend is deprecated, how can I do this?
```julia
using Plots
gadfly()
plot(rand(10))
ERROR: KeyError: xguide not found
 in createGadflyPlotObject at /home/astupidbear/.julia/v0.4/Plots/src/backends/gadfly.jl:60
 in _plot_setup at /home/astupidbear/.julia/v0.4/Plots/src/pipeline.jl:214
 in _plot! at /home/astupidbear/.julia/v0.4/Plots/src/plot.jl:178
```

**Comment by tbreloff** [comment]
Try a different backend? I don't expect that I'll get around to fixing the
Gadfly backend. There's just not enough features to justify the effort.

**Comment by AStupidBear** [comment]
I don't know how to do this using other backends.

**Comment by tbreloff** [comment]
Do you need to draw to a specific Gtk canvas?  Is this part of a GUI?

**Comment by AStupidBear** [comment]
Yes, it's a part of an interactive gui

**Comment by tbreloff** [comment]
@jheinen is there a way to draw to a Gtk canvas in GR?

I think PyPlot or GR can maybe do this, but I don't know how off the top of my head.

**Comment by jheinen** [comment]
This Gtk example works fine on OS X and Ubuntu: https://github.com/jheinen/GR.jl/blob/master/examples/gtk_ex.jl

I changed the quit() logic this morning - using exit() seems to be a better solution when the windows is closed (by the user).

**Comment by AStupidBear** [comment]
@jheinen 
I got the following message:
```julia
GKS: /home/astupidbear/.julia/v0.4/GR/deps/gr/lib/cairoplugin.so: undefined symbol: XRenderCompositeText32
```

**Comment by jheinen** [comment]
@AStupidBear : which OS are you using? You probably have to install a system-specific GR distribution instead of generic Linux binaries.

**Comment by AStupidBear** [comment]
@jheinen Ubuntu 16.04 LTS

**Comment by AStupidBear** [comment]
@jheinen I think this should be automatically done by GR.jl. I have only  seen instructions on how to install GR to python on Ubuntu 16.04, not julia.

**Comment by ChrisRackauckas** [comment]
> @jheinen I think this should be automatically done by GR.jl. I have only seen instructions on how to install GR to python on Ubuntu 16.04, not julia.

Installing GR in Julia is just `Pkg.add("GR")`.

**Comment by AStupidBear** [comment]
@ChrisRackauckas Of course I have installed GR using Pkg.add. But jheinen said "install a system-specific GR distribution".

**Comment by jheinen** [comment]
``Pkg.add("GR")`` works both for macOS X (10.6 - 10.12 Beta) and Windows 7 - 10. Those binary packages are self-comtained.

For Linux systems, although also built as self-contained packages, at least two different run-time libraries have to be provided: one for RedHat and one for Debian based systems. We prepared such packages, but they need further testing.

The safest way (on Linux) however, is to install a distribution specific package. Gone are the times where you could run X11 based programs on different Linux flavours.

**Comment by tbreloff** [comment]
I'm going to close this as I don't see anything actionable.
