### ISSUE TITLE
Custom yticks in PGFPlot not working

### ISSUE THREAD

**Issue by GravityAssisted** [tbreloff/Plots.jl#434]
So I am executing the following code
```
s = ["1.25", "2", "3","4", "5","7", "10", "12"]
x  = round(([1.25,2,3,4,5,7,10,12]),2)
plot(Df0_0[1],Df0_0[2],xscale=:log10,yscale=:log10,ylab="Speedup",xlab=L"$\frac{T^{*}}{T_p}$",marker=(:circle,0.35),markerstrokewidth=0.15,markersize=2,linestyle=:dash,lw=0.25,yticks=(x,s),lab=L"$N_{max}=0$")
plot!(Df0_1[1],Df0_1[2],xscale=:log10,yscale=:log10,marker=(:dtriangle,0.35),markerstrokewidth=0.15,markersize=2,linestyle=:dash,lw=0.25,yticks=(x,s),lab=L"$N_{max}=1$")
plot!(Df0_3[1],Df0_3[2],xscale=:log10,yscale=:log10,marker=(:d,0.35),markerstrokewidth=0.15,markersize=2,linestyle=:dash,lw=0.25,yticks=(x,s),lab=L"$N_{max}=3$")
plot!(Df0_5[1],Df0_5[2],xscale=:log10,yscale=:log10,marker=(:star5,0.35),markerstrokewidth=0.15,markersize=2,linestyle=:dash,lw=0.25,yticks=(x,s),lab=L"$N_{max}=5$")
plot!(Df0_10[1],Df0_10[2],xscale=:log10,yscale=:log10,marker=(:pentagon,0.35),markerstrokewidth=0.15,markersize=2,yticks=(x,s),linestyle=:dash,lw=0.25,lab=L"$N_{max}=10$")
savefig("test.pdf")
```
![screen shot 2016-08-06 at 8 52 03 pm](https://cloud.githubusercontent.com/assets/11938645/17460360/b07a1e38-5c17-11e6-9b96-58fa073373b2.png)

but the output doesn't show the custom yticks (see the picture above)..
Is there a way around this issue ? 

I am on Julia Version 0.4.4-pre+2 on MAC OSX, using Plots 0.8.1

thanks,
Nitin

**Comment by tbreloff** [comment]
The way around it is to implement that feature. I don't spend as much time
on that backend, so I depend on others to help add features.

**Comment by GravityAssisted** [comment]
I see. I found a workaround by first writing a tex file for the figure and then modifying the tex file (adding one line to it basically) to generate the needed yticks. I am more of Julia user and not a developer but would be willing to contribute to Plots.

Nitin

**Comment by GravityAssisted** [comment]
BTW: I did try using other backends and ran into following issues:

PlotlyJS: 
1. Wasn't able to generate latex labels.
2. Wasn't able to generate pdf output.

GR:
1. Wasn't able to generate LATEX output in xlabel. The legend labels worked fine.
2. The legend text opacity is for some reason connected to the opacity of the markers. When I increased the transparency on the markers the text also became more transparent.

**Comment by tbreloff** [comment]
Thanks. Even if you can't do the dev work for a new feature, it would be
helpful if you could research how you might do this in PGFPlots.jl to make
it easier for someone else to implement.

I'll have to add these other issues to the respective meta-issues for each
backend.

**Comment by tbreloff** [comment]
added to the meta-issue
