### ISSUE TITLE
Add a page for the Plots ecosystem to the docs?

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#439]
It seems like Plots has really grown. Because of type-recipes, authors of other packages can make type recipes so that the types in their package have nice looking default plots. I know that I do that with DifferentialEquations.jl, and have proposed recipes for the ConvergenceHistory type in IterativeSolvers.jl, am working on type recipes for SIUnits.jl, etc.

But what other packages can I just use `plot(...)` and expect it to work? It seems there are a lot of statistics types which have recipes via StatPlots. What else?

It would be nice to showcase all of this on one page of the documentation. It would be a nice showcase of the power of the Plots recipe system, and help users of Plots find out which packages have out-of-the-box compatibility with Plots.

**Comment by lobingera** [comment]
which docs? http://julialang.org/ mentioned Gadfly first and Plots.jl deprecates Gadfly. http://julialang.org/downloads/plotting.html lists PyPlot and Gadfly.

**Comment by ChrisRackauckas** [comment]
JuliaLang/julialang.github.com#399 is for that discussion. 

I am thinking about a tab in the Plots documentation to show the packages which have recipes for their types.

**Comment by pkofod** [comment]
Just like https://juliadocs.github.io/Documenter.jl/latest/man/examples/ for Documenter, right?

**Comment by ChrisRackauckas** [comment]
Yes, that's a good example.

**Comment by Evizero** [comment]
maybe with some screenshots? If I go on a plotting related homepage the first thing I really look for are screenshots to how the output actually looks. (I am superficial like that!)

**Comment by ChrisRackauckas** [comment]
Yes. There are a lot of people working on nice recipes right now, but unless you know about StatPlots, you're not finding those nice histograms. I think just package, summary, link, and a plot from that package would be a great way to show people the other parts of the Plots.jl ecosystem. 

I know that for me, I would pick my statistical packages based on which ones already have plots setup with Plots.jl (I'm too lazy to deal with making the plots myself...).

**Comment by tbreloff** [comment]
I'd like to do this, but the hardest part is compiling the list and screenshots!  It would be awesome if you would post a short description here for any packages which use Plots/RecipesBase with a screenshot, then I can link to the images in this issue from the docs.  Thanks in advance!

**Comment by ChrisRackauckas** [comment]
Might as well start it off. What image format should we give you? It doesn't let you post SVGs here.

(I'll take recommendations on how to make it look prettier too)

 DifferentialEquations.jl is a package for solving numerically solving differential equations in Julia by Chris Rackauckas. The purpose of this package is to supply efficient Julia implementations of solvers for various differential equations. Equations within the realm of this package include ordinary differential equations (ODEs), stochastic ordinary differential equations (SODEs or SDEs), stochastic partial differential equations (SPDEs), partial differential equations (with both finite difference and finite element methods), differential algebraic equations, and differential delay equations. It includes well-optimized implementations classic algorithms and ones from recent research, including algorithms optimized for high-precision and HPC applications.

<img src="https://raw.githubusercontent.com/ChrisRackauckas/DifferentialEquations.jl/master/examples/plots/DifferentialEquations_Example.svg" width="750" align="middle"  />

**Comment by ChrisRackauckas** [comment]
I will add one for IterativeSolvers when JuliaLang/IterativeSolvers.jl#77 gets merged.

**Comment by Evizero** [comment]
The plots look really nice! is this the output of a single plot command?

**Comment by ChrisRackauckas** [comment]
Alerting authors of packages who have RecipesBase dependencies:

@jverzani for SymPy and ImplicitEquations
@joshday for AverageShiftedHistograms
@jangevaare for PhyloTrees and OnlineStats
StatPlots

Other possibilities for featured recipes (found by Plots dependencies):

@baggepinnen for Robotlib.jl (do you need Plots as a dependency, or just RecipesBase?) and ExperimentalAnalysis.jl (could those plots be series recipes on DataFrames?)
@codles for EEG.jl (is the plot command needed. or could it just be changed so Signal has a recipe?)
@mfalt for ControlSystems.jl (candidate for recipes to clean up the code?)
@dlfivefifty for ApproxFun
And maybe @reworkhow JWAS is a candidate for type recipes.

**Comment by ChrisRackauckas** [comment]
@Evizero each plot was just `plot(solution)` with a few keyword arguments to add titles and such. Then there was one plot command to put them together. (The code for doing this is here)[https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/examples/plotsjl_example.jl].

**Comment by tbreloff** [comment]
for the link:

![image](https://cloud.githubusercontent.com/assets/933338/17529235/96a48040-5e40-11e6-8698-7d371f36fd22.png)

**Comment by pkofod** [comment]
Should Optim jump on the bandwagon and add convergence plots recipes? :)

**Comment by tbreloff** [comment]
Of course!

**Comment by tbreloff** [comment]
https://juliaplots.github.io/ecosystem/

**Comment by pkofod** [comment]
> Of course!

I'm afraid of the growing market powers of Plots.jl though... We might need to have FTC have a look at it.

**Comment by tbreloff** [comment]
Add:

- Reinforce
- Optim
- AtariAlgos

**Comment by jangevaare** [comment]
Here's a very short blurb about PhyloTrees for the community packages section on the ecosystem page:

The PhyloTrees.jl package provides a type representation of phylogenetic trees. Simulation, inference, and visualization functionality is also provided for phylogenetic trees. A plot recipe allows the structure of phylogenetic trees to be drawn by whichever plotting backend is preferred by the user.

![phylotrees](https://cloud.githubusercontent.com/assets/5422422/17630286/a25374fc-608c-11e6-9160-32466b094f0b.png)

**Comment by tbreloff** [comment]
Thanks Justin! Very cool. There was a recipes idea a while back that asked
for these as subplots, similar to marginalhist. It would be cool to add
those as well. I'll look for the issue number later.

**Comment by jangevaare** [comment]
If anybody is doing hierarchical clustering algorithm stuff, they could probably adopt the code for visualization of that (assuming they don't already have their own solution).

**Comment by tbreloff** [comment]
Just added PhyloTrees and AtariAlgos to the ecosystem page.  I also added QuantEcon to the TODO list.  @spencerlyon2 any chance you'd add a quick blurb about it and post image(s) to link to?

**Comment by spencerlyon2** [comment]
Yep I can do that. 

cc @alpeb and vgregory757. If you guys feel up for this and have certain Plots.jl plots you are particularly proud of, by all means have a go at it!

**Comment by tbreloff** [comment]
for the link:

![image](https://cloud.githubusercontent.com/assets/933338/17701986/0c447270-639a-11e6-8eb3-f890a95d1b0f.png)

**Comment by tbreloff** [comment]
@Evizero what package does that MNIST animation belong to?  It's very cool and I want it :)

**Comment by mfalt** [comment]
Is this plot meant to represent the ControlExamplePlots.jl?
We have a couple of plots in our reference [repository](https://github.com/JuliaControl/ControlExamplePlots.jl/tree/master/src/figures)
as well as a few in the [documentation](http://juliacontrol.github.io/ControlSystems.jl/latest/)
but I am not sure if they are the best examples. I am happy to provide an example, but I am not sure what is best suited.

**Comment by tbreloff** [comment]
for the link:

![ash](https://cloud.githubusercontent.com/assets/933338/17702262/3bfc9a96-639b-11e6-8976-aa8bb8fabfc8.gif)

**Comment by tbreloff** [comment]
> Is this plot meant to represent the ControlExamplePlots.jl?

Yes @mfalt ... happy for you to suggest a better example!

**Comment by tbreloff** [comment]
maybe https://github.com/JuliaControl/ControlExamplePlots.jl/blob/master/src/figures/nichols.png?

**Comment by mfalt** [comment]
The nichols is probably not a great option since it doesn't really look as it should (it could need some work). I will try to generate and upload a nice example. Otherwise, this is pretty nice http://juliacontrol.github.io/ControlSystems.jl/latest/plots/pidgofplot2.svg

**Comment by tbreloff** [comment]
for links:

![image](https://cloud.githubusercontent.com/assets/933338/17702652/bca0158c-639c-11e6-8e36-4bfc7b36727e.png)

![image](https://cloud.githubusercontent.com/assets/933338/17702662/cdc08752-639c-11e6-8c3c-e186456630e2.png)

**Comment by tbreloff** [comment]
for the link:


![tmp](https://cloud.githubusercontent.com/assets/933338/17703784/f3e18414-63a0-11e6-9f9e-f531278216f9.gif)

**Comment by Evizero** [comment]
how about:

![mnist](https://cloud.githubusercontent.com/assets/10854026/17645973/3894d2b0-61b6-11e6-8b10-1cb5139bfb6d.gif)

**Comment by tbreloff** [comment]
@Evizero great! Can I attribute this to a specific package?  Or should I put it in a "gallery"?

**Comment by Evizero** [comment]
It is from Augmentor.jl but a lot of custom settings (so not a provided user plot in this form). I will probably add this kind of visualisation natively down the road though

**Comment by tbreloff** [comment]
Ok cool.  I'm not putting any runnable code up (because that would be maintainence hell).  So I'm ok with displaying a custom plot if you are.  Let me know

**Comment by ChrisRackauckas** [comment]
Since this is going strong, adding more can probably be a case-by-case thing on the PlotDocs repo.
