### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#44]
In Qwt, I have an interface that looks like:

```
a = animation(plt, "/tmp/png")
for x in 0:0.1:5
    push!(plt, 1, x, sin(x))
    refresh(plt)
    saveframe(a)
end
makegif(a)
```

It creates a directory to store pngs of the snapshots, then at the end calls out to the system to run ffmpeg to create an animated gif.

This can't be the best way to do it.  Does anyone know of a better solution??  cc: @timholy

**Comment by lobingera** [comment]
Actually it's not a Bad interface to provide animations like this. Maybe some timing interface could be provided so you can control the default playback speed in writing already.

**Comment by tbreloff** [comment]
The part I'm really not happy with is the hacky dependence on the external program ffmpeg.  This is what I do now in Qwt (which is not a good solution for the general user):

```
makegif(animation::PlotAnimation) = run(`ffmpeg -framerate 20 -i $(animation.dir)/qtanim%04d.png -y $(animation.dir)/out.gif`)
```

**Comment by lobingera** [comment]
@tbreloff, would you like to have a native ffmpeg implemented in julia? https://github.com/kmsquire/VideoIO.jl exists.

**Comment by tbreloff** [comment]
Close, but it seems like only video playback is supported.

**Comment by Evizero** [comment]
:100: for creating GIFs out of plots

**Comment by tbreloff** [comment]
This was fairly easy (just need to document the ffmpeg dependency):

```
julia> using Plots
INFO: Recompiling stale cache file /home/tom/.julia/lib/v0.4/Plots.ji for module Plots.

julia> xy() = randn(10), randn(10)
xy (generic function with 1 method)

julia> p = scatter(xy()..., size=(500,300))
[Plots.jl] Initializing backend: immerse
WARNING: Method definition draw(Compose.Backend, Compose.Context) in module Compose at /home/tom/.julia/v0.4/Compose/src/container.jl:404 overwritten in module Immerse at /home/tom/.julia/v0.4/Immerse/src/compose.jl:33.
WARNING: Method definition display(Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, Base.Multimedia.MIME{:text/html}, Gadfly.Plot) in module Gadfly at /home/tom/.julia/v0.4/Gadfly/src/Gadfly.jl:969 overwritten in module Immerse at /home/tom/.julia/v0.4/Immerse/src/display_gadfly.jl:144.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0

julia> anim = Animation()
Plots.Animation{Plots.Plot{Plots.ImmersePackage}}(Plot{Plots.ImmersePackage() n=1},"/tmp/tmpDZKqcP",ASCIIString[])

julia> for i in 1:100
           append!(p, 1, xy()...)
           frame(anim)
       end

julia> gif(anim)
ffmpeg version 2.6.3 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-9)
  configuration: --disable-yasm
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
Input #0, image2, from '/tmp/tmpDZKqcP/%06d.png':
  Duration: 00:00:05.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgb24, 500x300, 20 fps, 20 tbr, 20 tbn, 20 tbc
Output #0, gif, to '/tmp/julia03oVZU.gif':
  Metadata:
    encoder         : Lavf56.25.101
    Stream #0:0: Video: gif, bgr8, 500x300, q=2-31, 200 kb/s, 20 fps, 100 tbn, 20 tbc
    Metadata:
      encoder         : Lavc56.26.100 gif
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> gif (native))
Press [q] to stop, [?] for help
frame=  100 fps=0.0 q=0.0 Lsize=     855kB time=00:00:05.00 bitrate=1401.3kbits/s    
video:954kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
INFO: Saved animation to /tmp/julia03oVZU.gif
```

![julia03ovzu](https://cloud.githubusercontent.com/assets/933338/10546514/5f4cfa20-73fc-11e5-9e6d-8912a7ff4b9f.gif)


I'm going to leave it open, since I need to remember to document this, and also I want to add a display method to be able to show the gifs in IJulia automatically.

**Comment by tbreloff** [comment]
The output from ffmpeg was surprisingly bad.  I might just have bad settings, but ImageMagick is much nicer.  I made it a call to `convert` with `ffmpeg` as a backup if that fails.

Also, it works in IJulia now, with the caveat that the filename has to be relative, and it has to be within the directory that  IJulia is serving from.

**Comment by timholy** [comment]
For writing a GIF, ImageMagick is a much better choice because it should be lossless. That said, it's true that tuning `ffmpeg` is an artform, and sometimes one can get very good results. My favorite "lazy" approach is to use `qscale` (thought I'd mention it in case you hadn't tried it).

**Comment by tbreloff** [comment]
Since `convert` works nicely, I'll leave it as-is (ffmpeg low quality as the backup to convert).  I added an example and a short section to the readme, so I think it's done.
