### ISSUE TITLE
plot(Array(Float64,2,0),Array(Float64,2,0)) throws DivideError

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#448]
```julia
plot(Array(Float64,2,0),Array(Float64,2,0))
``` 

throws a confusing `DivideError: integer division error`.  I would expect it to plot nothing, or throw an error that says 'plots must not be empty'.

**Comment by tbreloff** [comment]
Good catch (though I'm not sure why you'd ever do this?).  I'll push up a fix soon.

**Comment by dlfivefifty** [comment]
There was a bug in my code that triggered this.
