### ISSUE TITLE
add_backend methods

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#449]
Each backend package typically has a "standard install" of 1-5 lines.  Here's a method which checks whether the package is installed then does the "noob install" for them.  For example:

```julia
function add_backend(::PyPlotBackend)
    if !is_installed("PyPlot")
        withenv("PYTHON" => "") do
            Pkg.add("PyPlot")
            Pkg.build("PyPlot")
        end
    end
end
```

**Comment by Evizero** [comment]
is this function intended to be called by the user manually or by Plots automatically?

**Comment by tbreloff** [comment]
Meant to be called by the user manually.  Then I can eventually change the install instructions to "call add_backend or install it yourself"
