### ISSUE TITLE
Custom markers

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#45]
I started playing with the ability to create custom markers from polygon coordinates.  This is with the Gadfly backend.  I created a new `Gadfly.GeometryElement` which wraps the vertices of the `Shape` that you pass in... @dcjones do you want me to make a PR to expose this functionality to Gadfly directly?  Right now the definitions are in Plots only.

- [x] Gadfly
- [x] Immerse
- [x] PyPlot
- [ ] ~~Qwt~~
- [ ] ~~UnicodePlots~~
- [ ] Plotly

![tmp](https://cloud.githubusercontent.com/assets/933338/10496409/a68ab284-728e-11e5-801b-cfa16f072fc5.png)

**Comment by tbreloff** [comment]
Can do cool stuff like generating shapes now.  Here's a bunch of stars, created from weaving together the points from an outer circle and an inner circle:

![tmp](https://cloud.githubusercontent.com/assets/933338/10498736/3fce74a2-729a-11e5-89fc-efeb1e494bce.png)

**Comment by Evizero** [comment]
That's pretty cool

**Comment by tbreloff** [comment]
The framework is done... I'll add checkboxes for the individual backend support.  These are all procedurally generated now:

![tmp](https://cloud.githubusercontent.com/assets/933338/10518605/34e3e8ba-7330-11e5-928f-e5c4ab257388.png)

**Comment by ssouyris** [comment]
@tbreloff, is this functionality available in Gadfly directly? I see that you updated shapes.jl, but I'm not sure how to used it.

**Comment by tbreloff** [comment]
No... This is Plots-only at the moment. If I remember correctly, I asked the Gadfly crowd if they wanted me to submit a PR with the functionality, and no one responded. So I never got around to it. 

There might be an alternative way to accomplish it in Gadfly directly... I'm not sure.

**Comment by pkofod** [comment]
> If I remember correctly, I asked the Gadfly crowd if they wanted me to submit a PR with the functionality, and no one responded.

You pinged dcjones in the opening post :)

**Comment by ssouyris** [comment]
Thanks @tbreloff for the reply! In Plots, is it possible to specify the shapes in the labels-key? 
In the plot above the shape key is written; it would be useful if it can contain the shape itself.   

@dcjones, in guide.jl you have 

        # TODO: Draw key for shapes. We need to think about how to make this
        # work...
Is it something that you plan to do in the near future? Thanks!

**Comment by tbreloff** [comment]
>  In Plots, is it possible to specify the shapes in the labels-key?

This is done automatically for some backends (PyPlot for example)

> `@dcjones` ... Is it something that you plan to do in the near future?

He's been MIA for a little while now, but it's possible someone else is willing to help if you post an issue for Gadfly.  I suspect, however, that the most reliable method of getting that feature is to do it yourself.

**Comment by ssouyris** [comment]
> I suspect, however, that the most reliable method of getting that feature is to do it yourself.
That's what I thought, thanks!

**Comment by diegozea** [comment]
@tbreloff Is It imposible to support some shapes with UnicodePlots? Would be great to support something like that:
```julia
julia> boxplot(iris, :Species, :SepalLength)
[Plots.jl] Initializing backend: unicodeplots
WARNING: Exception during apply_recipe(Val{shape}, ...) with types (Array{Float64,1}, Array{Float64,1}, Void)
ERROR: The backend must not support the series type Val{:shape}, and there isn't a series recipe defined.
```
The boxes are shapes, but I guess that UnicodePlots' lines can make them.

**Comment by tbreloff** [comment]
@diegozea I challenge you to make the series recipe which converts a shape series into a path with fill!  (should be only a few lines of code)
