### ISSUE TITLE
Multiple plots with dates on the x-axis are shown incorrectly

### ISSUE THREAD

**Issue by maximsch2** [tbreloff/Plots.jl#451]
Output here looks very wrong:
```julia
using Plots

delta = Date(2004,2,1) - Date(2004, 1,1)
dates1 = collect(Date(2004,1,1):delta:Date(2016, 1,1))
dates2 = collect(Date(2004,1,3):delta:Date(2016, 1,1))
vals = rand(length(dates1));
vals2 = rand(length(dates2));

plot(dates1, cumsum(vals))
plot!(dates2, cumsum(vals2))
```
![image](https://cloud.githubusercontent.com/assets/464680/17790776/ed53cbd6-654c-11e6-9c09-ba75e782bf2d.png)

It is like Plots.jl doesn't understand how to order dates.

**Comment by maximsch2** [comment]
Adding a function like this helps:
```julia
function Plots.discrete_value!(axis::Axis, dv::Date)    
    cv_idx = get(axis[:discrete_map], dv, -1)
    # @show axis[:discrete_map], axis[:discrete_values], dv
    if cv_idx == -1
        cv = Int64(dv)
        Plots.expand_extrema!(axis, cv)
        push!(axis[:discrete_values], dv)
        push!(axis[:continuous_values], cv)
        cv_idx = length(axis[:discrete_values])
        axis[:discrete_map][dv] = cv_idx
        cv, cv_idx
    else
        cv = axis[:continuous_values][cv_idx]
        cv, cv_idx
    end
end
```
But the problem this time is that labels on x-axis are mis-aligned:
![image](https://cloud.githubusercontent.com/assets/464680/17791071/449d420e-654e-11e6-9edf-2ce1b2879322.png)

**Comment by tbreloff** [comment]
> Adding a function like this helps:

FYI this is not how I'd do it.  I was just about to prepare a solution, and I can add it to Plots.  Give me a few minutes

**Comment by maximsch2** [comment]
Awesome, thanks!

**Comment by tbreloff** [comment]
![tmp](https://cloud.githubusercontent.com/assets/933338/17791519/90d44aa8-6569-11e6-9df6-7af10907a994.png)

I'll push up soon

**Comment by maximsch2** [comment]
Awesome, thanks!

Something similar would probably be helpful for `DateTime` as well.

**Comment by tbreloff** [comment]
Agreed.  An easy PR... wanna give it a go?

**Comment by tbreloff** [comment]
(it's literally as easy as copy/paste what I just added and change to DateTime)

**Comment by maximsch2** [comment]
Yeah, sounds like a great idea. I'll send it in a bit.

**Comment by maximsch2** [comment]
The exact copy/paste is enough for `DateTime`-only plots, but if you mix Date and DateTime, then it breaks again. Converting `Date` to `DateTime` first before doing `convert(Int)` in your new recipe fixes plotting, but x-axis values are still getting crazy:
![image](https://cloud.githubusercontent.com/assets/464680/17792666/180c1324-6557-11e6-9827-c64d08b8bae7.png)

**Comment by maximsch2** [comment]
Converting `Date` type to string with `string(convert(DateTime, dt))` fixes the output (as types are now represented in the same way, but this seems redundant for the `Date`-only plots (they now include a timestamp)
