### ISSUE TITLE
Plots with proj=:polar do not have correct y axis range.

### ISSUE THREAD

**Issue by Ward9250** [tbreloff/Plots.jl#456]
```julia
sticks(linspace(0.25π,1.5π,5), rand(5), proj=:polar, yerr=[0.1, 0.2, 0.3, 0.4, 0.5])
```

Works fine, with a radial plot where the range of the rings goes from 0.0 in the center to 0.6 on the outide. However, the maximum range of 0.6 on the y axis does not increase when values of y are larger:

```julia
sticks(linspace(0.25π,1.5π,5), [5, 10, 15, 20, 25], yerr=[0.1, 0.2, 0.3, 0.4, 0.5])
```
Here y ranges from 5 to 25, but the axis still ranges from 0.0 to 0.6.

**Comment by tbreloff** [comment]
Seems to have the correct axis for me:

![tmp](https://cloud.githubusercontent.com/assets/933338/18275596/b619ecb8-7415-11e6-8a09-25ada40169dc.png)

Though the error bars look weird since they use horizontal line markers...

**Comment by Ward9250** [comment]
Which backend does that use?

**Comment by tbreloff** [comment]
that was pyplot... i just tested with GR and I agree there's a bug.  i'll link from the GR meta issue
