### ISSUE TITLE
Running Plots.jl as a new user with many issues

### ISSUE THREAD

**Issue by huckl3b3rry87** [tbreloff/Plots.jl#457]
My goal with this post is to make it easy for a new user to be able to (at the very least) be able to run the examples on this page [https://juliaplots.github.io/] with ease for at least one given configuration (operating system and version of julia). Because, currently I do not think this is possible. For instance, I was using Plots on Windows and trying to run the animation examples, I ran into issues and was told that Linux should solve my problems. So, I set up Ubuntu 16.04 on my machine and am now dual booting. Then I tried to run plots and I still had issues. I was told that the running the new julia that is being prepared for release (0.5.0-rc2) should fix my issues and it did not. I then tried to add several packages, build them and pull them from the current repositories. Then I tried using all of the different backends. While I have been able to run several of the examples most of the time I have had issues and I have never had an animation working (which again is what I am very interested in).

Through this process, I have received support from both the julia and plots.jl communities and I am very grateful for that. After watching the recent video from Tom Breloff describing Plots.jl at juliacon, I became very excited about using the software and I very much appreciate all of the hard work that he and the community have done to build these tools and I think that what they are trying to do is very ambitious and will eventually be extremely useful. I am still hopeful for this software and I am willing to do what I can to help develop it. 

Just to restate what I put on gitter and get things started here, after installing julia 0.5.0-rc2 on Ubuntu 16.04, I ran the following commands:
`Pkg.add("Conda")
ENV["PYTHON"]=""
Pkg.add("PyPlot")
Pkg.add("Plots")
Pkg.build("PyPlot")
Pkg.add("ImageMagick")
Pkg.add("GR")
Pkg.add("Plotly")
Pkg.add("StatPlots")
Pkg.add("PlotRecipes")
Pkg.add("UnicodePlots")
Blink.AtomShell.install()`

Is there any way that an advanced user can run the basic setup of Plots.jl on Ubuntu (or maybe just a Linux machine) and make a list of all of the things that need to be done in order to get it working (i.e. finish what I started above)? Basically installing a new version of julia (no prior packages) and then generating a set of code that one can run (for a particular version of julia and a particular operating system) that will make the examples on the Plots.jl website work. 

Thank you all very much for your consideration.

**Comment by ChrisRackauckas** [comment]
Hey, been working with you on this for a few days now. It's sad to hear you keep having troubles. If I remember correctly, it's just the animations that aren't working, correct? If that's the case, then maybe someone can chime in on whether they have had problems in Ubuntu? I know that for me, running those commands made pretty much everything work effortlessly, but that was about a month ago (haven't done animations in awhile).

**Comment by huckl3b3rry87** [comment]
Yes, I and really appreciate your help with this Chris. 

It is not only the animations, unfortunately there are many issues when I try to run the basic examples. I am not sure how it is best to proceed, but I feel like there should be a certain group of packages that when installed elicit a working piece of software. With that I have played with (as I mentioned) different backends and I have also played with many versions (i.e. checking out packages from the master branch etc.) Here is a look at the current packages that I have:  
`
julia> Pkg.status()
17 required packages:
 - Cairo                         0.2.34
 - Conda                         0.2.3
 - DataFrames                    0.7.8
 - GR                            0.14.0+            master
 - Gadfly                        0.4.3
 - IJulia                        1.2.0
 - ImageMagick                   0.1.7+             master
 - Ipopt                         0.2.4
 - JuMP                          0.14.0
 - PGFPlots                      1.3.5
 - Plotly                        0.1.0
 - Plots                         0.9.0+             master
 - PyPlot                        2.2.1
 - RDatasets                     0.1.3
 - StatPlots                     0.0.3
 - UnicodePlots                  0.1.4
 - Winston                       0.11.13
72 additional packages:
 - BinDeps                       0.4.3
 - Blink                         0.4.0
 - BufferedStreams               0.1.6
 - Calculus                      0.1.15
 - Codecs                        0.2.0
 - ColorBrewer                   0.3.0
 - ColorTypes                    0.2.6
 - ColorVectorSpace              0.1.7
 - Colors                        0.6.6
 - Compat                        0.8.8
 - Compose                       0.4.4
 - Contour                       0.1.1
 - DataArrays                    0.3.8
 - DataStructures                0.4.5
 - Dates                         0.4.4
 - Distances                     0.3.2
 - Distributions                 0.10.2
 - FileIO                        0.1.1
 - FixedPointNumbers             0.1.4
 - FixedSizeArrays               0.2.3
 - ForwardDiff                   0.2.4
 - GZip                          0.2.20
 - Graphics                      0.1.3
 - Grid                          0.4.2
 - Hexagons                      0.0.4
 - Hiccup                        0.0.3
 - HttpCommon                    0.2.6
 - HttpParser                    0.1.1
 - HttpServer                    0.1.6
 - Images                        0.5.9
 - IniFile                       0.2.5
 - Iterators                     0.1.10
 - JSON                          0.7.0
 - KernelDensity                 0.2.0
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.0
 - Libz                          0.2.0
 - Loess                         0.0.7
 - MacroTools                    0.3.2
 - MathProgBase                  0.5.3
 - MbedTLS                       0.3.0
 - Measures                      0.0.3
 - Mustache                      0.0.15
 - Mux                           0.2.1
 - NaNMath                       0.2.1
 - Nettle                        0.2.4
 - Optim                         0.6.1
 - PDMats                        0.4.2
 - PlotUtils                     0.0.4
 - PlotlyJS                      0.3.2
 - PositiveFactorizations        0.0.2
 - PyCall                        1.7.1
 - RecipesBase                   0.0.6
 - Reexport                      0.0.3
 - Requests                      0.3.10
 - Requires                      0.3.0
 - ReverseDiffSparse             0.5.8
 - Rmath                         0.1.2
 - SHA                           0.2.1
 - SIUnits                       0.0.6
 - Showoff                       0.0.7
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.9.0
 - StatsFuns                     0.3.0
 - TexExtensions                 0.0.3
 - TikzPictures                  0.3.3
 - Tk                            0.3.8
 - URIParser                     0.1.6
 - WebSockets                    0.2.1
 - WoodburyMatrices              0.2.0
 - ZMQ                           0.3.4
 - Zlib                          0.1.12
`
Can someone please share the list of versions that they have that make the examples work?

**Comment by ChrisRackauckas** [comment]
Part of the issues could be that the documentation may be behind some of the recent changes. For example, the move of stats recipes to StatsPlots was pretty recent, and I just changed the front page of the documentation example (the Iris one) to mention StatsPlots... last week?

So post some problems you're having with the errors. Let's see what's up with the non-animation examples first.

(I'm not at my normal computer so my Pkg.status() isn't up to date on this)

**Comment by tbreloff** [comment]
Very sorry you've had such a tough time getting started, but certainly that's not the experience for most people.  I suspect that one or more of the steps you reported did not actually finish successfully.  Based on my rough memory of your many posts, I think you don't have some basic build tools installed on your machine and some other packages were not built.  As I've said, you should be able to do most things by just adding the tagged versions of packages.  Animations on Windows I can't comment on... @ChrisRackauckas knows more about that.  But things should work on Ubuntu (which I use).

Without seeing the full transcript from clean install to errored commands, it's really hard to help you.  You keep sending partial-information messages with ambiguous "I tried lots of other things too", and it's hard to pinpoint what's going wrong for you.

**Comment by ChrisRackauckas** [comment]
You should just be fine with cmake. But that's because of an issue with how Julia is bundled: there is a main issue about bundling MbedTLS since it requires cmake for the install, and a lot of packages use it (I can't find the issue right now, but it's recent). But if MbedTLS is built, everything else should work.

**Comment by huckl3b3rry87** [comment]
So, currently I my issues are resolved. All of the basic examples are working and I am able to use the pyplot backend to run animations (albiet, the other backends do not seem to support animations on my current configuration). I would like to help others that may run into these issues that I ran into. So, below I will list the commands that I issues to make this work using julia 0.5.0-rc2 and Ubuntu 16.04 ( these commands are for a user just starting out that may not have the proper packages:
**In the terminal:**
`
sudo apt install ffmpeg
sudo apt-get install cmake bar time binutils make libssl-dev gfortran libunwind8-dev gcc g++ #clang curl perl wget m4 patch pkg-config
sudo apt-get update
sudo apt-get install gsfonts-x11
`
**In julia:**
`
Pkg.add("Conda")
ENV["PYTHON"]=""
Pkg.add("PyPlot")
Pkg.add("Plots")
Pkg.build("PyPlot")
Pkg.add("ImageMagick")
Pkg.add("GR")
Pkg.add("Plotly")
Pkg.add("StatPlots")
Pkg.add("PlotRecipes")
Pkg.add("UnicodePlots")
Pkg.add("Gadfly")
Pkg.add(“Winston”)
Pkg.add(“DataFrames”)
Pkg.add(“IJulia”)
Pkg.update() 
Blink.AtomShell.install()
# to fix pyplot
import Conda 
Conda.add("qt=4.8.5") 
`
Not necessarily do you need all of the packages listed above. For instance, you probably do not need Gadfly, Winston, IJulia, or DataFrames. I just included a list of all of the packages that I have been using to get started to make plots in julia. 

@ChrisRackauckas  and @tbreloff I realize That I am truly a beginner and that what I have said may not be that useful to other users. If that is the case, I am willing to try to clean this post up or delete it completely if that is what you think is best. Thank you both for your help with this.

**Comment by ChrisRackauckas** [comment]
We were all beginners once. Note that this is the glory of Plots.jl: Julia still very actively developed, and so it's really nice that you can know that at least one backend is going to work for what you need it. I can point to other examples, like how Plotly is the only package which handles Bigs smaller than 1e-30 correctly. PyPlot is what I use for animations too, and it's also the one which "stays" in IJulia so I use it in my notebooks for tutorials. But GR is faster, so it's necessary for other purposes. 

I would like to add a note that the list of packages you put is only necessary if you want to run a large number of the examples, and some of those commands are redundant (a package will automatically install its own dependencies, so I believe one of the packages would install DataFrames). But things like StatsPlots are only required if you doing the statistical plots, and installing the backends (GR, UnicodePlots, etc.) is only required if you're using that backend. I assume most people would be sticking to one or two backends, so suggesting that list is overkill (other than for doing the academic exercise of testing everything).
