### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by ghuba** [tbreloff/Plots.jl#459]
Hi,

Plotly used to work on juliabox but I recently tried to reinstall it and there is now a problem during the installation. The version of Julia has changed from 0.4.5 to 0.4.6.

In the console:

    $ rm -rf ~/.julia
    $ julia
    julia> Pkg.add("Plots")                                                                                                                             
    julia> Pkg.add("PlotlyJS") 

Julia: Version 0.4.6 (2016-06-19 17:16 UTC)

Up to that point, it seems to proceed fine. Then:

    julia> quit()

Create a Julia 0.4.6 notebook. Then:

    using Plots

This is where the error shows up:

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Plots.ji for module Plots.

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Reexport.ji for module Reexport.

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/FixedSizeArrays.ji for module FixedSizeArrays.

WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.

WARNING: deserialization checks failed while attempting to load cache from /opt/julia_packages/.julia/lib/v0.4/FixedSizeArrays.ji

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/RecipesBase.ji for module RecipesBase.

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/PlotUtils.ji for module PlotUtils.

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Colors.ji for module Colors.

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/FixedPointNumbers.ji for module FixedPointNumbers.

WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.

WARNING: deserialization checks failed while attempting to load cache from /opt/julia_packages/.julia/lib/v0.4/FixedPointNumbers.ji

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/ColorTypes.ji for module ColorTypes.

WARNING: Module FixedPointNumbers uuid did not match cache file
  This is likely because module FixedPointNumbers does not support  precompilation but is imported by a module that does.

WARNING: deserialization checks failed while attempting to load cache from /opt/julia_packages/.julia/lib/v0.4/ColorTypes.ji

WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.

WARNING: deserialization checks failed while attempting to load cache from /opt/julia_packages/.julia/lib/v0.4/Colors.ji

INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/Colors.ji for module Colors.
WARNING: Module Reexport uuid did not match cache file
  This is likely because module Reexport does not support  precompilation but is imported by a module that does.

WARNING: deserialization checks failed while attempting to load cache from /home/juser/.julia/lib/v0.4/Colors.ji

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Colors.ji for module Colors.

WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.

WARNING: deserialization checks failed while attempting to load cache from /opt/julia_packages/.julia/lib/v0.4/Colors.ji

INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/Colors.ji for module Colors.

WARNING: Module Reexport uuid did not match cache file
  This is likely because module Reexport does not support  precompilation but is imported by a module that does.

WARNING: require failed to create a precompiled cache file

**ERROR: requiring "Colors" did not define a corresponding module**

WARNING: deserialization checks failed while attempting to load cache from /opt/julia_packages/.julia/lib/v0.4/PlotUtils.ji

INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/Colors.ji for module Colors.

WARNING: Module Reexport uuid did not match cache file
  This is likely because module Reexport does not support  precompilation but is imported by a module that does.

WARNING: deserialization checks failed while attempting to load cache from /home/juser/.julia/lib/v0.4/Colors.ji

INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Colors.ji for module Colors.

WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.

WARNING: deserialization checks failed while attempting to load cache from /opt/julia_packages/.julia/lib/v0.4/Colors.ji

INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/Colors.ji for module Colors.

WARNING: Module Reexport uuid did not match cache file
  This is likely because module Reexport does not support  precompilation but is imported by a module that does.

WARNING: require failed to create a precompiled cache file

**ERROR: LoadError: UndefVarError: Colors not defined**

 in stale_cachefile at loading.jl:459
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in require at ./loading.jl:241
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

while loading /home/juser/.julia/v0.4/Plots/src/Plots.jl, in expression starting on line 13

Output:

LoadError: Failed to precompile Plots to /home/juser/.julia/lib/v0.4/Plots.ji
while loading In[1], in expression starting on line 1

 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in recompile_stale at loading.jl:476
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:235

**Comment by tbreloff** [comment]
Sounds like a corrupted cache... Best bet is probably to delete your lib
and .cache directories from your ~/.julia. This is likely unrelated to
Plots.

**Comment by ghuba** [comment]
Thanks for the quick reply. I started by deleting ~/.julia (see above). That should clean up all cache  right?

**Comment by ghuba** [comment]
I tried your suggestion. The output is slightly different but still failing.

I deleted .cache and lib inside ~/.julia. The output is now a bunch of WARNING and INFO similar to above. Then:

  LoadError: __precompile__(true) but require failed to create a precompiled cache file
  while loading In[5], in expression starting on line 1

 in require at ./loading.jl:268
 in stale_cachefile at loading.jl:457
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:235
 in stale_cachefile at loading.jl:457
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:235
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:235


I agree that this is probably not a Plots specific problem though.

Let me know if you have a suggestion. Otherwise I will just look around.

Thanks.

**Comment by tbreloff** [comment]
Are you sure ~ is pointing to the same directory that is getting loaded? In
/opt?

**Comment by ghuba** [comment]
Here is an update. I figured out the problem. There is something wrong in the way JuliaBox is set up. I don't understand the details but the directory 

    /opt/julia_packages/.julia/lib/v0.4

on JuliaBox is creating problems. Julia is trying to precompile some files and caching them and there is a conflict with the directory above.

So I removed the directory from 

    Base.LOAD_CACHE_PATH

and this solved my problem.

My installation script is now:

    if length(Base.LOAD_CACHE_PATH) >= 3
        splice!(Base.LOAD_CACHE_PATH, 3)
    end
    Pkg.add("Plots")
    Pkg.add("PlotlyJS")

This is for JuliaBox only. See in particular:

    /opt/julia-0.4.6/etc/julia/juliarc.jl

```
cat /opt/julia-0.4.6/etc/julia/juliarc.jl                                                                                           
# This file should contain site-specific commands to be executed on Julia startup                                                   
# Users should store their own personal commands in homedir(), in a file named .juliarc.jl                                          
                                                                                                                                    
push!(LOAD_PATH, "/opt/julia_packages/.julia/v0.4/"); push!(Base.LOAD_CACHE_PATH, "/opt/julia_packages/.julia/lib/v0.4"); try using 
JuliaBoxUtils; JuliaBoxUtils.SysLim.setrlimit(JuliaBoxUtils.SysLim.RLIMIT_NOFILE, 256) end 
```   

Before the splice:

```
julia> @show Base.LOAD_CACHE_PATH                                                                                                   
Base.LOAD_CACHE_PATH = Union{ASCIIString,UTF8String}["/home/juser/.julia/lib/v0.4","/opt/julia-0.4.6/usr/lib/julia","/opt/julia_pack
ages/.julia/lib/v0.4"]                                                                                                              
3-element Array{ByteString,1}:
 "/home/juser/.julia/lib/v0.4"                                                                                                      
 "/opt/julia-0.4.6/usr/lib/julia"                                                                                                   
 "/opt/julia_packages/.julia/lib/v0.4"
```

After the splice:


```
julia> splice!(Base.LOAD_CACHE_PATH, 3)                                                                                             
"/opt/julia_packages/.julia/lib/v0.4"                                                                                               
                                                                                                                                    
julia> @show Base.LOAD_CACHE_PATH                                                                                                   
Base.LOAD_CACHE_PATH = Union{ASCIIString,UTF8String}["/home/juser/.julia/lib/v0.4","/opt/julia-0.4.6/usr/lib/julia"]                
2-element Array{ByteString,1}:
 "/home/juser/.julia/lib/v0.4"                                                                                                      
 "/opt/julia-0.4.6/usr/lib/julia"
```

I read this thread to find this solution:

https://github.com/JuliaCloud/JuliaBox/issues/338
