### ISSUE TITLE
with macro

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#46]
I want to be able to do something like the following, which will just override the defaults for the block, resetting the defaults at the end:

```
@with color=:green , width = 10 begin
  plot(x, y)
  scatter!(x2, y2)
  ...
end
```

**Comment by tbreloff** [comment]
Credit to @spencerlyon2 for this thought:

> You mentioned you might do it with a macro. I think it might be cleaner to implement

> ```
> with (f::Function, args...)
> ```

> Then use `do` notation to use it:

> ```
> with (backend=:gadfly, size=(400, 200), ...) do
>    # plotting commands 
> end
> ```

Certainly easier to implement, so I'll probably go with this.

**Comment by tbreloff** [comment]
This works now (thanks again for the suggestion @spencerlyon2)

```
julia> using Plots

julia> Plots.CURRENT_BACKEND
Plots.CurrentBackend(:qwt,Plots.QwtPackage())

julia> default(leg=false, grid=false)

julia> p = with(:gadfly, :legend, :grid, w=5) do
           plot(rand(10))
           scatter!(rand(20))
       end

julia> default(:legend)
false

julia> Plots.CURRENT_BACKEND
Plots.CurrentBackend(:qwt,Plots.QwtPackage())
```

I'll leave it open for now, as I'd like to expand support for "magic args".  For example, putting `:scatter` in the arg list should be the same as setting the keyword arg `linetype = :scatter`.

**Comment by spencerlyon2** [comment]
Nice, it looks good. Cool functionality

**Comment by tbreloff** [comment]
I don't see myself expanding this functionality, so I'm closing the issue.
