### ISSUE TITLE
Plotly Axis Cutoff

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#465]
The y-axis for Plotly is cutoff. With no modifications to the spacing, you get something like this:

![feaginconvergence](https://cloud.githubusercontent.com/assets/1814174/18112138/47ca5ada-6eda-11e6-8f86-80c107af6f81.png)

where the axis labels cut into the tick labels. But even if you don't have axis labels, you get something like this:

![newplot](https://cloud.githubusercontent.com/assets/1814174/18112178/8af2ae84-6eda-11e6-9daf-e1e110a57489.png)

Since this occurs with both Plotly and PlotlyJS, this might be a Plots problem with choosing positioning?

**Comment by ghuba** [comment]
I would suggest
```
left_margin=50px
```
as as extra argument inside `plot()`. This will add some space to the left.

**Comment by tbreloff** [comment]
Yes adding margin is the best solution at the moment.  Right now the default margin calcs don't properly account for tick label size.

**Comment by tbreloff** [comment]
Closing in favor of #514

**Comment by willsharpless** [comment]
@tbreloff I am having this og issue as many others have but the problem with the `left_margin` fix is that with subplots, the left margin is applied to all plots, shrinking all subplots undesirably. Is there anything else that can be done?
