### ISSUE TITLE
plotly backend issue on juliabox

### ISSUE THREAD

**Issue by dgleich** [tbreloff/Plots.jl#467]
I'm trying to use Plots.jl in a class and we wanted to use the plotly backend for the interactive features that aren't so easy in pyplot (via juliabox.com).

Somehow, there is a subtle issue with Plots and the plotly backend we haven't been able to track down.

What appears to be the root cause is the javascript written to the output ...

    <script src="/home/juser/.julia/v0.4/Plots/deps/plotly-latest.min.js"></script>

which is a file link to the file on the juliabox, not on my local computer.

**Comment by tbreloff** [comment]
Ok just FYI I don't use juliabox so I'm not going to be much help here.  If anyone else can help debug, that would be great.

**Comment by ghuba** [comment]
May be I can help. I am also using plotlyjs() on juliabox.

I don't understand your exact problem though. Can you share your code?

**Comment by dgleich** [comment]
Funny, now I'm not getting this error any more... I'll see if I can reproduce it again. I'm wondering if there was just a slight error in one of the JS files that plotly was using.
