### ISSUE TITLE
Error showing an empty plot

### ISSUE THREAD

**Issue by fredrikekre** [tbreloff/Plots.jl#468]
Showing an empty plot gives an error.

REPL:
![repl](https://cloud.githubusercontent.com/assets/11698744/18161298/a589a83a-7031-11e6-8d5b-9b65d6180520.png)

In a notebook:
![notebook](https://cloud.githubusercontent.com/assets/11698744/18161312/b383aa26-7031-11e6-985b-e40e518a2427.png)

Should it be checked if the plot is empty before trying to show it?

And also, the second time in the REPL it gives a stacktrace, which it didn't the first time, not sure if this is a Plots.jl problem or something else:
![repl2](https://cloud.githubusercontent.com/assets/11698744/18161364/f412e642-7031-11e6-9a1e-65fe8d14a3ff.png)

Thanks @KristofferC for the nice error printing!

**Comment by KristofferC** [comment]
Use `plot()` instead of `Plot()`.

**Comment by fredrikekre** [comment]
Woops.
