### ISSUE TITLE
Mismatch between linestyle in plot and legend when one label is ="" for Pgfplots

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#473]
The legend should be orange:

![image](https://cloud.githubusercontent.com/assets/1282691/18275061/b45a0a5e-7445-11e6-850a-3f640c65f3fe.png)

**Comment by tbreloff** [comment]
I just confirmed that this is **not** an issue with GR.  Any pgfplots experts want to help out??

**Comment by KristofferC** [comment]
Yeah, I checked with pyplot and it works there to. So I specified pgfplots in title :)

**Comment by KristofferC** [comment]
Problem is that only a single line 
`\addlegendentry{sin}`

is added to the .tex file which will refer to the first plot.

**Comment by KristofferC** [comment]
Instead of having one legend entry per curve we could also specify all labels in a `\legend{,sin}` where an empty entry means it will not be added to the legend.

**Comment by KristofferC** [comment]
Adding `forget plot` to the plot options for that line also works.

**Comment by tbreloff** [comment]
I'm happy to merge a fix ;)
