### ISSUE TITLE
Surface with plotlyjs

### ISSUE THREAD

**Issue by ghuba** [tbreloff/Plots.jl#479]
Hi,

I ran into the following problem. This is inside a Julia notebook. Julia 0.4.5 on Mac.

I want to do a 3D surface plot.
```
using Plots
pyplot()
[... set up code ...]
plot(x,y,z,linetype=:surface)
```
That works. I get a nice sphere (x, y, z are points on the unit sphere).
But with
```
plotlyjs()
```
it fails:
```
LoadError: MethodError: `start` has no method matching start(::Plots.Surface{Array{Float64,2}})
while loading In[127], in expression starting on line 4

 in collect at array.jl:255
 in plotly_data at /Users//.julia/v0.4/Plots/src/backends/plotly.jl:334
 in plotly_series at /Users//.julia/v0.4/Plots/src/backends/plotly.jl:353
 in _series_added at /Users//.julia/v0.4/Plots/src/backends/plotlyjs.jl:36
 in _add_the_series at /Users//.julia/v0.4/Plots/src/pipeline.jl:360
 in _process_seriesrecipe at /Users//.julia/v0.4/Plots/src/pipeline.jl:382
 in _plot! at /Users//.julia/v0.4/Plots/src/plot.jl:204
 in plot at /Users//.julia/v0.4/Plots/src/plot.jl:52
```
However:
```
@show supported_types()
supported_types() = [:path,:scatter,:bar,:pie,:heatmap,:contour,:surface,:path3d,:scatter3d,:shape,:scattergl]
```
with `plotlyjs()`. 

I am a bit confused with the error. Shouldn't `:surface` work for plotlyjs?

**Comment by tbreloff** [comment]
Please include the missing [set up code] or a reduced example so I can
copy/paste.

Also I highly recommend switching to julia 0.5.

**Comment by ghuba** [comment]
Will upgrade!

```
using Plots
#plotlyjs()
pyplot()

N = 32
u = linspace(0, 2π, N)
v = linspace(0, π, N)
x = cos(u) * sin(v)'
y = sin(u) * sin(v)'
z = repeat(cos(v)',outer=[N, 1])

#@show supported_args()
@show supported_types()
@show supported_styles()
plot(x,y,z,linetype=:surface)
```

**Comment by tbreloff** [comment]
I just pushed up a "fix" to dev, but either the fix wasn't good enough or Plotly doesn't support surfaces which fold over each other:

<img width="577" alt="screen shot 2016-09-09 at 10 39 12 pm" src="https://cloud.githubusercontent.com/assets/933338/18407423/3dab8cfc-76de-11e6-9608-5788a46282f4.png">

You'll need to be on 0.5 to use the fix though...

**Comment by ghuba** [comment]
Thank you. 

`PlotlyJS` works for this, e.g.:
```
N = 32
u = linspace(0, 2π, N)
v = linspace(0, π, N)
x = cos(u) * sin(v)'
y = sin(u) * sin(v)'
z = repeat(cos(v)',outer=[N, 1])

import PlotlyJS
PlotlyJS.plot([PlotlyJS.surface(x=x,y=y,z=z)])
```
will plot a sphere.

As a side topic, `PlotlyJS` offers a lot of options, see

[plotly.js figure reference](https://plot.ly/javascript/reference/)

I have tried several of these options in `PlotlyJS` and they seem to work. I was interested in `surfacecolor` specifically.

Is that something that can be accessed through `Plots`?

**Comment by tbreloff** [comment]
Fixed on dev:

![tmp](https://cloud.githubusercontent.com/assets/933338/18996909/3aefc6f4-8700-11e6-9ae7-2576a97fe55c.png)

and I also took the opportunity to properly implement wireframes:

![tmp](https://cloud.githubusercontent.com/assets/933338/18996945/640f2aa2-8700-11e6-9bb7-fe90254b9819.png)

I'm having a hard time getting that colorbar to behave though...

**Comment by ghuba** [comment]
Awesome!
