### ISSUE TITLE
Changing fonts in pyplot

### ISSUE THREAD

**Issue by swt30** [tbreloff/Plots.jl#482]
How do I change the font face with the pyplot backend? I've set `titlefont = font("Times", 14)` and so on, but only the size change seems to get picked up. I'm also not having any luck directly altering the matplotlib rcParams dictionary.

**Comment by tbreloff** [comment]
You have the right idea. Maybe "Times" isn't supported?

**Comment by swt30** [comment]
This works fine:

```
using PyPlot
rc("font", family="serif")
plot(rand(20))
title("Here's the title")
```

But not this:
```
using Plots
pyplot(tickfont=font("serif"), titlefont=font("serif"))
plot(rand(20), title="Here's the title")
```

**Comment by swt30** [comment]
I have just managed to make it work by calling `PyPlot.rc("font", family="serif")` before `plot` though.

**Comment by tbreloff** [comment]
Ok thanks. Do any other fonts work? tickfont? legwndfont?

**Comment by swt30** [comment]
Nope, none of those.

**Comment by tbreloff** [comment]
So there was a slight problem in pyplot font families... umm.. I was never setting them! :)

`dev` branch:

```julia
using Plots; pyplot()
f=font(13,"cursive")
p = plot(rand(10), title="HI", titlefont=f, tickfont=f, legendfont=f, yguide="I'm a Y", guidefont=f)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/18456546/c85cbd6a-791f-11e6-9a56-2210025ae37e.png)

I could make it easier to change the font family... but that should be a different issue.
