### ISSUE TITLE
Inconsistent color maps on `contourf` with GR backend.

### ISSUE THREAD

**Issue by jkbest2** [tbreloff/Plots.jl#485]
When plotting filled contours with the GR backend, I get a plot with a `jet` color map in the plot area, and an `inferno` colorbar. Specifying a different color map only changes the colorbar, not the plot area. This does not happen with the PyPlot backend:

```
using Plots
gr()
x = linspace(0, 1, 257)
y = linspace(0, 1, 257)
z = 2x'.^2 .+ 2y
contourf(z)
```
[gr_colors.pdf](https://github.com/tbreloff/Plots.jl/files/473720/gr_colors.pdf)
 
(Not sure why, but .png export via `savefig` or `png` wouldn't work for this figure, it just saved a blank file.)

Using the PyPlot backend on the other hand I get:

```
pyplot()
contourf(z)
```

![pyplot_colors](https://cloud.githubusercontent.com/assets/5840976/18534910/8e8b1574-7aa4-11e6-8ec1-914cf14d47a2.png)

**Comment by tbreloff** [comment]
Thanks I've seen this too and been meaning to open an issue

**Comment by tbreloff** [comment]
This should be fixed now
