### ISSUE TITLE
SVG, EPS export support

### ISSUE THREAD

**Issue by bluehope** [tbreloff/Plots.jl#49]
Thank you for great plot lib for the Julia!.
Bytheway currently it seems that "savefig" exports graph only in png format.
Is it possible to add "SVG" and/or "eps" export option? 

Gadfly PyPlot works great with SVG and EPS formats.
It would be great for Plots to support vector graphic formats.

**Comment by tbreloff** [comment]
Thanks :)
Yes I can support it, but only for backends that support it.  If you need the features in a hurry let me know, otherwise it might be a few days before I get to it.

**Comment by bluehope** [comment]
Currently I'm working on with Gadfly (as it seems to have fastest SVG export).
If it is possible within 1, 2 weeks? This will be just great.
I will gladly wait for your update.
Thank you in advance!

**Comment by tbreloff** [comment]
I started to make some notes for later, then just decided to work on this now.  Should be done within an hour, then it'll be available next time I push to master.

In the meantime, if there's ever anything you can do with gadfly (or others) that you can't currently do with Plots, you can access the underlying gadfly object directly.  (of course please still open issues so I know that someone wants a feature).

```
using Plots
gadfly()
plt = plot(rand(10))

gadfly_object = plt.o
Gadfly.draw(Gadfly.SVG(io, Compose.default_graphic_width, Compose.default_graphic_height), gadfly_object)
```

**Comment by tbreloff** [comment]
pdf, ps, and svg are supported for Gadfly/Immerse/PyPlot now on the dev branch.  I'll probably push to master sometime tonight.

**Comment by diegozea** [comment]
Would be great to add *TIFF* in the list (https://github.com/tbreloff/Plots.jl/issues/201).

**Comment by lobingera** [comment]
@diegozea; TIFF support - especially with all non-RGB colorspaces - has a large impact. Most people use today a vector format like pdf/svg and render with external tools. Do you have a good reference for a X-to-TIFF converter?

**Comment by tbreloff** [comment]
> Would be great to add TIFF in the list

I don't know enough about TIFF to comment... if anyone wants to submit a PR for this, I will gladly review it.  Just please don't add any required dependencies to make it work!

> has a large impact

Can you explain what you mean by this?  What does it impact?

**Comment by lobingera** [comment]
TIFF is (one of the more heavy) container format, so there are endless options what is/can be inside a TIFF. Different word lengths for color components, different color models (rgb vs. cmyk), previews, compression types etc.
So all TIFF solutions i know import a lenghty list of own dependencies.

**Comment by diegozea** [comment]
TIFF is often required by journals, i.e.:

> *"Prepare your figures at publication quality resolution, using applications capable of generating high-resolution .tif files (1200 d.p.i. for line drawings and 350 d.p.i. for colour and half-tone artwork)."* [Bioinformatics](http://www.oxfordjournals.org/our_journals/bioinformatics/for_authors/general.html)
> *"At the time of manuscript revision, we will request high quality figures in separate files (high-resolution .tif files: 1200 dots per inch for line drawings and 300 dots per inch for color and half-tone artwork). "[MBE](http://www.oxfordjournals.org/our_journals/molbev/general_author_guidelines.html#Figures)*

I usually use R's ggplot2 for publication plots, because the `ggsave` function allows to [export tiff files of determined resolution (dpi)](http://docs.ggplot2.org/current/ggsave.html). When *eps* is allowed, I export a *svg* from R/Julia and I save an *eps* using *Inkscape*.

**Comment by lobingera** [comment]
In the same way you could export to bitmap from Inkscape and convert the result to tiff.

**Comment by lobingera** [comment]
I just see general TIFF support as a rare use case of plotting. any-to-TIFF conversion could be a part of https://github.com/JuliaIO/ImageMagick.jl

**Comment by diegozea** [comment]
ImageMagick sounds like a good solution to export a TIFF of determined resolution:
 - https://gist.github.com/matsen/4263955
 - http://magick-users.imagemagick.narkive.com/vbeh6mFF/convert-svg-to-tiff-setting-resolution
But I don't know how ImageMagick.jl can be used in that way...

**Comment by tbreloff** [comment]
closing in favor of meta-issue
