### ISSUE TITLE
PyPlot "pixel" marker equivalent in Plots

### ISSUE THREAD

**Issue by lbenet** [tbreloff/Plots.jl#494]
First of all, very nice package.

My situation is the following: I have two *very large* column vectors (~1e6) which I'd like to plot as dots but of very small size. 

In PyPlot I would do something like: 
```julia
plot(x, y, ",")
``` 
which would use pixels as the marker (see [this](http://matplotlib.org/api/markers_api.html)). 

However, using `Plots` I run into troubles, due to the size of the vectors: `gr` and `plotly` backends become unresponsive after a while (ploytly renders the plot, but it is impossible to play with it), and pyplot displays too large dots. Using `markersize=0.1` is not enough.

EDIT: Sorry, pressed the wrong key...

**Comment by tbreloff** [comment]
On dev: 555145a

```julia
scatter(y, m=:pixel)
```

You might also want to try the glvisualize backend...

**Comment by lbenet** [comment]
Thanks!

**Comment by SimonDanisch** [comment]
Actually, GR shouldn't be much slower in such a simple scenario. I'd be delighted to benchmark your use case ;)
Also, GLVisualize has something like `:pixel` as well... Guess it's worth adding now!

**Comment by lbenet** [comment]
My case is extremely simple and naive, and on-purpose non-optimized (part of some lectures using Julia). The idea is to plot the bifurcation diagram of the quadratic family, with millions of points. I wanted to make zooms live, so I thought about `plotly` or `plotlyjs` backends. But it took ages, and I couldn't get the output I wanted. `gr` was the next option; it renders something but then there is a kernel error message. Also, there is a warning about skipping arg pixel.

I'm testing now GLVisualize now (on Julia 0.5.0) but there is some weird error:
```
WARNING: Skipped marker arg pixel
LoadError: UndefVarError: get_screens not defined
while loading In[6], in expression starting on line 1
...
```

**Comment by SimonDanisch** [comment]
That means you're not on GLVisualize + family master ;) I'm in the middle
of tagging these, but for now you still need to go through this hassle ;)
there is Plots.add_backend(:glvisualize) to help you checkout all the right
branches. Make sure that they actually check out! In my experience, Pkg
doesn't always succeed to fetch everything :( let me know how it goes, I'd
love to make sure that GLVisualize supports this use case;)

**Comment by lbenet** [comment]
It does work, beautifully and fast!! Thanks a lot for your help!

This is what I got with: `scatter(cc, ff, m=:pixel, ms=1)`

<img width="680" alt="screen shot 2016-09-20 at 8 14 10 pm" src="https://cloud.githubusercontent.com/assets/5237744/18694352/e2f71184-7f6e-11e6-8808-93f75f07c26d.png">

I have a suggestion (which actually carries over to pyplot backend): make the default size of `:pixel` the smallest possible.

**Comment by SimonDanisch** [comment]
Great! Yeah, I don't support `:pixel` yet, but when I do I will adapt the default size and use the OpenGL fast path for drawing single pixels, which should be even faster than what you have now ;)
