### ISSUE TITLE
aspect_ratio attribute with plotlyjs()

### ISSUE THREAD

**Issue by ghuba** [tbreloff/Plots.jl#503]
The following code fails:

```
using Plots
plotlyjs()
θ = linspace(0,2*pi,100)
plot(cos(θ), sin(θ), aspect_ratio=:equal)
```

The aspect ratio is not set to 1. The following code will work:

```
using Plots
pyplot()
θ = linspace(0,2*pi,100)
plot(cos(θ), sin(θ), aspect_ratio=:equal)
```

with pyplot().

**Comment by ghuba** [comment]
I realized that the doc mentions that it's not supported. So we can close this.

https://juliaplots.github.io/supported/

**Comment by ghuba** [comment]
Let me know if I can help with adding some of these options. I have no idea how difficult this is. If you think that's it's reasonably possible to make some contribution (i.e., without a massive learning curve to understand the project) I would be happy to help. It'd be nice to have Plots support more options for plotlyjs(). I like the syntax and power of Plots/plotlyjs(). I am sometimes using just PlotlyJS because the plots look great, but the syntax is inferior to Plots (logical and clean, but more verbose and opaque).

**Comment by tbreloff** [comment]
Supported now on f41a09b

**Comment by tbreloff** [comment]
```julia
using Plots; plotlyjs(); θ = linspace(0,2*pi,100); plot(cos(θ), sin(θ), aspect_ratio=:equal)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/19001281/799e6d7e-8714-11e6-8fe7-960e2bc13129.png)
