### ISSUE TITLE
scatter does not move labels?

### ISSUE THREAD

**Issue by anriseth** [tbreloff/Plots.jl#506]
I came over a case where `scatter` puts the labels box on top of a point, whilst plot is doing the "expected" thing and moving the box:
``` julia
x = 1:10
y = x.^2
scatter(x,y) # label box hides top right point
plot(x,y) # works as "expected"
```

On Julia 0.5

**Comment by tbreloff** [comment]
I assume this is the pyplot backend?  You can position it yourself: `legend = :bottomright`

**Comment by anriseth** [comment]
I'm using PyPlot, yeah. Is it not `Plots` that does the automatic positioning when you call a `:path` plot?

It's not much of an hassle to do manual legend positioning, so I'll just do that.
