### ISSUE TITLE
bar plots issues plotlyjs / pyplot

### ISSUE THREAD

**Issue by mkborregaard** [tbreloff/Plots.jl#507]
I am trying to do a barplot and experiencing some difficulties - some are questions, some appear to be be bugs. I am on Plots dev (behaviour is identical on 0.9.3). The issues were encountered in Jupyter.

1. The syntax for `DataFrames` (`j` in my example) as input data does not appear to work as described in the documentation.
2. The `rotation` argument for x axis tick labels seems to be interpreted differently by plotlyjs and pyplot.
3. Pplotlyjs does not rescale the plot window, so axis tick labels end up hidden.
4. plotlyjs does not respect the `color` argument for bar colors.
5. A question: pyplot crops the plot area to the edge of the data (i.e. the edges of the outermost bars) which does not work well aesthetically - is there a setting to request some spacing around the data in a sensible manner?

![skaermbillede 2016-09-28 kl 11 50 35](https://cloud.githubusercontent.com/assets/8429802/18909096/943ba9ec-8572-11e6-918f-d3065e900f9b.png)

**Comment by tbreloff** [comment]
Yeah lots of issues here.

> The syntax for DataFrames (j in my example) as input data does not appear to work as described in the documentation.

Are you using StatPlots?  That's where DataFrames stuff is defined.

> The rotation argument for x axis tick labels seems to be interpreted differently by plotlyjs and pyplot.

I see... which is more intuitive in your opinion?  They should match... gotta pick one

> plotlyjs does not rescale the plot window, so axis tick labels end up hidden.

This is an issue with every backend except PyPlot (which specifically calculates the extents of tick labels and guides).  I need to account for the actual tick labels when computing padding.  It's on my radar.

> plotlyjs does not respect the color argument for bar colors.

Yeah I've seen this... might need to add it to the meta issue

> A question: pyplot crops the plot area to the edge of the data (i.e. the edges of the outermost bars) which does not work well aesthetically - is there a setting to request some spacing around the data in a sensible manner?

Something I could add... right now I widen automatically is there's markers.  This should probably be made more flexible.


Some of these already exist as issues... the others should probably get their own issues for easier tracking.

**Comment by mkborregaard** [comment]
> Are you using StatPlots? That's where DataFrames stuff is defined.
Oh yeah, you have said so before. No I wasn't - it would be good to update the plot documentation to reflect this, under 'input data'.

> I see... which is more intuitive in your opinion? They should match... gotta pick one
The plotlyjs one, where positive 90 gets the labels to read bottom up. But that is just my opinion, both would work.

> I need to account for the actual tick labels when computing padding. It's on my radar.
Awesome - is there a way to do it manually - bottom_margin?

> might need to add it to the meta issue
def - it means a lot

> the others should probably get their own issues for easier tracking.
I am happy to open the issues - can you flag the ones that you know without checking have issues? I will go through the issues and add the missing ones

**Comment by tbreloff** [comment]
> is there a way to do it manually - bottom_margin?

Yes

> can you flag the ones that you know without checking have issues?

To be honest I don't know.  The backend specific issues I've been trying to add appropriate labels to, so you could start there.

**Comment by tbreloff** [comment]
Going to close this as I think this is covered by other issues
