### ISSUE TITLE
Reusing function names keeps potting "old" function

### ISSUE THREAD

**Issue by denglerchr** [tbreloff/Plots.jl#508]
`t = linspace(0, 10, 100)
f(x) = x
plot(t, f); gui()
print("Press Enter for 2nd plot"); readline()
#now i want a quadratic plot
f(x) = x^2
plot(t, f); gui()`

Hello, i keep having troubles when redefining functions and plotting them. The plot function does not seem to realise the redefinition and keeps plotting the "old" function. E.g. in the example above, the linear function is plotted twice, instead of the quadratic plot. I'm using Julia 0.5.0 and Plots 0.9.3

**Comment by denglerchr** [comment]
Oh boy, my code got destroyed, here again safe mode for better copy paste:

t = linspace(0, 10, 100)
f(x) = x
plot(t, f); gui()
print("Press Enter for 2nd plot"); readline()

#
f(x) = x^2
plot(t, f); gui()

**Comment by KristofferC** [comment]
This is not Plots.jls fault:

https://github.com/JuliaLang/julia/issues/18076
https://github.com/JuliaLang/julia/issues/265

etc. For some reason this got worse on 0.5.

**Comment by tbreloff** [comment]
Yeah that's weird... I can reproduce.  Note that if you don't do that first plot command then the second plot works.  Glad to hear it's not my fault :)

**Comment by ChrisRackauckas** [comment]
Yeah, it's a Base thing:

JuliaLang/julia#16965
JuliaLang/julia#15602

It's because of how they changed function compilation in v0.5. The easy answer is, if you want to overwrite `f`, just make it an anonymous function.

```julia
f = (x) -> x^2
```

Then you can overwrite it without worry.
