### ISSUE TITLE
tick-mark labels only displaying for subplots 1:7

### ISSUE THREAD

**Issue by cjprybol** [tbreloff/Plots.jl#509]
I've run into speed bottlenecks using PyPlot (Python convert), and giving Plots a test drive and really enjoying it! Thanks to everyone for their work on this package thus far.

Here's a Jupyter notebook that shows the behavior I'm interested in:
https://gist.github.com/cjprybol/8fef3954497ae76a7077125689103154

When there are <= 7 subplots, there are labels on all of the tick-marks on both axes, yet for 7 or more subplots, the tick-mark labels always only show for plots 1:7

Any ideas what may be going on here, or if it's a problem with my code that I'm missing? I adjusted the size of the plots and that did not have any effect.

I've observed this behavior with the current release and the master branch, on Julia 0.6

Thanks!

**Comment by tbreloff** [comment]
Weird! No idea what's happening, but I will say that I haven't moved past 0.5 yet.  Did you try with 0.5?

**Comment by KristofferC** [comment]
Is it the same for other backends?

**Comment by cjprybol** [comment]
Just tried with 0.5, and it produced the same output with the GR backend. Interestingly, using the pyplot backend crashes the kernel when trying to plot more than 7 subplots on both Julia 0.5 and 0.6.

Here's the exception/crash trace that was generated
https://gist.github.com/cjprybol/429ff18eaf944301cd4832d731864235

Seems like it could be an error that throws an exception, and GR handles it by just not putting axes labels, but pyplot responds with a full crash

**Comment by tbreloff** [comment]
I just ran:

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1-pre+2 (2016-09-20 03:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f0d40ec (8 days old release-0.5)
|__/                   |  x86_64-linux-gnu

julia> using Plots; gr()
INFO: Recompiling stale cache file /home/tom/.julia/lib/v0.5/GR.ji for module GR.
Plots.GRBackend()

julia> plot_list = []
0-element Array{Any,1}

julia> for i in 1:20
           push!(plot_list, plot(1:10, rand(10), legend=false))
       end

julia> plot_list
20-element Array{Any,1}:
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}
 Plot{Plots.GRBackend() n=1}

julia> plot(plot_list[1:10]...)

julia> plot(plot_list[1:7]...)

julia> plot(plot_list[1:15]...)

julia> plot(plot_list[1:15]..., leg=false)

julia> plot(plot_list[1:15]..., leg=true)

julia> plot(plot_list..., leg=false)

julia> plot(plot_list..., leg=false)

julia> plot(plot_list..., leg=false)

julia> plot(plot_list..., leg=false)

julia> plot(plot_list[1:4]..., leg=false)

julia> plot(plot_list[1:14]..., leg=false)

julia> 
```

and it all worked fine.  Maybe it's IJulia-specific?  I'll try.

**Comment by cjprybol** [comment]
Those tests worked for me from the REPL as well, so I'll keep moving forward using the REPL for the time-being! Thanks!

Given the tests work from the REPL, it does seem like an IJulia or Jupyter specific problem. Any recommendations for how to generate a more verbose trace back on this? Or does Plots invoke a different rendering framework when run via IJulia than it does when invoked from the REPL? The GR backend didn't produce any error output, and I don't imagine the system-level traceback I put in that gist will be super helpful for the debugging. Given the crash was caught and reported at the operating system level (and crashed the kernel), it sounds pretty low-level. I'll reboot and see if it's just an unlucky bug specific to my setup.

If you have any ideas on traceback and we can narrow down to something more specific, I'd be happy to close this issue here and move the discussion to the appropriate location.

**Comment by tbreloff** [comment]
I just tried this in IJulia, and I can reproduce.  Super weird!

**Comment by tbreloff** [comment]
Seems to work fine with pyplot...

**Comment by tbreloff** [comment]
Ok so this is something when GR produces the svg.  It works fine when the output format is png:

![tmp](https://cloud.githubusercontent.com/assets/933338/19201480/0265fbcc-8c9c-11e6-832a-9bb6f5122911.png)

but if I leave out that `fmt=:png` (so that it produces svg), then it has the strange behavior above.

cc: @jheinen 

(Aside... is it possible the pyplot crash was just because of trying multiple backends in the same session and the graphics libraries clashing??  Let me know if you can reproduce that problem)

**Comment by jheinen** [comment]
@tbreloff : Works fine on my Mac, both ``pyplot()`` and ``gr()`` - no crashes. Unfortunately, I get the same result (missing axes labels) for ``gr()`` + SVG. There is probably a bug in my SVG driver.

**Comment by tbreloff** [comment]
I didn't get any crashes either... Just the missing axes.

**Comment by cjprybol** [comment]
Still getting the pyplot crashing, but that sounds like that's only a problem on my end. I'll reinstall my anaconda distribution and see if that fixes it

**Comment by tbreloff** [comment]
@cjprybol does pyplot crash in the REPL?

**Comment by cjprybol** [comment]
I don't recall, but after a clean reinstall pyplot is working great from the REPL and notebook! I think it was just a problem of carrying that anaconda installation over through multiple OS updates. Strange coincidence that it failed on the same plot in that example, but doesn't seem to be anything more than that

**Comment by jheinen** [comment]
@tbreloff : The SVG bug is fixed (https://github.com/jheinen/gr/commit/6ec7b6add05fde124c512e2985ec2204a0f87ac2)

**Comment by tbreloff** [comment]
Great!
