### ISSUE TITLE
plotly and gr do not resize window when tick labels are long

### ISSUE THREAD

**Issue by mkborregaard** [tbreloff/Plots.jl#514]
See example here
![skaermbillede 2016-09-28 kl 11 50 35](https://cloud.githubusercontent.com/assets/8429802/18990512/b352a794-8712-11e6-8b92-fb8fcefb9562.png)

**Comment by tbreloff** [comment]
Almost done

![tmp](https://cloud.githubusercontent.com/assets/933338/18999364/349235b6-870b-11e6-8033-3cec596348d4.png)

**Comment by mkborregaard** [comment]
Fantastic!
