### ISSUE TITLE
plotly and pyplot interprets rotation argument differently for x axis labels

### ISSUE THREAD

**Issue by mkborregaard** [tbreloff/Plots.jl#515]
rotation = -90 in plotly is equivalent to rotation = 90 in pyplot. I think the plotly one is more intuitive.

**Comment by mkborregaard** [comment]
gr() ignores rotation alltogether.

**Comment by tbreloff** [comment]
pyplot, plotly, and gr all rotate the same now (positive angle rotates counter-clockwise).  i know this is backwards for what you expect, but at least it's consistent.  :)  i guess you can never take the matplotlib out of me...

**Comment by mkborregaard** [comment]
Awesome! And 'positive angle rotates counter-clockwise' was exactly what I had hoped for :-)
