### ISSUE TITLE
Add option for colour bar

### ISSUE THREAD

**Issue by dpsanders** [tbreloff/Plots.jl#52]
It would be great to add an option for adding a colour bar to a plot; see e.g. this request:

http://stackoverflow.com/questions/33286085/how-to-plot-imagesc-style-heatmap-with-colorbar-in-julia/33304495#33304495

**Comment by dpsanders** [comment]
Great work by the way, @tbreloff !

**Comment by tbreloff** [comment]
This might be done already, assuming you want something like these:

![tmp](https://cloud.githubusercontent.com/assets/933338/10695373/5c246cbe-7971-11e5-900f-950c34570e59.png)

**Comment by tbreloff** [comment]
But your title reminds me that I need to add "colour" aliases for all the "color" arguments :)

**Comment by dpsanders** [comment]
That's great! What determines the height of the colour bar? And yes, "colour" aliases please ;)

**Comment by dpsanders** [comment]
In the default `PyPlot` backend, the heatmap appeared without a colour bar.

I then did `gadfly()`, but it didn't realise that Gadfly wasn't installed.

**Comment by dpsanders** [comment]
The colour bar doesn't appear in your PyPlot heatmap example either.
In PyPlot you do  `colorbar()` to add one.

How can you set the x and y ranges?

**Comment by tbreloff** [comment]
I went to add a PyPlot colorbar, but I don't think that's the right function for a `PyPlot.hexbin`... any idea the right method/arg?  If you give me a small pyplot example I can add it.

> What determines the height of the colour bar?

Gadfly does the layout.  I have intentions of creating a new Gadfly legend that is more flexible, but honestly there's a lot of other things that take priority right now.

> I then did gadfly(), but it didn't realise that Gadfly wasn't installed.

Can you copy/paste the command sequence?  If this is a bug I don't quite understand what happened.

> How can you set the x and y ranges?

Hopefully this answers it:

![tmp](https://cloud.githubusercontent.com/assets/933338/10698518/6e9285d0-797f-11e5-9095-1e0a373ae8f1.png)

Keep in mind that `heatmap` just maps to `plot(args...; kw..., linetype = :heatmap)`, so the arguments are for any kind of plot.

**Comment by tbreloff** [comment]
Nevermind... I figured it out.  Here's a couple slightly more complicated examples to show it:

![tmp](https://cloud.githubusercontent.com/assets/933338/10700082/6322c584-7989-11e5-90e0-ae9ffab8e01d.png)

Also FYI... it's been a while since I tagged a new version... I would do `Pkg.checkout("Plots")` if you haven't already.  

I'll push these changes up to master soon.

**Comment by dpsanders** [comment]
Really nice, thanks!
