### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by montyvesselinov** [tbreloff/Plots.jl#523]
https://juliaplots.github.io/examples/plotlyjs/#heatmap-categorical-axes-and-aspect_ratio

it it possible to impose the pixels to be squares?

BTW, The test example does not work.

`z = float((1:4) * 1:10')` fails.

**Comment by tbreloff** [comment]
> The test example does not work.

Precedence of `:` must have changed... wrap the `(1:10)` in parens.

> it it possible to impose the pixels to be squares?

Yup.  Check out Plots just to be sure.

```julia
using Plots; plotlyjs()
xs = [string("x",i) for i = 1:10]
ys = [string("y",i) for i = 1:4]
z = float((1:4) * (1:10)')
heatmap(xs,ys,z,aspect_ratio=10/4)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/19161900/9f78e994-8bc3-11e6-89b9-859334931f8b.png)

I should fix/regenerate the examples sometime soon...

**Comment by tbreloff** [comment]
FYI... I'm fixing this in Plotly, and changing the docs description of aspect_ratio to be:

```
Symbol (:equal) or Number. Plot area is resized so that 1 y-unit is the same size as `apect_ratio` x-units.
```
