### ISSUE TITLE
Subplots on a map

### ISSUE THREAD

**Issue by montyvesselinov** [tbreloff/Plots.jl#524]
I would like to be able to make a plot where i place subplots (scatter plots and heatmaps) overlaid over a base map. The location of the subplots should be at predefined x, y locations.

I believe in pyplot this is done using `PyPlot.annotate`.

Is it possible to do this with Plots.jl? I would prefer to use plotly.js backend if possible.

**Comment by tbreloff** [comment]
Yes, but currently it will take a tiny amount of leg work.  See the end of the [layouts page](https://juliaplots.github.io/layouts/) of the docs:

```julia
# Add sticks floating in the window (inset relative to the window, as opposed to being relative to a subplot)
sticks!(randn(100), inset = bbox(0,-0.2,200px,100px,:center), ticks=nothing, subplot=4)
```

When you pass the return of `bbox` directly to `inset`, it will use the full canvas as reference.  Then you can use percentages between [0,1] to define the position.

Also... questions like this are more appropriate for the [gitter chat](https://gitter.im/tbreloff/Plots.jl)
