### ISSUE TITLE
Not all arguments mapped when joining plots

### ISSUE THREAD

**Issue by joshday** [tbreloff/Plots.jl#526]
Found on dev and master with both pyplot and gr.  The `ylim` argument gets sent to both subplots, but not `w` for line width.  I've found at least `w` and `fillalpha` do not work this way.  There's the obvious workaround of giving the arguments to the individual plots being joined, but this would save a couple lines of code.

```julia
julia> using Plots; pyplot()

julia> p1 = plot(rand(5)); p2 = plot(rand(5))

julia> plot(p1, p2, w = 6, ylim = (-1, 1))
```

<img width="599" alt="screen shot 2016-10-08 at 3 25 45 pm" src="https://cloud.githubusercontent.com/assets/8075494/19215424/80be883e-8d6b-11e6-9be8-352f9f20a66b.png">

**Comment by tbreloff** [comment]
implemented... nice catch
