### ISSUE TITLE
[DataFrames] Doc example not working

### ISSUE THREAD

**Issue by nico202** [tbreloff/Plots.jl#528]
julia version: `Version 0.4.6 (2016-06-19 17:16 UTC)`

```
julia> using DataFrames, Plots; pyplot()
Plots.PyPlotBackend()
using RDatasets; iris = dataset("datasets", "iris");
julia> scatter(iris, :SepalLength, :SepalWidth,
               title = "My awesome plot", xlabel = "Length", ylabel = "Width",
               m=(0.5, [:+ :h :star7], 12), bg=RGB(.2,.2,.2))
[Plots.jl] Initializing backend: pyplot
ERROR: In convertToAnyVector, could not handle the argument types: (DataFrames.DataFrame,)
 in error at ./error.jl:21
 [inlined code] from /home/nixo/Scm/Git/JsB/.julia_pkgs/v0.4/Plots/src/series.jl:111
 in apply_recipe at /home/nixo/Scm/Git/JsB/.julia_pkgs/v0.4/RecipesBase/src/RecipesBase.jl:238
 in _process_userrecipes at /home/nixo/Scm/Git/JsB/.julia_pkgs/v0.4/Plots/src/pipeline.jl:73
```
I am not able to use dataframes with your package, am I doing something wrong?

Thanks, Nicolò

**Comment by tbreloff** [comment]
Yes. DataFrames support has been moved to StatPlots (the docs should say
that... Please let me know if it's not clear). Also you should switch to
julia 0.5... Its so much better.

**Comment by nico202** [comment]
Ok, adding `using StatPlots` works.

However, here is not clear: https://juliaplots.github.io/input_data/#dataframes-support

Thanks for your help :)

**Comment by tbreloff** [comment]
Thanks I need to update that

**Comment by tbreloff** [comment]
updating the docs...

```julia
using StatPlots, RDatasets
iris = dataset("datasets", "iris")
scatter(iris, :SepalLength, :SepalWidth, group=:Species,
        m=(0.5, [:+ :h :star7], 12), bg=RGB(.2,.2,.2))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/19221014/9bb6ad18-8e08-11e6-9030-9037352e3119.png)

**Comment by tbreloff** [comment]
That page is updated, also including the Images update from Chris.

**Comment by sspaenig** [comment]
Hi,
Where can I find the current docs? https://juliaplots.github.io/examples/plotlyjs/#dataframes seems to be still outdated...
Kind regards.
