### ISSUE TITLE
Improve doc/errors for DataFrame

### ISSUE THREAD

**Issue by dourouc05** [tbreloff/Plots.jl#531]
I recently tested some of my older code on new Plots.jl (it worked perfectly with Plots.jl 0.5, if my REQUIRE file is to be believed, which is now a bit dated), and I was surprised it did not work at all. With Julia 0.4.6, I got the following error messages when using `plot!` with data frames: 

```
ERROR: MethodError: `extractGroupArgs` has no method matching extractGroupArgs(::Symbol, ::DataFrames.DataFrame, ::Symbol, ::Symbol)
Closest candidates are:
  extractGroupArgs(::AbstractArray{T,1}, ::Any...)
  extractGroupArgs{T,V<:AbstractArray{Int64,1}}(::Dict{T,V<:AbstractArray{Int64,1}}, ::Any...)
 in _preprocess_args at C:\Users\Thibaut\.julia\v0.4\Plots\src\pipeline.jl:29
 in _process_userrecipes at C:\Users\Thibaut\.julia\v0.4\Plots\src\pipeline.jl:60
 in _plot! at C:\Users\Thibaut\.julia\v0.4\Plots\src\plot.jl:157
```

After looking through the documentation, I happened to find three interesting words on https://juliaplots.github.io/basics/: 

```jl
plot(dataset("Ecdat", "Airline"), :Cost)  # the :Cost column from a DataFrame... must import StatPlots
#                                                                                ^^^^^^^^^^^^^^^^^^^^^
```

With importing this package, the code now works much better (and even as it should, which was not exactly expected). 

Would it be possible to add a much better error message for this case? And a bit more than a comment in the documentation, maybe a proper note for this? 

(I can submit a PR for the doc update, but I'm unsure about how to deal with the error message without importing the DataFrame package, i.e. adding a hard dependency on it. However, it seems the error is thrown at a later stage, not with the call to `plot!`, so there is surely a way to deal with it inside Plots.jl.)

**Comment by tbreloff** [comment]
> Would it be possible to add a much better error message for this case?

No.  Plots doesn't know anything about DataFrames, so how could it possibly do something special for DataFrames?  `isa(x, DataFrame)` would error.

> And a bit more than a comment in the documentation, maybe a proper note for this?

I did a search and StatPlots is referenced 13 times in the docs, including:
https://juliaplots.github.io/input_data/#dataframes-support

**Comment by mmagnuski** [comment]
Testing for `string(typeof(x)) == "DataFrames.DataFrame"` is still possible though.

**Comment by tbreloff** [comment]
Fair enough.  But it's about time people realize that DataFrames are not some special built-in thing like in R.  The goal of Plots is that you can plot **anything**, not just DataFrames like in ggplot2.  Checking for types by their string is incredibly fragile and tedious, and not something I'm interested in considering the many different types one may wish to pass to the plot method.

**Comment by mmagnuski** [comment]
Yeah, I agree. However, the possibility of plotting only types that have at least two "a"s in their name is tempting. ;)

**Comment by dourouc05** [comment]
This test would only be consistent with what you do at https://github.com/tbreloff/Plots.jl/blob/04a435768477d6f6fd7063937299dc94d83ded0d/src/args.jl#L723: help your users to upgrade from a version to another when you introduce breaking changes. That's why no one so far has proposed to add this kind of tests for other types… 

As for the docs: it's not because something is cited 13 times that users can find it. You'd expect some easy to find documentation for breaking changes (not just the NEWS file, which all packages do not have… and few users have a look at due to the large number of packages that get updated), for example on a page like https://juliaplots.github.io/plots_v0.7/.

**Comment by tbreloff** [comment]
Fine.  You win:

```julia
julia> scatter(iris, :SepalLength, :SepalWidth, group=:Species,
               title = "My awesome plot",
               xlabel = "Length", ylabel = "Width",
               m=(0.5, [:cross :hex :star7], 12),
               bg=RGB(.2,.2,.2))
WARNING: You're trying to plot a DataFrame, but this functionality is provided by StatPlots
ERROR: MethodError: no method matching extractGroupArgs(::Symbol, ::DataFrames.DataFrame, ::Symbol, ::Symbol)
Closest candidates are:
  extractGroupArgs(::AbstractArray{T,1}, ::Any...) at /home/tom/.julia/v0.5/Plots/src/args.jl:743
  extractGroupArgs{T,V<:AbstractArray{Int64,1}}(::Dict{T,V<:AbstractArray{Int64,1}}, ::Any...) at /home/tom/.julia/v0.5/Plots/src/args.jl:755
 in _preprocess_args(::Dict{Symbol,Any}, ::Tuple{DataFrames.DataFrame,Symbol,Symbol}, ::Array{RecipesBase.RecipeData,1}) at /home/tom/.julia/v0.5/Plots/src/pipeline.jl:29
 in _process_userrecipes(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{DataFrames.DataFrame,Symbol,Symbol}) at /home/tom/.julia/v0.5/Plots/src/pipeline.jl:60
 in _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{DataFrames.DataFrame,Symbol,Symbol}) at /home/tom/.julia/v0.5/Plots/src/plot.jl:173
 in #plot#246(::Array{Any,1}, ::Function, ::DataFrames.DataFrame, ::Vararg{Any,N}) at /home/tom/.julia/v0.5/Plots/src/plot.jl:52
 in (::Plots.#kw##plot)(::Array{Any,1}, ::Plots.#plot, ::DataFrames.DataFrame, ::Symbol, ::Vararg{Symbol,N}) at ./<missing>:0
 in #scatter#329(::Array{Any,1}, ::Function, ::DataFrames.DataFrame, ::Vararg{Any,N}) at /home/tom/.julia/v0.5/Plots/src/Plots.jl:146
 in (::Plots.#kw##scatter)(::Array{Any,1}, ::Plots.#scatter, ::DataFrames.DataFrame, ::Vararg{Any,N}) at ./<missing>:0
```

**Comment by dourouc05** [comment]
Great, thanks!
