### ISSUE TITLE
Colour palettes

### ISSUE THREAD

**Issue by alancrawford** [tbreloff/Plots.jl#538]
I was wondering if there is a list of colour palettes supported by Plots? In particular, I am looking for a colour palette whose base colour is white to use in a filled contour plot. Or would i need to create one?

**Comment by tbreloff** [comment]
Assuming you mean "colormaps" or "color gradients" (in Plots, the "color palette" is the list of colors from which you automatically choose series colors).

See this: https://github.com/JuliaPlots/PlotUtils.jl/issues/2

**Comment by alancrawford** [comment]
Great thanks - just what i was looking for.
