### ISSUE TITLE
Labels not set properly with PlotlyJS

### ISSUE THREAD

**Issue by jebej** [tbreloff/Plots.jl#540]
It appears that labels are not passed properly when using the PlotlyJS backend, I just get `trace 0` and `trace 1` instead of the desired labels. This works properly with the GR backend.

![newplot](https://cloud.githubusercontent.com/assets/11141558/19493097/5281e91e-9547-11e6-9dc5-5c1bd0bb8711.png)

**Comment by tbreloff** [comment]
It helps if you include code I can copy and paste

**Comment by jebej** [comment]
Sorry about that, any example seems to exhibit the problem:
```julia
using Plots
plotlyjs()
plot(sin,0:0.1:π,lab=["notshown"])
```

**Comment by tbreloff** [comment]
Don't wrap it in brackets

**Comment by tbreloff** [comment]
Also this works: `plot([sin, cos],0:0.1:π,lab=["sin" "cos"])`

And it works because it's a 1x2 matrix (a row vector) and gets sliced up one value per series

**Comment by jebej** [comment]
Thanks, sorry about the noise.

**Comment by jebej** [comment]
Note that this does works with gr(): `plot([sin,cos], 0:0.1:π,lab=["AIN0","AIN1"])`

**Comment by tbreloff** [comment]
Ha... it shouldn't!  Believe it or not that's a bug

**Comment by olegshtch** [comment]
Found this bug while trying to fill a new one. Currently documentation says: 
```
label | AUTO | lab, labels | String type | The label for a series, which appears in a legend.  If empty, no legend entry is added.
```
Should correct type of this attribute mentioned here?
