### ISSUE TITLE
Missing colorschemes in heatmap plot

### ISSUE THREAD

**Issue by juliohm** [tbreloff/Plots.jl#542]
I couldn't find an example in the docs nor an issue mentioning this function, how can we get access to imshow() from PyPlot to visualize large 2D matrices?

**Comment by tbreloff** [comment]
heatmap?  If they are really large you shouldn't use pyplot.

**Comment by juliohm** [comment]
@tbreloff I am actually talking about matrices that represent images. They have 400x400 pixels for example.

**Comment by tbreloff** [comment]
What is the precise type that you want to display?  (show me the output of `typeof(mat)`)

**Comment by juliohm** [comment]
The type is `Array{Float64,2}`, nothing fancy.

**Comment by tbreloff** [comment]
so then: `heatmap(mat, yflip=true)`

**Comment by juliohm** [comment]
I don't know why it didn't work before! I was probably doing something wrong somewhere else in the code. Closing the issue :+1:

**Comment by juliohm** [comment]
How to change the colormap? I tried passing the option `cmap`, `colormap`, `cm`, none worked.

Where in the source I can find information on these keyword arguments that are valid across functions?

**Comment by tbreloff** [comment]
`fillcolor` or `fc`, or also `seriescolor`, `color`, `c` should do it.  See the attributes page of the docs

**Comment by juliohm** [comment]
I tried `color=:jet` but it didn't work. Where I can find a list of all these symbols?

**Comment by tbreloff** [comment]
```
julia> PlotUtils._gradients |> keys |> showall
Symbol[:phase,:lightrainbow,:ice,:curl,:matter,:speed,:turbid,:sand_grad,:tempo,:solarized_light_grad,:gray,:reds,:blues,:redsblues,:darkrainbow,:viridis,:algae,:greens,:balance,:solar,:solarized_grad,:dark_grad,:haline,:oxy,:plasma,:deep,:heat,:magma,:inferno,:rainbow,:orange_grad,:bluesreds,:amp,:dense,:darktest,:lime_grad,:grays,:thermal,:delta,:lighttest]
```

**Comment by juliohm** [comment]
Thanks! So, the standard `jet` is not available currently?

**Comment by tbreloff** [comment]
jet kinda sucks... you should try something else :)

**Comment by juliohm** [comment]
Well, `jet` is kind of very famous, no harm in include it to the list :)

**Comment by KristofferC** [comment]
It is harmful since it is so bad.

**Comment by juliohm** [comment]
Why is it so bad? Do you have links?

**Comment by tbreloff** [comment]
https://github.com/matplotlib/matplotlib/issues/875

**Comment by juliohm** [comment]
My eyes are not that sensitive, but if experts are saying `jet` is harmful, I accept it.

**Comment by juliohm** [comment]
I tried the `:ice` color listed above and it is also not recognized. Could you please update the docs and the code to translate the supported colorschemes? Many users like myself will open issues about it.

**Comment by juliohm** [comment]
Could you please help on this issue? I am gradually moving to Plots.jl, but there are still some corners I need to round for my day-to-day usage.

**Comment by tbreloff** [comment]
I'm sorry... I don't see anything actionable (besides a request for more docs?)  What do you need help with?  The [gitter channel](https://gitter.im/tbreloff/Plots.jl) is good for getting help when learning (as opposed to reporting a bug in the issues).

**Comment by juliohm** [comment]
Hi Tom, the `:ice` color scheme is not working for me even though it is listed above. I will double check again today the script to see if it was something else.

**Comment by tbreloff** [comment]
This works for me: `using Plots; heatmap(rand(100,100),c=:ice)`

You might need to check out Plots/PlotUtils.  I'll tag a new version in a couple months

**Comment by juliohm** [comment]
Hi Tom, the :ice color scheme is not working for me even though it is
listed above.

-Júlio

**Comment by tbreloff** [comment]
`Pkg.checkout("Plots"); Pkg.checkout("PlotUtils")` should work for you.

**Comment by ttparker** [comment]
@tbreloff your command `PlotUtils._gradients |> keys |> showall` didn't work for me. I might be worth adding the list of gradient schemes to the documentation.

**Comment by juliohm** [comment]
See https://discourse.julialang.org/t/current-list-of-colorschemes-in-plots-jl/5420

**Comment by mkborregaard** [comment]
You could also actually check the documentation: http://docs.juliaplots.org/latest/colors/ :joy:

**Comment by ttparker** [comment]
@mkborregaard I did - by searching for several of the color scheme names using the documentation's built-in search function. This got no results, because the names are listed in an image file :-)

**Comment by mkborregaard** [comment]
I see, good point. It would be nice with a revision of that page that changed the display of each gradient to a narrow rectangle with a markdown title.
