### ISSUE TITLE
Media not found in Juno

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#543]
This is with Juno on both v0.5 and v0.6, dev version of Juno. @pfitzseb

``` julia
LoadError: InitError: UndefVarError: Media not defined
 in media(::Type{T}, ::Type{T}) at C:\Users\Chris\.julia\v0.5\Media\src\system.jl:72
 in setup_atom() at C:\Users\Chris\.julia\v0.5\Plots\src\output.jl:257
 in __init__() at C:\Users\Chris\.julia\v0.5\Plots\src\Plots.jl:239
 in _include_from_serialized(::String) at .\loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:217
 in require(::Symbol) at .\loading.jl:371
 in include_from_node1(::String) at .\loading.jl:488
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:415
 in include_string(::String, ::String) at .\loading.jl:441
 in eval(::Module, ::Any) at .\boot.jl:234
 in (::Atom.##60#63)() at C:\Users\Chris\.julia\v0.5\Atom\src\eval.jl:39
 in withpath(::Atom.##60#63, ::Void) at C:\Users\Chris\.julia\v0.5\CodeTools\src\utils.jl:30
 in withpath(::Function, ::Void) at...
```

**Comment by ChrisRackauckas** [comment]
It doesn't copy paste the whole error:

![junosnip](https://cloud.githubusercontent.com/assets/1814174/19538764/828f66a4-960a-11e6-83cc-66f6a5794747.PNG)

**Comment by pfitzseb** [comment]
This is the same as #534, I think. Aaaand I'm somewhat confused as to why this happens -- might be related to precompilation (at least I couldn't reproduce this without, and 
```julia
module TestingStuff
import Media
__init__() = Media.media(Int, Media.Plot)
end

using TestingStuff
```
works for me). I'll look into it tomorrow...

**Comment by ChrisRackauckas** [comment]
Actually I have an update. It only happens to me when loading Plots through DifferentialEquations. This seems like a precompilation issue (for the record, DifferentialEquations has a true dependency and not a conditional dependency on Plots, so that makes this even more ???)

**Comment by ChrisRackauckas** [comment]
It errors in here:

```julia
function setup_atom()
    if isatom()
      println("here")
        @eval import Atom, Media
        Media.media(Plot, Media.Plot)

        # default text/plain so it doesn't complain
        function Base.show{B}(io::IO, ::MIME"text/plain", plt::Plot{B})
            print(io, "Plot{$B}()")
        end
        println("to here")
```

Only prints "here". For some reason it doesn't pull in Media. Is @eval happening in the wrong module?

**Comment by pfitzseb** [comment]
The problem is that even
```julia
__precompile__()

module Plots

using Juno, Media, Hiccup

type Plot end

function __init__()
    Media.media(Plot, Media.Plot)
end

end # module
```
fails when trying to do `using Plots` inside of a module. That seems somewhat strange, as, per the [docs](http://docs.julialang.org/en/latest/manual/modules/#module-initialization-and-precompilation):
> __init__ is only called once, and only after all statements in the module have been executed

**Comment by tbreloff** [comment]
Good to know it's not specific to Plots.
