### ISSUE TITLE
Issues when trying to plot Distributions(.jl)

### ISSUE THREAD

**Issue by AdrianSchurz** [tbreloff/Plots.jl#547]
Greatings,

good work so far. I fiddled with this package and Atom/Juno (64bit, up to date, arch linux) a bit and am enjoying it. Trying out the distributions package I ran into a few issues, though.

I will provide examples from the julia command line/REPL for the moment to cut out the middle man.

So, I fire up a julia instance and try to plot a neat little sequence of distributions like so
```
using Plots, Distributions
unicodeplots()

sigmas = collect(0.1:0.2:0.7)
mus = map(x->0, sigmas) #excuse the laziness
aFewDistributions = map(Normal, mus, sigmas)
```
Plotting a Distribution directly understandably fails as I cannot expect you to handle any type some pleb throws at you. So I go get me some functions supplying the value of the distribution function with something like
```
pdfFromDist(dist) = x -> pdf(dist, x)
aFewPdfs = map(pdfFromDist, aFewDistributions)
```
at which point I feel confident to bother the plot function
```
plot(aFewPdfs[1], -2, 2)
```
and , alas, it werks, even for the other array indexes. However,
```
plot([aFewPdfs[1], aFewPdfs[2]], -2, 2)
```
fails with
```
ERROR: ArgumentError: reducing over an empty collection is not allowed
 in mr_empty(::Function, ::Function, ::Type{T}) at ./reduce.jl:128
 in mapfoldl(::Base.#identity, ::Function, ::Base.Generator{Array{String,1},Base.#length}) at ./reduce.jl:60 bladiblubb
```

Clumsily, I tried with a transposed function array in case they were somehow the wrong way around, to no avail.

I am only moderately confident I did not commit a stupid error somewhere because I find investigating such things in julia a royal pain in the ass because I cannot find a clean way to clear defined variables when running the content of a file in atom/juno. How the fuck am I supposed to deal with 5 different obscure errors when running the same code 5 times in a row without a good way to return programmatically to a known state before or after each run of a script. Makes me wanna punch a kitty more often than my supply of fresh kitties permits.

During these adventures in Atom/Juno I encountered, sometimes, being able to plot a Distribution object (but not 2) directly, segfaults, empty plots with (unasked for) log scales and tick labels like "object[1]", changing behaviour based on what function definition idiom is used,  and more but these I cannot reproduce in a reasonable amount of time because julia. But more on them later, should they persist after this issue.

So the question for the moment is: Is this error an issue, a mistake of mine, or both?

Thanks in advance,

Adrian

**Comment by AdrianSchurz** [comment]
little update: the aforementioned "empty plot" happens when using Atom/Juno/Plotlyjs backend and forgetting a comma in the input array and not providing a range like so
```
using Plots, Distributions
plotlyjs()
plot([Normal() Normal()])
```
the plot does not show a point but rather has a log scaled x axis, a linearily scaled y axis having only one tick labelled "object]" with everthing left of that string being cut off by the end of the plot. Hovering the mouse over where the point should be shows the tooltip labels "[object Object]". It might be deserving of a check/error message if the plot gets fed random unintelligible objects by inept users :]

**Comment by AdrianSchurz** [comment]
After fiddling a bit more and reading the docs again I think I discovered my mistake. Instead of passing an array of functions as I would arrays of Xs and Ys I need to add the functions separately with plot!() instead plot(), in the above example amounting to something like
`map(f->plot!(f, -2, 2), aFewPdfs)`

Are there specific reasons to disallow my first approach passing an array of functions? If not I would probably file a gentle feature request at some point.

Anyhow, I am closing this one.
Unless I forget it I will open a separate issue for the thing described in the second comment.

Cheers

**Comment by tbreloff** [comment]
Check out StatPlots, and read through the docs on input types.

**Comment by AdrianSchurz** [comment]
> Check out StatPlots

Works like a charm so far, thanks.
