### ISSUE TITLE
Displaying gifs in Jupyter notebooks

### ISSUE THREAD

**Issue by juliohm** [tbreloff/Plots.jl#550]
If we follow the example:

``` julia
@gif for i=1:10
heatmap(rand(10,10))
end
```

in a Jupyter cell, the latest iteration is displayed (i=10) and below the gif is shown. Could you please fix the macro so that it only shows the gif?

Also, it looks like the `@animate` macro followed by `gif(anim, "/tmp/foo.gif")` saves the gif in the specified directory but isn't able to show it in the Jupyter cell. It shows as a missing image.

As a side question, I don't know how I can control the frames per second in the `@gif` macro, is it possible?

**Comment by juliohm** [comment]
Regarding the second comment, the issue is not present if I replace `/tmp/foo.gif` by a relative directory `tmp/foo.gif`. It seems that we can only display from a local folder under the Jupyter root?

The third comment was clarified in gitter, it is not possible to set the frames per second using the macro, we have to use the `gif` function instead.

**Comment by tbreloff** [comment]
> It seems that we can only display from a local folder under the Jupyter root?

Yes this is a known issue... I don't know how to work around it

> @animate macro followed by gif

This is the recommended workflow, unless you have something super-simple.  Also, note that there are now `mov` and `mp4` methods as alternatives to `gif`.

All of this seems to work for me... I'm going to close but let me know if your problem hasn't been solved yet.
