### ISSUE TITLE
Exported `Axis` clashes with AxisArrays.jl

### ISSUE THREAD

**Issue by ajkeller34** [tbreloff/Plots.jl#552]
[AxisArrays.jl](https://github.com/JuliaArrays/AxisArrays.jl) also exports `Axis`. It's convenient when using that package to use the exported `Axis` type for array indexing. I guess I'm wondering if `Plots.Axis` needs to be exported? I've never needed to interact with `Plots.Axis` directly, but if it is common to do so, then consider this issue more of a heads-up and go ahead and close it. cc @mbauman

**Comment by tbreloff** [comment]
This highlights a bigger issue that I probably export too much.  I think it would be safe to un-export Axis and others.
