### ISSUE TITLE
TimeSeries support

### ISSUE THREAD

**Issue by milktrader** [tbreloff/Plots.jl#56]
Not sure how this is implemented, but following https://github.com/tbreloff/Plots.jl/issues/16 the interface would be to load TimeSeries with `timeseries()` and then use multiple dispatch for the `plot` method.

Ideally, one should be able to do this:
````julia
julia> using MarketData

julia> plot(AAPL, style="ohlc")
````
And it would just work. The style options could be the standard
- [ ] line
- [ ] ohlc
- [ ] candlestick

**Comment by tbreloff** [comment]
There are 2 ways you could consider implementing this:

```
function Plots.plot(arr::TimeArray; linetype=:path, kw...)
  # extract x/y arrays from arr
  # if linetype is :ohlc or :candlestick do the necessary processing
  plot(x, y; kw..., otherkwargs...)
end
```

or you could make a PlotRecipe like in: https://github.com/tbreloff/Plots.jl/blob/master/src/recipes.jl#L8

I'm thinking either way, the ohlc/candlestick plots might make sense as PlotRecipes.

**Comment by milktrader** [comment]
So is `:path` a simple line?

Would the idea be to write a method like:
````function Plots.plot(arr::TimeArray; linetype=:path, kw...)
  x = arr.timestamp
  y = arr.values
  # if linetype is :ohlc or :candlestick do the necessary processing
  plot(x, y; kw..., otherkwargs...)
end
````

**Comment by tbreloff** [comment]
`:path` and `:line` are similar... the difference is that `:line` implies you want to sort the data by x-value, whereas `:path` will allow "backtracking".  Example:

```
julia> using Plots

julia> x, y = rand(20),rand(20);

julia> plot(x,y, lab="path", w=3)

julia> plot!(x,y, l=:line, lab="line", w=3)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/10828058/b54fbc72-7e48-11e5-8c3b-0b30297ef3c3.png)

**Comment by tbreloff** [comment]
I'm going to close this, as it likely belongs as an implementation in another package.  Feel free to ask questions if you need help implementing it.
