### ISSUE TITLE
changing the overall font size

### ISSUE THREAD

**Issue by fredRos** [tbreloff/Plots.jl#560]
how can I increase the overall font size? I need many plots for a presentation and the font is just too small to be legible. 
Is there a less clumsy way than manually defining all possible fonts than how I do it in this example

```julia
using Plots; pyplot()
font = Plots.font("Helvetica", 18)
myfonts = Dict(:guidefont=>font, :xtickfont=>font, :ytickfont=>font, :legendfont=>font)
...
plot(data; myfonts...)
pdf("first")
...
scatter(other_data; myfonts...)
pdf("second")
```

Suppose I like the relative size of an axis label and a tick label, so I don't want to have to play around how to keep their relative font size constant. This is similar but not identical to #482

**Comment by tbreloff** [comment]
You can set the defaults once at the beginning. You can also add custom
settings to your juliarc.jl file.

**Comment by fredRos** [comment]
> You can set the defaults once at the beginning. You can also add custom settings to your juliarc.jl file.

How do I do that? Can you provide example code, please?

**Comment by joshday** [comment]
```julia
using Plots;  pyplot(title = "every plot has this title")
```

**Comment by tbreloff** [comment]
From https://juliaplots.github.io/basics/:

> Tip: You can see the default value for a given argument with default(arg::Symbol), and set the default value with default(arg::Symbol, value) or default(; kw...). For example set the default window size and whether we should show a legend with default(size=(600,400), leg=false).

From https://juliaplots.github.io/install/:

> Choose a backend, and optionally override default settings at the same time:
pyplot(size = (300,300), legend = false)

> Tip: You can override standard default values in your ~/.juliarc.jl file: PLOTS_DEFAULTS = Dict(:markersize => 10, :legend => false)

You should really take the time to look through the docs.  I took the time to make them...

**Comment by fredRos** [comment]
Ok, so I have to do

```julia
font = Plots.font("Helvetica", 18)
pyplot(guidefont=font, xtickfont=font, ytickfont=font, legendfont=font)
```
but there is no support for just upscaling the font while keeping the relative size of tick to legend font constant?

**Comment by tbreloff** [comment]
I was just about to write out how easy this would be, and decided it would be quicker to just implement.  Give me a few minutes and this should work:

```julia
using Plots
Plots.scalefontsizes(2)
plot(rand(10), title="hello", guide="guide")
```

**Comment by tbreloff** [comment]
![tmp](https://cloud.githubusercontent.com/assets/933338/19932276/e90443ba-a0e5-11e6-8ecd-a79c2e6d1143.png)

**Comment by fredRos** [comment]
Awesome, thank you very much for the immediate fix! Plots.jl has a great promise, as an experienced matplotlib user, I appreciate how you made a lot of things much easier. Keep up the good work!

**Comment by ttparker** [comment]
@tbreloff Should `scalefontsizes` perhaps be exported?

**Comment by mkborregaard** [comment]
Makes sense. @floswald , maybe you can add the export to your PR?

**Comment by floswald** [comment]
yes sure. sorry guys now I actually *did* forget about this PR. can't finish before thursday morning, bear with me.

**Comment by juliohm** [comment]
Yet regarding this issue, is there any way to scale things up in a way that I can rerun the code multiple times without getting the font bigger and bigger? Something like a global font size. The idea of scaling is perfect except that it assumes a single run of the cell, which is never the case when we are working on the plot.

**Comment by mkborregaard** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/837

**Comment by ttparker** [comment]
@floswald FWIW, it looks like `scalefontsizes` and `resetfontsizes` still haven't been exported.

**Comment by crstnbr** [comment]
Unfortunately `scalefontsizes` doesn't seem to work with `pgfplots` backend.

**Comment by floswald** [comment]
Since GR has become the default backend I had no more use for this function
because stuff looks great with default settings on my screen.

I would have thought that pgfplots takes the font sizes from the
surrounding Tex document? At least that was my impression.

**Comment by BhupalaSriHari** [comment]
How do I increase fontsize only for legend (in the above case y1)

Appreciate any help.

Thanks.

**Comment by mkborregaard** [comment]
`legendfontsize`

**Comment by Vilin97** [comment]
I did
`using Plots
Plots.scalefontsizes(2)`
and now every time I call `plot()` I get errors `GKS: Character height is invalid in routine SET_TEXT_HEIGHT` and all plots look completely messed up.
Resetting the font size with `Plots.scalefontsizes()` does not work. 
Adding and removing the Plots package does not solve the issue. Updating Plots does not solve the issue. Is there a way to just undo this?..
