### ISSUE TITLE
Method for drawing colored rectangles and text onto subplots

### ISSUE THREAD

**Issue by ianshmean** [tbreloff/Plots.jl#561]
I'm looking to create a drawing comprised of a number differently colored/shaped rectangles and text in one of the subplots on a figure I'm animating. What's the best way to go about doing so?

**Comment by tbreloff** [comment]
Shape series and annotations? See the examples in the docs

**Comment by ianshmean** [comment]
Somehow missed that.. thanks for the patience (and great work)!
