### ISSUE TITLE
Reversing a colormap

### ISSUE THREAD

**Issue by BoundaryValueProblems** [tbreloff/Plots.jl#563]
Hello.
When I use a colormap, say ```grays``` in the ```contourf``` function like:
```
julia> contourf(f, c=:grays)
```
it displays the grayscale from white to black. I want to reverse it so that the minimum value of ```f``` corresponds to black and the maximum value to white. According to matplotlib, all such reverse colormaps are defined by appending ```_r``` to the colormap name, e.g., ```gray_r```. But under Plots.jl, neither```c=:grays_r``` nor ```c=:gray_r``` works. What should I do?
Thanks!
BVPs

**Comment by tbreloff** [comment]
```julia
cgrad(reverse(cgrad(:grays).colors))
```

I could maybe be convinced to add some conveniences:

```julia
contourf(f, c = :grays_r)
contourf(f, c = cgrad(:grays, rev=true))
```

**Comment by BoundaryValueProblems** [comment]
Hi, tbreloff.
Yes, please add one of those; the reversed grayscale colormap is particularly important and quite commonly used. In many image processing applications, the reversed grayscale colormap is the default, not the current grayscale colormap that can be specified by ```c=:grays```.
Thanks a lot!!
BVPs

**Comment by tbreloff** [comment]
I added this... `Pkg.checkout("PlotUtils")`

**Comment by BoundaryValueProblems** [comment]
Thanks a lot!
You also changed the default ```grays``` from black to white. So, ```grays_r``` now indicates a colormap from white to black. I just wanted to mention this for record so that other people may find them here.
Best,
BVPs

**Comment by tbreloff** [comment]
Ha... that was not intentional!  Fixed on master

**Comment by BoundaryValueProblems** [comment]
Well, actually, in my opinion, ```grays``` corresponds to black to white and ```grays_r``` corresponds to white to black. It's up to you, but the MATLAB grayscale colormap is from black to white for sure.
Best,
BVPs

**Comment by tbreloff** [comment]
This is beside the point... I accidentally reversed **every** color list.

Anyways if you can confirm the convention of grays in other frameworks (matplotlib, plotly, etc) I'd be happy to change that.

**Comment by BoundaryValueProblems** [comment]
OK, thanks! I'll check into it and get back to you (although it may take some time).
Best,
BVPs

**Comment by BoundaryValueProblems** [comment]
Hi, tbreloff.
I just checked matplotlib and PyPlot, and found out that their grayscale colormap called ```:gray``` (not ```:grays``` in their packages) are from black to white. This also agrees with the MATLAB convention. Hence, it may be a good idea to make ```:grays``` in Plots.jl (or PlotUtils) consistent with the other packages.
Thanks!
BVPs

**Comment by tbreloff** [comment]
Cool thanks for following up

**Comment by tbreloff** [comment]
Just changed on PlotUtils master

**Comment by BoundaryValueProblems** [comment]
Great! Thanks a lot!!
