### ISSUE TITLE
Refreshing GUI display data to create a live animation?

### ISSUE THREAD

**Issue by lwabeke** [tbreloff/Plots.jl#567]
Hi

I'm trying to process data and visualising the results as a live animation as the processing continues.
Most references to the term animation seems to be to generating an animated gif. While this is great for showing the results afterwards, I cannot determine how/if this would be practical if the gif needs to be updated and refreshed every 5 seconds to add in a new frame. 

I attempted to use the Plotlyjs backend to display in a standalone GUI. See below. But I either get it to:
1. Add data, instead of overwriting the existing data in the frame
2. Refresh the window, but with the stale data
3. Pop up a new window every time (not sure which variation of code I had that did that)

Thus to summarise, I'm trying to open a single GUI window, replace the data in it every iteration and refresh the window. I'm missing a nuance between display, gui, calling scatter! to modify an existing window, scatter creates a new window. I tried passing p in to scatter, but then getting an error 
ERROR: MethodError: Cannot `convert` an object of type String to an object of type MethodError

Can someone please help? Thanks in advance.

```
using Plots

Plots.PlotlyJSBackend()

function testerAddsInsteadOfOverwrites()
p = 0

    for cnt=1:10
            sleep(5)  # Dummy to simulate normal slow processing
        values = rand(10,2)
            if isa(p, Plots.Plot{Plots.PlotlyJSBackend})
                scatter!(values[:,1], label="Series1")
            else
                p=scatter(values[:,1], label="Series1")
                gui(p)

            end

            scatter!(values[:,2], label="Series2")
            display(p)

    end

end

function testerRefreshWindowButWithStaleData()
p = 0

    for cnt=1:10
            sleep(5)  # Dummy to simulate normal slow processing
        values = rand(10,2)
            if isa(p, Plots.Plot{Plots.PlotlyJSBackend})
                gui(p)
                scatter(values[:,1], label="Series1")
            else
                p=scatter(values[:,1], label="Series1")
                gui(p)

            end

             scatter!(values[:,2], label="Series2")
            display(p)

    end

end
```

**Comment by tbreloff** [comment]
This is a known problem for plotlyjs, but I'm not sure if there's an issue for it.  @spencerlyon2: a new Blink window is created for every call to `plot`... is there a way to reuse the window for the next call?

> Plots.PlotlyJSBackend()

This is an object... it doesn't do what you're thinking.  Try `plotlyjs()`

**Comment by spencerlyon2** [comment]
The type `PlotlyJS.SyncPlot` is responsible for displaying a plot. It contains two fields:

1. The  pure Julia `PlotlyJS.Plot` object that holds the data
2. A display that is a subtype of `PlotlyJS.AbstractPlotlyDisplay` that represents where the plot is supposed to be displayed. If plotting at the REPL this will be `ElectronDisplay`.

If you really wanted to re-use the window for the plot you'd have to create your own `SyncPlot` using a  display that has already be initialized. For example, suppose you have `p1::SyncPlot` that has already been displayed and `p2::SyncPlot` that isn't displayed yet. You could do something like this `p2 = SyncPlot(p2.plot, p1.display)` to create a new SyncPlot with p1's display and p2's data. But you'd have to call for a refresh of the display using something like `redraw!(p2)` after that.

That's kinda lot of work though -- there's probably a better way to achieve this.

**Comment by tbreloff** [comment]
Thanks @spencerlyon2 I'll try it out.

**Comment by spencerlyon2** [comment]
FWIW, if I were doing this with just PlotlyJS this is how I'd do it:

```
using PlotlyJS

function test_refresh_window()
    p = plot([scatter(y=rand(10), name="Series1"), 
              scatter(y=rand(10), name="Series2")],
              Layout(yaxis_range=(0, 1)))

    display(p)
    
    for cnt=1:30
        sleep(0.5)
        values = rand(10, 2)
        restyle!(p, y=(values[:, 1], values[:, 2]))
    end

end
```

with this result:

![plotlyjs_anim](https://cloud.githubusercontent.com/assets/1001948/20268432/1a53ca74-aa4d-11e6-8ec5-ec14c82b5b3a.gif)
