### ISSUE TITLE
Duplicated subplots don't appear

### ISSUE THREAD

**Issue by swt30** [tbreloff/Plots.jl#568]
From http://groups.google.com/forum/#!topic/julia-users/GBIc0jTCug8

```julia
using Plots
myplot = plot(randn(20))
myplot2 = plot(randn(20))
myplot3 = plot(randn(20))
normal = plot(myplot, myplot2, myplot3, layout= @layout [a; b c])
duplicated = plot(myplot, myplot, myplot, layout = @layout [a; b c])
```

**Normal plots**
![figure_1](https://cloud.githubusercontent.com/assets/6207820/20264419/61a9d786-aa63-11e6-86bd-d047b0e704fc.png)

**Duplicated plots**
![figure_2](https://cloud.githubusercontent.com/assets/6207820/20264421/64241c7e-aa63-11e6-9cd4-4a5bb8e40169.png)

**Comment by tbreloff** [comment]
I can't decide if this is something I want to handle...

**Comment by swt30** [comment]
Yeah bit of a weird case. Maybe providing `copy(::Plot)` could be a useful middle ground.

**Comment by tbreloff** [comment]
```julia
using Plots
p = plot(rand(10))
plot([deepcopy(p) for i=1:9]...)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/20267899/c7acafea-aa4a-11e6-9713-2ac748bea8a3.png)

**Comment by swt30** [comment]
Ah of course it would be deepcopy instead. :+1:
