### ISSUE TITLE
Problem plotting DateTime on x axis

### ISSUE THREAD

**Issue by crbinz** [tbreloff/Plots.jl#572]
```
julia> using Plots

julia> dates = DateTime("2016-01-01T00:00:00.000"):Dates.Day(1):DateTime("2017-01-01T00:00:00.000")
2016-01-01T00:00:00:1 day:2017-01-01T00:00:00

julia> plot(dates,rand(length(dates)))
```
![1](https://cloud.githubusercontent.com/assets/3694987/20319814/8b39326a-ab3d-11e6-8614-2e97731c15cf.png)

Using regular `Date`s works fine:
```
julia> plot(map(Date,dates),rand(length(dates)))
```
![2](https://cloud.githubusercontent.com/assets/3694987/20319820/8db2240c-ab3d-11e6-80ed-ec0696a6c093.png)

This is with `Plots.jl` v0.9.4 on julia v0.5

**Comment by tbreloff** [comment]
Are you on a recent commit?

**Comment by crbinz** [comment]
I'm on v0.9.4 of Plots (julia-v0.5)

**Comment by tbreloff** [comment]
Check out master.

**Comment by crbinz** [comment]
Looks fine on master, thanks.
