### ISSUE TITLE
Possible to change legend labels?

### ISSUE THREAD

**Issue by tcovert** [tbreloff/Plots.jl#575]
Suppose I have a line plot with several lines.  Is there a way to change the legend labels for these lines?    When I try something like:
```
plot!(p, label = ["a", "b", "c"])
```
the labels for all three lines become ["a", "b", "c"], instead of "a", "b" and "c" individually.

What am I doing wrong?

**Comment by tbreloff** [comment]
No commas. You need to pass in a 1x3 matrix of labels. If you read the docs
you'll see similar comments about 10 times.

**Comment by tcovert** [comment]
Thanks for the clarification.  Now that I re-read the "Columns are series" section of the manual, I do see that you've already made this point.
