### ISSUE TITLE
Set UnicodePlots Canvas

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#578]
It would be nice to have a way to set the canvas for Unicode plots, especially to something like the ASCII canvas when Unicode is not available.

**Comment by tbreloff** [comment]
I was gonna respond but figured it's faster to just do it.  On dev branch:

![tmp](https://cloud.githubusercontent.com/assets/933338/20498109/d3db6fe0-aff9-11e6-9f48-426bcfa59832.png)
