### ISSUE TITLE
Getting `UndefVarError: get_stroke_vector not defined` when trying to plot with Gadfly backend.

### ISSUE THREAD

**Issue by Lanzafame** [tbreloff/Plots.jl#59]
I am trying to run the following:
```julia
julia> using Plots

julia> gadfly()
Plots.GadflyPackage()

julia> plot(Plots.fakedata(50,5),w=3)
ERROR: UndefVarError: get_stroke_vector not defined
 in getGadflyLineTheme at /Users/lanzafame/.julia/v0.4/Plots/src/backends/gadfly.jl:63
 in addGadflyLine! at /Users/lanzafame/.julia/v0.4/Plots/src/backends/gadfly.jl:76
 in addGadflySeries! at /Users/lanzafame/.julia/v0.4/Plots/src/backends/gadfly.jl:213
 in plot! at /Users/lanzafame/.julia/v0.4/Plots/src/plot.jl:114
 in plot at /Users/lanzafame/.julia/v0.4/Plots/src/plot.jl:56
```
I have attempted this on the stable, master, and dev versions of the package.

**Comment by tbreloff** [comment]
I'm guessing this is because Immerse has pinned gadfly to an older tag, and
so gadfly is missing my PR where I added line styles. If you remove Immerse
and update, does it fix itself?  I'll see if I can come up with a solution
tomorrow so you don't have to choose between Plots and Immerse. If you
don't have Immerse installed, maybe you just need a Pkg.update?

**Comment by tbreloff** [comment]
I can recreate the problem simply with:

```
Pkg.add("Immerse")
Pkg.update()  # causes a downgrade of Gadfly
```

My solution will be to turn off line styles for Immerse/Gadfly if that method is missing.  I'll push a fix to master soon.

**Comment by tbreloff** [comment]
Ok I pushed the fix to master.  However, downgrading Gadfly also brings with it the millions of deprecation warnings, so my suggestion for now is:

```
julia> Pkg.rm("Immerse")
INFO: Upgrading Gadfly: v0.3.16 => v0.3.18
INFO: Removing Gtk v0.9.2
INFO: Removing GtkUtilities v0.0.6
INFO: Removing Immerse v0.0.8
INFO: Package database updated
```

For reference: https://github.com/JuliaLang/METADATA.jl/pull/3906
cc: @timholy

**Comment by Lanzafame** [comment]
Sorry, been busy with work. Cheers for the fix. Will check it out this
afternoon.
