### ISSUE TITLE
Correct animation show output for mov/mp4

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#596]
Currently I output `<img src...` but it should be something else for mov/mp4 videos.

cc: @jasongrout

**Comment by jasongrout** [comment]
It looks like Jupyter may not have a renderer to create video elements. For small videos, like things that can be Base64-encoded without too much trouble, I think it would make sense to be able to render mov/mp4 using a `<video>` tag.

**Comment by tbreloff** [comment]
Got it working!

![tmp](https://cloud.githubusercontent.com/assets/933338/20799381/ff9b7900-b7af-11e6-9025-f476eca1029b.png)

**Comment by tbreloff** [comment]
4ed7144
