### ISSUE TITLE
Canno't plot updated functions

### ISSUE THREAD

**Issue by k0pernicus** [tbreloff/Plots.jl#600]
Hi there!

I played with Julia a few days, and I don't understand this strange behaviour plotting some functions on the same graphic.
My code is:
```
using Plots
f(x) = -log(x)
g(x) = -log(1-x)
Plots.plot([f, g], 0, 1)
```
This code works great (but it's very slow importing and plotting data :-/...)
The strange behaviour is here:
```
# I update g(x)
g(x) = x
```
So, I updated `g(x)`, and it works great (obtained `1` for `g(1)`, `2` for `g(2)`, `3` for `g(3)`, etc...). But, when I tried to plot again `f` and `g`, I obtain again the same graph - so, `g(x)` has not been updated to plot it...

Is it something wrong in my code?

**Comment by KristofferC** [comment]
https://github.com/tbreloff/Plots.jl/issues/508
