### ISSUE TITLE
Stacked bar plot

### ISSUE THREAD

**Issue by staticfloat** [tbreloff/Plots.jl#613]
It would be great if I could make a stacked bar plot using the `bar!()` function calls; Perhaps this could be as simple as adding the `bottom` parameter, like [how PyPlot does it](http://matplotlib.org/examples/pylab_examples/bar_stacked.html)?

If this is possible using the current API, I haven't been able to find out how to do so, and would be happy to contribute and example to the docs.

**Comment by ChrisRackauckas** [comment]
There's already recipes for it in StatPlots.jl

https://github.com/JuliaPlots/StatPlots.jl

**Comment by staticfloat** [comment]
Perfect, exactly what I'm looking for.  Those are some great recipes, thanks @ChrisRackauckas!

**Comment by NHDaly** [comment]
(for other google-searchers like me, it's `groupedbar`: https://github.com/JuliaPlots/StatPlots.jl#grouped-bar-plots)

**Comment by fredcallaway** [comment]
Should this issue really be closed? The [API](https://docs.juliaplots.org/latest/attributes/#series) advertises this functionality (albeit with a warning that it may not be fully implemented). If there's no intention of the functionality being implemented, then maybe `bar_position` should be removed from the API?

**Comment by mkborregaard** [comment]
It's implemented, just in StatsPlots (which is the same package with a bit more bells and whistles, recommended for most users). The documentation is for all the packages (RecipesBase + PlotUtils + PlotThemes + Plots + StatsPlots).
