### ISSUE TITLE
Latex in Labels and Titles

### ISSUE THREAD

**Issue by Kelvyn88** [tbreloff/Plots.jl#619]
If there a possibility to use latex in the labels?

if I try:

yaxis!(L"Label")

I get the error: ERROR: UndefVarError: @L_str not defined

Please. I really need this.

**Comment by pkofod** [comment]
Sorry for asking the obvious, did you `using LaTeXStrings`?

**Comment by Kelvyn88** [comment]
Sorry, I didn't know the LaTeXStrings. That solves the problem. Thanks!

**Comment by zhyiyu** [comment]
I found that if I import `LaTeXStrings` in the main block:

```julia
if abspath(PROGRAM_FILE) == @__FILE__
    using LaTeXStrings
end
```

then I get:

```zsh
UndefVarError: `@L_str` not defined
```

Importing it outside `main` solves the issue.
