### ISSUE TITLE
Updating labels with `plot!`

### ISSUE THREAD

**Issue by joshday** [tbreloff/Plots.jl#62]
At least for Gadfly and PyPlot backends,

This works as expected:
```julia
plot(randn(100,2), label = ["one" "two"])
```

Whereas this does not:
```julia
plot(randn(100,2))
plot!(label = ["one" "two"])
```

Would it also be possible to allow `label` to accept a Vector?

**Comment by tbreloff** [comment]
Both requests might be tough, though I can see why you want it.  Series are made in one pass, although you can update plot-wide settings after the fact.  I'll brainstorm on it a little, but it would probably require a redesign of some core pieces. Something like an "update series" mechanic (which would be good to have in general).  I'll keep you posted.

**Comment by tbreloff** [comment]
As for Vector vs Matrix... I don't think I'm going to change that, as it's important for distinguishing between vectors that apply to all series vs matrices that map a column to a series.

**Comment by joshday** [comment]
Ah, I didn't realize that distinction between giving an argument a Vector vs. Matrix.  That makes sense.

**Comment by tbreloff** [comment]
I thought about it, and I'm going to do a slight redesign to make it easier to update series (and improve some other stuff along the way).

**Comment by tbreloff** [comment]
6 months later...

It's not perfect, but it works for me:

```
using Plots
p = plot(rand(10), size=(300,300))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/16060810/a463dbbe-3257-11e6-9679-c5c250a796d0.png)

```
p.series_list[1].d[:label] = "Look ma... a new label"; p
```

![tmp](https://cloud.githubusercontent.com/assets/933338/16060829/ba939e4c-3257-11e6-8064-62c6a01ad404.png)
