### ISSUE TITLE
Plot Recipe for Automatic Adaptive Plotting of Functions

### ISSUE THREAD

**Issue by ChrisRackauckas** [tbreloff/Plots.jl#621]
It would be nice to be able to `plot(f)` for `f(t)` some function which returns scalars (or more). Mathematica handles this with a sophisticated algorithm. It's only mentioned on this page:

https://reference.wolfram.com/language/ref/Plot.html

and described as

>Plot initially evaluates f at a number of equally spaced sample points specified by PlotPoints. Then it uses an adaptive algorithm to choose additional sample points, subdividing a given interval at most MaxRecursion times.

![image_5](https://cloud.githubusercontent.com/assets/1814174/21425820/2fb20cc0-c800-11e6-8754-6c82d2c10512.gif)

It seems like the algorithm does the following (or at least something like it): 

1. Take an initial number of points (lets say 100) 
2. Take two points skipping over one, do a linear interpolation
3. Check the difference between the linear interpolation and the actual value (the skipped point). If it's large enough, subdivide the interval.
4. Recurse 3 on the points you are getting until `max_recursion` or it hits the tolerance.
5. Repeat 2 until you're point of point triples.

This form of adaptive plotting would make it easy to plot a function without knowing the details. This is nice for when you don't actually know what the function looks like until plotting it! 

@Armavica

**Comment by KristofferC** [comment]
I was bored so I did the simplest thing I could: http://imgur.com/a/SksX3

Script is here: https://gist.github.com/KristofferC/b13f2375e4b7596db7b2a82237151709

**Comment by KristofferC** [comment]
I'm refining 50% of the intervals each iteration because the total cost of the function evaluation should then be just a factor of two compared to the last evaluation. (2^0 + 2^1 + ... 2^n) = 2 * 2^n

**Comment by tbreloff** [comment]
Awesome. We could make this be the new recipe for single-function calls

**Comment by KristofferC** [comment]
But you still need to give start and end points I guess?

Also, how would you differ between `plot(f, [0.0, 0.1])` where `[0.0, 0.1]` could either be the interval to plot, or a min and max point.

**Comment by KristofferC** [comment]
This implementation is of course also susceptible to aliasing, for example if you create a sine wave that is zero at two adjacent initial "seed" points. Maybe sprinkling some random points in each iteration could help. There must be tons of literature for this though. Not that I am personally not so interested in reading it :P

**Comment by Armavica** [comment]
Without looking at your posts I wrote exactly the same algorithm (also refining half the points). Mathematica seems to deal with the aliasing issue with a nontrivial periodic (?) pattern in the initial sampling: https://imgur.com/a/UC1vv (I plotted the differences between consecutive initial sampling points divided by the average interval length, so for a regular sampling everything would be 1).

**Comment by ChrisRackauckas** [comment]
Oh wow, you guys really ran with this!

>This implementation is of course also susceptible to aliasing, for example if you create a sine wave that is zero at two adjacent initial "seed" points. Maybe sprinkling some random points in each iteration could help. There must be tons of literature for this though. Not that I am personally not so interested in reading it :P

I presume there's some randomness at each step which gives new points. If you look at the picture from Mathematica at the top, you see that the points don't where the midpoints would be, they seem slightly off. I was wondering why this would be the case, and aliasing would be a really good explanation. I think throwing in a little bit of noise in the initial selection of points, and a little bit of noise in each interval subdivision (amount of noise as a percentage of the interval size?), and it should be good should be good enough.

>Also, how would you differ between plot(f, [0.0, 0.1]) where [0.0, 0.1] could either be the interval to plot on, or two individual points?

What about `plot(f, (0.0, 0.1))` as you had it? As a tuple, that means you can also dispatch on the fact that it has to be only two points: start and end. Or you can extend this a little by, if given more points, force a plot at those points. Like `plot(f, (0.0,0.5, 0.1))` will have an initial point at `0.5`. Though probably the parameters used should just be exposed as keyword args.

**Comment by Armavica** [comment]
> If you look at the picture from Mathematica at the top, you see that the points don't where the midpoints would be, they seem slightly off.

Actually running Mathematica code suggests that the refinements are always done in the middle of two consecutive points. I suspect that this picture is just an "artist view" and not to be taken too seriously.

That said, we are not a Mathematica clone and I don't see any problem with some randomness here.

**Comment by Armavica** [comment]
I am also thinking that we could easily extend this to parametric plots.

**Comment by ChrisRackauckas** [comment]
I think, going along with the idea I had about giving more timepoints, instead it would be really nice to be able to declare known points of discontinuity, and ensure that the initial points straddle it dis+epsilon/2 and dis-epsilon/2 away. Being able to declare discontinuities might reduce the number of points in some cases? But from @KristofferC 's pictures I don't see this as a real problem.

**Comment by Armavica** [comment]
Unless I am mistaken each discontinuity will generate at most `2*maxrecursions`, right? (`4*maxrecursions` in @KristofferC's version). It doesn't seem to be a huge cost.

**Comment by KristofferC** [comment]
I will fix something better than last one. Just gotta dress up the Christmas tree zzz.

**Comment by KristofferC** [comment]
Ok, new version at: https://gist.github.com/KristofferC/ce5169000b29cc6b15588dc4e133ee5c with results: http://imgur.com/a/iBAi2.

This one should just estimate the second derivative in each point and also wiggle the points a bit to try to remove degenerate cases. Not sure how to decide which one is best though. :P

**Comment by KristofferC** [comment]
I think it is important not to have too fine grid in the start as well. 50 points is probably too much.

**Comment by ChrisRackauckas** [comment]
It seems like this second one is safer, so I'd assume it is 👍 . The only way to really know is to let it in the wild for a year and see what crazy things end up causing a problem.

>50 points is probably too much.

And could that be a kwarg? Along with `rand_factor`? I think some way of using an error tolerance to stop early is really crucial though, because your plots do have a lot of points in them.

**Comment by KristofferC** [comment]
The function right now has a `max_points` kwarg. I don't think the `rand_factor` need to be user definable. Do you have a suggestion for an early exit criteria?

**Comment by KristofferC** [comment]
I think multiplying the error with the interval should be done as well. Basically integrating the second derivative over the interval. I updated the gist.

**Comment by ChrisRackauckas** [comment]
Call `error = sum(abs2,E)`, and exit early if `error<tol`?

**Comment by ChrisRackauckas** [comment]
I think you can just generate `err` once before the loop, and `resize!` in the loop. Maybe that could reduce some allocations due to how Julia caches it? I'm not sure how much that would really help though.

**Comment by KristofferC** [comment]
Yeah it is not optimized but to be honest, it is not really needed. It goes fast enough for simple functions and for complicated functions, time would be spent in evaluating the function.

I don't think `sum(abs2, E)` is so good because it will be unit dependent and also dependent on the number of points.

**Comment by ChrisRackauckas** [comment]
Then what about something like `abstol` + `reltol` of ODE solvers?

```julia
est = sum(abs2,err./abstol + max(err)*reltol)/length(err)
```

Then stop when `est<1`?

**Comment by KristofferC** [comment]
My use of `err` in the code is not good terminology.  An error should go to zero as the number of points goes to infinity. It is not actually an error, it is an estimation of the integral of the second derivative over a small interval and I use that to chose what intervals to refine.

In adaptive finite element, one way of estimating the error is to see what happens to the solution after an hierarchial p or h refinement where you project the solution of the coarse mesh onto the fine mesh (or higher polynomial mesh). I will try something like that.

**Comment by ChrisRackauckas** [comment]
I see. I thought it was a comparison. Then yes, a dual mesh comparison for an error is the way to go. Though you could estimate errors without resorting to a second mesh by checking the inbetween points against a linear interpolation.

**Comment by KristofferC** [comment]
Updated with error estimator: https://gist.github.com/KristofferC/4b999e8b376d5073f7d4d8f69cf3352e.

Results at: http://imgur.com/a/15WsA

For linear function we break straight away. Other function breaks at "decent" point density I think. Feel free to test with your own functions.

**Comment by Evizero** [comment]
Fancy!

**Comment by Armavica** [comment]
I think that the real test is `sin(1/x)`. Currently it does show some trouble to plot it between `0` and `0.1` (or rather `1e-6` and `0.1` since it does not like `1/0`). Even pushing the `max_point` limit to 1000 a lot of points get wasted on the left part. Maybe we could detect that a region is overcrowded and that it is useless to invest any more points in it.

**Comment by KristofferC** [comment]
Yeah, that is the evil one :P Does other software handle it "well"?.

**Comment by Evizero** [comment]
I am getting an error when trying a zero one loss function on 0.5, but that could very well be my fault somehow in my blind ignorance of just calling it with no careful thought whatsoever. 

Example plot of the function: 

![example](https://rawgit.com/JuliaML/FileStorage/master/LossFunctions/ZeroOneLoss1.svg)

```julia
julia> f = x -> x > 0 ? 0 : 1
(::#18) (generic function with 1 method)

julia> mm = (-2, 2)
(-2,2)

julia> xs = refine_grid(f, mm)
ERROR: InexactError()
 in setindex!(::Array{Int64,1}, ::Float64, ::Int64) at ./array.jl:415
 in #refine_grid#17(::Int64, ::Float64, ::Function, ::Function, ::Tuple{Int64,Int64}) at ./REPL[87]:67
 in refine_grid(::Function, ::Tuple{Int64,Int64}) at ./REPL[87]:3
```

**Comment by KristofferC** [comment]
It was just an array that got turned into `Int` from your function and then the interpolation failed. I updated script.

![image](https://cloud.githubusercontent.com/assets/1282691/21442620/47efd4b2-c89f-11e6-9352-606b5456cd28.png)

**Comment by KristofferC** [comment]
Right now I remove the top 5% of the maximum errros in order for the error not to blow up at discontinuties. No idea if it is a good idea.

**Comment by Armavica** [comment]
> Yeah, that is the evil one :P Does other software handle it "well"?.

It [works](https://imgur.com/a/SJ0Ci) in Mathematica like a charm. [1661 points](https://paste.fulltxt.net/tKNgIC4vt66o) though.

**Comment by KristofferC** [comment]
I would have thought the small intervals on the left side would have made the right side to start winning.

**Comment by KristofferC** [comment]
What does mathematica do for a square wave? How many points?

**Comment by KristofferC** [comment]
"subdividing a given interval at most MaxRecursion times". Maybe that is what is happening?

**Comment by Armavica** [comment]
[67 points](https://paste.fulltxt.net/9X5y9bfiQuMJa9) (discontinuity at 0.5).

**Comment by KristofferC** [comment]
It makes sense to limit the number of recursions because there is no point in having points too densely since they won't be visible anyway. Should help with discontinuity problem as well. Will implement and report back.

**Comment by Armavica** [comment]
Interestingly Mathematica never evaluates the function at the boundaries of the interval, and treats them basically like discontinuities (it pushes towards them from time to time). This is indeed generally what you want…

**Comment by ChrisRackauckas** [comment]
>Interestingly Mathematica never evaluates the function at the boundaries of the interval, and treats them basically like discontinuities (it pushes towards them from time to time). This is indeed generally what you want…

Is it always the same starting perturbation from the ends?

**Comment by Armavica** [comment]
It always starts at `min+(max+min)/(n-1)*10^-6` (`n` number of initial points) for the minimum, and symmetrically for the max.

**Comment by KristofferC** [comment]
Version 4 https://gist.github.com/KristofferC/284559e8f856066ec3b922dadcd3df03, http://imgur.com/a/ZFTrf

Still some stuff left to do but getting better I think.

**Comment by KristofferC** [comment]
New (and probably final) version. Now, never evaluates the function exactly at the end points and uses some more sensible pruning of intervals. Before it over refined regions it didn't need to just because the function was ill behaved somehwere else.

https://gist.github.com/KristofferC/6b68b23527e6e9e668708764128c39cd results http://imgur.com/a/yV4HK

**Comment by Evizero** [comment]
very cool!

as a side note: also a nice function that was annoying to plot correctly is this one: `f = x->abs(x)^.5`, which is the LP distance loss with P < 1 (here concretely the blue one with `P= 0.5`), because of how steep it is near 0

![](https://rawgit.com/JuliaML/FileStorage/master/LossFunctions/LPDistLoss1.svg)

**Comment by KristofferC** [comment]
Looks pretty good now?

![image](https://cloud.githubusercontent.com/assets/1282691/21454152/48311144-c916-11e6-9541-933e4b5784c2.png)

**Comment by Armavica** [comment]
Other interesting functions to plot: `lgamma` on `(-4, 8)`, `tan` on `(-5,5)` (for this one `ylims` needs to be specified manually, unless we implement some heuristics to detect the relevant y range). As a consequence of the nondeterministic plotting, the height of the peaks in `lgamma` varies from one plot to another, I think we should really consider if we want this to happen or not.

**Comment by KristofferC** [comment]
Yeah, manual ylims is also something worth considering. For the determinism, would it be good to just create a new RNG instance and give it a fixed seed. There fore the noise is "random" but constant for the same input points.

**Comment by KristofferC** [comment]
Updated gist with using a custom rng object. This is lgamma: http://imgur.com/a/s4b4X

**Comment by ChrisRackauckas** [comment]
Wow, that looks really good.

**Comment by tbreloff** [comment]
Great stuff! Do you know where to add this code in Plots? (Look for the
single function and function with endpoints recipes, I think in recipes.jl
or series.jl?)

**Comment by Evizero** [comment]
Maybe this would fit better into PlotUtils? so that freeloaders such as the UnicodePlots guy, can use it as well (if he ever gets around to his refactor that is). Anyhow, big fan either way

**Comment by tbreloff** [comment]
I'd be cool with adding the core logic to PlotUtils and just calling it
from the Plots recipe

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaPlots/PlotUtils.jl/pull/6.

Regarding explicit y-limits I guess it could be solved by returning many sub intervals where the function is inside the y-limits on all the intervals. However, I don't think I can allow myself to work much more on this (not that it isn't fun).

**Comment by KristofferC** [comment]
Another way of dealing with y-limit is simply not to refine intervals where the function is outside the y-limits.

**Comment by tbreloff** [comment]
This is great work... thanks!

```julia
using Plots; scatter(tan)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/21690229/969c3e98-d330-11e6-9869-3808f54c09c8.png)

**Comment by soegaard** [comment]
FWIW I have collected a small set of horror functions to test plotting algorithms:

https://github.com/soegaard/bracket/blob/master/plotting/adaptive-plotting.rkt#L225

A lot of them are from 
www.mines-paristech.fr/~kajler/pub/9507-RAOBNK-issac95.ps

**Comment by mkborregaard** [comment]
Have you tried plotting them with Plots?

**Comment by KristofferC** [comment]
FWIW, I am sure the stuff I implemented is not at all state of the art, quality wise. It was just me applying what sort of makes sense. It would be interesting to see how it works on these horror plots.

**Comment by soegaard** [comment]
No, I haven't tried Plots - I found this discussion through a comment on https://scicomp.stackexchange.com/q/2377/1541

**Comment by mkborregaard** [comment]
Are you familiar with Julia? Could you describe the racket syntax clearly enough for someone here to port them to Julia? It could be fun to see.

**Comment by soegaard** [comment]
I'm not familar with Julia. The Racket syntax is just prefix notation. Instead of a+b we write (+ a b).
So 
```
     (+  (tan (+ (expt x 3) (- x) 1)) 
             (/ (+ x (* 3 (exp x)))))) 
    (interval xmin=-2 to xmax=2)
```
is tan( x^3 -x + 1) + 1 / (+ x 3 e^x)

Here `(expt a b)`  means `a^b` and `(exp a)` means `e^a`. Finally the one argument version of `/` is the same as `1/x`.

Other functions on the list:

```
sin(1/x)
sin(x^4)
sin(300x)
1 + x^2 + 0.0125 log( abs(1- 3*(x-1)))
sin(e^x)
1/sin(x)
sin(x)/x
log(1+sin(cos(x)))

```
These are simpler. They check specific properties:
```
  1/x            ; check division by zero and singularity at x=0
  tan(x)       ; check multiple singularities
   -1/x         ; check symmetry
  1/abs(x)   ; check connected components of same sign
  1E6 * x     ; check that lines with high slopes are drawn
   1E50 * x ; check that lines with high slopes are drawn

```






-2. 2. -15. 15.)

**Comment by mkborregaard** [comment]
```julia
f(x) = sin.(1./x)
using Plots
plot(f)
```
<img width="592" alt="skaermbillede 2017-06-20 kl 20 04 09" src="https://user-images.githubusercontent.com/8429802/27348249-ab502390-55f3-11e7-8bce-af6fe3229911.png">
```julia
plot(f, -2, 2)
```
<img width="590" alt="skaermbillede 2017-06-20 kl 20 03 59" src="https://user-images.githubusercontent.com/8429802/27348251-af7adf64-55f3-11e7-8313-04e2771499c3.png">

```julia
plot(f, linspace(-2,2,1000))
```
<img width="594" alt="skaermbillede 2017-06-20 kl 20 03 45" src="https://user-images.githubusercontent.com/8429802/27348258-b2a7aa00-55f3-11e7-9305-a6d55df91f7e.png">

**Comment by KristofferC** [comment]
That looks awful lol.

**Comment by KristofferC** [comment]
I thought I tested sin(1/x) specifically...

**Comment by pkofod** [comment]
> I'm not familar with Julia. The Racket syntax is just prefix notation. Instead of a+b we write (+ a b).
> So

shouldn't be too hard too parse that as Julia, just ned to add commas
```
julia> +(2, /(4, 3))
3.333333333333333
```

**Comment by KristofferC** [comment]
I think there is a difference with how max deals with NaNs in 0.6 or something...

**Comment by KristofferC** [comment]
https://github.com/JuliaPlots/PlotUtils.jl/pull/20

**Comment by mkborregaard** [comment]
@pkofod great that it's that simple! So do all the functions plot as prettily as sin(1/x) after @KristofferC 's update?

**Comment by KristofferC** [comment]
Update what?

**Comment by KristofferC** [comment]
Oh lol nvm.

**Comment by pkofod** [comment]
> @pkofod great that it's that simple! So do all the functions plot as prettily as sin(1/x) after @KristofferC 's update?

I don't know... I've banned myself from using `Pkg.anything` until I've presented today!

**Comment by KristofferC** [comment]
What is really needed is to take the ylimits into account when doing the partitioning.
