### ISSUE TITLE
Convenient access to log-scale heatmap

### ISSUE THREAD

**Issue by staticfloat** [tbreloff/Plots.jl#625]
I'd like to allow log-scale heatmaps to be made easily.  Ideally, there would be some kind of `zscale = :log10` parameter or somesuch.  Looking at the Pyplot documentation, this seems to be possible through the use of a normalization function passed in to the color mapping code, as seen [here](http://matplotlib.org/users/colormapnorms.html), but I can't seem to get my extra keyword arguments passed through into pyplot.  I've been trying things similar to:

```julia
using Plots
using PyCall
@pyimport matplotlib.colors as colors

...

heatmap(flipdim(labels,1), labels, flipdim(confusion_matrix, 1), aspect_ratio=1, norm=colors.LogNorm(vmin=0, vmax=1))
```

However, the `norm` kwarg seems to be completely ignored.  Any ideas?

**Comment by tbreloff** [comment]
Plots is not PyPlot... you can't pass PyObjects into Plots methods.

Does this help? https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/cgrad.ipynb

You'll want to build a log-scaled color gradient using the `cgrad` method and pass that to the `fillcolor` for heatmap.

**Comment by staticfloat** [comment]
Thanks, that's exactly what I was looking for!  I guess I was getting confused by how similar the interfaces for `PyPlot` and `Plots` is, thanks again!
