### ISSUE TITLE
Set Gadfly z-order

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#63]
Layers seem to be randomly ordered on the screen:

![tmp](https://cloud.githubusercontent.com/assets/933338/11008507/feffbbc2-849e-11e5-9fb5-a782caa282a7.png)

I think it's possible to specify an order to them, so I should do that.

**Comment by rohitvarkey** [comment]
@tbreloff Yes! You can specify orders in Gadfly.

From the docs at http://gadflyjl.org/ ...

Ordering of layers can be controlled with the order keyword. A higher order number will cause a layer to be drawn on top of any layers with a lower number. If not specified, default order for a layer is 0.

plot(layer(x=rand(10), y=rand(10), Geom.point, order=1),
     layer(x=rand(10), y=rand(10), Geom.line, order=2))

**Comment by tbreloff** [comment]
Thanks for the time-save... I knew I saw that somewhere.
