### ISSUE TITLE
Incorrect error message when types of arrays differ

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#64]
This happens sometimes when I do list comprehensions in global scope and type inference fails:

```jl
using Plots
data = rand(10)
x = [data[i] for i in 1:length(data)]
plot(data,x)

ERROR: AssertionError: length(x) == length(y)
 in computeXandY at /home/kristoffer/.julia/v0.4/Plots/src/plot.jl:244
```

The vectors here are obviously of the same length so maybe the error message can be tweaked?

**Comment by tbreloff** [comment]
This is not a simple case of error message, unfortunately. Likely this is interpreted as "plot 10 series, each x[i] vs data". I'll see if I can improve the dispatch logic to check for numeric vectors without types, but that implies I'd need to make a pass though the data to check each type... Not ideal.
