### ISSUE TITLE
Feature request: Copy plots / leave original plot unmodified

### ISSUE THREAD

**Issue by KristofferC** [tbreloff/Plots.jl#67]
Sometimes I want to add to a plot while leaving the original plot object unmodified.

If plots could be copied then you could simply do something like:

```jl
new_p = plot!(copy(p), ....)
```

Are there plans for something like this or maybe there is a way to currently do it?

**Comment by tbreloff** [comment]
Hmm this is an interesting idea (really it just needs a `copy` function).  This **may** not be too hard... I'll have to think on it a little.

**Comment by Evizero** [comment]
:+1: I would like to second this suggestion. I currently use Plots.jl to prepare a talk and I would like to add different things to the same original plot. I also do this a lot in R with ggplot2 and it's really convenient

**Comment by Evizero** [comment]
By the way I currently solve it like this:

```Julia
plt() = scatter(x, y, xlab = "x (feature)", ylab = "y (target)", title = "Simple Regression Problem", leg = false)
plot!(plt(), x, h(X, θ))
```

**Comment by KristofferC** [comment]
I also want this for a presentation where I will incrementally add stuff to a plot. Your workaround is nice, didn't think about that possibility.

**Comment by tbreloff** [comment]
Fyi... I'm working on this now, and it's done for plots.  I want to get it working for subplots as well, then I'll push it up.

I felt the need to post this because you guys keep coming up with your own solutions before I can finish with mine ;)

**Comment by tbreloff** [comment]
This should now work on master:

```
using Plots
p = plot(rand(10))
p2 = plot!(copy(p), rand(10))

sp = subplot(rand(10,2), n=2)
sp2 = subplot!(copy(sp), rand(10,2))
```

Give it a try, and let me know if you see any issues.

**Comment by Evizero** [comment]
works like a charm

**Comment by Evizero** [comment]
FYI copy does not seem to work correctly for contour plots. An error occurs when displaying the copied plot

```
TypeError: setfield!: expected Union{Array{T,2},Function,Void}, got Array{Float64,1}

 in apply_scale at /home/csto/.julia/v0.4/Gadfly/src/scale.jl:795
 in apply_scales at /home/csto/.julia/v0.4/Gadfly/src/scale.jl:39
 in apply_scales at /home/csto/.julia/v0.4/Gadfly/src/scale.jl:59
 in render_prepare at /home/csto/.julia/v0.4/Gadfly/src/Gadfly.jl:652
 in render at /home/csto/.julia/v0.4/Gadfly/src/Gadfly.jl:718
 in draw at /home/csto/.julia/v0.4/Gadfly/src/Gadfly.jl:822
 in writemime at /home/csto/.julia/v0.4/Plots/src/backends/gadfly.jl:666
 in sprint at iostream.jl:206
 in display_dict at /home/csto/.julia/v0.4/IJulia/src/execute_request.jl:29
```

**Comment by tbreloff** [comment]
Ok can you reopen this, or start a new issue?

**Comment by Evizero** [comment]
Yes, I'll try to sketch up a minimal example after lunch.

ps: sorry for being such a pain with all the issues recently.

**Comment by tbreloff** [comment]
Don't be sorry! It's necessary for improvement. Keep 'em comin'.

**Comment by Wikunia** [comment]
> using Plots
> p = plot(rand(10))
> p2 = plot!(copy(p), rand(10))

Doesn't work anymore? I get
```
ERROR: MethodError: no method matching copy(::Plots.Plot{Plots.GRBackend})
```

**Comment by mkborregaard** [comment]
Could you open a new issue and link to this? This is ancient history
