### ISSUE TITLE
Gadfly and scatter

### ISSUE THREAD

**Issue by jverzani** [tbreloff/Plots.jl#68]
In trying to create a graph to emphasize zeros of a function, I notice that the gadfly backend doesn't actually plot points with y-coordinate 0 in the proper place. This hopefully illustrates

```
julia> plot([0,1], [0,0])
julia> scatter!([0,1], [0,0])
```

produced the attached file
![screen shot 2015-11-14 at 5 39 42 pm](https://cloud.githubusercontent.com/assets/421708/11166158/ef1c2f5c-8af6-11e5-827b-b0cf8ac4133d.png)

**Comment by tbreloff** [comment]
I don't see this... can you post the output of `Pkg.status()`.  I wonder if you have a more recent version of Gadfly/Compose that is broken.  Can you also confirm if you see this behavior in any other backends, or just Gadfly?

**Comment by jverzani** [comment]
Sorry for the noise. My Gadfly and Compose were pinned to earlier versions. Thanks.

**Comment by jverzani** [comment]
Sorry, this seems to have reared its head again. I can replicate locally and on JuliaBox where Pkg.status() reports after a recent `Pkg.update`:

```
 - Cairo                         0.2.31
 - Gadfly                        0.4.1
 - Compose                       0.4.1
 - DataArrays                    0.2.20
 - DataFrames                    0.6.10
 - DataStructures                0.4.1
 - Graphics                      0.1.3
 - Plots                         0.5.1
 - Showoff                       0.0.6
```

Any thoughts? I tried digging around in the plot object, but couldn't find any culprits but I wasn't sure exactly where to look.

**Comment by tbreloff** [comment]
Hmm I can recreate this now, but it works fine on PyPlot, so I assume this is a problem with Gadfly.  I'll look into it, and we might have to open an issue there.

**Comment by jverzani** [comment]
I tried to recreate on Gadfly using two layers:

```
Gadfly.plot(layer(x=[0,1],y=[0,0], Geom.line), layer(x=[0,1],y=[0,0], Geom.point))
```

But that works as exepected. I'm not sure that `scatter` resolves to something as easy as that last layer call though.

THanks for any help.

**Comment by tbreloff** [comment]
I suspect this is related to my `ShapeGeometry` for creating custom Gadfly shapes.  Bah.  I guess they changed something internal to Compose that broke it... I'll have to investigate (and then put a PR together to move it out of Plots and into Gadfly)

**Comment by tbreloff** [comment]
Best guess is that it's related to this commit: https://github.com/dcjones/Compose.jl/commit/6393d9134339672969f3f25d81287c51b791564b

I'll keep investigating

**Comment by tbreloff** [comment]
Found it!  I was looking in the wrong place.  I opened an issue in Measures.jl to get a new release tagged, but in the meantime, running `Pkg.checkout("Measures")` should fix the issue.  Please give it a try!

**Comment by jverzani** [comment]
Awesome! Will have a look when I get a chance later today. Many thanks.

On Tue, Jan 12, 2016 at 4:14 PM, Tom Breloff <notifications@github.com>
wrote:

> Found it! I was looking in the wrong place. I opened an issue in
> Measures.jl to get a new release tagged, but in the meantime, running
> Pkg.checkout("Measures") should fix the issue. Please give it a try!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbreloff/Plots.jl/issues/68#issuecomment-171056750>.
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by tbreloff** [comment]
Measures was tagged, so I think this can be closed
