### ISSUE TITLE
Jupyter PDF Export

### ISSUE THREAD

**Issue by jdtuck** [tbreloff/Plots.jl#72]
When I try to download my Jupyter notebook using Plots.jl as a PDF I get this error

      nbconvert failed: Inkscape svg to pdf conversion failed

When I dig into the log  I get the following

    NbConvertApp] WARNING | Collisions detected in jupyter_nbconvert_config.py and jupyter_nbconvert_config.json config files. jupyter_nbconvert_config.json has higher priority: {
      "Exporter": {
    "template_path": "['.', '/home/jdtuck/.local/share/jupyter/templates'] ignored, using ['/home/jdtuck/.local/share/jupyter/templates']"
      }
    }
    /usr/lib/python3.5/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
      "You should import from ipython_nbconvert instead.", ShimWarning)
    [NbConvertApp] Converting notebook AerialRadiationAlgorithmEvaluation.ipynb to latex
    /tmp/tmp_o4i1qpz/figure.svg:1: parser error : Document is empty
    
    ^
    /tmp/tmp_o4i1qpz/figure.svg:1: parser error : Start tag expected, '<' not found
    
    ^
    /tmp/tmp_o4i1qpz/figure.svg:1: parser error : Document is empty
    
    ^
    /tmp/tmp_o4i1qpz/figure.svg:1: parser error : Start tag expected, '<' not found
     
     ^

    ** (inkscape:16304): WARNING **: Specified document /tmp/tmp_o4i1qpz/figure.svg cannot be opened (does not exist or not a valid SVG file)

It seems as though the svg is not created properly. This normally works with Gadfly normally. Thoughts?

**Comment by tbreloff** [comment]
Can you provide a more complete example? This doesn't seem related to Plots, but I'm also not positive what you've tried.

**Comment by tbreloff** [comment]
Also please provide version info for julia and packages (copy output of Pkg.status())

**Comment by jdtuck** [comment]
The julia version is 0.4.1 and Pkg.status() is below. 

```
    14 required packages:
 - Cpp                           0.1.0
 - Debug                         0.1.6
 - ElasticFDA                    0.3.1
 - Gadfly                        0.4.0
 - HypothesisTests               0.2.10
 - IJulia                        1.1.8
 - Immerse                       0.0.9
 - JLD                           0.5.6
 - MAT                           0.2.14
 - Plotly                        0.0.3+             master
 - Plots                         0.5.0
 - PyPlot                        2.1.1
 - Qwt                           0.0.1
 - Winston                       0.11.13
63 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.19
 - Blosc                         0.1.4
 - Cairo                         0.2.31
 - Calculus                      0.1.14
 - Codecs                        0.1.5
 - ColorTypes                    0.2.0
 - Colors                        0.6.0
 - Compat                        0.7.8
 - Compose                       0.4.0
 - Conda                         0.1.8
 - Contour                       0.0.8
 - DataArrays                    0.2.20
 - DataFrames                    0.6.10
 - DataStructures                0.3.13
 - Dates                         0.4.4
 - Dierckx                       0.1.7
 - Distances                     0.2.1
 - Distributions                 0.8.7
 - Docile                        0.5.19
 - DualNumbers                   0.1.5
 - FileIO                        0.0.3
 - FixedPointNumbers             0.1.1
 - ForwardDiff                   0.1.2
 - GZip                          0.2.18
 - Graphics                      0.1.3
 - Grid                          0.4.0
 - Gtk                           0.9.3
 - GtkUtilities                  0.0.7
 - HDF5                          0.5.6
 - HTTPClient                    0.2.0
 - Hexagons                      0.0.4
 - ImmutableArrays               0.0.11
 - IniFile                       0.2.4
 - Iterators                     0.1.9
 - JSON                          0.5.0
 - KernelDensity                 0.1.2
 - LaTeXStrings                  0.1.6
 - LibCURL                       0.2.0
 - Loess                         0.0.5
 - MathProgBase                  0.3.19
 - Measures                      0.0.1
 - NLopt                         0.2.3
 - NaNMath                       0.1.1
 - Nettle                        0.2.0
 - Optim                         0.4.4
 - PDMats                        0.3.6
 - Polynomials                   0.0.4
 - ProgressMeter                 0.2.2
 - PyCall                        1.2.0
 - Reexport                      0.0.3
 - Roots                         0.1.20
 - SHA                           0.1.2
 - Showoff                       0.0.6
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.7.4
 - StatsFuns                     0.2.0
 - Tk                            0.3.6
 - URIParser                     0.1.1
 - WoodburyMatrices              0.1.2
 - ZMQ                           0.3.1
 - Zlib                          0.1.12
```

Also below is the example i am running on my Jupyter Notebook

```julia
using Plots
gadfly()
x = linspace(0,2*pi,101);
y = sin(x)
plot(x,y)
```

**Comment by tbreloff** [comment]
I can reproduce your error, but I can also reproduce it using Gadfly directly:

```
using Gadfly
x = linspace(0,2*pi,101);
y = sin(x)
plot(x=x,y=y,Geom.path)
```

and get the error:
```
nbconvert failed: Inkscape svg to pdf conversion failed
```

And if I try to use PyPlot instead I get the error:
```
nbconvert failed: pdflatex not found on PATH
```

I'm guessing you should ask at IJulia, but either way it's unlikely to be related to Plots.

**Comment by jdtuck** [comment]
Okay sounds good, I will post over there
