### ISSUE TITLE
plot() not working in Gadfly

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#73]
```julia
gadfly()
plot()
```

returns 

```julia
The following aesthetics are required by Geom.point but are not defined: y, x


 in error at /Applications/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in assert_aesthetics_defined at /Users/solver/.julia/v0.4/Gadfly/src/aesthetics.jl:160
 in render at /Users/solver/.julia/v0.4/Gadfly/src/geom/point.jl:31
 in render at /Users/solver/.julia/v0.4/Gadfly/src/geometry.jl:48
 in render_prepared at /Users/solver/.julia/v0.4/Gadfly/src/Gadfly.jl:783
 in render at /Users/solver/.julia/v0.4/Gadfly/src/Gadfly.jl:722
 in draw at /Users/solver/.julia/v0.4/Gadfly/src/Gadfly.jl:822
 in writemime at /Users/solver/.julia/v0.4/Plots/src/backends/gadfly.jl:648
 in sprint at iostream.jl:206
 in display_dict at /Users/solver/.julia/v0.4/IJulia/src/execute_request.jl:29
```

**Comment by dlfivefifty** [comment]
PS The package is great! I'm switching over ApproxFun right now (which had its own, half-baked support for Gadfly & PyPlot)

**Comment by tbreloff** [comment]
Yeah gadfly is a real pain sometimes. I want to say "not my problem... file an issue with Gadfly", but I'll see if there's a hack I can add to avoid the error.

**Comment by tbreloff** [comment]
For reference, [Gadfly adds a blank layer here](https://github.com/dcjones/Gadfly.jl/blob/master/src/Gadfly.jl#L358-L362).  It's surprising that it's a layer that will give an error just after it, as I'd rather it just spit out an error about having no layers if that's not allowed.  This should be fixed within Gadfly, not Plots.  However I'll still try to ensure that Gadfly has at least one valid layer when built from Plots so it never hits this logic.

**Comment by tbreloff** [comment]
The fix is on the dev branch, I'll push it to master sometime this morning.  This should work without error now:

```
using Plots; gadfly()
plot()
plot!(rand(10))
```

**Comment by ABMSUH** [comment]
Hi,
I have a problem, with PyPlot in julia as:

julia> using PyPlot

julia> x = range(0,stop=2pi,length=1000); y = sin.(3x + 4cos.(2x))
1000-element Array{Float64,1}:
-0.7568024953079282
-0.7687979429150046
-0.7801330261327849
-0.790830536475742
⋮
-0.7166271329853839
-0.7307395907784272
-0.7441239200875579
-0.7568024953079278

julia> plot(x, y, color="red", linewidth=2.0, linestyle="--")
ERROR: MethodError: no method matching plot(::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Array{Float64,1}; color="red", linewidth=2.0, linestyle="--")
Closest candidates are:
plot(::Any, ::Union{Array{Layer,1}, Function, Element, Theme, Type}...; mapping...) at C:\Users\Pechman.julia\packages\Gadfly\09PWZ\src\Gadfly.jl:287
plot(::Any, ::Dict, ::Union{Array{Layer,1}, Function, Element, Theme, Type}...) at C:\Users\Pechman.julia\packages\Gadfly\09PWZ\src\Gadfly.jl:321 got unsupported keyword arguments "color",
"linewidth", "linestyle"
Stacktrace:
[1] top-level scope at none:0

**Comment by mkborregaard** [comment]
If you have a problem with pyplot, open an issue on pyplot

**Comment by ABMSUH** [comment]
Could you please advice on it?

**Comment by ABMSUH** [comment]
Hi,
I am facing big problem in Julia as follow:

“We tried to lunch Julia from:
C:\Users\Pechman\AppData\Local\Julia-1.1.0\bin\julia.exe
This path can be changed in the settings.
Details:
Access is denied.”

Please advise me to fix it…

**Comment by mkborregaard** [comment]
You're in the wrong place. This is the repo for the Plots package. For help with Julia please go to discourse.julialang.org
