### ISSUE TITLE
semilogy?

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#74]
Is semilogy (i.e., log-scale the y axis) possible?

**Comment by tbreloff** [comment]
For backends that support it, you should be able to do "yscale = :log" or "yaxis = :log".  If that doesn't work let me know.  Check out the "supported graphs" linked from the readme.

**Comment by dlfivefifty** [comment]
gadfly()
plot(1:20,exp(1:20);yscale=:log)
plot(1:20,exp(1:20);yaxis=:log)

don’t work.  Gadfly does support scaling the yaxis using Scale.y_log10.

**Comment by tbreloff** [comment]
Do you mind posting the error and also the output of Pkg.status()?  I thought that would work.

**Comment by dlfivefifty** [comment]
There was no error: it just plotted with the standard scaling:



Pkg.status()

10 required packages:
 - ApproxFun                     0.0.8+             development
 - Atom                          0.2.0+             master
 - Cairo                         0.2.31
 - GLVisualize                   0.0.2+             master
 - Gadfly                        0.4.0
 - IJulia                        1.1.8
 - Plots                         0.5.0
 - PyPlot                        2.1.1
 - SingularIntegralEquations     0.0.1+             development
 - TikzGraphs                    0.0.2+             master
83 additional packages:
 - ArrayViews                    0.6.4
 - AutoHashEquals                0.0.8
 - BinDeps                       0.3.19
 - Calculus                      0.1.14
 - Clustering                    0.5.0
 - CodeTools                     0.2.0
 - Codecs                        0.1.5
 - ColorTypes                    0.2.0
 - ColorVectorSpace              0.1.0
 - Colors                        0.6.0
 - Compat                        0.7.8
 - Compose                       0.4.0
 - Conda                         0.1.8
 - Contour                       0.0.8
 - DataArrays                    0.2.20
 - DataFrames                    0.6.10
 - DataStructures                0.3.13
 - Dates                         0.4.4
 - Distances                     0.2.1
 - Distributions                 0.8.7
 - Docile                        0.5.19
 - DualNumbers                   0.1.5
 - FactCheck                     0.4.1
 - FastGaussQuadrature           0.0.1
 - FileIO                        0.0.3
 - FixedPointNumbers             0.1.1
 - FixedSizeArrays               0.0.7
 - FreeType                      1.0.1
 - GLAbstraction                 0.0.6
 - GLFW                          1.0.0-alpha.7
 - GLWindow                      0.0.6
 - GZip                          0.2.18
 - GeometryTypes                 0.0.4
 - Graphics                      0.1.3
 - Graphs                        0.6.0
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - Hiccup                        0.0.1
 - Homebrew                      0.2.0
 - Images                        0.5.0
 - ImmutableArrays               0.0.11
 - Iterators                     0.1.9
 - JSON                          0.5.0
 - JuliaParser                   0.6.3+             master
 - KernelDensity                 0.1.2
 - LNR                           0.0.2
 - LaTeXStrings                  0.1.6
 - Lazy                          0.10.1
 - LightGraphs                   0.4.0
 - LightXML                      0.2.1
 - Loess                         0.0.5
 - MacroTools                    0.2.0
 - Measures                      0.0.1
 - Media                         0.1.1
 - MeshIO                        0.0.2
 - ModernGL                      0.0.6
 - Mustache                      0.0.14
 - NaNMath                       0.1.1
 - Nettle                        0.2.0
 - Optim                         0.4.4
 - PDMats                        0.3.6
 - Packing                       0.0.2
 - ParserCombinator              1.7.3
 - PyCall                        1.2.0
 - Quaternions                   0.0.4
 - Reactive                      0.2.4+             master
 - Reexport                      0.0.3
 - Requires                      0.2.1
 - SHA                           0.1.2
 - SIUnits                       0.0.6
 - SO                            0.0.0-             master (unregistered)
 - Showoff                       0.0.6
 - SignedDistanceFields          0.0.1
 - SortingAlgorithms             0.0.6
 - SpectralMeasures              0.0.0-             master (unregistered)
 - StatsBase                     0.7.4
 - StatsFuns                     0.2.0
 - TexExtensions                 0.0.3
 - TikzPictures                  0.2.5+             master
 - URIParser                     0.1.1
 - WoodburyMatrices              0.1.2
 - ZMQ                           0.3.1
 - Zlib                          0.1.12

**Comment by tbreloff** [comment]
This was a bug for the Gadfly backend only.  It wasn't getting to the scales logic unless you also specified explicit limits.  It should be fixed the next time I push to master, probably sometime this morning.  Thanks @dlfivefifty

**Comment by yashpalgoyal1304** [comment]
it's pretty weird to me that specifying log with arbitrary base is not supported :(

i mean yeah, `ln` , `log10` , `log2` are listed in there, but as can be seen, not many of the backends support `ln` or `log2` - if the approach was allowing general log scales, then the lack of choice of base wouldn't be an option

https://docs.juliaplots.org/latest/generated/supported/#Scales

**Comment by mkborregaard** [comment]
Please open a new issue rather than awakening a 7 years old thread.

**Comment by yashpalgoyal1304** [comment]
;k
