### ISSUE TITLE
Plotly backend

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#77]
@joshday has put together a Plotly prototype at https://github.com/joshday/PlotlyLocal.jl.  I want to review which parts are Plotly-specific, and which are "javascript plotting libs" specific, and generalize as best as possible.

- [x] Lines
- [x] Scatters
- [x] Fills/strokes
- [x] Hist/density
- [x] heatmap
- [x] Contour/Surface
- [x] Dates
- [x] shapes, styles, etc
- [x] pie charts
- [x] annotations
- [x] 3D line/scatter
- [x] subplots
- [x] tick labels/values/limits override
- [ ] custom shapes
- [ ] smoothing/regression
- [ ] right y-axis
- [ ] hline/vline (not supported directly?)
- [ ] arbitrary fill range (not supported directly?)
- [ ] linked subplots

- [ ] proper writemime methods (need png)
- [x] easy embedding in IJulia
- [x] I would also like the ability to add/change the underlying plot data without rebuilding/reloading the html, but that might require something like WebSockets or Node.js (edit: done with plotlyjs!).

**Comment by rohitvarkey** [comment]
> I would also like the ability to add/change the underlying plot data without rebuilding/reloading the html, but that might require something like WebSockets or Node.js.

Maybe [Patchwork](https://github.com/shashi/Patchwork.jl)?

**Comment by tbreloff** [comment]
Possibly, but I think that might be lower-level than I was aiming for.  I was thinking about wrapping the Plotly javascript object with a socket to change it's data, then let them worry about individual DOM objects.

**Comment by waldyrious** [comment]
I think this issue should include a note about why https://github.com/plotly/Plotly.jl is inadequate for this purpose, for future reference.

**Comment by tbreloff** [comment]
Sure. Afaik, plotly/Plotly.jl is geared towards their cloud plotting API, whereas we want to access the newly released open source javascript lib.

**Comment by tbreloff** [comment]
I've made a bunch of progress with Plotly, for anyone that wants to start testing things out.  Latest is on the dev branch.  A bunch of plot types are supported, even including contours and pie-charts, but a lot is still missing.

cc: @joshday @ericforgy

**Comment by joshday** [comment]
:+1: Seems like a great start!

**Comment by tbreloff** [comment]
Has anyone figured out a good way to save a PNG of a Plotly graph automatically (and preferably without opening a browser window).  Can I bypass the browser?

cc: @spencerlyon2

**Comment by spencerlyon2** [comment]
I can do from Julia, but only through a javascript call after a Blink window is opened. 

I'm still trying to come up with a better way to do this.

The best case scenario for me would to be able to save in png and pdf from a Julia script and configure at least the dpi.

Maybe @jackparmer knows some tricks?

**Comment by tbreloff** [comment]
What is the javascript call for this?  I can do the same thing until we find a better solution.

**Comment by spencerlyon2** [comment]
It's basically [this function](https://github.com/plotly/plotly.js/blob/216599856f6757333c34c29fb2f3786f8f02cf9b/src/components/modebar/buttons.js#L46-L95), specifically the `click` callback

I haven't wrapped it up into something usable yet. I mostly played around at the js console in my electron window and mimicked the body of that function. I didn't have time to expose it from Julia -- though it's just a matter of pasting the code in as a string and letting blink call out to the js console for me.

I will say, however, that the quality is very disappointing. I think the image is saved at something like 96 dpi with no ability to configure

**Comment by tbreloff** [comment]
More progress!  Unlinked subplots (independent axes) and IJulia embedding are supported now.  

![tmp](https://cloud.githubusercontent.com/assets/933338/11662229/91c943e8-9da3-11e5-968b-62999afb1237.png)

**Comment by Evizero** [comment]
so this is already done completely locally? nice

**Comment by pkofod** [comment]
Nice progress! Tried it out, and the quality is great. Is it only on my part that the text is a wee bit tiny?

**Comment by Evizero** [comment]
>  Is it only on my part that the text is a wee bit tiny?

I second that observation

**Comment by tbreloff** [comment]
>  the text is a wee bit tiny

I like it that size, but of course you can always change it:

```
using Plots; plotly()
default(guidefont = font(20), tickfont = font(15))
plot(rand(10), title="check out my font size")
```

Of course this brings up one of the issues with the Plotly backend, which is that the margins don't properly account for the guide labels.

**Comment by Evizero** [comment]
> I like it that size, ..

In the end it's your decision. But I would encourage you to use the usual defaults. As a user I would expect the plot to look similar to when I create it in R using the `plotly` package

**Comment by pkofod** [comment]
In principle I am happy as long as I know how to change it (guidefont, legendfont, tickfont, I think I can remember three keywords :)).

If I am analysing data on my own, plotting variables I know the range of, then sure, I can live with small numbers. Though, it is a bit small for external communication - in my very humble opinion.

**Comment by tbreloff** [comment]
> But I would encourage you to use the usual defaults.

This brings up a tricky issue.  In theory, everything about the plot is already defined before it gets to backend-specific code.  That means the PyPlot title should be the same size as the Plotly title (it uses the Plots-default, regardless of what the backend default would be)  This is the same for color palettes, etc.  

I agree that there should be a way to use the backend defaults for certain things, maybe font is one of them?  This might require having a default font `nothing` or `:default`, which would tell the backend not to override the font.

The other issue it highlights is that there should be a nice way to specify per-user defaults.  (I guess you could always add something like this to your `.juliarc.jl`:

```
using Plots
pyplot()
default(guidefont = font(15))
```

**Comment by Evizero** [comment]
I'm not sure I understand. If all backends share the same defaults I would expect them to look similar when it comes to size. 

This is how plotly and gadfly look to me with default settings

![screenshot1](https://cloud.githubusercontent.com/assets/10854026/11795450/f590929c-a2b6-11e5-93ff-4c080a95e07a.png)

![screenshot2](https://cloud.githubusercontent.com/assets/10854026/11795453/f7a15a12-a2b6-11e5-8d77-837076f4bab6.png)

**Comment by tbreloff** [comment]
Ok I see... it's something weird with Plotly then.  Gadfly and PyPlot seem to match.  I'll try to figure out what's going on.

**Comment by Evizero** [comment]
> I agree that there should be a way to use the backend defaults for certain things, maybe font is one of them? 

After reading your comment I changed my opinion about the backend defaults. I agree that a consistent experience across different backends is a better idea than using the backend default. I think the Gadfly plot above looks very reasonable.

**Comment by pkofod** [comment]
A quick question, you've ( @tbreloff ) checked off "lines", and `plot(x=rand(10), y=rand(10), lt = :line)` does give the correct result (as the lt gets checked when arguments are parsed), but I get the warning stating that it is not supported. Is it simple because `:line` has not been added in the list of supported plots types, or is there still something missing?

**Comment by tbreloff** [comment]
I don't think "line" (connected points sorted by x-value) is supported right now, but "path" is supported. This follows Gadfly's naming convention.  "path" is the more general of the two.  I'm not at my computer to test.

**Comment by pkofod** [comment]
I get the naming conventions, but despite the warning, the command gives me the correct result.

```
julia> using Plots
julia> plotly()
Plots.PlotlyPackage()
julia> y=rand(10)
10-element Array{Float64,1}:
 0.0590158
 0.862781 
 0.180373 
 0.212442 
 0.31547  
 0.853284 
 0.0148744
 0.0347428
 0.584031 
 0.874814 
julia> x=rand(10)
10-element Array{Float64,1}:
 0.818161
 0.779927
 0.897816
 0.322846
 0.192778
 0.295251
 0.273533
 0.414125
 0.52945 
 0.568889
julia> plot(x=x, y=y)
julia> Created new window in existing browser session.
julia> plot(x=x, y=y, lt=:line)
WARNING: linetype line is unsupported with Plots.PlotlyPackage().  Choose from: [:none,:path,:scatter,:steppre,:steppost,:heatmap,:hist,:density,:bar,:contour,:surface,:path3d,:scatter3d,:pie]
julia> Created new window in existing browser session.
```

![path](https://cloud.githubusercontent.com/assets/8431156/11810344/939febc4-a32d-11e5-9fd8-c9600138c3d1.png)

![line](https://cloud.githubusercontent.com/assets/8431156/11810343/939e10ce-a32d-11e5-89b7-5f2eabf30cc0.png)

So it works, even if an error is thrown saying that it doesn't.

**Comment by tbreloff** [comment]
Perfect thanks. Just need to add it to the supported list then :)

**Comment by Evizero** [comment]
Is there a way to drawn onto a ploly surface plot? Last time I tried it said that it isn't allowed.

Context: I would like to be able to recreate GIFs like this one from an [NVIDIA blog](http://devblogs.nvidia.com/parallelforall/deep-learning-nutshell-history-training/)

![optimization](http://devblogs.nvidia.com/parallelforall/wp-content/uploads/sites/3/2015/12/NKsFHJb.gif)

**Comment by tbreloff** [comment]
You should be able to do this already.  This works for me:

```
surface(Surface((x,y)->cos(x)+sin(y),0:10,0:10))  # actually this constructor isn't pushed up yet, but any surface will work
path3d!(10rand(100),10rand(100),2rand(100), w=4)
```

The tough part is saving a PNG and creating the animation... Plotly is not the ideal choice because of that.

**Comment by Evizero** [comment]
I'll check it out, thanks

> The tough part is saving a PNG and creating the animation

actually, I would be fine with live animations as well. Would probably be cooler anyway to be able to rotate the thing while it's happening

**Comment by tbreloff** [comment]
>  I would be fine with live animations as well.

I'd like this too, but PyPlot is a better option for both approaches.  Right now, I create fresh html for Plotly every time you update/display the plot, so it would pop up 100 browser windows, each with the next frame.

Eventually I'd like to incorporate the approaches of @spencerlyon2 and/or @ericforgy to update existing Plotly plots.

**Comment by tbreloff** [comment]
Fyi... I just added PyPlot support for 3d surfaces and wireframes:

![tmp](https://cloud.githubusercontent.com/assets/933338/11876006/7655df68-a4b5-11e5-8020-0f909100f54f.png)

**Comment by tbreloff** [comment]
Closing in favor of meta-issue (#316)
