### ISSUE TITLE
Interact support

### ISSUE THREAD

**Issue by Evizero** [tbreloff/Plots.jl#78]
When using `@manipulate` the plot doesn't change after the first time it's drawn

I managed to get `@manipulate` running as expected by directly returning `plt.o`. This however only works for a gadfly backend AFAIK

**Comment by Evizero** [comment]
I am trying to figure out how I could fix this, but I am a little out of my league here. I can't quite pin down what makes Gadfly work with interact that's missing for Plots. Do you have any intuition what the missing piece could be?

**Comment by tbreloff** [comment]
I haven't worked with interact... I only have a high level understanding of how it works. I'll dig into it when I have a chance.

**Comment by tbreloff** [comment]
Looking at this now... it seems like `display(plot(...))` should be called on a slider change.  This is the "gui mode" call in Plots.  I'll try to pin down what does/doesn't work in Plots and fix it all.

**Comment by tbreloff** [comment]
I can't even get it to work with Gadfly.  This may take longer than I want.

**Comment by Evizero** [comment]
My current workaround is by returning `plt.o` directly. That only works for gadfly.
In the case of having multiple plots I use

```Julia
Compose.set_default_graphic_size(22cm, 10cm) # have to set this explicitly
Gadfly.hstack(p1.o, p2.o)
```

**Comment by dlfivefifty** [comment]
👍🏽 Using
```julia
@manipulate for k=1:10
     plot(...).o 
end
```
works for me

**Comment by tbreloff** [comment]
I clearly have something weird with my setup.  I tried running this from a fresh IJulia notebook:

```
using Plots, Interact; gadfly()
@manipulate for k=1:10
    plot(rand(100,k)).o 
end
```

Based on your posts, I would expect that to work, but the cell just hangs, never finishing or outputting anything.

For Gadfly, a better hack (until we figure out why it doesn't work directly) for subplots would look like:

```
using Plots, Interact; gadfly()
@manipulate for k=1:10
    getGadflyContext(subplot(rand(100,k))) 
end
```

This is untested of course because `@manipulate` just hangs for me.

**Comment by dlfivefifty** [comment]
Bizarre, your first example works for me.  I’m on “master” for Interact, and jupyter 4.0.6.

**Comment by dlfivefifty** [comment]
This issue also affects Juno compatibility: 
```julia
using Plots;gadfly()
plot(1:10,1:10)
```
puts the plot in the Console, so you need
```julia
plot(1:10,1:10).o
```
to plot inline.

**Comment by diegozea** [comment]
Plots (using Gadfly as backend) doesn't work with `Interact`. The plots don't respond to the slider, and two instead of one plot is generated:

![image](https://cloud.githubusercontent.com/assets/2822757/14832877/9f377d7a-0bfc-11e6-91dd-f9f0827a7d50.png)

**Comment by dlfivefifty** [comment]
Try using

plt.o

In place of the last plt

**Comment by diegozea** [comment]
Thanks @dlfivefifty ! It works using `.o`

**Comment by tbreloff** [comment]
I was just looking at this, and Interact seems to work with all backends except plotlyjs (which seems to break the notebook?).  Closing this, and I'll add an item to the plotly meta-issue.  cc: @spencerlyon2

**Comment by spencerlyon2** [comment]
I believe that things should work quite well with PlotlyJS. 

@tbreloff can you confirm? If it is still an issue please tell  me about it.
