### ISSUE TITLE
normed=true in histogram?

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#79]
Is it possible to normalize the histogram (normed=true in PyPlot)?

**Comment by tbreloff** [comment]
Is this the same as a density plot?  Or just a scaled histogram?

**Comment by tbreloff** [comment]
For now, I added a new plot type `:density`:

```
subplot(randn(10000,2), t=[:hist :density], n=2, nc=1, size=(400,600))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/11318856/77f9cd5e-9031-11e5-91e8-56e6359f5d46.png)

Only PyPlot supports it at the moment.  If you think this is the right way to go, I can extend to other backends.  I'm a little torn because usually density refers to a smoothed estimate, not a scaled histogram.

**Comment by tbreloff** [comment]
Btw... this is only on the `dev` branch right now.

**Comment by dlfivefifty** [comment]
Maybe “normalizedhist” is a better name?  In Gadfly I think the key command is

Geom.histogram(density=true)

**Comment by tbreloff** [comment]
I thought about it a little... I think I'll stick with `:hist` and `:density` as the types (for now).  For the case of smoothed density (pdf) for an estimated distribution fit, I think it could be supported as part of the `smooth` argument. 

Currently I can take a boolean (linear regression line) or float (Gadfly/Loess).   I could also take a `Distributions.Distribution` or a `Symbol` which represents a Distribution family, and add a smoothed/fitted density plot.

```
# these are the same
plot(y, type = :density, smooth = Normal)
density(y, smooth = Normal)
```

The main concern is the added dependency on Distributions... I wouldn't want to require it.  Hence the smoothing might be better (but not as convenient) as part of MLPlots.jl.

**Comment by tbreloff** [comment]
So I just plotted a density plot, and I expected it to be a smooth curve.  Instead I got a normalized histogram.  So... I think I disagree with the tbreloff from 6 months ago.  He was wrong.

I want to add an argument `normalize = true/false`, with aliases `norm` and  `normed`.  Then the plot type `density` would be reserved for a smoothed pdf of some sort (need to figure out specifics still... ideas welcome)

Possibly:
```julia
# normalized histogram
histogram(y, normed=true)

# smooth density curve
density(y, cumulative = false, distribution = Normal, ...)
```

**Comment by tbreloff** [comment]
Note: `density` still may be most appropriate as a recipe of some sort, and not as a core plot type.  It potentially incorporates conditional packages (Distributions, or OnlineStats, or something) and is just a method to build a line plot for a statistical concept.

**Comment by tbreloff** [comment]
Done... see 44079a7bf7cda370dff4e381090ec5ae9fa0c019

**Comment by tbreloff** [comment]
For reference: http://stackoverflow.com/questions/4150171/how-to-create-a-density-plot-in-matplotlib

**Comment by dlfivefifty** [comment]
I just tried 

```julia
histogram(randn(100), normed=true)
```

and got the error:

```julia
WARNING: Keyword argument normalize not supported with Plots.PlotlyJSBackend().  Choose from: [:annotation,:background_color,:color_palette,:fillrange,:fillcolor,:fillalpha,:foreground_color,:group,:label,:layout,:legend,:seriescolor,:seriesalpha,:linecolor,:linestyle,:linetype,:linewidth,:linealpha,:markershape,:markercolor,:markersize,:markeralpha,:markerstrokewidth,:markerstrokecolor,:markerstrokestyle,:n,:bins,:nc,:nr,:show,:size,:title,:windowtitle,:x,:xlabel,:xlims,:xticks,:y,:ylabel,:ylims,:yticks,:xscale,:yscale,:xflip,:yflip,:z,:marker_z,:tickfont,:guidefont,:legendfont,:grid,:levels,:xerror,:yerror,:ribbon,:quiver,:orientation,:polar]
```

I'm on master.
