### ISSUE TITLE
Priorities - please comment

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#8]
I'm trying to figure out the features and backends that are most important to support.  There's a long TODO list at the bottom of the readme... If you see any of those items that are important to you (or if there's anything I should add), please let me know.

I think the next backends I want to implement are (in order?):

- PyPlot
- Vega
- GLPlot  (@SimonDanisch, is GLPlot ready for this?  Personally I would be thrilled to have a good OpenGL plotting option available)
- Winston

In terms of features, I find these most important:

- categorical inputs (strings and other non-numeric items)
- date/time plots
- "groupby" (splitting one data series into multiple... for example: http://gadflyjl.org/geom_subplot_grid.html)
- DataFrame inputs (I don't love the idea of adding a dependency on DataFrames.jl, though)

What would you like to see next??

**Comment by SimonDanisch** [comment]
Close, but not yet ;) Give me one or two more weeks then I'll announce it officially together with some tutorials!

**Comment by tbreloff** [comment]
I'll leave it at 3rd priority then... looking forward to the official release!  (Also, I hope you can be available to help me support it, which basically means helping me to make each of the examples like: https://github.com/tbreloff/Plots.jl/blob/master/docs/gadfly_examples.md)

**Comment by SimonDanisch** [comment]
By the way, your collection of basic plot types is quite helpful. So I might incorperate them into my example collection, making your work easier.

**Comment by tbreloff** [comment]
Ok thanks, but no need to go overboard.  I have a pretty solid framework at this point, so all I need to know is how to do the basics... create a black plot area, add a line series, add markers, change line styles, colors, etc.  I'll take care of putting the pieces together properly.

**Comment by SimonDanisch** [comment]
Sure, but I need to create my own examples anyways to test out my API. So having your collection of `data -> expected plot` is pretty convenient ;)

**Comment by tbreloff** [comment]
@SimonDanisch What's the latest status on GLPlot?  Should I consider adding support for it soon?  Any interest in helping with the link code?

**Comment by SimonDanisch** [comment]
Good questions... Lines are there now. Do you actually have any infrastructure to draw labels and axes?
That's what's still missing at the moment.

**Comment by tbreloff** [comment]
I don't have that yet, but I'll need it for Qt5.jl. Maybe we can use the same framework... Do you have a simple example of drawing some text and lines?  It might help to see if a common interface makes any sense.

**Comment by SimonDanisch** [comment]
Sorry for my slow answers, but my priorities are to get a few other things running first and I'm trying to find a flat at the moment which is terribly time consuming. 
For lines it's just:
```Julia
visualize(::Vector{Point{2, Float32}}, :lines)
```
and for text I still don't have a nice interface for placing it nicely... If you know any interface that works nicely, let me know.
right now it's pretty low level and looks something like this:
```Julia
text_renderobject = visualize(text::AbstractString)
any_4x4_transformation_matrix = translationmarix(Vec3f0(1,1,0))*scalematrix(Vec3f0(0.5))
text_renderobject[:model] = any_4x4_transformation_matrix
# modify first 4 glyph positions
text_renderobject[:positions][1:4] = Point{2, Float16}[pos, pos, pos, pos] # modify directly on gpu
```
