### ISSUE TITLE
Countour plots are incorrect

### ISSUE THREAD

**Issue by Evizero** [tbreloff/Plots.jl#80]
Here is an example.

```Julia
using Plots
gadfly()

X = [0.0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.0;
     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0]
y = [1.03262, 1.06073, 1.15507, 1.08, 1.25422, 1.22779, 1.28097, 1.29575, 1.40697, 1.42855, 1.49955]

h(X, θ) = X'θ
L(y, t) = 1/2 * (t - y).^2
cost(X, θ, y) = mean(L(y, h(X, θ)))

r1 = -.5:.05:1.5
r2 = 0:.05:2
```

The true surface plot should look like this

```Julia
Gadfly.plot(z = (θ1, θ2) -> cost(X, [θ1, θ2], y), x = r1, y = r2, Gadfly.Geom.contour)
```
![gadfly](https://cloud.githubusercontent.com/assets/10854026/11319338/a5fe3612-9073-11e5-8fd6-51afbd1796c6.png)

Plots.jl shows it like this

```Julia
plot(r1, r2, (θ1, θ2) -> cost(X, [θ1, θ2], y))
```
![plots](https://cloud.githubusercontent.com/assets/10854026/11319339/a936efea-9073-11e5-87d5-986df3757df8.png)

**Comment by Evizero** [comment]
Simpleton me would suspect that the x axis is mirrored somehow

**Comment by Evizero** [comment]
Same example with different ranges:

```Julia
r1 = -.5:.05:2.5
r2 = -1:.05:2
```

Gadfly:

![gadfly](https://cloud.githubusercontent.com/assets/10854026/11319371/9b76e72e-9074-11e5-8e81-21df5bc31348.png)

Plots:

![plots](https://cloud.githubusercontent.com/assets/10854026/11319373/a231ca84-9074-11e5-9e75-9773bb74c5cd.png)

**Comment by tbreloff** [comment]
Thanks... If it's just an issue that the xaxis is flipped in the gadfly backend, then it's an easy fix.

**Comment by Evizero** [comment]
using `pyplot()` has a different bug in that the axis are switched somehow while the contours seem to be right

Sample example with `pyplot()`

```Julia
r1 = -.5:.05:2.5
r2 = -1:.05:2
plot(r1, r2, (θ1, θ2) -> cost(X, [θ1, θ2], y))
```

![pyplot](https://cloud.githubusercontent.com/assets/10854026/11319545/0f7c7976-907b-11e5-91f2-e5b8fd1a2c21.png)

**Comment by tbreloff** [comment]
> using pyplot() has a different bug in that the axis are switched somehow 

I'm not sure what you mean here.

I did my own (simpler) test.  Let me know if you agree the the PyPlot backend is correct here.  The minimum should be at (1,-2).

<img width="591" alt="screen shot 2015-11-21 at 1 01 58 pm" src="https://cloud.githubusercontent.com/assets/933338/11319761/2a229c90-9050-11e5-885d-d7a16c77be02.png">

The same test with gadfly:

<img width="581" alt="screen shot 2015-11-21 at 12 49 41 pm" src="https://cloud.githubusercontent.com/assets/933338/11319720/73881fba-904e-11e5-9fda-bf99e0617c9c.png">

There's a separate bug that gadfly doesn't seem to be respecting the colorscheme, so don't get confused with the red vs blue. (in pyplot the minimum is red, in gadfly the minimum is blue)

So based on this, it seems like:
- Gadfly's y-axis is flipped, and
- Gadfly doesn't use the colorscheme correctly

I'll work on both those fixes, please let me know if you agree with my assessment.

**Comment by Evizero** [comment]
make the ranges for x and y different and look at the axis labels

**Comment by Evizero** [comment]
IMHO blue seems more appropriate for a minimum than red

**Comment by tbreloff** [comment]
> make the ranges for x and y different and look at the axis labels

Ok I think I see what you're talking about... I'll try to figure out what's going on.

> IMHO blue seems more appropriate for a minimum than red

Hmm... not sure I agree, but this is clearly personal preference.  However either way the gradient is defined in Plots, and Gadfly should be respecting that, so it should be consistent with PyPlot.

**Comment by tbreloff** [comment]
To summarize, the bugs to fix:

- [ ] Flip Gadfly's y-axis
- [ ] Fix Gadfly contour colorscheme
- [ ] Fix strange axis behavior with PyPlot contours

**Comment by tbreloff** [comment]
I think I fixed all 3 issues... please review (pushed to `dev` branch):

<img width="457" alt="screen shot 2015-11-21 at 1 59 32 pm" src="https://cloud.githubusercontent.com/assets/933338/11319961/2db1af2e-9058-11e5-81c7-916978ec4b3c.png">

**Comment by Evizero** [comment]
works for my stuff now

**Comment by Evizero** [comment]
Could you consider merging this into master? I could use this, but feel a bit uneasy tracking the dev branch

**Comment by tbreloff** [comment]
Done.

**Comment by Evizero** [comment]
thanks!
