### ISSUE TITLE
Really cool package

### ISSUE THREAD

**Issue by Evizero** [tbreloff/Plots.jl#81]
I just wanted to say that this package is really cool to work with.

I am working on example notebooks for ML and they are turning out really cool and informative (I'll open source them once I am done in about one week).

Just wanted to say thanks for all the work you put into this! It's really easy and nice to cook up example code to show cool stuff like this:

![lr_large](https://cloud.githubusercontent.com/assets/10854026/11319706/154a1f48-9080-11e5-8994-47be27ead2c5.gif)

**Comment by tbreloff** [comment]
This is my favorite issue so far  :+1: 

Thanks for the thoughts.  This would be really cool as a blog post... we should consider starting a ML blog as part of JuliaML!

**Comment by KristofferC** [comment]
Yes this package is awesome. I'm doing all my plotting from it nowadays.

**Comment by Evizero** [comment]
Here's another one I produced with Plots.jl. Although I had to do some workarounds. Any tips of how I can update a contourplot (i.e. change the contours)?. At the moment I override the subplots directly (i.e. subplt.plts[i] = ...) but that messes with the settings.

The influence of L1 and L2 penalties on the error surface as one increases the regularization coefficient before training. the X denotes the minimum

![penalties](https://cloud.githubusercontent.com/assets/10854026/11350399/a67133d2-9231-11e5-831c-113857b1bb4f.gif)

**Comment by tbreloff** [comment]
Also cool :+1: 

Fairly soon you should be able to update x,y,z directly like this:
```
plt = plot(x, y, z, t=:contour)
plt[1] = (newx, newy, newz)
```

**Comment by pkofod** [comment]
Cool plots! Is the notebook out yet @Evizero ?

Also, thanks for pointing me towards your package over at julia-users, @tbreloff . It makes plotting so much easier in Julia. Especially as the plotting ecosystem is so fragmented as it is right now.

**Comment by Evizero** [comment]
Not yet. I'm still cleaning them up and fleshing them out based on feedback I received. I've been pretty busy with work the past weeks

**Comment by tbreloff** [comment]
Thanks! I agree, I can't imagine going back to a pre-Plots world.  And it's even cooler now that Plotly is mostly supported.

**Comment by Evizero** [comment]
I'm really looking forward to local plotly. what's the state/eta on that?

**Comment by tbreloff** [comment]
ETA is now! (on master) The biggest stumbling block is saving PNGs (and thus animations), but if you don't care about that then most functionality is ready to go... 2d, 3d, even pie charts, dates on axes, contours, subplots, etc. works in IJulia or REPL. It's my new go-to backend. 

I could use help/advice for saving to PNG... Plotly is JavaScript calls, and I'm not sure a good way to convert html/javascript directly to PNG without an annoying 3rd party application.

**Comment by Evizero** [comment]
Just gave it a shot! looks really nice! aside from some very minor hiccups like the title being partly cropped out or overplotted by the controls.

**Comment by tbreloff** [comment]
Yes there are still some problems with layout, so it can't be used
exclusively, but for many (interactive) uses, especially in IJulia
workflows, it should be the new standard.

**Comment by Evizero** [comment]
+:100: Love it. Really looking forward to 3d surface plots. Maybe the way to go for animations is to do them live. AFAIK plotly is based on d3 which allows for changing data and also animates the transition

**Comment by tbreloff** [comment]
> Really looking forward to 3d surface plots

Actually, this works already...
![tmp](https://cloud.githubusercontent.com/assets/933338/11747328/a13bf7a4-9ff0-11e5-9e54-076812a83340.png)

>  AFAIK plotly is based on d3 which allows for changing data and also animates the transition

Yes this should be possible to access, but I don't have that yet.  I certainly would like the ability to change everything on the fly without generating a new plot/html.  Stay tuned...

**Comment by Evizero** [comment]
Just tried the surface. This is incredible! Thanks for putting effort into this. Using plotly for notebooks is certainly the future.

**Comment by tbreloff** [comment]
@Evizero I'm reworking the Plots docs a little, and I was thinking about putting one of your animations on in the readme with only a link to a readthedocs site.  Do you have any cool ones you'd like to showcase?

**Comment by Evizero** [comment]
I'll think of something simple but interesting. Maybe k-means or EM clustering
