### ISSUE TITLE
Subplot ignores :marker 

### ISSUE THREAD

**Issue by Evizero** [tbreloff/Plots.jl#84]
```Julia
get!(d, :markershape, :ellipse)
get!(d, :markersize, 1.5)
```

this works for plot but not for subplot in `_apply_recipe` , while `subplot(history; markershape = :ellipse, markersize = 1.4)` works

Here is some code to see if it works (after merging [PR 5](https://github.com/tbreloff/MLPlots.jl/pull/5)).
The lines should have markers on them:

```Julia
using MLPlots, ValueHistories
immerse()

history = DynMultivalueHistory()
for i = 1:100
  push!(history, :myval1, i, i / 2)
  i % 10 == 0 && i != 20 && push!(history, :myval2, float(i), i)
end

subplot(history)
```

**Comment by tbreloff** [comment]
I'll try to get to this in the next day or 2, as well as getting your PR merged.  Sorry I haven't kept up... had a baby a few days ago!

**Comment by KristofferC** [comment]
Wow,  congratulations!

**Comment by Evizero** [comment]
congratulations! hope everything went well
