### ISSUE TITLE
Choosing colour for multiple plot! commands?

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#87]
I want to call plot! several times, but have each call use the same colour.  I also want this colour to be the "next" colour, if the plot already has a colour.  Is there an easy way to get the "next" colour in a plot?

**Comment by dlfivefifty** [comment]
Here's a simplified version of what I'm trying to do, which doesn't really work at the moment:

```julia
function foo(plt::Plots.Plot,v::Vector)
        plot!(plt,v[1])
        c=plt.plotargs[:color_palette][1]
        for k=2:length(v)
            plot!(plt,v[k];color=c)
        end
end
```

**Comment by tbreloff** [comment]
Try (untested):

with(c = :blue) do
    plot!(rand(10))
    plot!(rand(10))
end

You can also try playing around with the "color_palette" arg.

**Comment by dlfivefifty** [comment]
I don’t know want to hardcode the colour, as I want the following behaviour:

plt=plot()
foo(plt,v)  #  blue


plt=plot(1:10,1:10)  # blue
foo(plt,v)  #  red


plt=plot(1:10,1:10)  # blue
plot!(1:10,2*(1:10)) # red
foo(plt,1:10,1:10)  #  green

**Comment by tbreloff** [comment]
What's foo? I'd expect this to work automatically.

**Comment by dlfivefifty** [comment]
foo is a function that calls multiple plot!’s that I want to all be the same colour

**Comment by tbreloff** [comment]
I see. Try replacing "blue" with "getColor(plt.plotargs[:color_palette],plt.n + 1)" in the "with" call.

**Comment by dlfivefifty** [comment]
c=plt.plotargs[:color_palette][plt.n+1]  Works!

**Comment by tbreloff** [comment]
Should this be closed, or is there something actionable?
