### ISSUE TITLE
Upcoming breaking changes in UnicodePlots

### ISSUE THREAD

**Issue by Evizero** [tbreloff/Plots.jl#88]
~~This is not actionable but just a heads up.~~

~~It's not tagged yet (and won't be for at least a week or so), but~~ I have made some changes to the `Canvas` types and also some refactoring to get rid of some more camelCase stuff.

It's likely that I broke stuff for you. I can tell for example that [this line](https://github.com/tbreloff/Plots.jl/blob/master/src/backends/unicodeplots.jl#L100) will be broken (the constant is now called `color_cycle` instead of `autoColors`) (**edit**: this is fixed in master)

**Comment by tbreloff** [comment]
Thanks for the heads up. A PR with relevant fixes would be ideal. Otherwise it may be a week or 2 before I get to it.

**Comment by Evizero** [comment]
Sure! I'll look into this when I get close to tagging a new version. It might very well be a while until I am done with the code clean-up of UnicodePlots.

**Comment by Evizero** [comment]
There is still an issue with unicodeplots that I can't quite pin down. I think this is on the Plots.jl side of things though

The following code will throw an error. However, you can just execute it again and everytime the error changes a little. after executing it 6 times it works.

```Julia
using Plots
unicodeplots()
x = linspace(0,2pi,20);
plot(x,sin(x))
```

The final error message shows the origin to be

```
....
 in typeinf at ./inference.jl:1339
 in typeinf_ext at ./inference.jl:1283
 in display at /home/csto/.julia/v0.4/Plots/src/backends/unicodeplots.jl:185
 in gui at /home/csto/.julia/v0.4/Plots/src/output.jl:110
 in display at /home/csto/.julia/v0.4/Plots/src/output.jl:114
 in display at REPL.jl:117
 [inlined code] from multimedia.jl:151
 in display at multimedia.jl:162
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
 in run_interface at ./LineEdit.jl:1610
 in run_frontend at ./REPL.jl:863
 in run_repl at ./REPL.jl:167
 in _start at ./client.jl:420
```

**Comment by GravityAssisted** [comment]
+1 , hope it gets fixed soon. Unicodeplots is cool and useful for quick plotting over SSH when x forwarding is not possible.

**Comment by tbreloff** [comment]
To be honest, I haven't used UnicodePlots in a while, so I don't even know if it's working. We should really add tests for it (which would be proper motivation for me to keep it working). Christof: do you have a good mechanism to compare the REPL output of UnicodePlots to known/working output?  I use VisualRegressionTests.jl for Gadfly/PyPlot backends, but that depends on PNG generation.

**Comment by Evizero** [comment]
I absolutely forgot about this issue. Yes, tests would be good. The current way of testing in Unicodeplots is not really automated. Basically I plot a lot of things and I as a human look at all of them and see if they are ok.... don't judge :)

**Comment by Evizero** [comment]
I will take a look a this

**Comment by Evizero** [comment]
this should be fixed once the new version is tagged. No need to change anything in Plots.jl. The issue was hidden in custom pre-compilation code on the UnicodePlots end of things.
