### ISSUE TITLE
Legend position

### ISSUE THREAD

**Issue by pkofod** [tbreloff/Plots.jl#89]
I tried searching, but couldn't find anything.

I have a figure as below ( I wonder why the background is not completely black after exporting as png from matplotlib...), and I want to move the legend outside of the plot itself. When I look at a lot of the examples given, the legend is outside, but no keywords are given, as far as I can see, to do this. Is this local configuration of matplotlib, an automated feature, or is it something I can change from Plots.jl ?
![figure_17](https://cloud.githubusercontent.com/assets/8431156/11739796/59608096-9fee-11e5-8a45-812c08e75113.png)

**Comment by tbreloff** [comment]
Yeah I don't expose fine-tuning for the legend, although I should probably accept directions (:left, :top, etc) to override the backend default. 

Matplotlib puts the legend inside the plot area by default. You can adjust it manually by accessing the underlying PyPlot figure (I think "plt.o.fig"). I'll try to give an example when I'm in front of my computer.

**Comment by tbreloff** [comment]
This is actually a little more complicated than I'd like for PyPlot.  If I uncomment [this line](https://github.com/tbreloff/Plots.jl/blob/master/src/backends/pyplot.jl#L707) then the following will work well:

![tmp](https://cloud.githubusercontent.com/assets/933338/11746093/3849b62e-9fea-11e5-9636-af21353b29ce.png)

but while that is uncommented, my tests break as the size of the resulting PNG is now platform-dependent (different versions of matplotlib is the likely cause).  

If I leave that line commented out, then the generated PNGs are the correct size, but the legend will get cut off when you change the position.  Apparently the legends are not part of the calculations when matplotlib lays out the axes. (really, I don't get why matplotlib is the standard for many people... it sucks in many ways)

I'm not sure what the right answer is... thoughts?

**Comment by tbreloff** [comment]
>  I wonder why the background is not completely black after exporting as png from matplotlib...

It should be.  If I do:

```
using Plots; pyplot()
default(size=(300,300))
plot(rand(10,4), bg=:black)
png("/home/tom/tmp")
```

then I get the saved PNG:

![tmp](https://cloud.githubusercontent.com/assets/933338/11746396/029cec56-9fec-11e5-9253-feaa9bc5fda6.png)

I assume that you're saving the figure another way?  Perhaps using the matplotlib GUI?  That's broken I think... I had to bypass PyPlot's method to get it to save the correct background.

**Comment by pkofod** [comment]
Yes, @tbreloff I used the GUI, that is good to know! Thanks for looking into this. Is there a reason Pyplot is the standard backend if you dislike it so much? :)

**Comment by tbreloff** [comment]
Good question! It's currently the best supported option with the most functionality, and comparatively fast. I dislike it less than Gadfly, Qwt, etc ;)

In the future, I think the standard backends will be Plotly for features (tons of support for it already on master) and GLVisualize for speed (early stages of support).

**Comment by pkofod** [comment]
It will be interesting to see how Plotly pans out. They have some really nice "show case" figures online, but I never got around to try using it.

**Comment by tbreloff** [comment]
You should try it now!  The biggest annoyance is that you can't as easily save PNGs/GIFs, but you'll find that there's not too much otherwise that you can do in PyPlot but not in Plotly.  You can track progress: #77

**Comment by pkofod** [comment]
On that note, I will close this issue. Thanks for the help.
