### ISSUE TITLE
GLVisualize backend

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#93]
cc: @dlfivefifty @simondanisch   First PR is merged in dev!  I'll collect a TODO list and any issues/progress here and in the comments.

**Comment by tbreloff** [comment]
A long way to go, but this is the first time I've been able to see something on screen!

```
glvisualize(); x = 1:50; y=x; f(x,y) = sin(x)+cos(y)
contour(x,y,f,fill=true)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/11899389/7ee758f2-a56c-11e5-974d-29c191d82aaa.png)

**Comment by tbreloff** [comment]
I'll be honest, I'm having trouble understanding the right way to add components.  Maybe you could supply a few bare-minimum examples (using GLVisualize, not Plots) of how to do a few basic plots:

- dots
- lines
- text
- how to change colors (can it be a different color for each dot/line?)
- how to change sizes
- how to programatically set the view area so the whole plot is shown without needing mouse commands
- anything else basic you can think of...

**Comment by dlfivefifty** [comment]
Figured out how to do dots:

using GLVisualize,GLAbstraction, GeometryTypes
window, renderloop = glscreen()
pts=[Point(0.1f0,0.2f0,0.3f0),Point(0.1f0,0.2f0,0.4f0)]
view(visualize(pts))
@async renderloop()

**Comment by dlfivefifty** [comment]
Here does different colours.  Note that if you call view(visualize..)  after the @async renderloop() it adds to the current plot, so that should support plot! commands. @simondanisch <https://github.com/simondanisch> had a way to clear the current plot, which could be used for regular plot() commands.  I think its not possible to have more than one window at the same time, though.




using GLVisualize,GLAbstraction, GeometryTypes,Colors
window, renderloop = glscreen()
pts=[Point(0.1f0,0.2f0,0.3f0),Point(0.1f0,0.2f0,0.4f0),Point(0.2f0,0.1f0,0.3f0),Point(0.f0,0.f0,0.f0)]
view(visualize(pts[1:2];color=RGBA{Float32}(1.,0.,0,1.)))
view(visualize(pts[3:4];color=RGBA{Float32}(0,1.,0,1.)))
@async renderloop()

**Comment by mmagnuski** [comment]
This looks great!

**Comment by SimonDanisch** [comment]
Sorry, I put all my work into releasing GLVisualize currently.
Here are a few examples:
```Julia
#Circles
    positions = Point2f0[....]
    view(visualize(positions,
        shape=CIRCLE,
        style=Cint(OUTLINED)|Cint(FILLED) # not necessary in next2 anymore
    	color=RGBA{Float32}/Vector{RGBA{Float32}},
    	stroke_color=RGBA{Float32}/Vector{RGBA{Float32}},
        scale= Vec2f0
    ), method=:orthographic_pixel)

function draw(img::GLVisualizeBackend, prim::LinePrimitive)
	N = length(prim.points)
    N <= 1 && return
    points = Point2f0[absolute_native_units(img, p) for p in prim.points]
    if N == 2 # currently a workaround, partly fixed in next2 branch
    	a,b = points
    	ab = b-a
    	points = vcat(a-(ab*0.00001f0),a,b,b+(ab*0.00001f0))
    end
    view(visualize(Signal(points), :lines,
    	color=RGBA{Float32}/Vector{RGBA{Float32}},
    	thickness=Float32
    ), method=:orthographic_pixel)
end

function Compose.draw(img::GLVisualizeBackend, prim::RectanglePrimitive)
    positions=Point2f0[...]
    view(visualize(positions,
        shape=RECTANGLE
       style=Cint(OUTLINED)|Cint(FILLED) # not necessary in next2 anymore
        scale=Vec3f0,
    	color=RGBA{Float32}/Vector{RGBA{Float32}},
    	stroke_color=RGBA{Float32}/Vector{RGBA{Float32}},
        stroke_width=Float32,
    ), img.screen, method=:orthographic_pixel)
end


function Compose.draw(img::GLVisualizeBackend, prim::Compose.BitmapPrimitive)
    xyz = Vec3f0(...)
    scale = Vec3f0(...)
    view(visualize(::Union{Image/Matrix{Color}}, model=translationmatrix(xyz)*scalematrix(scale)), method=:orthographic_pixel)
end

function Compose.draw(img::GLVisualizeBackend, prim::Compose.TextPrimitive)
	pos 	= Vec2f0(...)
	s 	= Vec3f0(..., 1)
	obj 	= visualize(::AbstractString, model=scalematrix(s), color=RGBA{Float32})
	bb    = boundingbox(obj).value
    w,h,_   = width(bb)
	x,y,_ = minimum(bb)
    pos     -= Point2f0(x, y)
# a lot of noise, positioning the text like Compose wants to have it.
    transmat = eye(Mat{4,4,Float32})
	if prim.rot.theta != 0.0
        pivot = Vec3f0(absolute_native_units(img, prim.rot.offset), 0)
        rot = GLAbstraction.rotationmatrix_z(Float32(-prim.rot.theta))
        transmat *= translationmatrix(pivot)*rot*translationmatrix(-pivot)
    end
    if prim.halign != Compose.hleft || prim.valign != Compose.vbottom
        if prim.halign == Compose.hcenter
            pos = (pos[1] - (w/2f0), pos[2])
        elseif prim.halign == Compose.hright
            pos = (pos[1] - w, pos[2])
        end
        if prim.valign == Compose.vcenter
            pos = (pos[1], pos[2] - h/2f0)
        elseif prim.valign == Compose.vtop
            pos = (pos[1], pos[2] - h)
        end
    end
    transmat *= translationmatrix(Vec3f0(pos..., 0))
	GLAbstraction.transformation(obj, transmat)
	view(obj, img.screen, method=:orthographic_pixel)
end
```
Sorry if this doesn't work right away, I couldn't test this, since I need to leave now!

There are inconsistencies, like that lines need to be supplied as a Signal, which are fixed in the next2 branch of GLVisualize. Next2 is nearly feature complete, but still has a few bugs and is not fully tested yet, which is where all my work is going to currently.

Here are 2 issues with a little bit of troubleshooting:
https://github.com/JuliaGL/GLVisualize.jl/issues/46
https://github.com/JuliaGL/GLVisualize.jl/issues/47
And there was an issue due to a change in GeometryTypes master, so when you do Pkg.update(), you might need to checkout another commit in GeoemtryTypes:
````
cd GeometryTypes
git checkout master
git checkout 762f23a14528e5085d81cfb3659da321f9e85786
```

Best,
Simon

**Comment by SimonDanisch** [comment]
in the future, this is the way to go:
`visualize((Primitive, Positions))`, where you can leave out the position.
Primitive can be most types in GeometryTypes (Circle, Rectangle, Cube, etc), 3D Meshes and unicode signs as `Chars`...

**Comment by tbreloff** [comment]
I know that GLVisualize has been improving daily... I'm wondering how stable the interface is at this point.  If we implement the backend code for Plots, will it stop working next week?  I don't want to sink too much time into it if everything will still be changing.  (thanks for the monster effort on that @SimonDanisch )

**Comment by SimonDanisch** [comment]
It should be quite stable ;)
At some point you might want to target what I'm talking about in https://github.com/JuliaGeometry/GeometryTypes.jl/issues/46, but that's not there yet and it won't replace the old API (it's rather another layer that the GLVisualize API will target) ;)
How to update and draw stuff as fast as possible might change slightly in the future.
If well done, the code that is specific to GLVisualize should be very short anyways!
Please don't hesitate to open issues or write me directly! I'm definitely willing to help :)

**Comment by dlfivefifty** [comment]
I started fixing the backend, I'll finish that up and make a pull request

**Comment by tbreloff** [comment]
i just cleaned up the glvisualize backend code.  I think we could tackle this in a similar fashion to GR.  Everything gets drawn all at once in the `gl_display` method.  I started it off with the same functionality as before (surface plots), and was able to install and view with:

```
using Plots; glvisualize(); surface(rand(100,20))
```

Anyone want to hack on this during JuliaCon?

**Comment by SimonDanisch** [comment]
Awesome!
Yess, I'm all in! :)
I'll be there starting tomorrow and I'll leave on 3rd of June!
I have to prepare my talk until the 22nd, but afterwards, hacking this will be one of my top priorities (and talking about Visualize IR and RecipeBase )
Spoiler, I'm working on some GUI:
![image](https://cloud.githubusercontent.com/assets/1010467/16023097/7006f7d0-31bb-11e6-8830-2adb07ad1a5a.png)

**Comment by tbreloff** [comment]
See: https://github.com/tbreloff/Plots.jl/pull/374
