### ISSUE TITLE
surface(::Matrix,::Matrix,::Matrix) gives error `type Void has no field surf`

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#96]
```julia
using Plots
xv=1:.1:10
yv=1:.1:10

x=xv*ones(yv)';
y=ones(xv)*yv';
z=exp(x).*cos(2y)
surface(x,y,z)
```
gives error
```julia
[Plots.jl] Initializing backend: pyplot
ERROR: type Void has no field surf
 in _add_series at /Users/solver/.julia/v0.4/Plots/src/backends/pyplot.jl:347
 in plot! at /Users/solver/.julia/v0.4/Plots/src/plot.jl:119
 in plot at /Users/solver/.julia/v0.4/Plots/src/plot.jl:56
 in surface at /Users/solver/.julia/v0.4/Plots/src/Plots.jl:169/usr/local/lib/python2.7/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
```

**Comment by tbreloff** [comment]
Do you really need gridded x/y form?  It's so wasteful, and annoying to handle.  I'm partway through fixing it, but I'd prefer that you get in the habit of using vector x/y instead:

![tmp](https://cloud.githubusercontent.com/assets/933338/11980815/933c3374-a96b-11e5-8d58-8d29e17e6a73.png)

**Comment by dlfivefifty** [comment]
Yes it's needed for plotting on disks and other domains

**Comment by tbreloff** [comment]
Ok cool. If you have any examples of plots you can't currently do, that would be super helpful to make sure I'm giving you a useful solution.

**Comment by dlfivefifty** [comment]
Here’s an example that works in PyPlot:

using PyPlot
r=0:.1:1
θ=-π:0.1π:π
x=cos(θ)*r'
y=sin(θ)*r'
z=exp(x).*sin(y)
surf(x,y,z)

**Comment by tbreloff** [comment]
This example works now on the dev branch.  It will likely only work with PyPlot.  Please let me know if you agree, and if you can think of any other examples that are still broken.  Thanks.

**Comment by dlfivefifty** [comment]
Great!  It should also work in GLVisualize, but I can add that when I need it.
