### ISSUE TITLE
Reduce 60x overhead for Gadfly

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#97]
Right now Plots takes 60x as long as Gadfly:

```julia
using Plots;gadfly()

@time for k=1:100 
    plot(1:100,1:100)
end #0.09s

@time for k=1:100
    Gadfly.plot(x=1:100,y=1:100);
end #0.0015s
```

Profiling reveals that the following is the worst culprit:

```
28 ...s/src/colors.jl; get_color_palette; line: 281
```

**Comment by dlfivefifty** [comment]
Looking through the code, it looks like its generating a new palette everytime

**Comment by tbreloff** [comment]
Thanks... I should start an "optimizations" meta-issue.  When I do, I'll close this one.

A couple related points, though... you should very rarely be creating a new plot from scratch in a loop.  In this scenario, you're updating the underlying plot data, without making any change to the rest of the plot, so you should be doing something like:

```
julia> using Plots; gadfly();

julia> p = plot(1:10);

julia> @time for i in 1:1000000
           p[1] = 1:10,1:10
       end
  1.393081 seconds (9.00 M allocations: 335.693 MB, 4.69% gc time)
```
which averages about 1.4 microseconds per update.  

I admit there are occasions when you'll want to update other plot attributes in a loop, and ideally there's a good way to do that without starting from scratch.  Maybe something like:

```
p = plot(rand(10), c=:red)
similar(p, c=:blue)
```

I'll need to think this through a little more before I start implementing anything though.

Also, keep in mind that you never actually displayed anything, and that's where 99% of the processing in Gadfly occurs.  When you add a call to display inside the loop, then there's a much smaller relative difference (still non-zero overhead, but not as noticeable).

**Comment by dlfivefifty** [comment]
Thanks for the tip! The main reason to need speed is @manipulate loops, so I'll try updating the data directly

**Comment by tbreloff** [comment]
I'm going to close this as I don't see myself focusing on these sorts of micro-optimizations in the near future.  If time-to-plot gets to be 60x, then we have a problem... this is only time-to-initialize, which is a comparative drop in the bucket.  Let me know if you disagree.
