### ISSUE TITLE
PGF/TIKZ Output

### ISSUE THREAD

**Issue by jdtuck** [tbreloff/Plots.jl#98]
It would be nice if we could save figures as PGF or TIKZ for latex integration.

**Comment by tbreloff** [comment]
Do you know if any of the backends support this currently? If you have an equivalent call in Gadfly, PyPlot, etc please provide it. Thanks.

**Comment by jdtuck** [comment]
I know that Gadfly does and the call is below

    draw(PGF("plot.tex", 5inch, 3inch), p)

this will return a tex document that can be compiled

it also has the call

     draw(PGF("images/Int_J1_tex2.tex", 5inch, 3inch, true, texfonts=true), my_plot_pgf)

which using tex fonts and only returns the tikzpicture environment

**Comment by tbreloff** [comment]
You can always access the underlying Gadfly object if needed.  In this case you would do

```
using Plots; gadfly()
p = plot(rand(10))
draw(PGF("plot.tex", 5inch, 3inch), p.o)
```

However, I just added this so next time I merge with master you can do:

```
using Plots; gadfly()
Plots.tex(plot(rand(10)), "/home/tom/tmp")
```

Which will save to `/home/tom/tmp.tex`

**Comment by jdtuck** [comment]
Awesome, thank you and it is good to know you can access the object underneath.

**Comment by mykelk** [comment]
The [juliaplots.sty](https://github.com/sisl/juliaplots.sty) makes integration of plots with latex documents really easy. You can write your plot code directly within your tex document, and it will generate the plot and embed it for you. It supports pgfplots, gadfly, and pyplots directly, but I think it would be easy to add plots.jl support.

**Comment by tbreloff** [comment]
After looking at it for 6.5 seconds, it does seem like it could be easy.
Someone that is tex-savvy should submit a PR ;)

**Comment by tbreloff** [comment]
closing in favor of meta-issue
